### ISSUE TITLE
An error occurred while attempting to load Web Apps.

### ISSUE THREAD

**Issue by bbetstcw** [Microsoft/azure-tools-for-java#1]
If the subscription is added by signing in, everything is good. However, if the subscription is added by importing a .publishsettings file, web apps cannot be loaded.

I need to use .publishsettings file because, this tool does not allow me to log into AzureChinaCloud.

Setting the Azure Service Endpoints does not help at all. Please fix this. Either letting users to choose the cloud environment, or making the .publishsettings file good for web apps.

**Comment by martinsawicki** [comment]
interesting find. Investigating. thanks.

**Comment by hbayyavarapu** [comment]
Is there any configuration in the azure portal to fix this issue. One day everything worked fine, the second day I see this "An error occurred while attempting to load web apps". I haven't seen a single error in google. This is the exception i see in intellij, didn't see a detailed error in eclipse
```
com.microsoft.windowsazure.exception.ServiceException: null
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:295)
	at com.microsoft.azure.management.resources.ResourceGroupOperationsImpl.list(ResourceGroupOperationsImpl.java:971)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:884)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:880)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:2514)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestResourceManagementSDK(AzureManagerImpl.java:2463)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.getResourceGroupNames(AzureManagerImpl.java:1443)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refresh(Unknown Source)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(Unknown Source)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

**Comment by swistaq** [comment]
Can confirm. Logging in works, importing *.publishsettings does not with the above error.

**Comment by martinsawicki** [comment]
.publishsettings would not work for WebApps, only cloud services. For WebApps you need to be logged in - that's just how Azure works.

**Comment by bbetstcw** [comment]
I know .publishsettings would not work for web apps, so can you implement the login for AzureChinaCloud Environment?
