### ISSUE TITLE
[Mooncake]Storage accounts are not available under Automated login in method 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#1150]
Automated->Browse...
Create any configuration storage account: e.g.monaac1
After creation, right click a storage account and choose Refresh 
![image](https://user-images.githubusercontent.com/22470312/31875907-b58aa47c-b802-11e7-85e2-da2fd747543a.png)
Right click a storage account and choose Create blob container
![image](https://user-images.githubusercontent.com/22470312/31875956-dfd88f50-b802-11e7-95d8-f2909d0a7cec.png)

**Error Log for refresh the storage account**
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:118)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode.refreshItems(StorageNode.java:106)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:130)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:109)
	... 18 more

**Error Log for Creating blob container**
An error occurred while attempting to create blob container.
(Message from Azure: "Error retrieving the Blob Container list"): Error retrieving the Blob Container list
com.microsoft.azuretools.azurecommons.helpers.AzureCmdException: Error retrieving the Blob Container list
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:148)
	at com.microsoft.intellij.forms.CreateBlobContainerForm$1.run(CreateBlobContainerForm.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:118)
	... 14 more
Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:109)
	... 15 more

 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@179031ec Current thread: Thread[ApplicationImpl pooled thread 45,4,Idea Thread Group] 464180324 SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.2.5#IU-172.4343.14 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-915-b12,6,main] 1880319053

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:520)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1104)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1093)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:1142)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusTransferReady(FocusManagerImpl.java:648)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusBeingTransferred(FocusManagerImpl.java:1095)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.isFocusBeingTransferred(IdeFocusManagerImpl.java:156)
	at com.intellij.ide.impl.DataManagerImpl.a(DataManagerImpl.java:255)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:216)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:101)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:37)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:840)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:227)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:223)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:219)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:268)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1352)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:288)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:301)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:312)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:737)
	at com.microsoft.intellij.util.PluginUtil.displayErrorDialog(PluginUtil.java:106)
	at com.microsoft.intellij.util.PluginUtil.displayErrorDialogAndLog(PluginUtil.java:111)
	at com.microsoft.intellij.forms.CreateBlobContainerForm$1.run(CreateBlobContainerForm.java:116)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adashen** [comment]
@Mona, Have you try to do it under interactive login?

**Comment by bsaby** [comment]
Work fine under Interactive login

**Comment by bsaby** [comment]
Other state for this issue:
![image](https://user-images.githubusercontent.com/22470312/31879561-50dccc86-b810-11e7-9da3-2d9b5b74e765.png)

**Comment by adashen** [comment]
The root cause is the url change in AzureEnvironment.
https://github.com/Azure/autorest-clientruntime-for-java/pull/268

We will fix the code to get the correct environment.

**Comment by adashen** [comment]
@bsaby please verify the fix

**Comment by bsaby** [comment]
Test passed both refresh specific storage account and create blob container
Build: Dev 461
