### ISSUE TITLE
[InteillJ] Cannot submit job from project explorer by right-click

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1208]
1. Right-click on project explorer.
2. choose the option 'Submit Spark Application to Cluster'

null
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionExDialog.getContentPane(SparkSubmissionExDialog.java:96)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionExDialog.setSubmitButtonStatus(SparkSubmissionExDialog.java:147)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionExDialog.lambda$initializeComponents$0(SparkSubmissionExDialog.java:69)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.setStatusForMessageLabel(SparkSubmissionContentPanel.java:648)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.setStatusForMessageLabel(SparkSubmissionContentPanel.java:653)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.setVisibleForFixedErrorMessageLabel(SparkSubmissionContentPanel.java:636)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.access$000(SparkSubmissionContentPanel.java:57)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$2.propertyChange(SparkSubmissionContentPanel.java:250)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8436)
	at javax.swing.JComboBox.setModel(JComboBox.java:318)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanelConfigurable.createUIComponents(SparkSubmissionContentPanelConfigurable.java:68)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanelConfigurable.$$$setupUI$$$(SparkSubmissionContentPanelConfigurable.java)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanelConfigurable.<init>(SparkSubmissionContentPanelConfigurable.java:63)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionExDialog.initializeComponents(SparkSubmissionExDialog.java:68)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionExDialog.<init>(SparkSubmissionExDialog.java:58)
	at com.microsoft.azure.hdinsight.spark.actions.SubmitAction.actionPerformed(SubmitAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ruoxinCheng** [comment]
Verified it.
