### ISSUE TITLE
SparkSqlSample can't be supported by Spark Local Run configuration

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#1224]
```
17/11/03 02:11:13 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
17/11/03 02:11:13 INFO SharedState: Warehouse path is 'file:/C:/src/intellij/mvn4/data/__default__/user/current/spark-warehouse'.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.hdinsight.spark.mock.SparkLocalRunner.runJobMain(SparkLocalRunner.java:74)
	at com.microsoft.azure.hdinsight.spark.mock.SparkLocalRunner.main(SparkLocalRunner.java:47)
Caused by: org.apache.spark.sql.AnalysisException: Unable to infer schema for JSON at /people.json. It must be specified manually;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$16.apply(DataSource.scala:426)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$16.apply(DataSource.scala:426)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:425)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:294)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:249)
	at org.apache.spark.examples.sql.SparkSQLExample$.runBasicDataFrameExample(SparkSqlExample.scala:57)
	at org.apache.spark.examples.sql.SparkSQLExample$.main(SparkSqlExample.scala:47)
	at org.apache.spark.examples.sql.SparkSQLExample.main(SparkSqlExample.scala)
	... 6 more
```

**Comment by ruoxinCheng** [comment]
package org.apache.spark.examples.sql
import org.apache.spark.sql.SparkSession


/**
  * Created by v-rouche on 11/28/2017.
  */
object sparkJson {

  def main(args: Array[String]) {
    val spark = SparkSession
      .builder()
      .appName("Spark SQL basic example")
      .config("spark.some.config.option", "some-value")
      .getOrCreate()

    import spark.implicits._

    val df = spark.read.json("/HdiSamples/people.json")

    // Displays the content of the DataFrame to stdout
    df.show()
  }

}

Json:
{"name":"Michael"}

{"name":"Andy", "age":30}

{"name":"Justin", "age":19}

**Comment by ruoxinCheng** [comment]
Verified it.

**Comment by ruoxinCheng** [comment]
Resolved.
