### ISSUE TITLE
'Failed to get default storage account name' when listing HDInsight clusters

### ISSUE THREAD

**Issue by mmaitre314** [microsoft/azure-tools-for-java#1245]
Using the Azure Toolkit for IntelliJ 3.0.11-2017.2, listing HDInsight (Spark) cluster errors out because the default Storage account name is missing. The Azure Portal is able to list the default Storage account in the Spark cluster blade, but in PowerShell `Get-AzureRmHDInsightCluster` also returns an empty DefaultStorageAccount field. The Spark cluster was created yesterday through the Azure Portal

<img width="688" alt="hdi" src="https://user-images.githubusercontent.com/8584604/32631904-8829272c-c556-11e7-8cf4-f6044167cf75.png">

```
com.microsoft.azure.hdinsight.sdk.common.HDIException: Failed to get default storage account name
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getDefaultStorageAccount(ClusterDetail.java:260)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getConfigurationInfo(ClusterDetail.java:226)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountFolderNode.refreshItems(StorageAccountFolderNode.java:52)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:130)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gogbg** [comment]
We have exactly the same issue and it is blocking the deployment of our Data Analytics platform. Can you please prioritize this as it is stopping the whole project right now? Thanks

**Comment by jingyanjingyan** [comment]
This issue should be fixed in most recent released build. Please reopen the issue if it still happens to you. Thank you.
