### ISSUE TITLE
[intellij] [2017.3] Access is allowed from event dispatch thread only.

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#1281]
The plugin hit the following issue on IntelliJ 2017.3

![image](https://user-images.githubusercontent.com/7385667/33539400-2cba712a-d901-11e7-8677-f2515e39bb25.png)

```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@d4d38b8 Current thread: Thread[ApplicationImpl pooled thread 9,4,main] 963545077 SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.3#IC-173.3727.127 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-1024-b6,6,main] 41841012

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:486)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1089)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.impl.LaterInvocator.getCurrentModalityState(LaterInvocator.java:323)
	at com.intellij.openapi.application.impl.ApplicationImpl.getCurrentModalityState(ApplicationImpl.java:676)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.setModalityProgress(AbstractProgressIndicatorBase.java:231)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:96)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:85)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:63)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:44)
	at com.microsoft.intellij.util.MethodUtils.loadSubInfoFirstTime(MethodUtils.java:151)
	at com.microsoft.intellij.ui.StorageAccountPanel.init(StorageAccountPanel.java:83)
	at com.microsoft.intellij.ui.StorageAccountPanel.<init>(StorageAccountPanel.java:65)
	at com.microsoft.intellij.AzureConfigurable.buildConfigurables(AzureConfigurable.java:60)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:88)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:254)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.collect(ShowSettingsUtilImpl.java:89)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurables(ShowSettingsUtilImpl.java:80)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.checkModelsUpToDate(SearchEverywhereAction.java:1972)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1365)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wezhang** [comment]
Looks I got a wrong plugin.

**Comment by wezhang** [comment]
The installed Azure Toolkit for Intellij version is v1.5.5, we need to upgrade the tool version to support 2017.3

**Comment by wezhang** [comment]
3.1 version released.

![image](https://user-images.githubusercontent.com/7385667/34334407-508efd2e-e981-11e7-8b9b-a2d6eb58821a.png)
