### ISSUE TITLE
NullPointerException on WebAppDeployDialog

### ISSUE THREAD

**Issue by lenala** [Microsoft/azure-tools-for-java#129]
![image](https://cloud.githubusercontent.com/assets/6208231/23081785/4ba23f3a-f50b-11e6-8f7c-0672c17283ce.png)

**Comment by anuchandy** [comment]
Here is the repo steps in my machine (Windows 8.1 Enterprise 8.1,  32 bit,  IntelliJ 2016.3.4 ) - 

1. New Project -> Java -> JavaEE -> Web Application
2. Provide project name as "SampleWebApp1"
3. Click Finish
4. File -> Project Structure -> Artifacts
		Change type to: Web Application:Archive
		Don't remove colon or space in the Name, keep it as it is (e.g. "SampleWebApp1:war exploded")

5. Apply -> OK
6. Build -> Build Artifacts
7. Right Click project name, Azure -> "Publish as Azure Web App"
8. You will get error message saying "The artifact name 'SampleWebApp1:war exploded' is invalid"
9. Go back to File -> Project Structure -> Artifacts
		Change name to "SampleWebApp1warexploded" (removed colon and space)
10. Build -> Build Artifacts
11. Try Right Click project name, Azure -> "Publish as Azure Web App"
12. You should see a "Error Dialog box" with no message
13. Cick on error icon in the bottom right corner of InteiiJ, you should see the error

```
actionPerformed
java.lang.NullPointerException
	at com.microsoft.azuretools.ijidea.ui.WebAppDeployDialog.doFillTable(WebAppDeployDialog.java:295)
	at com.microsoft.azuretools.ijidea.ui.WebAppDeployDialog.fillTable(WebAppDeployDialog.java:243)
	at com.microsoft.azuretools.ijidea.ui.WebAppDeployDialog.show(WebAppDeployDialog.java:175)
	at com.microsoft.azuretools.ijidea.ui.WebAppDeployDialog.go(WebAppDeployDialog.java:165)
	at com.microsoft.intellij.actions.AzureWebDeployAction.actionPerformed(AzureWebDeployAction.java:104)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:315)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

**Comment by vladimir-shcherbakov** [comment]
no repro
