### ISSUE TITLE
refreshing "Azure" in azure explorer shows error

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#130]
![image](https://cloud.githubusercontent.com/assets/16231002/23081941/fba7ba5e-f50b-11e6-9680-92b905a0af73.png)

![image](https://cloud.githubusercontent.com/assets/16231002/23081911/e2581df0-f50b-11e6-892f-0d66d02689b0.png)

java.lang.NullPointerException
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.fillWebappsNodes(WebappsModule.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refreshItems(WebappsModule.java:64)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:110)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lenala** [comment]
This was fixed, please verify.

**Comment by songkaiape** [comment]
Not repro. Verified this issue  in azure-toolkit-for-intellij.14.zip
