### ISSUE TITLE
Exception in plugin for IntelliJ IDEA MacOS

### ISSUE THREAD

**Issue by dautovri** [Microsoft/azure-tools-for-java#1302]
null
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.projects.samples.ProjectSampleUtil.getRootOrSourceFolder(ProjectSampleUtil.java:78)
	at com.microsoft.azure.hdinsight.projects.samples.ProjectSampleUtil.copyFileToPath(ProjectSampleUtil.java:55)
	at com.microsoft.azure.hdinsight.projects.HDInsightModuleBuilder.moduleCreated(HDInsightModuleBuilder.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy80.moduleCreated(Unknown Source)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.onModuleInitialized(ModuleBuilder.java:272)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.lambda$null$1(ModuleBuilder.java:299)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.intellij.ide.util.projectWizard.ModuleBuilder.lambda$createAndCommitIfNeeded$2(ModuleBuilder.java:299)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:359)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:197)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:415)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by wezhang** [comment]
Dup #1281
