### ISSUE TITLE
[Intellij][HDInsight] Spark Remote debug executor heartbeat timeout warning can be suspended

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#1307]
```
17/12/20 02:25:48 INFO Executor: Finished task 0.0 in stage 1.0 (TID 2). 2391 bytes result sent to driver
17/12/20 02:26:05 WARN NettyRpcEndpointRef: Error sending message [message = Heartbeat(1,[Lscala.Tuple2;@5dcbaef9,BlockManagerId(1, 10.0.0.4, 39388, None))] in 1 attempts
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
```

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748184
