### ISSUE TITLE
[IntelliJ] Popup an error when click the HDInsight Explorer

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#1328]
![image](https://user-images.githubusercontent.com/20041888/34665499-4e523588-f49b-11e7-84fa-efd7e491078b.png)

**Comment by wezhang** [comment]
What's the 'show advanced info' detail message?

**Comment by ruoxinCheng** [comment]
com.microsoft.azure.hdinsight.sdk.common.HDIException: Failed to get default storage account name
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getDefaultStorageAccount(ClusterDetail.java:260)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getConfigurationInfo(ClusterDetail.java:226)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountFolderNode.refreshItems(StorageAccountFolderNode.java:52)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:130)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wezhang** [comment]
Dup #1326 , wasbs not supporting issue
