### ISSUE TITLE
refreshing webapps from azure explorer throws error

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#134]
java.lang.NullPointerException
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.fillWebappsNodes(WebappsModule.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refreshItems(WebappsModule.java:64)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:110)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

![image](https://cloud.githubusercontent.com/assets/16231002/23082111/c27fa006-f50c-11e6-9ddd-b392f26afbb9.png)

![image](https://cloud.githubusercontent.com/assets/16231002/23082117/d1de3120-f50c-11e6-942e-63a9a39304e4.png)

**Comment by lenala** [comment]
This was fixed, please verify.

**Comment by songkaiape** [comment]
Not repro. Verified this issue in azure-toolkit-for-intellij.14.zip
