### ISSUE TITLE
deleting storage container throws error even though deletion is successfull

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#140]
![image](https://cloud.githubusercontent.com/assets/16231002/23082509/87057b02-f50e-11e6-97d0-dac4f000fdd3.png)

com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode cannot be cast to 
com.microsoft.tooling.msservices.serviceexplorer.azure.storage.BlobModule
java.lang.ClassCastException: com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode cannot be cast to com.microsoft.tooling.msservices.serviceexplorer.azure.storage.BlobModule
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.ContainerNode$DeleteBlobContainer.azureNodeAction(ContainerNode.java:73)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureNodeActionListener.actionPerformed(AzureNodeActionListener.java:54)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListenerAsync$1.run(NodeActionListenerAsync.java:56)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lenala** [comment]
This is fixed, please verify.

**Comment by arroyc** [comment]
@lenala  .. which build? 166? I found this in 165

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.172.zip
