### ISSUE TITLE
[Intellij][hdinsight] get Spark job log Error: 404 Not Found

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#1539]
```
get Spark job log Error: 404 Not Found for https://zhwe-spk21.azurehdinsight.net/yarnui/null/stdout?start=0
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 404 Not Found for https://zhwe-spk21.azurehdinsight.net/yarnui/null/stdout?start=0
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:579)
```

**Comment by wezhang** [comment]
Also sometimes got:

```
get Spark job log Error: 404 Not Found for https://zhwe-spk20.azurehdinsight.net/yarnui/wn1-zhwe-s.dlaibsjnhkiezoyqowrnnvwwld.dx.internal.cloudapp.net/node/containerlogs/container_1519369043841_0009_01_000001/livy/stdout?start=0
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 404 Not Found for https://zhwe-spk20.azurehdinsight.net/yarnui/wn1-zhwe-s.dlaibsjnhkiezoyqowrnnvwwld.dx.internal.cloudapp.net/node/containerlogs/container_1519369043841_0009_01_000001/livy/stdout?start=0
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:579)

```
