### ISSUE TITLE
[IntelliJ] Submit maven20  to spark20 fail

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1546]
Bit: https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/1380/Azure/ 

Repro Steps:
1. Open an existing Maven/spark20 project, which include the "out" folder.
2. Set remote configuration to use spark20 cluster
3. Set break point and start remote debug

Result:
![image](https://user-images.githubusercontent.com/36756024/37763267-8dd05860-2df9-11e8-9e9f-8173fdf07756.png)

or just shut down without debugging
![image](https://user-images.githubusercontent.com/36756024/37763288-944808a0-2df9-11e8-9751-ebb751e58988.png)

**Comment by wezhang** [comment]
```
get Spark job log Error: 404 Not Found for https://zhwe-spk20.azurehdinsight.net/yarnui/wn2-zhwe-s.xeir3wk41pjexki4jmhcbqv2sd.dx.internal.cloudapp.net/node/containerlogs/container_1520473656686_0047_01_000003/livy/stdout?start=-4096
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 404 Not Found for https://zhwe-spk20.azurehdinsight.net/yarnui/wn2-zhwe-s.xeir3wk41pjexki4jmhcbqv2sd.dx.internal.cloudapp.net/node/containerlogs/container_1520473656686_0047_01_000003/livy/stdout?start=-4096
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:579)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:404)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:459)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:444)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getInformationFromYarnLogDom(JobUtils.java:254)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchRemoteDebugJob.getYarnContainerJDBListenPort(SparkBatchRemoteDebugJob.java:56)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteDebugExecutorProcess.createEventWithJdbPorForwarding(SparkBatchJobRemoteDebugExecutorProcess.java:101)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteDebugProcess.lambda$createDebugSession$2(SparkBatchJobRemoteDebugProcess.java:118)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:704)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 404 Not Found for https://zhwe-spk20.azurehdinsight.net/yarnui/wn1-zhwe-s.xeir3wk41pjexki4jmhcbqv2sd.dx.internal.cloudapp.net/node/containerlogs/container_1520473656686_0047_01_000002/livy/stdout?start=-4096
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:579)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:404)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:311)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:459)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:444)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getInformationFromYarnLogDom(JobUtils.java:254)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchRemoteDebugJob.getYarnContainerJDBListenPort(SparkBatchRemoteDebugJob.java:56)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteDebugExecutorProcess.createEventWithJdbPorForwarding(SparkBatchJobRemoteDebugExecutorProcess.java:101)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteDebugProcess.lambda$createDebugSession$2(SparkBatchJobRemoteDebugProcess.java:118)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:704)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by wezhang** [comment]
new version HDInsight cluster has port parameter in the container url.
