### ISSUE TITLE
There is an error after clicking Create button

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#156]
In Azure Toolkit of IntelliJ, after clicking **Create** button in creating storage account dialog, creating virtual machine dialog and  creating app service dialog, an error occurred.

com.google.common.reflect.TypeToken.isAssignableFrom(Ljava/lang/reflect/Type;)Z
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isAssignableFrom(Ljava/lang/reflect/Type;)Z
	at com.microsoft.rest.Validator.validate(Validator.java:50)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.createOrUpdateWithServiceResponseAsync(ResourceGroupsInner.java:474)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.createOrUpdateAsync(ResourceGroupsInner.java:446)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupImpl.createResourceAsync(ResourceGroupImpl.java:120)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreateUpdateTask.executeAsync(CreateUpdateTask.java:39)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroupBase.executeAsync(TaskGroupBase.java:130)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.executeTaskGroupAsyncStreaming(CreatableUpdatableImpl.java:215)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.createAsync(CreatableUpdatableImpl.java:136)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:156)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:27)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKManager.createStorageAccount(AzureSDKManager.java:72)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.createStorageAccount(CreateArmStorageAccountForm.java:251)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.access$400(CreateArmStorageAccountForm.java:67)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm$7.run(CreateArmStorageAccountForm.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:572)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martinsawicki** [comment]
addressed by dependency cleanup?

**Comment by songkaiape** [comment]
Not repro. Verified this issue in azure-toolkit-for-intellij.14.zip
