### ISSUE TITLE
[HDInsight][Spark] Busy HDInsight cluster causes the uploading help session can't be created

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#1567]
```
Exception:com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session Helper session to upload /SparkSubmission/2018/03/16/b2xx9e77-3356-4xx1-b0x0-807385xx42/default_artifact.jar is DEAD. YARN Diagnostics: Application killed by user.
```

Same issue is occurring for the current version of Eclipse plugin as well.

**Comment by wezhang** [comment]
The helper session can’t be created issue mostly is because the running application is beyond the Yarn resource limitation. The user need to log into Yarn UI https://<cluster_name>.azurehdinsight.net/yarnui/hn/cluster/apps/scheduler to see if too many applications are running.

The issue is reproduced after running lots of Jupyter notebook sessions:
```
Package and deploy the job to Spark cluster
INFO: Get target jar from C:/src/intellij/mvn_21_v6/out/artifacts/mvn_21_v6_DefaultArtifact/default_artifact.jar.
INFO: Create Spark helper interactive session...
ERROR: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session Helper session to upload /SparkSubmission/2018/03/30/beb779f6-3cff-4c81-af45-0796015fdb47/default_artifact.jar is DEAD. YARN Diagnostics:
Application killed by user.
stack trace: java.lang.RuntimeException: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session Helper session to upload /SparkSubmission/2018/03/30/beb779f6-3cff-4c81-af45-0796015fdb47/default_artifact.jar is DEAD. YARN Diagnostics:
Application killed by user.
                at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
                at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.Session.lambda$awaitReady$9(Session.java:308)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.onNext(OperatorSwitchIfEmpty.java:90)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
                at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                at rx.internal.operators.OperatorDoAfterTerminate$1.onNext(OperatorDoAfterTerminate.java:50)
                at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
                at rx.Subscriber.setProducer(Subscriber.java:211)
                at rx.Subscriber.setProducer(Subscriber.java:205)
                at rx.Subscriber.setProducer(Subscriber.java:205)
                at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
                at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
                at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
                at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
                at rx.internal.operators.OnSubscribeRedo$4$1.onNext(OnSubscribeRedo.java:336)
                at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
                at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session Helper session to upload /SparkSubmission/2018/03/30/beb779f6-3cff-4c81-af45-0796015fdb47/default_artifact.jar is DEAD. YARN Diagnostics:
Application killed by user.
                at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.Session.lambda$awaitReady$9(Session.java:312)
                ... 59 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.SparkSession.class
                at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
                ... 58 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.SparkSession.class
                at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
                at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                at rx.internal.operators.OperatorDoAfterTerminate$1.onNext(OperatorDoAfterTerminate.java:50)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
                at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
                at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
                at rx.internal.operators.OperatorDoAfterTerminate$1.onNext(OperatorDoAfterTerminate.java:50)
                at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
                at rx.Subscriber.setProducer(Subscriber.java:211)
                at rx.Subscriber.setProducer(Subscriber.java:205)
                at rx.Subscriber.setProducer(Subscriber.java:205)
                at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
                at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.subscribe(Observable.java:10238)
                at rx.Observable.subscribe(Observable.java:10205)
                at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
                at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
                at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToHDFS(JobUtils.java:565)
                at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToCluster(JobUtils.java:574)
                at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$10(JobUtils.java:616)
                at rx.Single.subscribe(Single.java:1876)
                at rx.Single$13$1.call(Single.java:1948)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
                at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
                at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
                at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
                at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                ... 3 more
```

**Comment by wezhang** [comment]
Fix it by:

1. Provide more information when the issue hits
2. If the user is logged in with Azure subscription, the jar file will be uploaded by the Azure storage API with the user subscription infomation.

**Comment by jingyanjingyan** [comment]
verify in develop 633
