### ISSUE TITLE
Deploy to existing docker host fails

### ISSUE THREAD

**Issue by selvasingh** [Microsoft/azure-tools-for-java#159]
Use build 22
Create a simple Web app in IntelliJ
Deploy to an existing docker host created by IntelliJ
You will see Error: Unexpected param values; dockerHost cannot be null

**Comment by milismsft** [comment]
The selected Docker host does not have valid credentials. I'm adding a missing piece of UI that will prompt the user to specify a valid set of credentials for the selected host.

**Comment by milismsft** [comment]
fixed

**Comment by bsaby** [comment]
Test build used:artifacts/azure-toolkit-for-intellij.20.zip
Deploy to an existing docker host created by IntelliJ  with an error.


Error log:
java.lang.NullPointerException
	at com.microsoft.intellij.docker.forms.AzureDockerHostUpdateLoginPanel.initDefaultUI(AzureDockerHostUpdateLoginPanel.java:192)
	at com.microsoft.intellij.docker.forms.AzureDockerHostUpdateLoginPanel.<init>(AzureDockerHostUpdateLoginPanel.java:78)
	at com.microsoft.intellij.docker.dialogs.AzureInputDockerLoginCredsDialog.<init>(AzureInputDockerLoginCredsDialog.java:28)
	at com.microsoft.intellij.docker.wizards.publish.AzureSelectDockerWizardDialog$1$1.run(AzureSelectDockerWizardDialog.java:150)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by martinsawicki** [comment]
Millis re-fixed it again

**Comment by bsaby** [comment]
Test passed in artifacts/azure-toolkit-for-intellij.27.zip
