### ISSUE TITLE
[Intellij]The job failed to start when submit to Spark22

### ISSUE THREAD

**Issue by liyanp1987** [microsoft/azure-tools-for-java#1645]
Log:
Package and deploy the job to Spark cluster
INFO: Get target jar from /home/clear/IdeaProjects/SBTSpark220511/out/artifacts/sbtspark220511_DefaultArtifact/default_artifact.jar.
INFO: Create Spark helper interactive session...
INFO: Uploading /home/clear/IdeaProjects/SBTSpark220511/out/artifacts/sbtspark220511_DefaultArtifact/default_artifact.jar...
INFO: Uploaded to /SparkSubmission/2018/05/11/5e2edfcb-a5d9-49b4-a4f1-51630944017d/default_artifact.jar.
LOG: Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
LOG: Warning: Skip remote jar wasb://spark22-2018-03-31t10-16-54-558z@jilldong.blob.core.windows.net/SparkSubmission/2018/05/11/5e2edfcb-a5d9-49b4-a4f1-51630944017d/default_artifact.jar.
LOG: SLF4J: Class path contains multiple SLF4J bindings.
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.3.2-13/spark2/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.3.2-13/spark_llap/spark-llap-assembly-1.0.0.2.6.3.2-13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
LOG: SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
LOG: 18/05/11 03:46:21 WARN SparkConf: The configuration key 'spark.yarn.access.namenodes' has been deprecated as of Spark 2.2 and may be removed in the future. Please use the new key 'spark.yarn.access.hadoopFileSystems' instead.
LOG: 18/05/11 03:46:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
LOG: 18/05/11 03:46:22 INFO MetricsConfig: loaded properties from hadoop-metrics2-azure-file-system.properties
LOG: 18/05/11 03:46:22 INFO WasbAzureIaasSink: Init starting.
LOG: 18/05/11 03:46:22 INFO AzureIaasSink: Init starting. Initializing MdsLogger.
LOG: 18/05/11 03:46:22 INFO AzureIaasSink: Init completed.
LOG: 18/05/11 03:46:22 INFO WasbAzureIaasSink: Init completed.
LOG: 18/05/11 03:46:22 INFO MetricsSinkAdapter: Sink azurefs2 started
LOG: 18/05/11 03:46:22 INFO MetricsSystemImpl: Scheduled snapshot period at 60 second(s).
LOG: 18/05/11 03:46:22 INFO MetricsSystemImpl: azure-file-system metrics system started
LOG: 18/05/11 03:46:23 INFO RequestHedgingRMFailoverProxyProvider: Looking for the active RM in [rm1, rm2]...
LOG: 18/05/11 03:46:23 INFO RequestHedgingRMFailoverProxyProvider: Found active RM [rm2]
LOG: 18/05/11 03:46:23 INFO Client: Requesting a new application from cluster with 2 NodeManagers
LOG: 18/05/11 03:46:23 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (51200 MB per container)
LOG: 18/05/11 03:46:23 INFO Client: Will allocate AM container, with 1408 MB memory including 384 MB overhead
LOG: 18/05/11 03:46:23 INFO Client: Setting up container launch context for our AM
LOG: 18/05/11 03:46:23 INFO Client: Setting up the launch environment for our AM container
LOG: 18/05/11 03:46:25 INFO Client: Uploading resource file:/tmp/spark-6247db2c-bbd2-4949-a4e3-2d441d212033/__spark_conf__6924519764185281149.zip -> wasb://spark22-2018-03-31t10-16-54-558z@jilldong.blob.core.windows.net/user/livy/.sparkStaging/application_1525085382308_0173/__spark_conf__.zip
LOG: 18/05/11 03:46:25 INFO SecurityManager: Changing view acls to: livy
LOG: 18/05/11 03:46:25 INFO SecurityManager: Changing modify acls to: livy
LOG: 18/05/11 03:46:25 INFO SecurityManager: Changing view acls groups to: 
LOG: 18/05/11 03:46:25 INFO SecurityManager: Changing modify acls groups to: 
LOG: 18/05/11 03:46:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(livy); groups with view permissions: Set(); users  with modify permissions: Set(livy); groups with modify permissions: Set()
LOG: 18/05/11 03:46:25 INFO Client: Submitting application application_1525085382308_0173 to ResourceManager
LOG: 18/05/11 03:46:26 INFO Client: 
LOG: 	 client token: N/A
LOG: 	 diagnostics: [Fri May 11 03:46:25 +0000 2018] Application is Activated, waiting for resources to be assigned for AM.  Details : AM Partition = <DEFAULT_PARTITION> ; Partition Resource = <memory:102400, vCores:30> ; Queue's Absolute capacity = 50.0 % ; Queue's Absolute used capacity = 61.5 % ; Queue's Absolute max capacity = 100.0 % ; 
LOG: 	 ApplicationMaster host: N/A
LOG: 	 ApplicationMaster RPC port: -1
LOG: 	 queue: default
LOG: 	 start time: 1526010385817
LOG: 	 final status: UNDEFINED
LOG: 	 tracking URL: http://hn1-spark2.y45bqqxxgu0uhd2xfdptx0fble.bx.internal.cloudapp.net:8088/proxy/application_1525085382308_0173/
LOG: 	 user: livy
LOG: 18/05/11 03:46:26 INFO ShutdownHookManager: Shutdown hook called
LOG: 18/05/11 03:46:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-6247db2c-bbd2-4949-a4e3-2d441d212033
ERROR: The Spark job failed to start due to 	 ApplicationMaster RPC port: -1
	 queue: default
	 start time: 1526010385817
	 final status: UNDEFINED
	 tracking URL: https://spark22.azurehdinsight.net/yarnui/hn/proxy/application_1525085382308_0173/
	 user: livy
18/05/11 03:46:26 INFO ShutdownHookManager: Shutdown hook called
18/05/11 03:46:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-6247db2c-bbd2-4949-a4e3-2d441d212033

stderr: 

YARN Diagnostics: 
 stack trace: com.microsoft.azure.hdinsight.spark.common.SparkJobException: The Spark job failed to start due to 	 ApplicationMaster RPC port: -1
	 queue: default
	 start time: 1526010385817
	 final status: UNDEFINED
	 tracking URL: https://spark22.azurehdinsight.net/yarnui/hn/proxy/application_1525085382308_0173/
	 user: livy
18/05/11 03:46:26 INFO ShutdownHookManager: Shutdown hook called
18/05/11 03:46:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-6247db2c-bbd2-4949-a4e3-2d441d212033

stderr: 

YARN Diagnostics: 
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteProcess.lambda$awaitForJobStarted$9(SparkBatchJobRemoteProcess.java:208)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OperatorTakeUntilPredicate$ParentSubscriber.onNext(OperatorTakeUntilPredicate.java:61)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at rx.internal.operators.OnSubscribeRedo$2$1.setProducer(OnSubscribeRedo.java:267)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
	at rx.internal.operators.DeferredScalarSubscriber.complete(DeferredScalarSubscriber.java:102)
	at rx.internal.operators.OnSubscribeTakeLastOne$TakeLastOneSubscriber.onCompleted(OnSubscribeTakeLastOne.java:57)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$getSubmissionLog$26(SparkBatchJob.java:716)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by t-rufang** [comment]
Fixed in #1637
