### ISSUE TITLE
[IntelliJ] Remote submit has no function 

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1646]
Steps:
1. Create a new project, open file (like SparkCore_WasbIOTest), the edit configuration and run buttons are all disabled now.
2. Right click on file editor，local run and local debug are enabled
3. Local run，then remote submit button change to enable now
4. Do not open edit configuration，remote submit

Result:
no action and no warning.

2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - null 
java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:203)
    at com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration.getState(RemoteDebugRunConfiguration.java:155)
    at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
    at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
    at com.intellij.execution.ProgramRunnerUtil.executeConfigurationAsync(ProgramRunnerUtil.java:97)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:44)
    at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:111)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:59)
    at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:439)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
    at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
    at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - IntelliJ IDEA 2018.1.2 Build #IC-181.4668.68 
2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - JDK: 1.8.0_152-release 
2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - VM: OpenJDK 64-Bit Server VM 
2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - Vendor: JetBrains s.r.o 
2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - OS: Windows 10 
2018-05-11 00:01:26,942 [1810592] ERROR - til.concurrency.QueueProcessor - Last Action: SparkJobRun

**Comment by jingyanjingyan** [comment]
Fix with build dev-646
