### ISSUE TITLE
[IntelliJ][Windows]Sign in and close intellij get errors in log

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1697]
Repro
1. launch intellij with sign-in account includes 2 subscriptions
2. Get event log
3. Close intellij, get the error log 

Result:
**Sign in event log**
java.lang.RuntimeException: org.apache.http.client.HttpResponseException: Bad Request
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
	at rx.observables.BlockingObservable.singleOrDefault(BlockingObservable.java:373)
	at com.microsoft.azure.sparkserverless.serverexplore.sparkserverlessnode.SparkServerlessClusterRootModuleImpl.isFeatureEnabled(SparkServerlessClusterRootModuleImpl.java:55)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.refreshItems(AzureModule.java:146)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:136)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.HttpResponseException: Bad Request
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$toStringOnlyOkResponse$1(HttpObservable.java:230)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:64)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more

**Close Intellij get error log**
2018-06-12 18:46:26,964 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2018-06-12 18:46:27,037 [     73]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-181.4892.42, 08 May 2018 14:27) 
2018-06-12 18:46:27,037 [     73]   INFO -        #com.intellij.idea.Main - OS: Windows 10 (10.0, amd64) 
2018-06-12 18:46:27,037 [     73]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_152-release-1136-b38 (JetBrains s.r.o) 
2018-06-12 18:46:27,037 [     73]   INFO -        #com.intellij.idea.Main - JVM: 25.152-b38 (OpenJDK 64-Bit Server VM) 
2018-06-12 18:46:27,039 [     75]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Djb.vmOptionsFile=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\bin\idea64.exe.vmoptions -Didea.platform.prefix=Idea -Didea.jre.check=true -Dide.native.launcher=true -Didea.paths.selector=IdeaIC2018.1 -XX:ErrorFile=C:\Users\v-yajing\java_error_in_idea_%p.log -XX:HeapDumpPath=C:\Users\v-yajing\java_error_in_idea.hprof 
2018-06-12 18:46:27,039 [     75]   INFO -        #com.intellij.idea.Main - ext: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\jre64\lib\ext: [access-bridge-64.jar, cldrdata.jar, dnsns.jar, jaccess.jar, jfxrt.jar, localedata.jar, meta-index, nashorn.jar, sunec.jar, sunjce_provider.jar, sunmscapi.jar, sunpkcs11.jar, zipfs.jar] 
2018-06-12 18:46:27,039 [     75]   INFO -        #com.intellij.idea.Main - JNU charset: GBK 
2018-06-12 18:46:27,077 [    113]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 38 ms 
2018-06-12 18:46:27,079 [    115]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2018-06-12 18:46:27,104 [    140]   INFO -     #com.intellij.util.ui.JBUI - User scale factor: 1.0 
2018-06-12 18:46:27,104 [    140]   INFO -     #com.intellij.util.ui.JBUI - System scale factor: 1.0 (JRE-managed HiDPI) 
2018-06-12 18:46:27,372 [    408]   INFO - .intellij.idea.IdeaApplication - CPU cores: 8; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@65d72158[Running, parallelism = 7, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@2f0c4c9 
2018-06-12 18:46:27,808 [    844]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor duplicates-groovy.xml 
2018-06-12 18:46:28,057 [   1093]   INFO - llij.ide.plugins.PluginManager - Plugin 'Android Support' can't be loaded because: Plugin is disabled 
2018-06-12 18:46:28,233 [   1269]   INFO - llij.ide.plugins.PluginManager - 36 plugins initialized in 698 ms 
2018-06-12 18:46:28,239 [   1275]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Ant Support (1.0), Bytecode Viewer (0.1), CVS Integration (11), Copyright (8.1), Coverage (181.4892.42), Eclipse Integration (3.0), EditorConfig (181.4892.42), Git Integration (8.1), GitHub (181.4892.42), Gradle (181.4892.42), Groovy (9.0), I18n for Java (181.4892.42), IDEA CORE (181.4892.42), IntelliLang (8.0), JUnit (1.0), Java Bytecode Decompiler (181.4892.42), Java Stream Debugger (181.4892.42), JavaFX (1.0), Kotlin (1.2.31-release-IJ2018.1-1), Maven Integration (181.4892.42), Mercurial Integration (10.0), Plugin DevKit (1.0), Properties Support (181.4892.42), Settings Repository (181.4892.42), Smali Support (1.0), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), UI Designer (181.4892.42), XPathView + XSLT Support (4), XSLT-Debugger (1.4), YAML (181.4892.42) 
2018-06-12 18:46:28,239 [   1275]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Azure Toolkit for IntelliJ (3.7.0-2018.1), Scala (2018.1.9) 
2018-06-12 18:46:28,240 [   1276]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Android Support (10.3.0) 
2018-06-12 18:46:28,853 [   1889]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2018-06-12 18:46:28,926 [   1962]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\bin\fsnotifier64.exe 
2018-06-12 18:46:28,949 [   1985]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2018-06-12 18:46:29,041 [   2077]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2018-06-12 18:46:29,041 [   2077]   INFO - pi.util.registry.RegistryState -   SBT.system.in.process = true 
2018-06-12 18:46:29,483 [   2519]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=0.0; restored: fontSize=12, fontScale=1.0 
2018-06-12 18:46:29,571 [   2607]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: Git4Idea] 
2018-06-12 18:46:29,588 [   2624]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: hg4idea] 
2018-06-12 18:46:29,735 [   2771]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.OptionsTopHitProvider$Activity@7c1506bf 
2018-06-12 18:46:29,820 [   2856]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2018-06-12 18:46:29,831 [   2867]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2018-06-12 18:46:29,868 [   2904]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2018-06-12 18:46:30,025 [   3061]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:123, number of extensions:42 
2018-06-12 18:46:30,028 [   3064]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:2 
2018-06-12 18:46:30,047 [   3083]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:15, number of extensions:69 
2018-06-12 18:46:30,047 [   3083]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:0 
2018-06-12 18:46:30,191 [   3227]   INFO - pi.util.registry.RegistryValue - Registry value 'SBT.system.in.process' has changed to 'true" 
2018-06-12 18:46:30,578 [   3614]   INFO - plication.impl.ApplicationImpl - 94 application components initialized in 3046ms 
2018-06-12 18:46:30,592 [   3628]   INFO - .intellij.idea.IdeaApplication - App initialization took 4120 ms 
2018-06-12 18:46:30,759 [   3795]   INFO - pl$FileIndexDataInitialization - Initialization done:730 
2018-06-12 18:46:30,912 [   3948]   INFO - exImpl$StubIndexInitialization - Initialization done:152 
2018-06-12 18:46:31,559 [   4595]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2018-06-12 18:46:32,504 [   5540]   INFO - microsoft.intellij.AzurePlugin - Starting Azure Plugin 
2018-06-12 18:46:33,609 [   6645]   INFO - ellij.project.impl.ProjectImpl - 168 project components initialized in 2625 ms 
2018-06-12 18:46:33,860 [   6896]   INFO - le.impl.ModuleManagerComponent - 2 module(s) loaded in 250 ms 
2018-06-12 18:46:34,031 [   7067]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2018-06-12 18:46:34,837 [   7873]   INFO - CompilerBackwardReferenceIndex - backward reference index version differ due to: class java.io.FileNotFoundException 
2018-06-12 18:46:35,053 [   8089]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Remote Spark Job in Cluster) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/ToolWindowSparkJobRun.png 
2018-06-12 18:46:35,056 [   8092]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Debug Remote Spark Job in Cluster) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/ToolWindowSparkJobDebug.png 
2018-06-12 18:46:35,472 [   8508]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2018-06-12 18:46:35,584 [   8620]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 325ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-12 18:46:35,889 [   8925]   INFO - tartup.impl.StartupManagerImpl - OpenFilesActivity run in 701ms under project opening modal progress 
2018-06-12 18:46:35,996 [   9032]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Azure Activity Log) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/RoleFolder.gif 
2018-06-12 18:46:36,004 [   9040]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Azure Explorer) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/AzureExplorer_16.png 
2018-06-12 18:46:36,478 [   9514]   INFO - ge.ExternalProjectsDataStorage - Loaded external projects data in 538 millis 
2018-06-12 18:46:36,485 [   9521]   INFO - tartup.impl.StartupManagerImpl - ExternalSystemStartupActivity run in 578ms under project opening modal progress 
2018-06-12 18:46:36,501 [   9537]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 1343ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish 
2018-06-12 18:46:37,611 [  10647]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 2025ms; general responsiveness: ok; EDT responsiveness: 1/1 sluggish 
2018-06-12 18:46:57,500 [  30536]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@314dff5a 
2018-06-12 18:46:58,188 [  31224]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@32c24f0f 
2018-06-12 18:46:58,380 [  31416]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.codeInsight.completion.CompletionPreloader@4cee4a89 
2018-06-12 18:46:58,383 [  31419]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.actions.GotoClassPresentationUpdater@540af1a 
2018-06-12 18:47:11,120 [  44156]   INFO - j.ide.ui.OptionsTopHitProvider - 189 ms spent to cache options in application 
2018-06-12 18:47:11,156 [  44192]   INFO - tartup.impl.StartupManagerImpl - C:/Users/v-yajing/IdeaProjects/sbt220612/.idea case-sensitivity: expected=false actual=false 
2018-06-12 18:47:11,162 [  44198]   INFO - pl.projectlevelman.NewMappings - VCS Root: [] - [<Project>] 
2018-06-12 18:47:11,583 [  44619]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 40683 ms 
2018-06-12 18:47:11,707 [  44743]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2018-06-12 18:47:11,995 [  45031]   INFO - j.ide.ui.OptionsTopHitProvider - 170 ms spent to cache options in project 
2018-06-12 18:47:12,025 [  45061]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 2ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-12 18:47:12,205 [  45241]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 180ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-12 18:47:12,538 [  45574]   INFO - ramework.JobViewEditorProvider - start JobViewEditorProvider 
2018-06-12 18:47:12,546 [  45582]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2018-06-12 18:47:12,577 [  45613]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 6/12/2018 6:44 PM) 
2018-06-12 18:47:13,158 [  46194]   INFO -       ScriptTemplatesProviders - [kts] loading script definitions [] using cp:  
2018-06-12 18:47:31,859 [  64895]   INFO - microsoft.intellij.AzurePlugin - Starting Azure Plugin 
2018-06-12 18:47:32,340 [  65376]   INFO - ellij.project.impl.ProjectImpl - 22 project components initialized in 983 ms 
2018-06-12 18:47:38,920 [  71956]   INFO - ution.rmi.RemoteProcessSupport - Terminating: 58052/Maven3ServerImpl8e80ea0a 
2018-06-12 18:47:39,157 [  72193]  ERROR - api.util.objectTree.ObjectNode - Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.$$$reportNull$$$0(ActionManagerImpl.java)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getId(ActionManagerImpl.java)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.remove(DefaultActionGroup.java:226)
	at com.intellij.execution.ExecutorRegistryImpl.unregisterAction(ExecutorRegistryImpl.java:98)
	at com.intellij.execution.ExecutorRegistryImpl.deinitExecutor(ExecutorRegistryImpl.java:92)
	at com.intellij.execution.ExecutorRegistryImpl.dispose(ExecutorRegistryImpl.java:175)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:169)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:169)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:144)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$disposeSelf$7(ApplicationImpl.java:244)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:244)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:772)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:748)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:737)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:714)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:709)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$3.windowClosing(IdeFrameImpl.java:272)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-06-12 18:47:39,161 [  72197]  ERROR - api.util.objectTree.ObjectNode - IntelliJ IDEA 2018.1.3  Build #IC-181.4892.42 
2018-06-12 18:47:39,161 [  72197]  ERROR - api.util.objectTree.ObjectNode - JDK: 1.8.0_152-release 
2018-06-12 18:47:39,161 [  72197]  ERROR - api.util.objectTree.ObjectNode - VM: OpenJDK 64-Bit Server VM 
2018-06-12 18:47:39,161 [  72197]  ERROR - api.util.objectTree.ObjectNode - Vendor: JetBrains s.r.o 
2018-06-12 18:47:39,161 [  72197]  ERROR - api.util.objectTree.ObjectNode - OS: Windows 10 
2018-06-12 18:47:39,161 [  72197]  ERROR - api.util.objectTree.ObjectNode - Last Action:  
2018-06-12 18:47:39,161 [  72197]   INFO - stubs.SerializationManagerImpl - START StubSerializationManager SHUTDOWN 
2018-06-12 18:47:39,162 [  72198]   INFO - stubs.SerializationManagerImpl - END StubSerializationManager SHUTDOWN 
2018-06-12 18:47:39,162 [  72198]   INFO - il.indexing.FileBasedIndexImpl - START INDEX SHUTDOWN 
2018-06-12 18:47:39,190 [  72226]   INFO - il.indexing.FileBasedIndexImpl - END INDEX SHUTDOWN 
2018-06-12 18:47:39,203 [  72239]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2018-06-12 18:47:39,258 [  72294]   INFO - Types.impl.FileTypeManagerImpl - FileTypeManager: 0 auto-detected files
Elapsed time on auto-detect: 0 ms 
2018-06-12 18:47:39,261 [  72297]   INFO - pl.local.NativeFileWatcherImpl - Watcher terminated with exit code 0 
2018-06-12 18:47:39,266 [  72302]   INFO - newvfs.persistent.PersistentFS - VFS dispose started 
2018-06-12 18:47:39,332 [  72368]   INFO - newvfs.persistent.PersistentFS - VFS dispose completed 
2018-06-12 18:47:39,333 [  72369]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2018-06-12 18:47:39,335 [  72371]   INFO - org.jetbrains.io.BuiltInServer - web server stopped

**Comment by jingyanjingyan** [comment]
Fix with recent build
