### ISSUE TITLE
[IntelliJ] Keep intellij sign in, the cluster will not show after a long time

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1703]
Repro Steps:
1, Open intellij and sign in
2. Keep if for several hours

Result:
Display in sign in statue, but the cluster does not listed
![image](https://user-images.githubusercontent.com/36756024/41343977-923863f0-6f32-11e8-954f-a67a3bdd7eeb.png)

As well as the status in PPE environment:
![image](https://user-images.githubusercontent.com/36756024/41344019-ae97e87c-6f32-11e8-8c58-6f7c94361d11.png)

log:
2018-06-13 10:21:02,356 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2018-06-13 10:21:02,437 [     81]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-181.4892.42, 08 May 2018 14:02) 
2018-06-13 10:21:02,437 [     81]   INFO -        #com.intellij.idea.Main - OS: Windows 10 (10.0, amd64) 
2018-06-13 10:21:02,437 [     81]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_152-release-1136-b38 (JetBrains s.r.o) 
2018-06-13 10:21:02,437 [     81]   INFO -        #com.intellij.idea.Main - JVM: 25.152-b38 (OpenJDK 64-Bit Server VM) 
2018-06-13 10:21:02,454 [     98]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Djb.vmOptionsFile=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\bin\idea64.exe.vmoptions -Didea.platform.prefix=Idea -Didea.jre.check=true -Dide.native.launcher=true -Didea.paths.selector=IdeaIC2018.1 -XX:ErrorFile=C:\Users\v-yajing\java_error_in_idea_%p.log -XX:HeapDumpPath=C:\Users\v-yajing\java_error_in_idea.hprof 
2018-06-13 10:21:02,454 [     98]   INFO -        #com.intellij.idea.Main - ext: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\jre64\lib\ext: [access-bridge-64.jar, cldrdata.jar, dnsns.jar, jaccess.jar, jfxrt.jar, localedata.jar, meta-index, nashorn.jar, sunec.jar, sunjce_provider.jar, sunmscapi.jar, sunpkcs11.jar, zipfs.jar] 
2018-06-13 10:21:02,454 [     98]   INFO -        #com.intellij.idea.Main - JNU charset: GBK 
2018-06-13 10:21:02,506 [    150]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 52 ms 
2018-06-13 10:21:02,548 [    192]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2018-06-13 10:21:02,630 [    274]   INFO -     #com.intellij.util.ui.JBUI - User scale factor: 1.0 
2018-06-13 10:21:02,631 [    275]   INFO -     #com.intellij.util.ui.JBUI - System scale factor: 1.0 (JRE-managed HiDPI) 
2018-06-13 10:21:03,608 [   1252]   INFO - .intellij.idea.IdeaApplication - CPU cores: 8; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@6f3c09f7[Running, parallelism = 7, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@796f0996 
2018-06-13 10:21:04,365 [   2009]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor duplicates-groovy.xml 
2018-06-13 10:21:04,881 [   2525]   INFO - llij.ide.plugins.PluginManager - Plugin 'Android Support' can't be loaded because: Plugin is disabled 
2018-06-13 10:21:05,042 [   2686]   INFO - llij.ide.plugins.PluginManager - 36 plugins initialized in 1257 ms 
2018-06-13 10:21:05,048 [   2692]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Ant Support (1.0), Bytecode Viewer (0.1), CVS Integration (11), Copyright (8.1), Coverage (181.4892.42), Eclipse Integration (3.0), EditorConfig (181.4892.42), Git Integration (8.1), GitHub (181.4892.42), Gradle (181.4892.42), Groovy (9.0), I18n for Java (181.4892.42), IDEA CORE (181.4892.42), IntelliLang (8.0), JUnit (1.0), Java Bytecode Decompiler (181.4892.42), Java Stream Debugger (181.4892.42), JavaFX (1.0), Kotlin (1.2.31-release-IJ2018.1-1), Maven Integration (181.4892.42), Mercurial Integration (10.0), Plugin DevKit (1.0), Properties Support (181.4892.42), Settings Repository (181.4892.42), Smali Support (1.0), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), TestNG-J (8.0), UI Designer (181.4892.42), XPathView + XSLT Support (4), XSLT-Debugger (1.4), YAML (181.4892.42) 
2018-06-13 10:21:05,048 [   2692]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Azure Toolkit for IntelliJ (3.7.0-2018.1), Scala (2018.1.9) 
2018-06-13 10:21:05,048 [   2692]   INFO - llij.ide.plugins.PluginManager - Disabled plugins: Android Support (10.3.0) 
2018-06-13 10:21:11,523 [   9167]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=705 
2018-06-13 10:21:11,743 [   9387]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.3\bin\fsnotifier64.exe 
2018-06-13 10:21:12,511 [  10155]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2018-06-13 10:21:13,119 [  10763]   INFO - pi.util.registry.RegistryState - Registry values changed by user: 
2018-06-13 10:21:13,119 [  10763]   INFO - pi.util.registry.RegistryState -   SBT.system.in.process = true 
2018-06-13 10:21:13,638 [  11282]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=0.0; restored: fontSize=12, fontScale=1.0 
2018-06-13 10:21:13,717 [  11361]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: Git4Idea] 
2018-06-13 10:21:13,824 [  11468]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: hg4idea] 
2018-06-13 10:21:14,185 [  11829]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.OptionsTopHitProvider$Activity@275768af 
2018-06-13 10:21:14,392 [  12036]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2018-06-13 10:21:14,406 [  12050]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2018-06-13 10:21:14,449 [  12093]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2018-06-13 10:21:14,627 [  12271]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:146, number of extensions:42 
2018-06-13 10:21:14,630 [  12274]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:2 
2018-06-13 10:21:14,682 [  12326]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:23, number of extensions:69 
2018-06-13 10:21:14,682 [  12326]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:0 
2018-06-13 10:21:14,812 [  12456]   INFO - pi.util.registry.RegistryValue - Registry value 'SBT.system.in.process' has changed to 'true" 
2018-06-13 10:21:15,207 [  12851]   INFO - plication.impl.ApplicationImpl - 94 application components initialized in 11425ms 
2018-06-13 10:21:15,238 [  12882]   INFO - .intellij.idea.IdeaApplication - App initialization took 15288 ms 
2018-06-13 10:21:16,183 [  13827]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2018-06-13 10:21:16,945 [  14589]   INFO - pl$FileIndexDataInitialization - Initialization done:2315 
2018-06-13 10:21:17,604 [  15248]   INFO - microsoft.intellij.AzurePlugin - Starting Azure Plugin 
2018-06-13 10:21:18,297 [  15941]   INFO - exImpl$StubIndexInitialization - Initialization done:1352 
2018-06-13 10:21:19,664 [  17308]   INFO - ellij.project.impl.ProjectImpl - 168 project components initialized in 3968 ms 
2018-06-13 10:21:20,000 [  17644]   INFO - le.impl.ModuleManagerComponent - 2 module(s) loaded in 335 ms 
2018-06-13 10:21:20,174 [  17818]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2018-06-13 10:21:20,988 [  18632]   INFO - CompilerBackwardReferenceIndex - backward reference index version differ due to: class java.io.FileNotFoundException 
2018-06-13 10:21:21,323 [  18967]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 57ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-13 10:21:21,531 [  19175]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2018-06-13 10:21:21,942 [  19586]   INFO - tartup.impl.StartupManagerImpl - OpenFilesActivity run in 713ms under project opening modal progress 
2018-06-13 10:21:22,097 [  19741]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Azure Activity Log) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/RoleFolder.gif 
2018-06-13 10:21:22,106 [  19750]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Azure Explorer) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/AzureExplorer_16.png 
2018-06-13 10:21:22,482 [  20126]   INFO - ge.ExternalProjectsDataStorage - Loaded external projects data in 480 millis 
2018-06-13 10:21:22,488 [  20132]   INFO - tartup.impl.StartupManagerImpl - ExternalSystemStartupActivity run in 538ms under project opening modal progress 
2018-06-13 10:21:22,508 [  20152]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 1306ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-13 10:21:23,423 [  21067]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 2098ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-13 10:21:55,841 [  53485]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@760e6c44 
2018-06-13 10:21:56,497 [  54141]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@61fb74e3 
2018-06-13 10:21:56,697 [  54341]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.codeInsight.completion.CompletionPreloader@70e13ee5 
2018-06-13 10:21:56,701 [  54345]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.actions.GotoClassPresentationUpdater@1b876f09 
2018-06-13 10:22:07,720 [  65364]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Remote Spark Job in Cluster) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/ToolWindowSparkJobRun.png 
2018-06-13 10:22:07,723 [  65367]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Debug Remote Spark Job in Cluster) or icon jar:file:/C:/Users/v-yajing/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/ToolWindowSparkJobDebug.png 
2018-06-13 10:22:07,952 [  65596]   INFO - j.ide.ui.OptionsTopHitProvider - 204 ms spent to cache options in application 
2018-06-13 10:22:07,977 [  65621]   INFO - tartup.impl.StartupManagerImpl - C:/Users/v-yajing/IdeaProjects/sbt220612/.idea case-sensitivity: expected=false actual=false 
2018-06-13 10:22:07,983 [  65627]   INFO - pl.projectlevelman.NewMappings - VCS Root: [] - [<Project>] 
2018-06-13 10:22:08,397 [  66041]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 52767 ms 
2018-06-13 10:22:08,515 [  66159]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2018-06-13 10:22:08,809 [  66453]   INFO - j.ide.ui.OptionsTopHitProvider - 163 ms spent to cache options in project 
2018-06-13 10:22:08,812 [  66456]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2018-06-13 10:22:08,851 [  66495]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 1ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-13 10:22:09,017 [  66661]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 165ms; general responsiveness: ok; EDT responsiveness: ok 
2018-06-13 10:22:09,542 [  67186]   INFO - ramework.JobViewEditorProvider - start JobViewEditorProvider 
2018-06-13 10:22:10,129 [  67773]   INFO -       ScriptTemplatesProviders - [kts] loading script definitions [] using cp:  
2018-06-13 10:22:16,772 [  74416]   INFO - microsoft.intellij.AzurePlugin - Starting Azure Plugin 
2018-06-13 10:22:17,068 [  74712]   INFO - ellij.project.impl.ProjectImpl - 22 project components initialized in 648 ms 
2018-06-13 10:24:14,725 [ 192369]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\v-yajing\.IdeaIC2018.1\system\compile-server\m22_c858dd7 
2018-06-13 10:24:15,258 [ 192902]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\v-yajing\.IdeaIC2018.1\system\compile-server\maven210514_a8a2c09c 
2018-06-13 10:24:15,837 [ 193481]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\v-yajing\.IdeaIC2018.1\system\compile-server\maven2205141_dbfcc926 
2018-06-13 10:24:16,626 [ 194270]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\v-yajing\.IdeaIC2018.1\system\compile-server\maven220514_3d87735d 
2018-06-13 10:24:17,506 [ 195150]   INFO - j.compiler.server.BuildManager - Clearing project build data because the project does not exist or was not opened for more than 30 days: C:\Users\v-yajing\.IdeaIC2018.1\system\compile-server\werwerwerwer_3e722688 
2018-06-13 14:40:43,773 [15581417]  ERROR - llij.ide.plugins.PluginManager - Exception thrown on Scheduler.Worker thread. Add `onError` handling. 
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Unauthorized
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.onError(OperatorSwitchIfEmpty.java:84)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OperatorToObservableList$1.onError(OperatorToObservableList.java:104)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OperatorDoAfterTerminate$1.onError(OperatorDoAfterTerminate.java:56)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: org.apache.http.client.HttpResponseException: Unauthorized
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$toStringOnlyOkResponse$1(HttpObservable.java:230)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:64)
	... 33 more
2018-06-13 14:40:43,788 [15581432]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.1.3  Build #IC-181.4892.42 
2018-06-13 14:40:43,788 [15581432]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-06-13 14:40:43,788 [15581432]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-06-13 14:40:43,788 [15581432]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-06-13 14:40:43,788 [15581432]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2018-06-13 14:40:43,788 [15581432]  ERROR - llij.ide.plugins.PluginManager - Last Action:

**Comment by wezhang** [comment]
@jingyanjingyan , could you help to verify this in most new bits?

**Comment by jingyanjingyan** [comment]
Verify with build develop-644, keep the intellij opennin for several hours, the cluster list in configuration dialog will become non-sign-in statue, refresh will make it back to work.
