### ISSUE TITLE
[IntelliJ][Spark on ADL] re-login will show two adl accounts

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1733]
Note: Tester met the issue with the build https://vscjavaci.cloudapp.net/job/Azure_Toolkits_for_Java/job/AzureToolsManager_PR/1576/ 

Repro Steps
I logoff and re-login, I am seeing two genericconkobo03 here. And after refresh, it get exception

Screenshort
![image](https://user-images.githubusercontent.com/36756024/41696618-86eba050-7547-11e8-8362-ece5ce8dfac6.png)

Exception
Exception thrown on Scheduler.Worker thread. Add `onError` handling.
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Unauthorized
                at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
                at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.onError(OperatorSwitchIfEmpty.java:84)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
                at rx.internal.operators.OperatorToObservableList$1.onError(OperatorToObservableList.java:104)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
                at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852)
                at rx.observers.Subscribers$5.onError(Subscribers.java:230)
                at rx.internal.operators.OperatorDoAfterTerminate$1.onError(OperatorDoAfterTerminate.java:56)
                at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
                at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
                at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
                at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
                at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
                at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.unsafeSubscribe(Observable.java:10142)
                at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                ... 7 more
Caused by: org.apache.http.client.HttpResponseException: Unauthorized
                at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$toStringOnlyOkResponse$1(HttpObservable.java:239)
                at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:64)
                ... 33 more

**Comment by jingyanjingyan** [comment]
Fix
