### ISSUE TITLE
Certificate issue leading to job submission fail in cosmos09

### ISSUE THREAD

**Issue by t-rufang** [Microsoft/azure-tools-for-java#1764]
```
Package and deploy the job to Spark cluster
INFO: Begin uploading file C:/Users/rufan/IdeaProjects/spark22maven/out/artifacts/spark22maven_DefaultArtifact/default_artifact.jar to Azure Datalake store adl://searchdmprod-c09.azuredatalakestore.net/SparkSubmission/2018/07/12/fdbd43f3-b683-4f01-bf2a-9a743160b592/default_artifact.jar ...
INFO: Upload to Azure Datalake store 67651 bytes successfully.
ERROR: Certificate for <119d555e-eb39-48ad-840d-bb1db9317a85.livy.pools.westus2.azuredatalakeanalytics.net> doesn't match any of the subject alternative names: [*.adlus81.projectkonacompute.net, *.adlus81.projectcabostore.net, *.azuredatalakestore.net, *.azuredatalakeanalytics.net, adlus81.projectkonacompute.net, adlus81.projectcabostore.net, *.westus2.azuredatalakestore.net, *.westus2.azuredatalakeanalytics.net, *.adlus81-c08.projectcabostore.net, *.adlus81-c08.projectkonacompute.net, *.adlus81-c09.projectcabostore.net, *.adlus81-c09.projectkonacompute.net, *.adlus81-c17.projectcabostore.net, *.adlus81-c17.projectkonacompute.net, *.adlus81-cbcp.projectcabostore.net, *.adlus81-cbcp.projectkonacompute.net]
 stack trace: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <119d555e-eb39-48ad-840d-bb1db9317a85.livy.pools.westus2.azuredatalakeanalytics.net> doesn't match any of the subject alternative names: [*.adlus81.projectkonacompute.net, *.adlus81.projectcabostore.net, *.azuredatalakestore.net, *.azuredatalakeanalytics.net, adlus81.projectkonacompute.net, adlus81.projectcabostore.net, *.westus2.azuredatalakestore.net, *.westus2.azuredatalakeanalytics.net, *.adlus81-c08.projectcabostore.net, *.adlus81-c08.projectkonacompute.net, *.adlus81-c09.projectcabostore.net, *.adlus81-c09.projectkonacompute.net, *.adlus81-c17.projectcabostore.net, *.adlus81-c17.projectkonacompute.net, *.adlus81-cbcp.projectcabostore.net, *.adlus81-cbcp.projectkonacompute.net]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:467)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.createBatchSparkJob(SparkBatchSubmission.java:172)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.createBatchJob(SparkBatchJob.java:272)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$submit$41(SparkBatchJob.java:1045)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:53)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by t-rufang** [comment]
When we submit job to serverless cluster, we have to access `${cluster-id}.livy.pools.westus2.azuredatalakeanalytics.net`, which means we need a certificate for `*.livy.pools.westus2.azuredatalakeanalytics.net`. FYI, the dogfood env can work since the certificate is for `*.livy.pools.centralus.konaaccountdogfood.net`
