### ISSUE TITLE
[IntelliJ][ReportedByUser] Browse Web App

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#1770]
IntelliJ build version: 2018.1.2 IC-181.4668.68
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.8.0
Error message: java.lang.IllegalArgumentException: Malformed escape pair at index 2081: https://github.com/Microsoft/azure-tools-for-java/issues/new?title=%5BIntelliJ%5D%5BReportedByUser%5D+MS+Azure+Explorer+-+Error+Loading+cosmos-partner-c14&labels=IntelliJ%2Cbug&body=IntelliJ+build+version%3A+2018.1.2+IC-181.4668.68%0AJDK%3A+JetBrains+s.r.o+1.8.0_152-release%0APlugin+version%3A+3.8.0%0AError+message%3A+rx.exceptions.OnErrorNotImplementedException%3A+Bad+Request%0D%0A%09at+rx.internal.util.InternalObservableUtils%24ErrorNotImplementedAction.call%28InternalObservableUtils.java%3A386%29%0D%0A%09at+rx.internal.util.InternalObservableUtils%24ErrorNotImplementedAction.call%28InternalObservableUtils.java%3A383%29%0D%0A%09at+rx.internal.util.ActionSubscriber.onError%28ActionSubscriber.java%3A44%29%0D%0A%09at+rx.observers.SafeSubscriber._onError%28SafeSubscriber.java%3A153%29%0D%0A%09at+rx.observers.SafeSubscriber.onError%28SafeSubscriber.java%3A115%29%0D%0A%09at+rx.internal.operators.OperatorSwitchIfEmpty%24ParentSubscriber.onError%28OperatorSwitchIfEmpty.java%3A84%29%0D%0A%09at+rx.internal.operators.OnSubscribeMap%24MapSubscriber.onError%28OnSubscribeMap.java%3A88%29%0D%0A%09at+rx.internal.operators.OnSubscribeMap%24MapSubscriber.onError%28OnSubscribeMap.java%3A88%29%0D%0A%09at+rx.internal.operators.OperatorMerge%24MergeSubscriber.reportError%28OperatorMerge.java%3A266%29%0D%0A%09at+rx.internal.operators.OperatorMerge%24MergeSubscriber.checkTerminate%28OperatorMerge.java%3A818%29%0D%0A%09at+rx.internal.operators.OperatorMerge%24MergeSu

=================================================================
rx.exceptions.OnErrorNotImplementedException: Bad Request
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSwitchIfEmpty$ParentSubscriber.onError(OperatorSwitchIfEmpty.java:84)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:852)
	at rx.observers.Subscribers$5.onError(Subscribers.java:230)
	at rx.internal.operators.OperatorDoAfterTerminate$1.onError(OperatorDoAfterTerminate.java:56)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44)
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:10010)
	at com.microsoft.azure.sparkserverless.serverexplore.sparkserverlessnode.SparkServerlessADLAccountNode.refreshItems(SparkServerlessADLAccountNode.java:53)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:136)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.HttpResponseException: Bad Request
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$toStringOnlyOkResponse$1(HttpObservable.java:239)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:64)
	... 42 more

**Comment by jingyanjingyan** [comment]
```
java.lang.IllegalArgumentException: Malformed escape pair at index 2082: https://github.com/Microsoft/azure-tools-for-java/issues/new?title=%5BIntelliJ%5D%5BReportedByUser%5D+Uncaught+Exception+Unexpected+exception%3A+Malformed+escape+pair+at+index+2081%3A+https%3A%2F%2Fgithub.com%2FMicrosoft%2Fazure-tools-for-java%2Fissues%2Fnew%3Ftitle%3D%255BIntelliJ%255D%255BReportedByUser%255D%2BMS%2BAzure%2BExplorer%2B-%2BError%2BLoading%2Bcosmos-partner-c14%26labels%3DIntelliJ%252Cbug%26body%3DIntelliJ%2Bbuild%2Bversion%253A%2B2018.1.2%2BIC-181.4668.68%250AJDK%253A%2BJetBrains%2Bs.r.o%2B1.8.0_152-release%250APlugin%2Bversion%253A%2B3.8.0%250AError%2Bmessage%253A%2Brx.exceptions.OnErrorNotImplementedException%253A%2BBad%2BRequest%250D%250A%2509at%2Brx.internal.util.InternalObservableUtils%2524ErrorNotImplementedAction.call%2528InternalObservableUtils.java%253A386%2529%250D%250A%2509at%2Brx.internal.util.InternalObservableUtils%2524ErrorNotImplementedAction.call%2528InternalObservableUtils.java%253A383%2529%250D%250A%2509at%2Brx.internal.util.ActionSubscriber.onError%2528ActionSubscriber.java%253A44%2529%250D%250A%2509at%2Brx.observers.SafeSubscriber._onError%2528SafeSubscriber.java%253A153%2529%250D%250A%2509at%2Brx.observers.SafeSubscriber.onError%2528SafeSubscriber.java%253A115%2529%250D%250A%2509at%2Brx.internal.operators.OperatorSwitchIfEmpty%2524ParentSubscriber.onError%2528OperatorSwitchIfEmpty.java%253A84%2529%250D%250A%2509at%2Brx.internal.operators.OnSubscribeMap%2524MapSubscriber.onError%2528OnSubscribeMap.java%253A88%2529%250D%250A%2509at%2Brx.internal.operators.OnSubscribeMap%2524MapSubscriber.onError%2528OnSubscribeMap.java%253A88%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.reportError%2528OperatorMerge.java%253A266%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.checkTerminate%2528OperatorMerge.java%253A818%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.emitLoop%2528OperatorMerge.java%253A579%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.emit%2528OperatorMerge.java%253A568%2529%250D%
	at java.net.URI.create(URI.java:852)
	at com.microsoft.intellij.helpers.IDEHelperImpl.openLinkInBrowser(IDEHelperImpl.java:460)
	at com.microsoft.intellij.feedback.GithubIssue.report(GithubIssue.kt:60)
	at com.microsoft.intellij.feedback.MSErrorReportHandler.submit(MSErrorReportHandler.kt:49)
	at com.intellij.diagnostic.IdeErrorsDialog$BlameAction.reportMessage(IdeErrorsDialog.java:909)
	at com.intellij.diagnostic.IdeErrorsDialog$BlameAction.actionPerformed(IdeErrorsDialog.java:880)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 2082: https://github.com/Microsoft/azure-tools-for-java/issues/new?title=%5BIntelliJ%5D%5BReportedByUser%5D+Uncaught+Exception+Unexpected+exception%3A+Malformed+escape+pair+at+index+2081%3A+https%3A%2F%2Fgithub.com%2FMicrosoft%2Fazure-tools-for-java%2Fissues%2Fnew%3Ftitle%3D%255BIntelliJ%255D%255BReportedByUser%255D%2BMS%2BAzure%2BExplorer%2B-%2BError%2BLoading%2Bcosmos-partner-c14%26labels%3DIntelliJ%252Cbug%26body%3DIntelliJ%2Bbuild%2Bversion%253A%2B2018.1.2%2BIC-181.4668.68%250AJDK%253A%2BJetBrains%2Bs.r.o%2B1.8.0_152-release%250APlugin%2Bversion%253A%2B3.8.0%250AError%2Bmessage%253A%2Brx.exceptions.OnErrorNotImplementedException%253A%2BBad%2BRequest%250D%250A%2509at%2Brx.internal.util.InternalObservableUtils%2524ErrorNotImplementedAction.call%2528InternalObservableUtils.java%253A386%2529%250D%250A%2509at%2Brx.internal.util.InternalObservableUtils%2524ErrorNotImplementedAction.call%2528InternalObservableUtils.java%253A383%2529%250D%250A%2509at%2Brx.internal.util.ActionSubscriber.onError%2528ActionSubscriber.java%253A44%2529%250D%250A%2509at%2Brx.observers.SafeSubscriber._onError%2528SafeSubscriber.java%253A153%2529%250D%250A%2509at%2Brx.observers.SafeSubscriber.onError%2528SafeSubscriber.java%253A115%2529%250D%250A%2509at%2Brx.internal.operators.OperatorSwitchIfEmpty%2524ParentSubscriber.onError%2528OperatorSwitchIfEmpty.java%253A84%2529%250D%250A%2509at%2Brx.internal.operators.OnSubscribeMap%2524MapSubscriber.onError%2528OnSubscribeMap.java%253A88%2529%250D%250A%2509at%2Brx.internal.operators.OnSubscribeMap%2524MapSubscriber.onError%2528OnSubscribeMap.java%253A88%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.reportError%2528OperatorMerge.java%253A266%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.checkTerminate%2528OperatorMerge.java%253A818%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.emitLoop%2528OperatorMerge.java%253A579%2529%250D%250A%2509at%2Brx.internal.operators.OperatorMerge%2524MergeSubscriber.emit%2528OperatorMerge.java%253A568%2529%250D%
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.scanEscape(URI.java:2978)
	at java.net.URI$Parser.scan(URI.java:3001)
	at java.net.URI$Parser.checkChars(URI.java:3019)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 44 more
```

**Comment by wezhang** [comment]
URI didn't cut right
