### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception org.apache.http.client.HttpResponseException: Bad Request java.lang.RuntimeException: org.apache.http.client.HttpResponseException: Bad Request

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1772]
IntelliJ build version: 2018.1.2 IC-181.4668.68
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.8.0
Additional Info: None
Parent component: javax.swing.JPanel[,0,0,747x287,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.border.EmptyBorder@24cfed53,flags=9,maximumSize=,minimumSize=,preferredSize=]
Error message: IdeaLoggingEvent[message=org.apache.http.client.HttpResponseException: Bad Request, throwable=java.lang.RuntimeException: org.apache.http.client.HttpResponseException: Bad Request
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:464)
	at rx.observables.BlockingObservable.singleOrDefault(BlockingObservable.java:373)
	at com.microsoft.azure.sparkserverless.serverexplore.ui.SparkServerlessProvisionDialog.setClusterNameSets(SparkServerlessProvisionDialog.java:93)
	at com.microsoft.azure.sparkserverless.serverexplore.ui.SparkServerlessProvisionDialog.<init>(SparkServerlessProvisionDialog.java:116)
	at com.microsoft.azure.sparkserverless.SparkServerlessClusterOpsCtrl.lambda$new$2(SparkServerlessClusterOpsCtrl.java:60)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(Exe

**Comment by jingyanjingyan** [comment]
fix
