### ISSUE TITLE
[IntelliJ][Spark on ADL] web app refreshing has warning 

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1775]
Enrironment: PPE
Repro Steps:
1, Sign in and refresh on Azure node 
Result:
Warning dialog
![image](https://user-images.githubusercontent.com/36756024/42743723-e990c392-88f8-11e8-85b8-03da983bd6ed.png)

com.microsoft.azure.CloudException: Status code 502, {"error":{"code":"InvalidGatewayHost","message":"Host name resolution failed for 'Microsoft.Web'; cannot fulfill the request."}}: Host name resolution failed for 'Microsoft.Web'; cannot fulfill the request.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.listDelegate(WebAppsInner.java:1302)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$000(WebAppsInner.java:49)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$5.call(WebAppsInner.java:1289)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$5.call(WebAppsInner.java:1285)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1205)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listWebAppsBySubscriptionId(AzureWebAppMvpModel.java:335)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listWebApps(AzureWebAppMvpModel.java:354)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModulePresenter.onModuleRefresh(WebAppModulePresenter.java:32)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModule.refreshItems(WebAppModule.java:35)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:136)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jdneo** [comment]
@jingyanjingyan Could you please provide more details about this issue? Like repro steps, etc...

**Comment by jingyanjingyan** [comment]
Update the repro steps with screenshot

**Comment by jdneo** [comment]
@jingyanjingyan May I ask what is `PPE` environment?

**Comment by jingyanjingyan** [comment]
Pre product environment? It used for test, but i am not sure the difference compare to product environment. This issue is not repro with product environment from my side.

**Comment by jdneo** [comment]
@jingyanjingyan Just used the package with build number 676. I cannot repro this issue either.

Closing this for now. But please feel free to reopen this if anyone find any stable repro steps. Thanks.
