### ISSUE TITLE
[IntelliJ][ReportedByUser] User feedback

### ISSUE THREAD

**Issue by andrejjovanov** [Microsoft/azure-tools-for-java#1831]
IntelliJ build version: 2018.1.6 IC-181.5540.7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.1

# 1. Are you satisfied with the Azure Spark development functionalities & experiences offered in Azure Toolkit for IntelliJ? Please rate us from 1 (poor) to 10 (excellent).
1
# 2. What did you like or dislike about Azure Toolkit for IntelliJ?
I have problem signing in with my students account from Sierra or Windows 10

# 3. What enhancements would you like Azure Toolkit for IntelliJ to implement?
Live support for Azure toolkit :(

**Comment by wezhang** [comment]
@andrejjovanov , could you provide more logs about your signing in issue? You can find the IDEA log file from the menu `Help -> Show Log In Explorer`, and the Azure Plugin log file in `<UserHomeFolder>/AzureToolsForIntelliJ/corelibs.log`

**Comment by andrejjovanov** [comment]
**Help -> Show Log In Explorer**

2018-07-29 00:05:41,963 [   3264]  ERROR - ij.components.ComponentManager - Cyclic component initialization: class com.intellij.execution.ExecutorRegistry [Plugin: com.intellij] 
com.intellij.diagnostic.PluginException: Cyclic component initialization: class com.intellij.execution.ExecutorRegistry [Plugin: com.intellij]
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:464)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:155)
	at com.intellij.execution.ExecutorRegistry.getInstance(ExecutorRegistry.java:29)
	at com.intellij.execution.executors.DefaultDebugExecutor.getDebugExecutorInstance(DefaultDebugExecutor.java:82)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:99)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:43)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionIndex(ExtensionPointImpl.java:329)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:139)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:260)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:190)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:105)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:93)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.intellij.execution.ExecutorRegistryImpl.initComponent(ExecutorRegistryImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
	at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-07-29 00:05:41,966 [   3267]  ERROR - ij.components.ComponentManager - IntelliJ IDEA 2018.1.4  Build #IC-181.5087.20 
2018-07-29 00:05:41,966 [   3267]  ERROR - ij.components.ComponentManager - JDK: 1.8.0_152-release 
2018-07-29 00:05:41,966 [   3267]  ERROR - ij.components.ComponentManager - VM: OpenJDK 64-Bit Server VM 
2018-07-29 00:05:41,966 [   3267]  ERROR - ij.components.ComponentManager - Vendor: JetBrains s.r.o 
2018-07-29 00:05:41,966 [   3267]  ERROR - ij.components.ComponentManager - OS: Windows 10 
2018-07-29 00:05:41,967 [   3268]  ERROR - nsions.impl.ExtensionPointImpl - Fatal error initializing 'com.intellij.execution.ExecutorRegistry' 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:255)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:155)
	at com.intellij.execution.ExecutorRegistry.getInstance(ExecutorRegistry.java:29)
	at com.intellij.execution.executors.DefaultDebugExecutor.getDebugExecutorInstance(DefaultDebugExecutor.java:82)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:99)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:43)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionIndex(ExtensionPointImpl.java:329)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:139)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:260)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:190)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:105)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:93)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.intellij.execution.ExecutorRegistryImpl.initComponent(ExecutorRegistryImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
	at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Recursive processAdapters() detected. You must have called 'getExtensions()' from within your extension constructor - don't. Either pass extension via constructor parameter or call getExtensions() later.
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:217)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:190)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:105)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:93)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.intellij.execution.ExecutorRegistryImpl.initComponent(ExecutorRegistryImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
	... 43 more
2018-07-29 00:05:41,967 [   3268]  ERROR - nsions.impl.ExtensionPointImpl - IntelliJ IDEA 2018.1.4  Build #IC-181.5087.20 
2018-07-29 00:05:41,967 [   3268]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 1.8.0_152-release 
2018-07-29 00:05:41,967 [   3268]  ERROR - nsions.impl.ExtensionPointImpl - VM: OpenJDK 64-Bit Server VM 
2018-07-29 00:05:41,967 [   3268]  ERROR - nsions.impl.ExtensionPointImpl - Vendor: JetBrains s.r.o 
2018-07-29 00:05:41,967 [   3268]  ERROR - nsions.impl.ExtensionPointImpl - OS: Windows 10 
2018-07-29 00:05:42,443 [   3744]   INFO - plication.impl.ApplicationImpl - 92 application components initialized in 3104ms 
2018-07-29 00:05:42,443 [   3744]   INFO - pl$FileIndexDataInitialization - Initialization done:538 
2018-07-29 00:05:42,456 [   3757]   INFO - .intellij.idea.IdeaApplication - App initialization took 4226 ms 
2018-07-29 00:05:42,503 [   3804]   INFO - exImpl$StubIndexInitialization - Initialization done:60 
2018-07-29 00:05:43,057 [   4358]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@54097652 
2018-07-29 00:05:43,229 [   4530]   INFO - com.intellij.ide.ui.UISettings - Loaded: fontSize=12, fontScale=1.0; restored: fontSize=12, fontScale=1.0 
2018-07-29 00:05:44,137 [   5438]   INFO - microsoft.intellij.AzurePlugin - Starting Azure Plugin 
2018-07-29 00:05:44,324 [   5625]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.ui.search.SearchableOptionPreloader@776b735f 
2018-07-29 00:05:44,490 [   5791]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.codeInsight.completion.CompletionPreloader@403e46b0 
2018-07-29 00:05:44,490 [   5791]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.ide.actions.GotoClassPresentationUpdater@302588df 
2018-07-29 00:05:45,413 [   6714]   INFO - ellij.project.impl.ProjectImpl - 155 project components initialized in 2607 ms 
2018-07-29 00:05:45,569 [   6870]   INFO - le.impl.ModuleManagerComponent - 1 module(s) loaded in 156 ms 
2018-07-29 00:05:45,668 [   6969]   INFO - j.ide.script.IdeStartupScripts - 0 startup script(s) found 
2018-07-29 00:05:46,105 [   7406]   INFO - CompilerBackwardReferenceIndex - backward reference index version differ due to: class java.io.FileNotFoundException 
2018-07-29 00:05:46,371 [   7672]   INFO - ge.ExternalProjectsDataStorage - Loaded external projects data in 0 millis 
2018-07-29 00:05:46,412 [   7713]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 104ms; general responsiveness: ok; EDT responsiveness: ok 
2018-07-29 00:05:46,459 [   7760]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Azure Activity Log) or icon jar:file:/C:/Users/Asus/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/RoleFolder.gif 
2018-07-29 00:05:46,459 [   7760]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Azure Explorer) or icon jar:file:/C:/Users/Asus/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/AzureExplorer_16.png 
2018-07-29 00:05:46,553 [   7854]   INFO - .diagnostic.PerformanceWatcher - Post-startup activities under progress took 338ms; general responsiveness: ok; EDT responsiveness: ok 
2018-07-29 00:05:46,840 [   8141]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Remote Spark Job in Cluster) or icon jar:file:/C:/Users/Asus/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/ToolWindowSparkJobRun.png 
2018-07-29 00:05:46,840 [   8141]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Debug Remote Spark Job in Cluster) or icon jar:file:/C:/Users/Asus/.IdeaIC2018.1/config/plugins/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar!/icons/ToolWindowSparkJobDebug.png 
2018-07-29 00:05:46,950 [   8251]   INFO - j.ide.ui.OptionsTopHitProvider - 268 ms spent to cache options in application 
2018-07-29 00:05:46,950 [   8251]   INFO - tartup.impl.StartupManagerImpl - D:/FINKI/WEB/untitled/.idea case-sensitivity: expected=false actual=false 
2018-07-29 00:05:46,965 [   8266]   INFO - pl.projectlevelman.NewMappings - VCS Root: [] - [<Project>] 
2018-07-29 00:05:47,090 [   8391]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 4399 ms 
2018-07-29 00:05:47,840 [   9141]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 1428ms; general responsiveness: ok; EDT responsiveness: ok 
2018-07-29 00:05:48,105 [   9406]   INFO - j.ide.ui.OptionsTopHitProvider - 139 ms spent to cache options in project 
2018-07-29 00:05:48,168 [   9469]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 7/28/2018 10:13 PM) 
2018-07-29 00:05:48,569 [   9870]   INFO - CompilerWorkspaceConfiguration - Available processors: 8 
2018-07-29 00:05:49,293 [  10594]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 31 ms 
2018-07-29 00:05:53,886 [  15187]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1 
2018-07-29 00:05:54,827 [  16128]   INFO - rojectCodeStyleSettingsManager - Initialized from default code style settings. 
2018-07-29 00:06:10,808 [  32109]   INFO - plication.impl.ApplicationImpl - Received external Windows command line: current directory C:\WINDOWS\system32, command line "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4\bin\idea64.exe" "C:\Users\Asus\.IdeaIC2018.1\system\log\idea.log" 
2018-07-29 00:06:10,808 [  32109]   INFO - ellij.ide.CommandLineProcessor - External command line: 
2018-07-29 00:06:10,808 [  32109]   INFO - ellij.ide.CommandLineProcessor - Dir: C:\WINDOWS\system32 
2018-07-29 00:06:10,808 [  32109]   INFO - ellij.ide.CommandLineProcessor - "C:\Users\Asus\.IdeaIC2018.1\system\log\idea.log" 
2018-07-29 00:06:10,808 [  32109]   INFO - ellij.ide.CommandLineProcessor - ----- 
2018-07-29 00:06:10,996 [  32297]   INFO - microsoft.intellij.AzurePlugin - Starting Azure Plugin 

**there's nothing in **corelibs.log** 
**nothing written in **idea.log** after the sign in error 

![sign in azure toolkit](https://user-images.githubusercontent.com/26550570/43361013-90d1b3f8-92c4-11e8-969a-61bc7718b1af.png)

**Comment by wezhang** [comment]
Feel free to reopen it if hits again.
