### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception updateSubscriptionWithProgressDialog java.lang.IllegalArgumentException%3A Please specify either a client key or a client certificate.

### ISSUE THREAD

**Issue by field-theory** [microsoft/azure-tools-for-java#1847]
IntelliJ build version: 2018.2 IU-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2
Additional Info: None
Parent component: com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
Error message:
```
 IdeaLoggingEvent[message=updateSubscriptionWithProgressDialog, throwable=java.lang.IllegalArgumentException: Please specify either a client key or a client certificate.
        at com.microsoft.azure.credentials.AuthFile.generateCredentials(AuthFile.java:126)
        at com.microsoft.azure.credentials.ApplicationTokenCredentials.fromFile(ApplicationTokenCredentials.java:111)
        at com.microsoft.azure.management.Azure$ConfigurableImpl.authenticate(Azure.java:227)
        at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.auth(ServicePrincipalAzureManager.java:81)
        at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getTenants(ServicePrincipalAzureManager.java:136)
        at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getSubscriptionsWithTenant(ServicePrincipalAzureManager.java:106)
        at com.microsoft.azuretools.authmanage.SubscriptionManager.updateAccountSubscriptionList(SubscriptionManager.java:106)
        at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(SubscriptionManagerPersist.java:67)
        at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:91)
        at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails
```

**Comment by wezhang** [comment]
@field-theory Could you try the interactive logon mode?
