### ISSUE TITLE
[IntelliJ][ReportedByUser][NPE] Uncaught Exception Error populating subscriptions and resource groups. java.lang.NullPointerException

### ISSUE THREAD

**Issue by estatic** [microsoft/azure-tools-for-java#1856]
IntelliJ build version: 2018.2 IU-182.3684.101
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2
Additional Info: None
Parent component: com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,22,837x494,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
Error message:
```
 IdeaLoggingEvent[message=Error populating subscriptions and resource groups., throwable=java.lang.NullPointerException
        at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.populateValues(ApplicationInsightsNewDialog.java:120)
        at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.init(ApplicationInsightsNewDialog.java:99)
        at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.<init>(ApplicationInsightsNewDialog.java:71)
        at com.microsoft.intellij.ui.AppInsightsMngmtPanel$1.run(AppInsightsMngmtPanel.java:234)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:648)
        at com.microsoft.intellij.ui.AppInsightsMngmtPanel.createNewDilaog(AppInsightsMngmtPanel.java:231)
        at com.microsoft.intellij.ui.AppInsightsMngmtPanel.lambda$newButtonListener$0(AppInsightsMngmtPanel.java:222)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252
```

**Comment by wezhang** [comment]
@Eskibear Could you have a look? Looks like Application Insights related issue.

**Comment by Eskibear** [comment]
https://github.com/Microsoft/azure-tools-for-java/blame/a315479aae801a710dee4d010d77b09aced01004/PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/ui/ApplicationInsightsNewDialog.java#L120

Potential NPE in outdated code. 
Should use latest API `AzureMvpModel.getInstance().getSelectedSubscriptions()` to handle subscriptions.

**Comment by andxu** [comment]
Fixed in this PR https://github.com/microsoft/azure-tools-for-java/pull/4458
