### ISSUE TITLE
[IntelliJ][ReportedByUser] NPE Error

### ISSUE THREAD

**Issue by ColemanTO** [microsoft/azure-tools-for-java#1870]
IntelliJ build version: 2018.2.1 IC-182.3911.36
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.9.0-2018.2
Error message:
```
 java.lang.NullPointerException
	at com.microsoft.azure.management.network.implementation.NicIPConfigurationImpl.subnetToAssociate(NicIPConfigurationImpl.java:286)
	at com.microsoft.azure.management.network.implementation.NicIPConfigurationImpl.ensureConfigurations(NicIPConfigurationImpl.java:247)
	at com.microsoft.azure.management.network.implementation.NetworkInterfaceImpl.beforeCreating(NetworkInterfaceImpl.java:497)
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupableParentResourceImpl.createResourceAsync(GroupableParentResourceImpl.java:52)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreateUpdateTask.executeAsync(CreateUpdateTask.java:56)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroupEntry.executeTaskAsync(TaskGroupEntry.java:77)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeTaskAsync(TaskGroup.java:208)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeReadyTasksAsync(TaskGroup.java:168)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeAsync(TaskGroup.java:108)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.executeTaskGroupAsyncStreaming(CreatableUpdatableImpl.java:176)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.createAsync(CreatableUpdatableImpl.java:127)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:137)
	at com.microsoft.azure.manag...
```

**Comment by ColemanTO** [comment]
Creating a new VM

**Comment by Flanker32** [comment]
@ColemanTO Thanks for your report and really sorry for the late reply, we have update the Azure SDK and could you please try the latest release to see whether this issue could be reproduced?
