### ISSUE TITLE
[IntelliJ][ReportedByUser][DeviceCodeFlow] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by tccSup** [microsoft/azure-tools-for-java#1880]
IntelliJ build version: 2018.2.1 IU-182.3911.36
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1366x705,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Status code 400, {"error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.KeyVault'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Reso

**Comment by wezhang** [comment]
@Eskibear , could you have a look?

**Comment by andxu** [comment]
@Flanker32 ,Register Key Vault Provider for subs before using it.

**Comment by andxu** [comment]
Seems we have registered in before start, see https://github.com/microsoft/azure-tools-for-java/blob/0efe5e430305369e17dadc214c256cbb4a906372/Utils/azuretools-core/src/com/microsoft/azuretools/utils/AzureRegisterProviderNamespaces.java,
please reopen it if it occurs again.
