### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'HDInsightSettings': class com.microsoft.azure.hdinsight.common.HDInsightSettings and class com.microsoft.intellij.ApplicationSettings

### ISSUE THREAD

**Issue by samirissa00** [Microsoft/azure-tools-for-java#1935]
IntelliJ build version: 2018.2.2 IC-182.4129.33
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1920x1017,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'HDInsightSettings': class com.microsoft.azure.hdinsight.common.HDInsightSettings and class com.microsoft.intellij.ApplicationSettings
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.configurationStore.ComponentStoreImpl.doAddComponent(ComponentStoreImpl.kt:300)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:114)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:15)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:212)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:247)
	at com.intellij.util.pico.Defau

**Comment by wezhang** [comment]
Thanks @samirissa00 ! It's fixed.
