### ISSUE TITLE
[IntelliJ][Spark on ADL] Submit fail

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#1957]
Build: PR1888

Repro Steps:
1. Submit job with following config
![image](https://user-images.githubusercontent.com/36756024/45131175-9de73a00-b140-11e8-9d8d-9fee9bf0a0fa.png)

Result:
Submit fail with following log
Package and deploy the job to Spark cluster
INFO: Begin uploading file C:/Users/v-yajing/Desktop/default_artifact.jar to Azure Datalake store adl://cosmosadmin-c09.azuredatalakestore.net/SparkSubmission/2018/09/06/531170bf-aa5c-4b30-ae3c-9c3261085b46/default_artifact.jar ...
INFO: Upload to Azure Datalake store 67643 bytes successfully.
ERROR: org.apache.http.client.ClientProtocolException
 stack trace: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.createBatchSparkJob(SparkBatchSubmission.java:172)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.createBatchJob(SparkBatchJob.java:272)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$submit$41(SparkBatchJob.java:1044)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 25 more

**Comment by wezhang** [comment]
Is it 100% reproduced?

**Comment by jingyanjingyan** [comment]
Not 100%, repro a lot yesterday

**Comment by wezhang** [comment]
> org.apache.http.ProtocolException: Target host is not specified

**Comment by wezhang** [comment]
Should be backend issue, we'd better to provide more specify error message.

**Comment by wezhang** [comment]
Tracked by #1825
