### ISSUE TITLE
Run on web app get NPE error 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2020]
Build: Develop731
OS: Windows/Mac/Linux

Can be Reproduced by below steps:

1. Right-click the project and choose Azure
2. Select Run on Web App
3. Click Cancel in the Run on Web App dialog box

Log:
```
java.lang.NullPointerException
	at com.microsoft.intellij.runner.webapp.webappconfig.ui.WebAppSettingPanel.isAbleToDeployToRoot(WebAppSettingPanel.java:563)
	at com.microsoft.intellij.runner.webapp.webappconfig.ui.WebAppSettingPanel.toggleDeployToRoot(WebAppSettingPanel.java:551)
	at com.microsoft.intellij.runner.webapp.webappconfig.ui.WebAppSettingPanel.apply(WebAppSettingPanel.java:425)
	at com.microsoft.intellij.runner.webapp.webappconfig.ui.WebAppSettingPanel.apply(WebAppSettingPanel.java:78)
	at com.microsoft.intellij.runner.AzureSettingsEditor.applyEditorTo(AzureSettingsEditor.java:45)
	at com.microsoft.intellij.runner.AzureSettingsEditor.applyEditorTo(AzureSettingsEditor.java:36)
	at com.intellij.openapi.options.SettingsEditor.applyTo(SettingsEditor.java:102)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.applyEditorTo(ConfigurationSettingsEditor.java:303)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.applyEditorTo(ConfigurationSettingsEditor.java:282)
	at com.intellij.openapi.options.SettingsEditor.applyTo(SettingsEditor.java:102)
	at com.intellij.openapi.options.CompositeSettingsEditor.applyEditorTo(CompositeSettingsEditor.java:62)
	at com.intellij.openapi.options.SettingsEditor.applyTo(SettingsEditor.java:102)
	at com.intellij.execution.impl.ConfigurationSettingsEditor.getSnapshot(ConfigurationSettingsEditor.java:221)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.getSnapshot(ConfigurationSettingsEditorWrapper.java:103)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.getSnapshot(ConfigurationSettingsEditorWrapper.java:26)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.getSnapshot(SingleConfigurationConfigurable.java:298)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.getValidationResult(SingleConfigurationConfigurable.java:183)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.access$1500(SingleConfigurationConfigurable.java:47)
	at com.intellij.execution.impl.SingleConfigurationConfigurable$MyValidatableComponent.getValidationResult(SingleConfigurationConfigurable.java:397)
	at com.intellij.execution.impl.SingleConfigurationConfigurable$MyValidatableComponent.updateWarning(SingleConfigurationConfigurable.java:401)
	at com.intellij.execution.impl.SingleConfigurationConfigurable$MyValidatableComponent.<init>(SingleConfigurationConfigurable.java:350)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.reset(SingleConfigurationConfigurable.java:145)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:101)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:122)
	at com.microsoft.intellij.actions.WebDeployAction.runConfiguration(WebDeployAction.java:80)
	at com.microsoft.intellij.actions.WebDeployAction.lambda$onActionPerformed$0(WebDeployAction.java:62)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by SummerSun** [comment]
@bsaby Fixed. Please help verify this in the newest bits. Thanks.

**Comment by bsaby** [comment]
Test passed on Windows and Mac.
Build used: dev 734 and dev739
