### ISSUE TITLE
NPE error when clicking the web app in Azure Explorer

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2022]
Build: Develop731
OS: Windows/Mac/Linux

**Repro steps:**
1. Click a Web App in Azure explorer
2. Expand the web app

**Result:**
![image](https://user-images.githubusercontent.com/22470312/45617773-f524cd00-baa5-11e8-8830-0f1c6b2d583e.png)
**Log:**
```
java.lang.NullPointerException
	at com.microsoft.azuretools.azureexplorer.views.ServiceExplorerView$ViewLabelProvider.getImage(ServiceExplorerView.java:279)
	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.getImage(WrappedViewerLabelProvider.java:101)
	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.update(WrappedViewerLabelProvider.java:146)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:943)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:117)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1022)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2158)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:837)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:815)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:601)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:763)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleTreeExpand(AbstractTreeViewer.java:1535)
	at org.eclipse.jface.viewers.TreeViewer.handleTreeExpand(TreeViewer.java:886)
	at org.eclipse.jface.viewers.AbstractTreeViewer$3.treeExpanded(AbstractTreeViewer.java:1547)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:133)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7532)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5786)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:2001)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5344)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4821)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2197)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1551)
	at org.eclipse.swt.widgets.Tree.WM_LBUTTONDOWN(Tree.java:6428)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4801)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5960)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4757)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2303)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3532)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
       at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
       at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
```

**Comment by Eskibear** [comment]
Missing icon issue. It should have been fixed.

**Comment by bsaby** [comment]
Build used: daily 534

Still repro this issue, I think now that we don't have the plan for the new feature now, how about hide the new feature code in Eclipse, so that we can find if there are regrssion issues af

**Comment by bsaby** [comment]
Build used: daily534
Still repro this issue in today's regression test, I think that since we don't have a new feature plan now, how about hide the new feature code in Eclipse so that we can find out if there are regrssion issues in the previous web app feature after SDK upgrade.

**Comment by Eskibear** [comment]
@SummerSun How about adding the related icons into eclipse plugin to unblock regression tests?

**Comment by bsaby** [comment]
Fix this issue in dev994 bits, close it.
