### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2024]
Build: Develop731
OS: Windows/Mac/Linux

Repro steps:
1. Create a proejct(Maven web app/web project) or open a spring boot jar project
2. Click 'Run on Web app' option to deploy this project to linux web app 
3. After deployment and reopen the intelliJ window

Result:
There is an error in the lower right corner of IntelliJ

```
Cannot read scheme com_microsoft_intellij_run_configuration_WebAppConfigurationType-Azure Web App_ demo1_demo1_ factoryName_ Azure Web App.xml: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.microsoft.azure.management.appservice.RuntimeStack.<init>()
com.intellij.util.xmlb.XmlSerializationException: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.microsoft.azure.management.appservice.RuntimeStack.<init>()
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:102)
	at com.microsoft.intellij.runner.AzureRunConfigurationBase.readExternal(AzureRunConfigurationBase.java:62)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:219)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:51)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:34)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:20)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:69)
	at com.intellij.configurationStore.SchemeManagerImpl.loadScheme(SchemeManagerImpl.kt:503)
	at com.intellij.configurationStore.SchemeManagerImpl.access$loadScheme(SchemeManagerImpl.kt:64)
	at com.intellij.configurationStore.SchemeManagerImpl$loadSchemes$2.invoke(SchemeManagerImpl.kt:335)
	at com.intellij.configurationStore.SchemeManagerImpl$loadSchemes$2.invoke(SchemeManagerImpl.kt:64)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:31)
	at com.intellij.configurationStore.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:333)
	at com.intellij.configurationStore.SchemeManagerImpl.reload(SchemeManagerImpl.kt:381)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:572)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:47)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:375)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:331)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:121)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:96)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.requestLoadWorkspaceAndProjectRunConfiguration(ProjectRunConfigurationInitializer.kt:47)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.access$requestLoadWorkspaceAndProjectRunConfiguration(ProjectRunConfigurationInitializer.kt:24)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$1.projectComponentsInitialized(ProjectRunConfigurationInitializer.kt:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy60.projectComponentsInitialized(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:279)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:274)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectWithProgress(ProjectManagerImpl.java:536)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$200(ProjectManagerImpl.java:54)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:482)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:479)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:320)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:565)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.microsoft.azure.management.appservice.RuntimeStack.<init>()
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:174)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:427)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:119)
	at com.intellij.util.xmlb.NotNullDeserializeBinding.deserializeUnsafe(NotNullDeserializeBinding.java:32)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:45)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:94)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:216)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:170)
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:96)
	... 61 more
Caused by: java.lang.NoSuchMethodException: com.microsoft.azure.management.appservice.RuntimeStack.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:412)
	... 69 more

```

**Comment by Eskibear** [comment]
Same blocking issue with #2027

**Comment by SummerSun** [comment]
@bsaby Fixed. Please help verify with the latest build.

**Comment by bsaby** [comment]
Test passed on Windows and Mac.
Build used: dev741
