### ISSUE TITLE
update failed for AnAction(com.intellij.execution.actions.RunContextAction) with ID=RunClass: org/jetbrains/plugins/scala/runner/ScalaMainMethodUtil

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2033]
Build: Dev739

Right click the project in IntelliJ
![image](https://user-images.githubusercontent.com/22470312/45668111-396ba800-bb4e-11e8-9c04-1b23322163d6.png)
Log:
```
update failed for AnAction(com.intellij.execution.actions.RunContextAction) with ID=RunClass: org/jetbrains/plugins/scala/runner/ScalaMainMethodUtil
java.lang.NoClassDefFoundError: org/jetbrains/plugins/scala/runner/ScalaMainMethodUtil
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.findScalaMainClass(SparkBatchJobLocalRunConfigurationProducer.java:145)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.lambda$getMainClassFromContext$11(SparkBatchJobLocalRunConfigurationProducer.java:167)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.getMainClassFromContext(SparkBatchJobLocalRunConfigurationProducer.java:159)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.lambda$setupConfigurationFromContext$2(SparkBatchJobLocalRunConfigurationProducer.java:70)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.setupConfigurationFromContext(SparkBatchJobLocalRunConfigurationProducer.java:70)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.setupConfigurationFromContext(SparkBatchJobLocalRunConfigurationProducer.java:61)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:78)
	at com.intellij.execution.junit.JavaRunConfigurationProducerBase.createConfigurationFromContext(JavaRunConfigurationProducerBase.java:64)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:166)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:112)
	at com.intellij.execution.actions.PreferredProducerFind.findConfigurationFromContext(PreferredProducerFind.java:137)
	at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:44)
	at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:149)
	at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:140)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:187)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:259)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:153)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:228)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:365)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:110)
	at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:91)
	at com.intellij.ui.PopupHandler.mouseReleased(PopupHandler.java:59)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:423)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Eskibear** [comment]
@wezhang Please help to take a look. From the description, it should be blocking.

**Comment by wezhang** [comment]
The root cause is Scala plugin missed, revert the change to access the class with reflection.

**Comment by bsaby** [comment]
Test passed.
Build used: pre-release build 3.12.0
