### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by SeanIanHale** [microsoft/azure-tools-for-java#2077]
IntelliJ build version: 2018.2.1 IU-182.3911.36
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2
Error message: 
```
com.microsoft.azure.CloudException: Status code 401, {"error":{"code":"InvalidAuthenticationTokenAudience","message":"The access token has been obtained for wrong audience or resource 'https://datalake.azure.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'."}}: The access token has been obtained for wrong audience or resource 'https://datalake.azure.net/'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.listDelegate(TenantsInner.java:169)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.access$000(TenantsInner.java:36)
	at com.microsof

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  com.microsoft.azure.CloudException: Status code 401, The access token has been ... (#1874)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  com.microsoft.azure.CloudException: Status code 401, The access token has been ... (#1874)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: The access token has been obtained for wrong audience or resource * It should exactly match with one of the allowed audience
