### ISSUE TITLE
[IntelliJ] Fail to start Spark Livy Interactive Session Console remotely

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2102]
Build: Develop 762
IntelliJ 18.1

Repro Steps:
1. Create a project with scala version 11.8
2. Create a run config file with sample.LogQuery, set cluster to zhwe-spk20
3. Right click on script, choose "Spark Console\Run Spark Livy Interactive Session Console(scala)"

Result:
It does not show the console window

2018-09-27 02:57:13,836 [1734733]  ERROR - llij.ide.plugins.PluginManager - Last Action: Spark.RunScalaLivyConsole 
2018-09-27 03:36:36,779 [4097676]  ERROR - llij.ide.plugins.PluginManager - null 
java.security.PrivilegedActionException: java.security.PrivilegedActionException: com.intellij.execution.configurations.RuntimeConfigurationError: Can't find the target cluster zhwe-spk20
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: com.intellij.execution.configurations.RuntimeConfigurationError: Can't find the target cluster zhwe-spk20
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	... 12 more
Caused by: com.intellij.execution.configurations.RuntimeConfigurationError: Can't find the target cluster zhwe-spk20
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration$checkSettingsBeforeRun$1.get(SparkScalaLivyConsoleRunConfiguration.kt:74)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration$checkSettingsBeforeRun$1.get(SparkScalaLivyConsoleRunConfiguration.kt:39)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration.checkSettingsBeforeRun(SparkScalaLivyConsoleRunConfiguration.kt:74)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.runFromSetting(RunSparkLivyConsoleAction.kt:120)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.access$runFromSetting(RunSparkLivyConsoleAction.kt:47)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction$runExisting$1.invoke(RunSparkLivyConsoleAction.kt:96)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction$runExisting$1.invoke(RunSparkLivyConsoleAction.kt:47)
	at com.microsoft.intellij.util.ApplicationHelpersKt.runInReadAction(ApplicationHelpers.kt:42)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.runExisting(RunSparkLivyConsoleAction.kt:95)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.onActionPerformed(RunSparkLivyConsoleAction.kt:63)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:301)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:291)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:528)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:48)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:548)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	... 17 more
2018-09-27 03:36:36,780 [4097677]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.1.2  Build #IC-181.4668.68 
2018-09-27 03:36:36,780 [4097677]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-09-27 03:36:36,780 [4097677]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-09-27 03:36:36,781 [4097678]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-09-27 03:36:36,781 [4097678]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2018-09-27 03:36:36,781 [4097678]  ERROR - llij.ide.plugins.PluginManager - Last Action: Spark.RunScalaLivyConsole

**Comment by wezhang** [comment]
Could you create a cluster to have a try?

**Comment by jingyanjingyan** [comment]
Use cluster spark23hdinsight

2018-09-27 05:30:40,683 [10941580]  ERROR - llij.ide.plugins.PluginManager - null 
java.security.PrivilegedActionException: java.security.PrivilegedActionException: com.intellij.execution.configurations.RuntimeConfigurationWarning: A Spark Run Configuration should be selected to start a console
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: com.intellij.execution.configurations.RuntimeConfigurationWarning: A Spark Run Configuration should be selected to start a console
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	... 12 more
Caused by: com.intellij.execution.configurations.RuntimeConfigurationWarning: A Spark Run Configuration should be selected to start a console
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration.<init>(SparkScalaLivyConsoleRunConfiguration.kt:48)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfigurationFactory.createTemplateConfiguration(SparkScalaLivyConsoleRunConfigurationFactory.kt:33)
	at com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration(ConfigurationFactory.java:64)
	at com.intellij.execution.impl.RunManagerImpl.createTemplateSettings$intellij_platform_lang_impl(RunManagerImpl.kt:239)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:226)
	at com.intellij.execution.impl.RunManagerImpl.getEffectiveBeforeRunTasks(RunManagerImpl.kt:885)
	at com.intellij.execution.impl.RunManagerImpl.getEffectiveBeforeRunTasks$default(RunManagerImpl.kt:878)
	at com.intellij.execution.impl.RunManagerImpl.getBeforeRunTasks(RunManagerImpl.kt:872)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:291)
	at com.intellij.execution.impl.ExecutionManagerKtImpl.startRunProfile(ExecutionManagerKtImpl.kt:128)
	at com.intellij.execution.runners.GenericProgramRunnerKt.startRunProfile(GenericProgramRunner.kt:64)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.kt:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.runFromSetting(RunSparkLivyConsoleAction.kt:122)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.access$runFromSetting(RunSparkLivyConsoleAction.kt:47)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction$runExisting$1.invoke(RunSparkLivyConsoleAction.kt:96)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction$runExisting$1.invoke(RunSparkLivyConsoleAction.kt:47)
	at com.microsoft.intellij.util.ApplicationHelpersKt.runInReadAction(ApplicationHelpers.kt:42)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.runExisting(RunSparkLivyConsoleAction.kt:95)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkLivyConsoleAction.onActionPerformed(RunSparkLivyConsoleAction.kt:63)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:301)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:291)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:528)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:48)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:548)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	... 17 more
2018-09-27 05:30:40,684 [10941581]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.1.2  Build #IC-181.4668.68 
2018-09-27 05:30:40,684 [10941581]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-09-27 05:30:40,684 [10941581]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-09-27 05:30:40,684 [10941581]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-09-27 05:30:40,684 [10941581]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2018-09-27 05:30:40,684 [10941581]  ERROR - llij.ide.plugins.PluginManager - Last Action: Spark.RunScalaLivyConsole

**Comment by jingyanjingyan** [comment]
2018-10-10 02:58:00,421 [4679173]  ERROR - llij.ide.plugins.PluginManager - null 
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkConsoleActionDelegate.onActionPerformed(RunSparkConsoleActionDelegate.kt:56)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:301)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:291)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:528)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:48)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:548)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	... 17 more
Caused by: com.intellij.execution.configurations.RuntimeConfigurationWarning: A Spark Run Configuration should be selected to start a console
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration.<init>(SparkScalaLivyConsoleRunConfiguration.kt:50)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfigurationFactory.createTemplateConfiguration(SparkScalaLivyConsoleRunConfigurationFactory.kt:33)
	at com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration(ConfigurationFactory.java:64)
	at com.intellij.execution.impl.RunManagerImpl.createTemplateSettings$intellij_platform_lang_impl(RunManagerImpl.kt:239)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:226)
	at com.intellij.execution.impl.RunManagerImpl.getEffectiveBeforeRunTasks(RunManagerImpl.kt:885)
	at com.intellij.execution.impl.RunManagerImpl.getEffectiveBeforeRunTasks$default(RunManagerImpl.kt:878)
	at com.intellij.execution.impl.RunManagerImpl.getBeforeRunTasks(RunManagerImpl.kt:872)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:291)
	at com.intellij.execution.impl.ExecutionManagerKtImpl.startRunProfile(ExecutionManagerKtImpl.kt:128)
	at com.intellij.execution.runners.GenericProgramRunnerKt.startRunProfile(GenericProgramRunner.kt:64)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.kt:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runFromSetting(RunSparkScalaConsoleAction.kt:127)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.access$runFromSetting(RunSparkScalaConsoleAction.kt:50)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction$runExisting$1.invoke(RunSparkScalaConsoleAction.kt:101)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction$runExisting$1.invoke(RunSparkScalaConsoleAction.kt:50)
	at com.microsoft.intellij.util.ApplicationHelpersKt.runInReadAction(ApplicationHelpers.kt:42)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runExisting(RunSparkScalaConsoleAction.kt:100)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.actionPerformed(RunSparkScalaConsoleAction.kt:68)
	... 56 more
2018-10-10 02:58:00,422 [4679174]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.1.2  Build #IC-181.4668.68 
2018-10-10 02:58:00,423 [4679175]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-10-10 02:58:00,423 [4679175]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-10-10 02:58:00,423 [4679175]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-10-10 02:58:00,423 [4679175]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2018-10-10 02:58:00,423 [4679175]  ERROR - llij.ide.plugins.PluginManager - Last Action: Spark.RunScalaLivyConsole

**Comment by t-rufang** [comment]
- start Spark Livy Interactive Session Console with only linked clusters
```
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.$$$reportNull$$$0(ActionManagerImpl.java)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getId(ActionManagerImpl.java)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.remove(DefaultActionGroup.java:226)
	at com.intellij.execution.ExecutorRegistryImpl.unregisterAction(ExecutorRegistryImpl.java:95)
	at com.intellij.execution.ExecutorRegistryImpl.deinitExecutor(ExecutorRegistryImpl.java:89)
	at com.intellij.execution.ExecutorRegistryImpl.dispose(ExecutorRegistryImpl.java:177)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:151)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$disposeSelf$7(ApplicationImpl.java:249)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:249)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:790)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:766)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:755)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:751)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:718)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:713)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$3.windowClosing(IdeFrameImpl.java:275)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - IntelliJ IDEA 2018.2  Build #IC-182.3684.90 
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - JDK: 1.8.0_152-release 
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - VM: OpenJDK 64-Bit Server VM 
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - Vendor: JetBrains s.r.o 
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - OS: Windows 10 
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - Last Action: Spark.RunScalaLivyConsole 

```

**Comment by wezhang** [comment]
@lcadzy helped test the dev and installed version, can't repro

**Comment by jingyanjingyan** [comment]
This issue does not repro with IntelliJ 18.2

**Comment by wezhang** [comment]
So, please use IntelliJ 2018.2 version.
