### ISSUE TITLE
[IntelliJ] Submit fail when use non-default storage account

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#2164]
Build: Private 2219

Repro Steps:
1. Set run config file with 
![image](https://user-images.githubusercontent.com/36756024/46709842-02605200-cc35-11e8-9d3e-4ce7fb6d8216.png)

2. Submit

Result:
Fail

```
Package and deploy the job to Spark cluster
INFO: Begin uploading file C:\Users\v-yajing\IdeaProjects\mavensamplesdfgsdfsdf\out\artifacts\mavensamplesdfgsdfsdf_DefaultArtifact\default_artifact.jar to Azure Blob Storage Account wasbs://jilllinux34-2017-03-07t03-36-36-305z@adlstest.blob.core.windows.net/SparkSubmission/2018/10/10/592001aa-81d1-481a-9bdd-a80b2a9399b6/default_artifact.jar ...
INFO: Submit file to azure blob 'wasbs://jilllinux34-2017-03-07t03-36-36-305z@adlstest.blob.core.windows.net/SparkSubmission/2018/10/10/592001aa-81d1-481a-9bdd-a80b2a9399b6/default_artifact.jar' successfully.
LOG: SLF4J: Found binding in [jar:file:/usr/hdp/2.6.5.10-2/spark_llap/spark-llap-assembly-1.0.0.2.6.5.10-2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
LOG: SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
LOG: SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
LOG: Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
LOG: 18/10/10 02:31:08 INFO WasbAzureIaasSink: Init starting.
LOG: 18/10/10 02:31:08 INFO AzureIaasSink: Init starting. Initializing MdsLogger.
LOG: 18/10/10 02:31:08 INFO AzureIaasSink: Init completed.
LOG: 18/10/10 02:31:08 INFO WasbAzureIaasSink: Init completed.
LOG: 18/10/10 02:31:08 INFO MetricsSinkAdapter: Sink azurefs2 started
LOG: 18/10/10 02:31:08 INFO MetricsSystemImpl: Scheduled snapshot period at 60 second(s).
LOG: 18/10/10 02:31:08 INFO MetricsSystemImpl: azure-file-system metrics system started
LOG: 18/10/10 02:31:09 INFO Client: Requesting a new application from cluster with 2 NodeManagers
LOG: 18/10/10 02:31:09 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (51200 MB per container)
LOG: 18/10/10 02:31:09 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead
LOG: 18/10/10 02:31:09 INFO Client: Setting up container launch context for our AM
LOG: 18/10/10 02:31:09 INFO Client: Setting up the launch environment for our AM container
LOG: 18/10/10 02:31:09 INFO Client: Preparing resources for our AM container
LOG: 18/10/10 02:31:11 INFO Client: Deleted staging directory wasb://spark23hdinsight-2018-09-12t05-52-39-851z@spark22secblobsa.blob.core.windows.net/user/livy/.sparkStaging/application_1536732500114_0397
LOG: Exception in thread "main" org.apache.hadoop.fs.azure.AzureException: org.apache.hadoop.fs.azure.AzureException: No credentials found for account adlstest.blob.core.windows.net in the configuration, and its container jilllinux34-2017-03-07t03-36-36-305z is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
LOG: 	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1086)
LOG: 	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.initialize(AzureNativeFileSystemStore.java:538)
LOG: 	at org.apache.hadoop.fs.azure.NativeAzureFileSystem.initialize(NativeAzureFileSystem.java:1346)
LOG: 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2796)
LOG: 	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
LOG: 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2830)
LOG: 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2812)
LOG: 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:390)
LOG: 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
LOG: 	at org.apache.spark.deploy.yarn.Client.copyFileToRemote(Client.scala:351)
LOG: 	at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:478)
LOG: 	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$12.apply(Client.scala:590)
LOG: 	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$12.apply(Client.scala:589)
LOG: 	at scala.Option.foreach(Option.scala:257)
LOG: 	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:589)
LOG: 	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:882)
LOG: 	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:169)
LOG: 	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1217)
LOG: 	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1585)
LOG: 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:906)
LOG: 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
LOG: 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
LOG: 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
LOG: 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
LOG: Caused by: org.apache.hadoop.fs.azure.AzureException: No credentials found for account adlstest.blob.core.windows.net in the configuration, and its container jilllinux34-2017-03-07t03-36-36-305z is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
LOG: 	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.connectUsingAnonymousCredentials(AzureNativeFileSystemStore.java:863)
LOG: 	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1081)
LOG: 	... 23 more
LOG: 18/10/10 02:31:11 INFO ShutdownHookManager: Shutdown hook called
LOG: 18/10/10 02:31:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-040d1867-ac12-4f15-825d-a4fe84e1117a
LOG: java.lang.Exception: No YARN application is found with tag livy-batch-351-xcotsi01 in 120 seconds. Please check your cluster status, it is may be very busy.
LOG: org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:94)
ERROR: The Spark job failed to start due to Caused by: org.apache.hadoop.fs.azure.AzureException: No credentials found for account adlstest.blob.core.windows.net in the configuration, and its container jilllinux34-2017-03-07t03-36-36-305z is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.connectUsingAnonymousCredentials(AzureNativeFileSystemStore.java:863)
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1081)
	... 23 more
18/10/10 02:31:11 INFO ShutdownHookManager: Shutdown hook called
18/10/10 02:31:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-040d1867-ac12-4f15-825d-a4fe84e1117a

stderr: 

YARN Diagnostics: 
java.lang.Exception: No YARN application is found with tag livy-batch-351-xcotsi01 in 120 seconds. Please check your cluster status, it is may be very busy.
org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:94)
 stack trace: com.microsoft.azure.hdinsight.spark.common.SparkJobException: The Spark job failed to start due to Caused by: org.apache.hadoop.fs.azure.AzureException: No credentials found for account adlstest.blob.core.windows.net in the configuration, and its container jilllinux34-2017-03-07t03-36-36-305z is not accessible using anonymous credentials. Please check if the container exists first. If it is not publicly available, you have to provide account credentials.
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.connectUsingAnonymousCredentials(AzureNativeFileSystemStore.java:863)
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.createAzureStorageSession(AzureNativeFileSystemStore.java:1081)
	... 23 more
18/10/10 02:31:11 INFO ShutdownHookManager: Shutdown hook called
18/10/10 02:31:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-040d1867-ac12-4f15-825d-a4fe84e1117a

stderr: 

YARN Diagnostics: 
java.lang.Exception: No YARN application is found with tag livy-batch-351-xcotsi01 in 120 seconds. Please check your cluster status, it is may be very busy.
org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:94)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$awaitStarted$55(SparkBatchJob.java:1196)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OperatorTakeUntilPredicate$ParentSubscriber.onNext(OperatorTakeUntilPredicate.java:61)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at rx.internal.operators.OnSubscribeRedo$2$1.setProducer(OnSubscribeRedo.java:267)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
	at rx.internal.operators.DeferredScalarSubscriber.complete(DeferredScalarSubscriber.java:102)
	at rx.internal.operators.OnSubscribeTakeLastOne$TakeLastOneSubscriber.onCompleted(OnSubscribeTakeLastOne.java:57)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$getSubmissionLog$33(SparkBatchJob.java:879)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onNext(OperatorSubscribeOn.java:74)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by wezhang** [comment]
This issue is because the cluster doesn't configure right for the Storage. We can check it or config it for the user with the following settings:

```
 fs.azure.account.keyprovider.mystorage.blob.core.windows.net
 fs.azure.account.key.mystorage.blob.core.windows.net
```

**Comment by v-xiaocw** [comment]
Build :azure-toolkit-for-intellij-2018.1.develop.783.10-10-2018
Submit with cluster spark22blobhdi successfully

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748166
