### ISSUE TITLE
[Intellij] Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2167]
```
2018-10-10 11:10:39,693 [ 207638]  ERROR - api.util.objectTree.ObjectNode - Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/impl/ActionManagerImpl.getId must not be null
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.$$$reportNull$$$0(ActionManagerImpl.java)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getId(ActionManagerImpl.java)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.remove(DefaultActionGroup.java:226)
	at com.intellij.execution.ExecutorRegistryImpl.unregisterAction(ExecutorRegistryImpl.java:95)
	at com.intellij.execution.ExecutorRegistryImpl.deinitExecutor(ExecutorRegistryImpl.java:89)
	at com.intellij.execution.ExecutorRegistryImpl.dispose(ExecutorRegistryImpl.java:177)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
```

**Comment by wezhang** [comment]
There is ExecutorAction missing for SparkJobRun executors.

**Comment by jingyanjingyan** [comment]
Verify with build develop 788 as fixed. Close IntelliJ and no errors in log.
