### ISSUE TITLE
[IntelliJ] Link livy cluster without username/password, submit with "Use Spark interactive session to upload artifacts" fails

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2171]
Build: Private 2199

Repro Steps:
1. Link a livy cluster without username and password
![image](https://user-images.githubusercontent.com/36756024/46719575-cbeafd00-cc5d-11e8-86ea-1db2acf600a9.png)

2. Open a run config file, set with the livy cluster and "Use Spark interactive session to upload artifacts"
![image](https://user-images.githubusercontent.com/36756024/46719630-f2109d00-cc5d-11e8-8c1b-0af715099527.png)

3. Save the run config file and submit

Result:
Fail

Package and deploy the job to Spark cluster
INFO: Get target jar from C:/Users/v-yajing/IdeaProjects/mvnv1/out/artifacts/mvnv1_DefaultArtifact/default_artifact.jar.
INFO: Create Spark helper interactive session...
ERROR: Username may not be null
 stack trace: java.lang.IllegalArgumentException: Username may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.auth.UsernamePasswordCredentials.<init>(UsernamePasswordCredentials.java:81)
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.<init>(HttpObservable.java:131)
	at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.Session.<init>(Session.java:98)
	at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.SparkSession.<init>(SparkSession.java:37)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$uploadFileToHDFS$6(JobUtils.java:564)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:54)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToHDFS(JobUtils.java:592)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToCluster(JobUtils.java:606)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$10(JobUtils.java:637)
	at rx.Single.subscribe(Single.java:1979)
	at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:45)
	at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:30)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jingyanjingyan** [comment]
Verify with private build 2230, fixed. Submit success.
