### ISSUE TITLE
[Intellij] Memory leak when shutting down Intellij after adding actions from SparkJobRun and SparkJobDebug

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2172]
```
2018-10-10 00:50:34,476 [2143699]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: 'com.intellij.execution.impl.ConsoleViewImpl[,389,1,678x372,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]' of class com.intellij.execution.impl.ConsoleViewImpl
See the cause for the corresponding Disposer.register() stacktrace:
 
java.lang.RuntimeException: Memory leak detected: 'com.intellij.execution.impl.ConsoleViewImpl[,389,1,678x372,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]' of class com.intellij.execution.impl.ConsoleViewImpl
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:247)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:146)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:251)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:790)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:766)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:755)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:751)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:718)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:713)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$3.windowClosing(IdeFrameImpl.java:275)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.objectTree.ObjectNode.<init>(ObjectNode.java:56)
	at com.intellij.openapi.util.objectTree.ObjectTree.createNodeFor(ObjectTree.java:122)
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:84)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.util.Alarm.<init>(Alarm.java:139)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:97)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:156)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:149)
	at com.microsoft.azure.hdinsight.spark.ui.SparkJobLogConsoleView.<init>(SparkJobLogConsoleView.java:45)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRunner.doExecute(SparkBatchJobRunner.java:79)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:61)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	... 9 more
2018-10-10 00:50:34,477 [2143700]  ERROR - api.util.objectTree.ObjectTree - IntelliJ IDEA 2018.2  Build #IC-182.3684.90 
2018-10-10 00:50:34,477 [2143700]  ERROR - api.util.objectTree.ObjectTree - JDK: 1.8.0_152-release 
2018-10-10 00:50:34,477 [2143700]  ERROR - api.util.objectTree.ObjectTree - VM: OpenJDK 64-Bit Server VM 
2018-10-10 00:50:34,477 [2143700]  ERROR - api.util.objectTree.ObjectTree - Vendor: JetBrains s.r.o 
2018-10-10 00:50:34,477 [2143700]  ERROR - api.util.objectTree.ObjectTree - OS: Windows Server 2012 R2 
2018-10-10 00:50:34,481 [2143704]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2018-10-10 00:50:34,490 [2143713]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
```

**Comment by wezhang** [comment]
`com.microsoft.azure.hdinsight.spark.ui.SparkJobLogConsoleView` should dispose the second view

**Comment by wezhang** [comment]
Also found in provision dialog:

```
2018-10-10 20:35:33,220 [60755294]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: 'com.intellij.execution.impl.ConsoleViewImpl[,28,0,-28x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=265,maximumSize=,minimumSize=,preferredSize=]' of class com.intellij.execution.impl.ConsoleViewImpl
See the cause for the corresponding Disposer.register() stacktrace:
 
java.lang.RuntimeException: Memory leak detected: 'com.intellij.execution.impl.ConsoleViewImpl[,28,0,-28x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=265,maximumSize=,minimumSize=,preferredSize=]' of class com.intellij.execution.impl.ConsoleViewImpl
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:247)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:146)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:251)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:790)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:766)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:755)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:751)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:718)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:713)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$3.windowClosing(IdeFrameImpl.java:275)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.objectTree.ObjectNode.<init>(ObjectNode.java:56)
	at com.intellij.openapi.util.objectTree.ObjectTree.createNodeFor(ObjectTree.java:122)
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:84)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.util.Alarm.<init>(Alarm.java:139)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:97)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:156)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:149)
	at com.microsoft.azure.sparkserverless.serverexplore.ui.SparkServerlessProvisionDialog.<init>(SparkServerlessProvisionDialog.java:130)
	at com.microsoft.azure.sparkserverless.SparkServerlessClusterOpsCtrl.lambda$new$2(SparkServerlessClusterOpsCtrl.java:78)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:648)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:661)
	at com.microsoft.intellij.rxjava.IdeaSchedulers.lambda$dispatchUIThread$4(IdeaSchedulers.java:78)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.schedule(ExecutorScheduler.java:79)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.schedule(OperatorObserveOn.java:188)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:163)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
	at com.microsoft.azure.sparkserverless.serverexplore.sparkserverlessnode.SparkServerlessProvisionAction.actionPerformed(SparkServerlessProvisionAction.java:55)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$createPopupMenuForNode$0(ServerExplorerToolWindowFactory.java:211)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	... 7 more
2018-10-10 20:35:33,221 [60755295]  ERROR - api.util.objectTree.ObjectTree - IntelliJ IDEA 2018.2  Build #IC-182.3684.90 
2018-10-10 20:35:33,221 [60755295]  ERROR - api.util.objectTree.ObjectTree - JDK: 1.8.0_152-release 
2018-10-10 20:35:33,221 [60755295]  ERROR - api.util.objectTree.ObjectTree - VM: OpenJDK 64-Bit Server VM 
2018-10-10 20:35:33,221 [60755295]  ERROR - api.util.objectTree.ObjectTree - Vendor: JetBrains s.r.o 
2018-10-10 20:35:33,221 [60755295]  ERROR - api.util.objectTree.ObjectTree - OS: Windows Server 2012 R2 
```

**Comment by jingyanjingyan** [comment]
Verify with build develop 788 as fixed. Close IntelliJ and no errors in log.

**Comment by jingyanjingyan** [comment]
Veirfy as fix with build develop 792. Open Provision cluster dialog will not get error in log.
