### ISSUE TITLE
[IntelliJ][ReportedByUser] Provision Spark Resource Pool, AU computing issue(is 0): Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2180]
IntelliJ build version: 2018.2 IC-182.3684.90
OS: Windows Server 2012 R2
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.12.0
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,31,1187x1186,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "degreeOfParallelismPercent" (class com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation), not marked as ignorable (18 known properties: "logFilePatterns", "priority", "submitTime", "endTime", "submitter", "name", "startTime", "state", "logFolder", "properties", "jobId", "degreeOfParallelism", "type", "result", "errorMessage", "related", "tags", "stateAuditRecords"])
 at [Source: (String)"{"value":[{"jobId":"8751777c-f613-4a85-980b-3e8e5b610016","name":"JobRepository_v2_08_7c01da95-52fd-4982-a0a5-f7f54a0318cd_2018-10-11","type":"Scope","submitter":"CO3SCH080090448","degreeOfParallelism":210,"degreeOfParallelismPercent":20.0,"priority":990,"submitTime":"2018-10-11T01:20:40.5480796+00:00","startTime":"2018-10-11T01:36:56.419+00:00","state":"Running","result":"None","stateAuditRecords":[{"newState":"New","timeStamp":"2018-10-11T01:20:40.5480796+00:00","details":"CJS: MW2SCH101150202"[truncated 20870 chars]; line: 1, column: 240] (through reference chain: com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInfoListResult["value"]->java.util.ArrayList[0]->com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation["degreeOfParallelismPercent"])
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onError(OperatorZip.java:313)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.internal.operators.OnSubscribeReduce$ReduceSubscriber.onError(OnSubscribeReduce.java:95)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty$ParentSubscriber.onError(OnSubscribeSwitchIfEmpty.java:115)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:818)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:579)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:395)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:355)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:846)
	at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
	at rx.internal.operators.OperatorDoAfterTerminate$1.onNext(OperatorDoAfterTerminate.java:50)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:94)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty$ParentSubscriber.subscribe(OnSubscribeSwitchIfEmpty.java:104)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty.call(OnSubscribeSwitchIfEmpty.java:52)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty.call(OnSubscribeSwitchIfEmpty.java:31)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeReduce.call(OnSubscribeReduce.java:48)
	at rx.internal.operators.OnSubscribeReduce.call(OnSubscribeReduce.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "degreeOfParallelismPercent" (class com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation), not marked as ignorable (18 known properties: "logFilePatterns", "priority", "submitTime", "endTime", "submitter", "name", "startTime", "state", "logFolder", "properties", "jobId", "degreeOfParallelism", "type", "result", "errorMessage", "related", "tags", "stateAuditRecords"])
 at [Source: (String)"{"value":[{"jobId":"8751777c-f613-4a85-980b-3e8e5b610016","name":"JobRepository_v2_08_7c01da95-52fd-4982-a0a5-f7f54a0318cd_2018-10-11","type":"Scope","submitter":"CO3SCH080090448","degreeOfParallelism":210,"degreeOfParallelismPercent":20.0,"priority":990,"submitTime":"2018-10-11T01:20:40.5480796+00:00","startTime":"2018-10-11T01:36:56.419+00:00","state":"Running","result":"None","stateAuditRecords":[{"newState":"New","timeStamp":"2018-10-11T01:20:40.5480796+00:00","details":"CJS: MW2SCH101150202"[truncated 20870 chars]; line: 1, column: 240] (through reference chain: com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInfoListResult["value"]->java.util.ArrayList[0]->com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation["degreeOfParallelismPercent"])
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.convertJsonResponseToObject(HttpObservable.java:276)
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$get$7(HttpObservable.java:332)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	... 58 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "degreeOfParallelismPercent" (class com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation), not marked as ignorable (18 known properties: "logFilePatterns", "priority", "submitTime", "endTime", "submitter", "name", "startTime", "state", "logFolder", "properties", "jobId", "degreeOfParallelism", "type", "result", "errorMessage", "related", "tags", "stateAuditRecords"])
 at [Source: (String)"{"value":[{"jobId":"8751777c-f613-4a85-980b-3e8e5b610016","name":"JobRepository_v2_08_7c01da95-52fd-4982-a0a5-f7f54a0318cd_2018-10-11","type":"Scope","submitter":"CO3SCH080090448","degreeOfParallelism":210,"degreeOfParallelismPercent":20.0,"priority":990,"submitTime":"2018-10-11T01:20:40.5480796+00:00","startTime":"2018-10-11T01:36:56.419+00:00","state":"Running","result":"None","stateAuditRecords":[{"newState":"New","timeStamp":"2018-10-11T01:20:40.5480796+00:00","details":"CJS: MW2SCH101150202"[truncated 20870 chars]; line: 1, column: 240] (through reference chain: com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInfoListResult["value"]->java.util.ArrayList[0]->com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation["degreeOfParallelismPercent"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1582)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1560)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at com.microsoft.azure.hdinsight.sdk.rest.ObjectConvertUtils.convertJsonToObject(ObjectConvertUtils.java:46)
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.convertJsonResponseToObject(HttpObservable.java:272)
	... 60 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.microsoft.azure.hdinsight.sdk.common.HttpResponse.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 58 more
```

**Comment by wezhang** [comment]
```
 com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "degreeOfParallelismPercent" (class com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation), not marked as ignorable (18 known properties: "logFilePatterns", "priority", "submitTime", "endTime", "submitter", "name", "startTime", "state", "logFolder", "properties", "jobId", "degreeOfParallelism", "type", "result", "errorMessage", "related", "tags", "stateAuditRecords"])
 at [Source: (String)"{"value":[{"jobId":"8751777c-f613-4a85-980b-3e8e5b610016","name":"JobRepository_v2_08_7c01da95-52fd-4982-a0a5-f7f54a0318cd_2018-10-11","type":"Scope","submitter":"CO3SCH080090448","degreeOfParallelism":210,"degreeOfParallelismPercent":20.0,"priority":990,"submitTime":"2018-10-11T01:20:40.5480796+00:00","startTime":"2018-10-11T01:36:56.419+00:00","state":"Running","result":"None","stateAuditRecords":[{"newState":"New","timeStamp":"2018-10-11T01:20:40.5480796+00:00","details":"CJS: MW2SCH101150202"[truncated 20870 chars]; line: 1, column: 240] (through reference chain: com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInfoListResult["value"]->java.util.ArrayList[0]->com.microsoft.azure.hdinsight.sdk.rest.azure.datalake.analytics.job.models.JobInformation["degreeOfParallelismPercent"])
```
