### ISSUE TITLE
Should disable swap option during swapping process

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2192]
Repro steps:
1. Right-click a slot in Azure explorer and click `Swap with production` option
1. It starts to swap, now click `Swap with Production` option again

Error occurs in lower right corner of IntelliJ

```
com.microsoft.azure.CloudException: Cannot modify this site because another operation is in progress. Details: Id: d4c5a5a2-10ef-4e62-916b-61493f9a1243, OperationName: SwapSiteSlots, CreatedTime: 10/11/2018 6:50:37 AM, WebSystemName: websites, SubscriptionName: ffa52f27-be12-4cad-b1ea-c2c241b6cceb, WebspaceName: monalinux-EastUSwebspace, SiteName: monajarlinux1, SlotName: slot2, ServerFarmName: : Cannot modify this site because another operation is in progress. Details: Id: d4c5a5a2-10ef-4e62-916b-61493f9a1243, OperationName: SwapSiteSlots, CreatedTime: 10/11/2018 6:50:37 AM, WebSystemName: websites, SubscriptionName: ffa52f27-be12-4cad-b1ea-c2c241b6cceb, WebspaceName: monalinux-EastUSwebspace, SiteName: monajarlinux1, SlotName: slot2, ServerFarmName: 
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:740)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$12.call(AzureClient.java:387)
	at com.microsoft.azure.AzureClient$12.call(AzureClient.java:384)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:27)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
	at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.Completable$10.call(Completable.java:588)
	at rx.Completable$10.call(Completable.java:567)
	at rx.Completable.unsafeSubscribe(Completable.java:2035)
	at rx.Completable.unsafeSubscribe(Completable.java:2083)
	at rx.Completable.unsafeSubscribe(Completable.java:2067)
	at rx.Completable$32.call(Completable.java:2253)
	at rx.Completable$32.call(Completable.java:2250)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:477)
	at com.microsoft.azure.management.appservice.implementation.DeploymentSlotBaseImpl.swap(DeploymentSlotBaseImpl.java:294)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.swapSlotWithProduction(AzureWebAppMvpModel.java:416)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.deploymentslot.DeploymentSlotNodePresenter.onSwapWithProduction(DeploymentSlotNodePresenter.java:73)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.deploymentslot.DeploymentSlotNode.swapWithProduction(DeploymentSlotNode.java:114)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.deploymentslot.DeploymentSlotNode.lambda$loadActions$3(DeploymentSlotNode.java:67)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit2.Response.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
	... 64 more
```

**Comment by SummerSun** [comment]
Whenever a slot is swapping with production, other slots can't perform swap with production operation. So to solve this issue, a flag indicating that whether the web app is in swapping state is needed. Since the exception explains the error message in a very detailed way, we will take some time to make more discussion.

**Comment by Eskibear** [comment]
@SummerSun Is it possible to catch all the `CloudException` as the error is not as expected instead of an "exception". We can show the error message carried in CloudException instead of letting it appear in IJ's event log view.

**Comment by SummerSun** [comment]
@Eskibea Yes, we could do that first.

**Comment by EricZhangzf** [comment]
Can not repro this issue on v3.37.0
