### ISSUE TITLE
java.lang.SecurityException when building IntelliJ plugin with signed utils jars.

### ISSUE THREAD

**Issue by Eskibear** [microsoft/azure-tools-for-java#2199]
```
> Task :cucumber FAILED
Exception in thread "main" java.lang.SecurityException: class "com.microsoft.azu                       re.hdinsight.spark.common.SparkSubmitModelScenario$checkSparkSubmitMode$1"'s sig                       ner information does not match signer information of other classes in the same package
        at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at cucumber.runtime.io.ResourceLoaderClassFinder.loadClass(ResourceLoade                       rClassFinder.java:38)
        at cucumber.runtime.io.ResourceLoaderClassFinder.getDescendants(Resource                       LoaderClassFinder.java:26)
        at cucumber.runtime.java.MethodScanner.scan(MethodScanner.java:34)
        at cucumber.runtime.java.JavaBackend.loadGlue(JavaBackend.java:86)
        at cucumber.runtime.Runtime.<init>(Runtime.java:91)
        at cucumber.runtime.Runtime.<init>(Runtime.java:69)
        at cucumber.runtime.Runtime.<init>(Runtime.java:65)
        at cucumber.api.cli.Main.run(Main.java:35)
        at cucumber.api.cli.Main.main(Main.java:18)

FAILURE: Build failed with an exception.


```

## Root cause

```
package com.microsoft.azure.hdinsight.spark.common;
```
This package name is used in both `Utils/hdinsight-node-common` and [HERE](https://github.com/Microsoft/azure-tools-for-java/blob/develop/PluginsAndFeatures/azure-toolkit-for-intellij/Test/java/com/microsoft/azure/hdinsight/spark/common/SparkSubmitModelScenario.

[Ref](https://stackoverflow.com/questions/2877262/java-securityexception-signer-information-does-not-match/8324539)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748165
