### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by Kastrupf** [microsoft/azure-tools-for-java#2226]
IntelliJ build version: 2018.2.2 IU-182.4129.33
OS: Linux
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.2
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:105)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.handleSubscriptionChange(AzureModule.java:220)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.access$100(AzureModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule$SignInOutListener.run(AzureModule.java:229)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:124)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:107)
	at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction$1.actionPerformed(SignInOutAction.java:46)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambd

**Comment by pl07** [comment]
- IntelliJ build version: IU2020.1-jre11
 - OS: Windows
 - Plugin version: 3.37.0

Sign in with a no-subs account, new an application insight, refresh resource management, create resource management, create virtual machine, create redis cache will show this error message.

**Comment by pl07** [comment]
- IntelliJ build version: IU2020.1-jre11
 - OS: Windows
 - Plugin version: 3.37.0

Sign in with a no-subs account, deploy to azure spring cloud dialog, `Spring Cloud` keeps refreshing
![image](https://user-images.githubusercontent.com/46642771/84363424-4de4b380-ac01-11ea-80c5-0baa4ade2fbf.png)
