### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugConfigurationFactory@704c8afe produced wrong type java.lang.ClassCastException: scala.None$ cannot be cast to scala.Option

### ISSUE THREAD

**Issue by lucianenache** [Microsoft/azure-tools-for-java#2272]
IntelliJ build version: 2018.2.5 IU-182.4892.20
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1357x1179,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugConfigurationFactory@704c8afe produced wrong type, throwable=java.lang.ClassCastException: scala.None$ cannot be cast to scala.Option
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.findScalaMainClass(SparkBatchJobLocalRunConfigurationProducer.java:152)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.lambda$getMainClassFromContext$10(SparkBatchJobLocalRunConfigurationProducer.java:195)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.getMainClassFromContext(SparkBatchJobLocalRunConfigurationProducer.java:187)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.lambda$setupConfigurationFromContext$1(SparkBatchJobLocalRunConfigurationProducer.java:70)
	at java.util.Optional.flatMap(Optional.java:241)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobLocalRunConfigurationProducer.setupConfigurationFromContext(SparkB

**Comment by wezhang** [comment]
@lucianenache Thanks!

**Comment by wezhang** [comment]
Repro with opening context menu on a .sbt file.

**Comment by jingyanjingyan** [comment]
Fix in develop 839
