### ISSUE TITLE
Cannot enable the plugin in IntelliJ IDEA for Mac OS X

### ISSUE THREAD

**Issue by windoze** [Microsoft/azure-tools-for-java#23]
Cannot enable the plugin, IntelliJ IDEA shows error message:
`JAR entry com.microsoftopentechnologies.qpid not found in /Users/xxxxxx/Library/Application Support/IntelliJIdea2016.2/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar`

Detailed message:
```
JAR entry com.microsoftopentechnologies.qpid not found in /Users/xxxxxx/Library/Application Support/IntelliJIdea2016.2/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar
java.io.FileNotFoundException: JAR entry com.microsoftopentechnologies.qpid not found in /Users/xxxxxx/Library/Application Support/IntelliJIdea2016.2/azure-toolkit-for-intellij/lib/azure-toolkit-for-intellij.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at com.microsoftopentechnologies.windowsazure.tools.cspack.Utils.getJarEntries(Utils.java:301)
	at com.microsoft.intellij.AzurePlugin.copyPluginComponents(AzurePlugin.java:311)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:127)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:222)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:464)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$100(ProjectManagerImpl.java:60)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:405)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:402)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$9.run(CoreProgressManager.java:384)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:548)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
Licensed to XXXXXX
Subscription is active until November 3, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

macOS macOS 10.12 (16A323)

MacBook Pro (Retina, 15-inch, Mid 2015)
2.5 GHz Intel Core i7
16 GB 1600 MHz DDR3

**Comment by vladimir-shcherbakov** [comment]
Hi @windoze,

Could please add steps to reproduce.

**Comment by windoze** [comment]
I just installed the plugin and restarted the IntelliJ IDEA, then the error appeared.
Tried to disable and enable the plugin and the problem still exists.

**Comment by vladimir-shcherbakov** [comment]
Hi @windoze,

Could you please 

1.  go to the folder: 
  ```
/Users/xxxxxx/Library/Application Support/IntelliJIdea2016.2/azure-toolkit-for-intellij/lib/
```

2. unpack **azure-toolkit-for-intellij.jar**

  ![image](https://cloud.githubusercontent.com/assets/6579928/18923363/c7349366-8560-11e6-9baa-c98db48495f3.png)

3. make sure **com.microsoftopentechnologies.qpid** is there

![image](https://cloud.githubusercontent.com/assets/6579928/18923637/e1ae1d1a-8561-11e6-83e6-6f062e3131c4.png)

**Comment by windoze** [comment]
Yes, it's there.

**Comment by vladimir-shcherbakov** [comment]
Hi @windoze,
I got the repro, but after the exception I can use the plugin. Can you?

**Comment by vladimir-shcherbakov** [comment]
Fixed.

**Comment by windoze** [comment]
Sorry for the delay, I was on vacation last week.
Yes the plugin can work even there is an exception, but I'm not sure if there is any problem.
BTW I don't see any updates for this plugin in IntelliJ repo, is it released?

**Comment by martinsawicki** [comment]
the fix update will be released probably today or so.

**Comment by martinsawicki** [comment]
update with the fix release a few days ago, so closing.

**Comment by windoze** [comment]
Hi @martinsawicki,

After updating to the new version, I got another error:
MS Services - Error Loading Web Apps
	com.microsoft.windowsazure.exception.ServiceException: 
	atnull com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:295)
	at com.microsoft.azure.management.resources.ResourceGroupOperationsImpl.list(ResourceGroupOperationsImpl.java:971)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:887)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$30.execute(AzureSDKHelper.java:883)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1409)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestResourceManagementSDK(AzureManagerImpl.java:1336)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.getResourceGroupNames(AzureManagerImpl.java:693)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refresh(WebappsModule.java:68)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


MS Services - Error Loading Virtual Machines
	com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: No User Information for the specified Subscription Id
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerBaseImpl.getUserInfo(AzureManagerBaseImpl.java:171)
	at com.microsoft.tooling.msservices.helpers.azure.AzureArmManagerImpl.getUserInfo(AzureArmManagerImpl.java:53)
	at com.microsoft.tooling.msservices.helpers.azure.AzureArmManagerImpl.requestAzureSDK(AzureArmManagerImpl.java:141)
	at com.microsoft.tooling.msservices.helpers.azure.AzureArmManagerImpl.getVirtualMachines(AzureArmManagerImpl.java:195)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.vmarm.VMArmServiceModule.refresh(VMArmServiceModule.java:57)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Nothing was shown under "Virtual Machine" and "Web Apps" nodes.

I'm using Azure.CN and imported the publisher settings file downloaded from the site, I can still see "virtual machines (classic)" and "storage accounts (classic)" contents.
