### ISSUE TITLE
[IntelliJ] ADLS gen 1 - unknow error when submit with invalid root path

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2317]
Build: PR 2438

Repro steps:
1. Create a config with ADLS cluster and invalid ADLS gen 1 root path as following:
![image](https://user-images.githubusercontent.com/36756024/47724969-9ed3ae00-dc4f-11e8-94a6-6041b28aa616.png)

2. Apply and submit

Result:
Unknown error dialog
![image](https://user-images.githubusercontent.com/36756024/47725051-c165c700-dc4f-11e8-9b9f-2fbfba88c826.png)

**Comment by jingyanjingyan** [comment]
2018-10-31 02:51:05,865 [44014360]   INFO - s.CompilerReferenceServiceBase - backward reference index reader is opened 
2018-10-31 02:51:06,884 [44015379]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: C:/Users/v-yajing/AppData/Local/JetBrains/Toolbox/apps/IDEA-C/ch-0/182.4892.20/lib/jps-launcher.jar;C:/Program Files/Java/jdk1.8.0_181/lib/tools.jar;C:/Users/v-yajing/AppData/Local/JetBrains/Toolbox/apps/IDEA-C/ch-0/182.4892.20/lib/optimizedFileManager.jar 
2018-10-31 02:51:06,917 [44015412]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
2018-10-31 02:51:06,917 [44015412]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: Defaulting to no-operation (NOP) logger implementation 
2018-10-31 02:51:06,917 [44015412]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stderr]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
2018-10-31 02:51:43,430 [44051925]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRunner.buildSparkBatchJob(SparkBatchJobRunner.java:115)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRunner.doExecute(SparkBatchJobRunner.java:141)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:61)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by t-rufang** [comment]
Fixed in #2313

**Comment by jingyanjingyan** [comment]
Verify with develop 869
Submit with invalid root path of ADLS gen1, warning message show as following
![image](https://user-images.githubusercontent.com/36756024/48818452-50439c00-ed43-11e8-8481-c752c51a5268.png)
