### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception com.intellij.execution.junit.JUnitConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration java.lang.ClassCastException: com.intellij.execution.junit.JUnitConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration

### ISSUE THREAD

**Issue by stevevd** [Microsoft/azure-tools-for-java#2337]
IntelliJ build version: 2018.1.6 IC-181.5540.7
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1920x1017,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=com.intellij.execution.junit.JUnitConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration, throwable=java.lang.ClassCastException: com.intellij.execution.junit.JUnitConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.submit(SparkSubmitJobAction.kt:71)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.onActionPerformed(SparkSubmitJobAction.kt:47)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:301)
	at com.intellij

**Comment by wezhang** [comment]
Thanks @stevevd! Dup #2267
