### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: org.jetbrains.plugins.cucumber.java.run.CucumberJavaRunConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration

### ISSUE THREAD

**Issue by pgogad** [Microsoft/azure-tools-for-java#2340]
IntelliJ build version: 2018.2.5 IU-182.4892.20
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.14.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1035,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: org.jetbrains.plugins.cucumber.java.run.CucumberJavaRunConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.RemoteDebugRunConfiguration
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.submit(SparkSubmitJobAction.kt:67)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.onActionPerformed(SparkSubmitJobAction.kt:47)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:255)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(Ac

**Comment by wezhang** [comment]
Thanks! Dup #2267
