### ISSUE TITLE
Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed

### ISSUE THREAD

**Issue by sallyur** [Microsoft/azure-tools-for-java#2369]
Build: 864

Repro steps:
1.	Open Azure Sign in window and choose Device login
2.	Click sign in
3.	Choose "copy & open" in Azure device login window

Result: 

Report error in IDE Fatal Errors window
```
[Correlation ID: 3dde1449-5192-4ba3-9dfc-8ff34ecbc3ca] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: Pending end-user authorization.
Trace ID: 0a774853-298d-4ee0-909c-24f0ba4b0500
Correlation ID: 3dde1449-5192-4ba3-9dfc-8ff34ecbc3ca
Timestamp: 2018-11-20 03:54:04Z
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:117)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by bsaby** [comment]
Close this issue since duplicate with #2368
