### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Services Explorer - Error Refreshing Docker Hosts

### ISSUE THREAD

**Issue by isWangZL** [microsoft/azure-tools-for-java#2386]
IntelliJ build version: 2018.2.5 IU-182.4892.20
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.14.0-2018.2
Error message: 
```
java.lang.NullPointerException
	at com.microsoft.azure.docker.AzureDockerHostsManager.<init>(AzureDockerHostsManager.java:136)
	at com.microsoft.azure.docker.AzureDockerHostsManager.getAzureDockerHostsManagerEmpty(AzureDockerHostsManager.java:107)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostModule.refreshItems(DockerHostModule.java:130)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:96)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:148)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at

**Comment by andxu** [comment]
@isWangZL Seems you are expanding Docker Hosts before signing in to Azure,  could you please try it using latest version, I tested, cannot reproduce this bug.
