### ISSUE TITLE
[intelliJ 3][Linux]Error message pops up when creating a SBT project.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2393]
Build:
artifacts/azure-toolkit-for-intellij-183.4284.118.PR.2528.11-21-2018.zip

Repro Steps:
1. Create a new SBT project.
2. **Import Module from sbt**  pops up. Then click OK to install the needed.

Result:
Error message shows out when clicking **Event Log**.
But it will disappear after waiting for a long time.
![image](https://user-images.githubusercontent.com/35950097/48830732-3e4c1280-edb0-11e8-85b0-04b4e03a8e9c.png)
![image](https://user-images.githubusercontent.com/35950097/48830654-12309180-edb0-11e8-9e57-4c399d5d0bbf.png)
java.lang.InterruptedException

java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:108)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:164)
	at com.intellij.openapi.options.CompositeSettingsEditor.applyEditorTo(CompositeSettingsEditor.java:70)
	at com.intellij.openapi.options.SettingsEditor.applyTo(SettingsEditor.java:89)
	at com.intellij.execution.impl.ConfigurationSettingsEditor.getSnapshot(ConfigurationSettingsEditor.java:211)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.getSnapshot(ConfigurationSettingsEditorWrapper.java:111)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.getSnapshot(ConfigurationSettingsEditorWrapper.java:25)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.createSnapshot(SingleConfigurationConfigurable.java:291)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.getValidationResult(SingleConfigurationConfigurable.java:172)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.access$1400(SingleConfigurationConfigurable.java:39)
	at com.intellij.execution.impl.SingleConfigurationConfigurable$MyValidatableComponent.getValidationResult(SingleConfigurationConfigurable.java:392)
	at com.intellij.execution.impl.SingleConfigurationConfigurable$MyValidatableComponent.updateWarning(SingleConfigurationConfigurable.java:396)
	at com.intellij.execution.impl.SingleConfigurationConfigurable$MyValidatableComponent.lambda$new$0(SingleConfigurationConfigurable.java:335)
	at com.intellij.openapi.options.SettingsEditor.fireEditorStateChanged(SettingsEditor.java:131)
	at com.intellij.openapi.options.SettingsEditor$2.stateChanged(SettingsEditor.java:114)
	at sun.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:133)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:25)
	at com.intellij.util.EventDispatcher$3.invoke(EventDispatcher.java:96)
	at com.sun.proxy.$Proxy179.stateChanged(Unknown Source)
	at com.intellij.ui.UserActivityWatcher.fireUIChanged(UserActivityWatcher.java:92)
	at com.intellij.ui.UserActivityWatcher$7.itemStateChanged(UserActivityWatcher.java:98)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1271)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionJobUploadStorageCtrl.setDefaultStorageType(SparkSubmissionJobUploadStorageCtrl.kt:165)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionJobUploadStorageCtrl.access$setDefaultStorageType(SparkSubmissionJobUploadStorageCtrl.kt:59)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionJobUploadStorageCtrl$validateStorageInfo$2.call(SparkSubmissionJobUploadStorageCtrl.kt:174)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionJobUploadStorageCtrl$validateStorageInfo$2.call(SparkSubmissionJobUploadStorageCtrl.kt:59)
	at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
	at rx.internal.operators.OperatorDebounceWithTime$DebounceState.emit(OperatorDebounceWithTime.java:132)
	at rx.internal.operators.OperatorDebounceWithTime$1$1.call(OperatorDebounceWithTime.java:79)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.progress.ProcessCanceledException: java.lang.InterruptedException
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:76)
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:678)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.checkInputs(SparkSubmissionContentPanel.kt:367)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanelConfigurable.validate(SparkSubmissionContentPanelConfigurable.java:361)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionDebuggablePanelConfigurable.validate(SparkSubmissionDebuggablePanelConfigurable.kt:94)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.validate(SparkBatchJobConfigurable.java:113)
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkRunConfigurationSettingsEditor.applyEditorTo(LivySparkRunConfigurationSettingsEditor.kt:46)
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkRunConfigurationSettingsEditor.applyEditorTo(LivySparkRunConfigurationSettingsEditor.kt:36)
	at com.intellij.openapi.options.SettingsEditor.applyTo(SettingsEditor.java:89)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.applyEditorTo(ConfigurationSettingsEditor.java:292)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.applyEditorTo(ConfigurationSettingsEditor.java:271)
	at com.intellij.openapi.options.SettingsEditor.applyTo(SettingsEditor.java:89)
	at com.intellij.openapi.options.CompositeSettingsEditor.applyEditorTo(CompositeSettingsEditor.java:64)
	... 83 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:81)
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:73)
	... 96 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.microsoft.azure.hdinsight.spark.common.SparkSubmitJobUploadStorageModel.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:98)
	... 50 more

**Comment by v-jiche** [comment]
Bug repros in Build:
azure-toolkit-for-intellij-183.4284.118.develop.900.12-12-2018

**Comment by v-jiche** [comment]
Not repro
