### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error

### ISSUE THREAD

**Issue by kenogr** [microsoft/azure-tools-for-java#2401]
IntelliJ build version: 2018.2.4 IC-182.4505.22
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.2
Error message: 
```
org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.createBatchSparkJob(SparkBatchSubmission.java:174)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.createBatchJob(SparkBatchJob.java:362)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$submit$50(SparkBatchJob.java:1172)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressMana

**Comment by wezhang** [comment]
Thanks @kenogr !

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
- [Spark on ADL] Submit fail (#1957)

**Comment by wezhang** [comment]
A transient backend issue.
