### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Services Explorer - Error Refreshing Docker Hosts

### ISSUE THREAD

**Issue by bsao** [microsoft/azure-tools-for-java#2408]
IntelliJ build version: 2018.3 IU-183.4284.148
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.3
Error message: 
```
java.lang.NullPointerException
	at com.microsoft.azure.docker.AzureDockerHostsManager.<init>(AzureDockerHostsManager.java:136)
	at com.microsoft.azure.docker.AzureDockerHostsManager.getAzureDockerHostsManagerEmpty(AzureDockerHostsManager.java:107)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostModule.refreshFromAzure(DockerHostModule.java:109)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:148)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAd

**Comment by andxu** [comment]
Duplicate as #2386
