### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2411]
IntelliJ build version: 2018.3.1 IC-183.4588.27
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-183.4284.118
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesInner.listByResourceGroup(RegistriesInner.java:992)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesImpl$1.listNextGroup(RegistriesImpl.java:58)
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupPagedList.nextPage(GroupPagedList.java:41)
	at com.microsoft.azure.PagedList.cachePage(PagedList.java:62)
	at com.microsoft.azure.PagedList.loadNextPage(PagedList.java:104)
	at com.microsoft.azure.PagedList$ListItr.next(PagedList.java:172)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listRegistryBySubscriptionId(ContainerRegistryMvpModel.java:87)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listContainerRegistries(ContainerRegistryMvpModel.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModulePresenter.onModuleRefresh(ContainerRegistryModulePresenter.java:38)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModule.refreshItems(ContainerRegistryModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.Refreshable

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Refresh then sign out, pops error dialogs (#1643)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: unknown_user
