### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception From listener com.intellij.execution.ui.RunContentManagerImpl$CloseListener@5354897 (class com.intellij.execution.ui.RunContentManagerImpl$CloseListener) java.lang.RuntimeException: com.microsoft.azure.hdinsight.sdk.common.SparkAzureDataLakePoolServiceException: Not Found

### ISSUE THREAD

**Issue by v-xiaocw** [Microsoft/azure-tools-for-java#2431]
IntelliJ build version: 2018.3.1 IC-183.4588.27
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-183.4284.118
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1384x781,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=From listener com.intellij.execution.ui.RunContentManagerImpl$CloseListener@5354897 (class com.intellij.execution.ui.RunContentManagerImpl$CloseListener), throwable=java.lang.RuntimeException: com.microsoft.azure.hdinsight.sdk.common.SparkAzureDataLakePoolServiceException: Not Found
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:497)
	at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.Session.close(Session.java:207)
	at com.microsoft.azure.hdinsight.spark.console.SparkLivySessionProcess.destroy(SparkLivySessionProcess.kt:45)
	at com.microsoft.azure.hdinsight.spark.console.SparkLivySessionProcessHandler.destroyProcessImpl(SparkLivySessionProcessHandler.kt:41)
	at com.intellij.execution.process.ProcessHandler$1.run(ProcessHandler.java:100)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:256)
	at com.intellij.execution.process.ProcessHandl

**Comment by v-xiaocw** [comment]
From listener com.intellij.execution.ui.RunContentManagerImpl$CloseListener@5354897 (class com.intellij.execution.ui.RunContentManagerImpl$CloseListener)

java.lang.RuntimeException: com.microsoft.azure.hdinsight.sdk.common.SparkAzureDataLakePoolServiceException: Not Found
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:497)
	at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.Session.close(Session.java:207)
	at com.microsoft.azure.hdinsight.spark.console.SparkLivySessionProcess.destroy(SparkLivySessionProcess.kt:45)
	at com.microsoft.azure.hdinsight.spark.console.SparkLivySessionProcessHandler.destroyProcessImpl(SparkLivySessionProcessHandler.kt:41)
	at com.intellij.execution.process.ProcessHandler$1.run(ProcessHandler.java:100)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:256)
	at com.intellij.execution.process.ProcessHandler.destroyProcess(ProcessHandler.java:95)
	at com.intellij.execution.ui.RunContentManagerImpl$CloseListener.closeQuery(RunContentManagerImpl.java:697)
	at com.intellij.execution.ui.RunContentManagerImpl$CloseListener.canClose(RunContentManagerImpl.java:671)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.canClose(ProjectManagerImpl.java:834)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:668)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:719)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:97)
	at com.intellij.ide.impl.NewProjectUtil.closePreviousProject(NewProjectUtil.java:207)
	at com.intellij.ide.impl.NewProjectUtil.doCreate(NewProjectUtil.java:134)
	at com.intellij.ide.impl.NewProjectUtil.createFromWizard(NewProjectUtil.java:60)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.java:54)
	at com.intellij.ide.actions.NewProjectAction.lambda$actionPerformed$0(NewProjectAction.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.microsoft.azure.hdinsight.sdk.common.SparkAzureDataLakePoolServiceException: Not Found
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$toStringOnlyOkResponse$1(HttpObservable.java:242)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:66)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty$ParentSubscriber.subscribe(OnSubscribeSwitchIfEmpty.java:104)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty.call(OnSubscribeSwitchIfEmpty.java:52)
	at rx.internal.operators.OnSubscribeSwitchIfEmpty.call(OnSubscribeSwitchIfEmpty.java:31)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:477)
	... 38 more
