### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: com.intellij.execution.application.ApplicationConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration

### ISSUE THREAD

**Issue by dgilling** [Microsoft/azure-tools-for-java#2439]
IntelliJ build version: 2018.3.1 IU-183.4588.61
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1155,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: com.intellij.execution.application.ApplicationConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.submit(SparkSubmitJobAction.kt:67)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.onActionPerformed(SparkSubmitJobAction.kt:47)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMe

**Comment by wezhang** [comment]
Thanks @dgilling !

**Comment by wezhang** [comment]
Dup #2267

**Comment by wezhang** [comment]
@dgilling , may I get how to repro the issue? My `SparkJobRun` button is disabled after switched to a generic Java application configuration.
