### ISSUE TITLE
[IntelliJ][ReportedByUser] HDInsight Explorer ConcurrentModificationException

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2448]
IntelliJ build version: 2018.3.1 IC-183.4588.61
OS: Windows Server 2012 R2
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0
Error message: 
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.fireChangeListenerEvent(ObservableList.java:124)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.add(ObservableList.java:76)
	at com.google.common.collect.ForwardingList.standardAdd(ForwardingList.java:139)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.add(ObservableList.java:44)
	at com.microsoft.tooling.msservices.serviceexplorer.Node.addChildNode(Node.java:193)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountFolderNode.refreshItems(StorageAccountFolderNode.java:59)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:96)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:148)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessU

**Comment by wezhang** [comment]
Triggered when click HDInsight node of explorer
