### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 1aa1fd05-2bac-4b65-b33e-00a1eef26e93] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed. com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: Pending end-user authorization.

### ISSUE THREAD

**Issue by tilumi** [Microsoft/azure-tools-for-java#2461]
IntelliJ build version: 2018.3.1 IC-183.4588.61
OS: Windows Server 2016
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,31,824x494,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 1aa1fd05-2bac-4b65-b33e-00a1eef26e93] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed., throwable=com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: Pending end-user authorization.
Trace ID: be00a398-62f1-41be-931c-bdda48890800
Correlation ID: 1aa1fd05-2bac-4b65-b33e-00a1eef26e93
Timestamp: 2018-12-07 08:36:22Z
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:117)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurren

**Comment by wezhang** [comment]
@SummerSun , could you help to have a look? Thanks!

**Comment by Eskibear** [comment]
duplicated with #2368
