### ISSUE TITLE
[Intellij][2018.3][HDInsight] IntelliJ 183 regresion of Spark livy interactive console

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#2468]
```
Failed to get PID with winp, fallback to default logic

org.jvnet.winp.NotWindowsException: java.lang.NoSuchFieldException: handle
	at org.jvnet.winp.WinProcess.<init>(WinProcess.java:48)
	at com.intellij.execution.process.OSProcessUtil.createWinProcess(OSProcessUtil.java:127)
	at com.intellij.execution.process.OSProcessUtil.getProcessID(OSProcessUtil.java:104)
	at com.intellij.execution.impl.DefaultJavaProgramRunner$AttachDebuggerAction$1.lambda$startNotified$0(DefaultJavaProgramRunner.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldException: handle
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.jvnet.winp.WinProcess.<init>(WinProcess.java:43)
	... 9 more
```

**Comment by jingyanjingyan** [comment]
Fix with develop 901
