### ISSUE TITLE
[IntelliJ][ReportedByUser][log] Uncaught Exception JobUtils set Response error java.io.IOException: Программа на вашем хост-компьютере разорвала установленное подключение

### ISSUE THREAD

**Issue by starostinEgo** [microsoft/azure-tools-for-java#2475]
IntelliJ build version: 2018.2.7 IC-182.5107.41
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1366x745,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=JobUtils set Response error, throwable=java.io.IOException: Программа на вашем хост-компьютере разорвала установленное подключение
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
	at sun.net.httpserver.FixedLengthOutputStream.write(Fi

**Comment by wezhang** [comment]
Thanks @starostinEgor !

**Comment by wezhang** [comment]
> IdeaLoggingEvent[message=JobUtils set Response error, throwable=java.io.IOException: A program on your host has terminated the connection

**Comment by wezhang** [comment]
The message should not be logged as error.

**Comment by fengshuaihu** [comment]
Please update to the latest version and try again, if you encounter this issue again, feel free to turn it on again
