### ISSUE TITLE
Error Loading WebApps in Intellij

### ISSUE THREAD

**Issue by gary555594** [Microsoft/azure-tools-for-java#25]
Recently started getting the following exception when looking at WebApps:
java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.websites.models.SkuOptions.Dynamic
	at com.microsoft.windowsazure.core.utils.EnumUtility.fromString(EnumUtility.java:43)
	at com.microsoft.azure.management.websites.WebSiteOperationsImpl.list(WebSiteOperationsImpl.java:6602)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper.getWebSites(AzureSDKHelper.java:1916)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper.access$3100(AzureSDKHelper.java:173)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$31.execute(AzureSDKHelper.java:923)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$31.execute(AzureSDKHelper.java:916)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl$10.execute(AzureManagerImpl.java:1465)
	at com.microsoft.tooling.msservices.helpers.auth.AADManagerImpl.request(AADManagerImpl.java:111)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1472)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestWebSiteSDK(AzureManagerImpl.java:1313)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.getWebSites(AzureManagerImpl.java:700)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refresh(WebappsModule.java:69)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

It is no longer usable - can't see existing Web Apps or deploy new ones.
I'm using Version 1.5.1. of the plugin, Windows Server 2012 and Intellij 2016.2.4

Any help greatly appreciated.

Gary

**Comment by vladimir-shcherbakov** [comment]
@martinsawicki, 
This is SDK issue -  [com.microsoft.azure.management.websites] - we need to update it.

**Comment by martinsawicki** [comment]
@vladimir-shcherbakov, the one we use for webapps is 0.9.x - not generated anymore, so if a fix is needed, it'd have to be a manual patch over the existing sources. 
Can you tell what the issue is exactly?

**Comment by vladimir-shcherbakov** [comment]
we need to add the missing  **Dynamic** enum constant to the [SkuOptions enum](https://github.com/Azure/azure-sdk-for-java/blob/0.9/resource-management/azure-mgmt-websites/src/main/java/com/microsoft/azure/management/websites/models/SkuOptions.java#L29)
I'll send a pull request.

**Comment by vladimir-shcherbakov** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/1185

**Comment by martinsawicki** [comment]
this update for the IntelliJ plugin is coming out later today.

**Comment by gary555594** [comment]
That's fixed it!
Many thanks
G

**Comment by martinsawicki** [comment]
good to hear, thanks for the feedback!
