### ISSUE TITLE
Login while creating new cred file failes

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Microsoft/azure-tools-for-java#250]
==> locationEvent.location: https://msopentech.com/?code=AQABAAIAAADRNYRQ3dhRSrm-4K-adpCJzYLQKUTZe6TgWU7OB9q6IVpFVLCTvWfFFn-OzUNeI1dMpHjCapCJD5nXojreObcazbTaJw_8IbuY11xupf_ovvfXlRr0tuQv_WYn3-HFJtyFud5_Sowxrp6u-9-eNtQ9Zw6uNAh0CLtKcgxT1z0NrCu5MmXqXLJ6Qm9YY9UNBCLJlF0LpMHpcbnYuXJVrLu0KzuwKLlPLQkjXAbxSsCe4wCi6TqH-Ukoie4XDDblvdHp5CKL5PB0pgAHwXszsDnoGiqTtxlSaBf0TozECyvq62dy5xnvpx6O4p4B4FNwLXPwFeOv_GLKJkai4_EbSCG1xX9-P1DdzGPxsxr8lZ72xh7TtYFBKkoUAkDQ7J_B2y_oXCr1cW2ZT9BVTzHCA3K3EX8hU8MwS3gv3b1P3k8B3P8CKVz_IcLG5St989krdu5ET58fVFJyDIxlwnwRbqxm3RLWQhdPcqQclB-B2QrmAX4h2KBJPkh5fi4-sy5zTL7nsw2zU7VdhS3brKAlzH5NCTZpCrh2qOaX39GDIKydsGibRgryx1fJ1Ep_wJlVd0GHvCkp5k7ZRYRrFwYC6_nm5jSkJbumEJ6-C4FEartIJdkWISiZ2u4kvvQk2nTashAZLKRsnHFx4hGuXB-a1ureiItVkcDaqx6k_3XPiiZs7V4WSKmfISKDmNiErXdBeifpmKdEOleumxWYjTLTvKjmIAA&session_state=4e1ec04c-b48f-488e-8b79-005b11a66793
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Read timed out
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase.run(AcquireTokenHandlerBase.java:83)
	at com.microsoft.azuretools.adauth.AuthContext.acquireToken(AuthContext.java:57)
	at com.microsoft.azuretools.authmanage.AdAuthManager.getAccessToken(AdAuthManager.java:65)
	at com.microsoft.azuretools.authmanage.RefreshableTokenCredentials.getToken(RefreshableTokenCredentials.java:71)
	at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:42)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:342)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:75)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:33)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getTenants(AccessTokenAzureManager.java:125)
	at com.microsoft.azuretools.authmanage.AdAuthManager.signIn(AdAuthManager.java:84)
	at com.microsoft.azuretools.core.ui.SignInDialog$5.run(SignInDialog.java:289)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.microsoft.azuretools.adauth.HttpHelper.sendPostRequestAndDeserializeJsonResponse(HttpHelper.java:61)
	at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase.sendHttpMessage(AcquireTokenHandlerBase.java:202)
	at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase.sendTokenRequestByRefreshToken(AcquireTokenHandlerBase.java:197)
	at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase$4.call(AcquireTokenHandlerBase.java:174)
	at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase$4.call(AcquireTokenHandlerBase.java:167)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
signInAsync ex: {"error":{"code":"InvalidAuthenticationToken","message":"The access token is invalid."}}
>> Canceled by the user
>> Signing out...

**Comment by vladimir-shcherbakov** [comment]
#268 duplicate
