### ISSUE TITLE
[IntelliJ] Could not link aris cluster when use url as name

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2500]
Build: private build 2642

Repro Steps:
1. Use the url as cluster name, click OK 

Result:
Nothing happened, the link dialog keep openning without any warning.
![image](https://user-images.githubusercontent.com/36756024/49849768-0ca9f280-fe16-11e8-8b74-a18274fb46a7.png)

Refresh aris node, null[linked] display and get errors

java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at com.microsoft.azure.hdinsight.common.JobViewManager.registerJovViewNode(JobViewManager.java:59)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.ClusterNode.refreshItems(ClusterNode.java:165)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:96)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:148)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by t-rufang** [comment]
I will add some restriction to the naming of cluster.

**Comment by jingyanjingyan** [comment]
Refresh aris node, null[linked] display and get errors, update the steps.

**Comment by t-rufang** [comment]
Fixed in #2535

**Comment by v-jiche** [comment]
Verified. Fixed.
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018
