### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error - ADLS gen1 path include return sign

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2515]
IntelliJ build version: 2018.3.1 IC-183.4588.27
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.16.0-2018.3

Build: https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.16.0/azure-toolkit-for-intellij-2018.3.84.12-12-2018.zip 

Repro Steps:
1. Create a HDInsight config file, set the adls cluster
2. In storage type, choose ADLS Gen1, set the path with: **(Please copy the following 2 lines)** adl://devtooltelemetryadls.azuredatalakestore.net/clusters/hdi-root
     
3. Tab away to make the path display
4. Click Apply then Close, and submit

![enterinadlsgen1path](https://user-images.githubusercontent.com/36756024/49932222-6c5cd800-fec0-11e8-9700-ce2f71f5f366.gif)

Result:
Get error 
![image](https://user-images.githubusercontent.com/36756024/49930035-babba800-febb-11e8-8a83-59b96632d346.png)

Error message: 
```
java.net.URISyntaxException: Illegal character in path at index 67: adl://devtooltelemetryadls.azuredatalakestore.net/clusters/hdi-root /
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifactToADLS$8(JobUtils.java:637)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:50)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wezhang** [comment]
@t-rufang , we can add a validation check for adl url

**Comment by jingyanjingyan** [comment]
Fixed in private build 2834
