### ISSUE TITLE
[IntelliJ][ReportedByUser][Log][Spark] Azure Plugin for IntelliJ Error

### ISSUE THREAD

**Issue by starostinEgor** [microsoft/azure-tools-for-java#2523]
IntelliJ build version: 2018.2.7 IC-182.5107.41
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.15.0-2018.2
Error message: 
```
com.microsoft.azure.hdinsight.spark.common.SparkJobException: The Spark job failed to start due to 	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:317)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 1
Failing this attempt. Failing the application.
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$awaitStarted$58(SparkBatchJob.java:1252)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OperatorTakeUntilPredicate$ParentSubscriber.onNext(OperatorTakeUntilPredicate.java:61)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.

**Comment by t-rufang** [comment]
Close the issue since duplciate
