### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file.

### ISSUE THREAD

**Issue by sergiogragera** [microsoft/azure-tools-for-java#2525]
IntelliJ build version: 2018.3.1 IU-183.4588.61
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.16.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1280x755,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at com.microsoft.azuretools.azurecommons.util.ParserXMLUtility.parseXMLFile(ParserXMLUtility.java:68)
	at com.microsoft.intellij.AzurePlugin.setValues(AzurePlugin.java:235)
	at com.microsoft.intellij.AzurePlugin.initializeTelemetry(AzurePlugin.java:164)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:144)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:264)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$loadProjectWithProgress$13(Projec

**Comment by andxu** [comment]
@selvasingh Cloud you please delete this file and retry it:
C:\Users\<your username>\AppData\Roaming\JetBrains\IntelliJIdea2020.1\plugins\azure-toolkit-for-intellij\data.xml

**Comment by andxu** [comment]
Follow action: delete data.xml if it is corrupt.
