### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception updateSubscriptionWithProgressDialog com.microsoft.azuretools.adauth.AuthException: No subscription found in the account

### ISSUE THREAD

**Issue by sureshrr** [microsoft/azure-tools-for-java#2536]
IntelliJ build version: 2018.3.1 IU-183.4588.61
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.16.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1440x782,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=updateSubscriptionWithProgressDialog, throwable=com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.azuretools.ijidea.actions.SelectSubscriptionsAction$1.run(SelectSubscriptionsAction.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressM

**Comment by wezhang** [comment]
Thanks @sureshrr! @andxu, could you have a look?

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
