### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error - [HDInsight] invalid connection string when submit with empty azure blob

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2553]
Build: develop 920

Repro Steps:
1. Link cluster spark22blobhdi
2. Create a HDInsight config file, set cluster spark22blobhdi, set main class, set storage account to Azure blob and keep the form empty, save config file
3. Click remote submit, click "Continue anyway"

Result:
![image](https://user-images.githubusercontent.com/36756024/50441271-d5e1db00-08f1-11e9-9883-e5ef6ce2b145.png)

IntelliJ build version: 2018.3 IC-183.4284.148
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.16.0-2018.3
Error message: 
```
java.lang.IllegalArgumentException: Invalid connection string.
	at com.microsoft.azure.storage.CloudStorageAccount.parse(CloudStorageAccount.java:270)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getCloudStorageAccount(StorageClientSDKManager.java:742)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getCloudBlobClient(StorageClientSDKManager.java:761)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:116)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getSparkClusterDefaultContainer(JobUtils.java:433)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToAzure(JobUtils.java:454)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$9(JobUtils.java:661)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lcadzy** [comment]
will show when running the job
![image](https://user-images.githubusercontent.com/43339305/50471890-87b40100-09f1-11e9-9ed9-8654c5786bbf.png)

**Comment by v-xiaocw** [comment]
Verified, Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.928.12-28-2018
