### ISSUE TITLE
[IntelliJ][Linux]Frequent pop-ups when list HDInsight clusters.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2567]
Build:
azure-toolkit-for-intellij-2018.3.develop.923.12-27-2018

Repro Steps:
1. Open Azure.
2. Click HDInsight to list clusters.

Result:
1. Pop-up windows pop up frequently.
![image](https://user-images.githubusercontent.com/35950097/50473366-916b4380-09b4-11e9-95ee-ba89d48d094d.png)
2. Clusters is always refreshing.
![image](https://user-images.githubusercontent.com/35950097/50474772-2ae92400-09ba-11e9-8941-d9338268a6a4.png)

**Comment by wezhang** [comment]
@t-rufang , could you check it with other refresh issue #2392

**Comment by jingyanjingyan** [comment]
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:903)
	at java.util.ArrayList$Itr.next(ArrayList.java:853)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.fireChangeListenerEvent(ObservableList.java:124)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.add(ObservableList.java:76)
	at com.google.common.collect.ForwardingList.standardAdd(ForwardingList.java:139)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.add(ObservableList.java:44)
	at com.microsoft.tooling.msservices.serviceexplorer.Node.addChildNode(Node.java:193)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountNode.lambda$refreshItems$1(StorageAccountNode.java:107)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountNode.refreshItems(StorageAccountNode.java:106)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jingyanjingyan** [comment]
The error log with build Develop 934 18.3

java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountNode.refreshItems(StorageAccountNode.java:116)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by v-jiche** [comment]
Verified, Fixed.
Build:azure-toolkit-for-intellij-2018.3.PR.2806.12-29-2018
