### ISSUE TITLE
[IntelliJ][ReportedByUser] [Log][Spark]Azure Plugin for IntelliJ Error - [HDInsight] invalid connection string when submit with  azure blob 

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2580]
Build: 
azure-toolkit-for-intellij-2018.3.develop.928.12-28-2018

Repro Steps:
1. Link cluster spark22blobhdi
2. Create a HDInsight config file, set cluster spark22blobhdi, set main class, set storage Type to Azure blob and correct storage account ,then **keep the key empty,** save config file
3. Click remote submit, click "Continue anyway"

Result:
![image](https://user-images.githubusercontent.com/35950097/50508389-92dd5000-0a36-11e9-9bcd-8e3b177be08b.png)

Error details:
java.lang.IllegalArgumentException: Invalid connection string.
	at com.microsoft.azure.storage.CloudStorageAccount.parse(CloudStorageAccount.java:270)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getCloudStorageAccount(StorageClientSDKManager.java:742)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getCloudBlobClient(StorageClientSDKManager.java:761)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:116)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getSparkClusterDefaultContainer(JobUtils.java:433)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToAzure(JobUtils.java:454)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$9(JobUtils.java:661)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by v-jiche** [comment]
You can refer to bug #2553

**Comment by v-jiche** [comment]
Change the condition of step 2, then click remote submit and click "Continue anyway".
Step 2:
Create a HDInsight config file, set cluster spark22blobhdi, set main class, set storage type to Azure blob and **storage account ,then keep the key empty**, save config file

1. Set **correct storage account and key**, then save config file before the container is refreshed out.
![image](https://user-images.githubusercontent.com/35950097/50508938-c9b46580-0a38-11e9-9894-2d3ce2b05521.png)
![image](https://user-images.githubusercontent.com/35950097/50508959-e0f35300-0a38-11e9-941f-1076baa7cfbd.png)
2. Set **wrong storage account and key**, then save config file.
![image](https://user-images.githubusercontent.com/35950097/50509047-552df680-0a39-11e9-9337-df79b4a13961.png)
![image](https://user-images.githubusercontent.com/35950097/50509070-67a83000-0a39-11e9-9d23-058d6c5815fc.png)
3. Set **wrong storage account and keep the key empty**, then save config file.
![image](https://user-images.githubusercontent.com/35950097/50509153-b655ca00-0a39-11e9-99fd-b8861240d2db.png)
![image](https://user-images.githubusercontent.com/35950097/50509167-c4a3e600-0a39-11e9-8a69-ffb0eb5e3897.png)
4. Set **correct storage account and keep the key empty**, then save config file.
![image](https://user-images.githubusercontent.com/35950097/50509251-0df43580-0a3a-11e9-8f3d-3b407430e8b2.png)
![image](https://user-images.githubusercontent.com/35950097/50509269-1ba9bb00-0a3a-11e9-8cf8-c2593176a05d.png)
5. Keep **the account empty and set correct key,** then save config file.
![image](https://user-images.githubusercontent.com/35950097/50509385-822ed900-0a3a-11e9-86c7-f1944bb6fb28.png)
6. Keep **the account empty and set wrong key**, then save config file.
![image](https://user-images.githubusercontent.com/35950097/50509452-bbffdf80-0a3a-11e9-8c3b-0186da97fc90.png)
7. Keep **the account and key empty**, then save config file.(Fixed in bug #2553 )
![image](https://user-images.githubusercontent.com/35950097/50509617-77c10f00-0a3b-11e9-8d32-014f0e178249.png)

**Comment by v-jiche** [comment]
Build: azure-toolkit-for-intellij-2018.3.develop.953.01-02-2019

1. correct storage account + correct key + empty container = Exception without detail message
Note: click ok button before the container is refreshed.
![image](https://user-images.githubusercontent.com/35950097/50590578-81a3a180-0e83-11e9-8963-89ff1251512f.png)
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getSparkClusterDefaultContainer(JobUtils.java:435)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToAzure(JobUtils.java:454)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$9(JobUtils.java:661)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2. wrong storage account + wrong key = Storage Key is not a valid base64 encoded string
![image](https://user-images.githubusercontent.com/35950097/50590663-c8919700-0e83-11e9-95f1-2f65eda4318a.png)
java.security.InvalidKeyException: Storage Key is not a valid base64 encoded string.
	at com.microsoft.azure.storage.StorageCredentials.tryParseCredentials(StorageCredentials.java:68)
	at com.microsoft.azure.storage.CloudStorageAccount.tryConfigureServiceAccount(CloudStorageAccount.java:657)
	at com.microsoft.azure.storage.CloudStorageAccount.parse(CloudStorageAccount.java:280)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getCloudStorageAccount(StorageClientSDKManager.java:747)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getCloudBlobClient(StorageClientSDKManager.java:766)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:121)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:113)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getSparkClusterDefaultContainer(JobUtils.java:433)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.uploadFileToAzure(JobUtils.java:454)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$9(JobUtils.java:661)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

3. wrong storage account + empty key = Invalid connection string
![image](https://user-images.githubusercontent.com/35950097/50590765-27571080-0e84-11e9-9089-69a9072a3c94.png)

4. correct storage account + empty key = Invalid connection string
![image](https://user-images.githubusercontent.com/35950097/50590805-4f467400-0e84-11e9-9ab1-4918403252d5.png)


5. empty storage account + correct key
![image](https://user-images.githubusercontent.com/35950097/50590848-80bf3f80-0e84-11e9-894c-ecc9d79c9535.png)


6. empty storage account + wrong key
![image](https://user-images.githubusercontent.com/35950097/50590870-9fbdd180-0e84-11e9-97e5-5cb4694d9cf4.png)

7. empty storage + empty key
![image](https://user-images.githubusercontent.com/35950097/50590900-bfed9080-0e84-11e9-8f23-20b24c688174.png)

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.978.01-23-2019
