### ISSUE TITLE
[intelliJ][Linux] StackOverflowError when link Aris Cluster.

### ISSUE THREAD

**Issue by v-jiche** [Microsoft/azure-tools-for-java#2599]
Build:
azure-toolkit-for-intellij-2018.3.develop.943.12-29-2018

Note:
It repros only once.

Repro Steps:
1. Link Aris Cluster.
    host: 10.91.134.112
    name: 10.91.134.112
    user name: root
    Password: Yukon900

Result:
Dialogue box pops up .
![image](https://user-images.githubusercontent.com/35950097/50538328-beab2380-0b65-11e9-8029-995ec8196879.png)

Log detail:
update failed for AnAction(com.intellij.execution.actions.RunContextAction) with ID=RunClass

java.lang.StackOverflowError
	at com.microsoft.azure.hdinsight.spark.run.configuration.CosmosServerlessSparkSubmitModel.getSubmissionParameter(CosmosServerlessSparkSubmitModel.kt:40)
	at com.microsoft.azure.hdinsight.spark.run.configuration.CosmosServerlessSparkSubmitModel.getSubmissionParameter(CosmosServerlessSparkSubmitModel.kt:40)
	at com.microsoft.azure.hdinsight.spark.run.configuration.CosmosServerlessSparkSubmitModel.getSubmissionParameter(CosmosServerlessSparkSubmitModel.kt:40)
	at com.microsoft.azure.hdinsight.spark.run.configuration.CosmosServerlessSparkSubmitModel.getSubmissionParameter(CosmosServerlessSparkSubmitModel.kt:40)
	at com.microsoft.azure.hdinsight.spark.run.configuration.CosmosServerlessSparkSubmitModel.getSubmissionParameter(CosmosServerlessSparkSubmitModel.kt:40)
...

**Comment by wezhang** [comment]
https://github.com/Microsoft/azure-tools-for-java/commit/4eff8894cd034e8655c677417afa47a19abbc1c6#diff-14e3153ce802cdabb8e3f45a9526a4ad

causes that

**Comment by v-jiche** [comment]
Verified. Fixed.
Build: azure-toolkit-for-intellij-2018.3.develop.946.12-30-2018
