### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ClassCastException: com.intellij.execution.jar.JarApplicationConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration

### ISSUE THREAD

**Issue by bandfish** [Microsoft/azure-tools-for-java#2657]
IntelliJ build version: 2018.3.2 IC-183.4886.37
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.17.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1920x1137,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ClassCastException: com.intellij.execution.jar.JarApplicationConfiguration cannot be cast to com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.submit(SparkSubmitJobAction.kt:87)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.onActionPerformed(SparkSubmitJobAction.kt:66)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$A

**Comment by wezhang** [comment]
Thanks @bandfish ! Dup #2749
