### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@59ac1ea5] - other than com.intellij.util.proxy.CommonProxy.ourInstance.

### ISSUE THREAD

**Issue by ShingmoYeung** [microsoft/azure-tools-for-java#2665]
IntelliJ build version: 2018.3.3 IU-183.5153.38
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.17.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1553x944,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@59ac1ea5] - other than com.intellij.util.proxy.CommonProxy.ourInstance.
This will make some IDEA network calls fail.
Instead, methods of com.intellij.util.proxy.CommonProxy should be used for proxying.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.util.proxy.CommonProxy.isInstalledAssertion(CommonProxy.java:65)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:187)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.SystemDefaultRoutePlanner.determineProxy(SystemDefaultRoutePlanner.java:94)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:78)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at com.microsof

**Comment by Flanker32** [comment]
@ShingmoYeung Thanks a lot for your report and really sorry for the late reply, did you remember how this issue occurs, or could you please try our latest version to see whether this issue could be reproduced?
