### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file.

### ISSUE THREAD

**Issue by marcuslang** [microsoft/azure-tools-for-java#2683]
IntelliJ build version: 2018.3.4 Preview IU-183.5429.1
OS: Linux
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.17.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,23,2525x1392,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at com.microsoft.azuretools.azurecommons.util.ParserXMLUtility.parseXMLFile(ParserXMLUtility.java:68)
	at com.microsoft.intellij.AzurePlugin.setValues(AzurePlugin.java:235)
	at com.microsoft.intellij.AzurePlugin.initializeTelemetry(AzurePlugin.java:164)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:144)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:264)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$l

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file. (#2525)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: throwable=org.xml.sax.SAXParseException; Premature end of file.
