### ISSUE TITLE
[IntelliJ][ReportedByUser][AzureExplorer]HDInsight Explorer——Failed to get HDInsight configuration

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#2698]
IntelliJ build version: 2018.3.1 IC-183.4588.27
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.17.0-2018.3
 Build: azure-toolkit-for-intellij-2018.3.develop.972.01-22-2019

Repro Steps:
After a period of time using the PPE environment:
1.Remove the Josn file for the PPE environment settings.
2.Then restart IntelliJ and sign in with the PROD environment mailbox account.
3.Ritght click on "HDInsight",and select "Refresh"

Result:
![image](https://user-images.githubusercontent.com/43333874/51523776-3f65e400-1de1-11e9-8fa5-5a74ee627964.png)

Error message: 
com.microsoft.azure.hdinsight.sdk.common.HDIException: Failed to get default storage account name
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getDefaultStorageAccount(ClusterDetail.java:264)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getConfigurationInfo(ClusterDetail.java:230)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountFolderNode.refreshItems(StorageAccountFolderNode.java:55)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  HDInsight Explorer (#2800)

**Comment by wezhang** [comment]
Not production environment
