### ISSUE TITLE
An error occurred while attempting to load Web Apps.

### ISSUE THREAD

**Issue by hsirtl** [Microsoft/azure-tools-for-java#27]
Made a clean install of JDK, Eclipse (Neon) and the toolkit. When refreshing the Azure explorer all resources refresh fine, except Web Apps. Following message appears:

An error occurred while attempting to load Web Apps.

Stack Trace:

com.microsoft.tooling.msservices.helpers.azure.AzureCmdException: No enum constant com.microsoft.azure.management.websites.models.RemoteDebuggingVersion.VS2015
	at com.microsoft.tooling.msservices.helpers.auth.AADManagerImpl.request(AADManagerImpl.java:114)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestAzureSDK(AzureManagerImpl.java:1472)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.requestWebSiteSDK(AzureManagerImpl.java:1313)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl.getWebSiteConfiguration(AzureManagerImpl.java:715)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refresh(WebappsModule.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureRefreshableNode$1.interruptibleAction(AzureRefreshableNode.java:62)
	at com.microsoft.tooling.msservices.serviceexplorer.EventHelper$2.run(EventHelper.java:100)
	at com.microsoft.azureexplorer.helpers.IDEHelperImpl$2.run(IDEHelperImpl.java:88)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.management.websites.models.RemoteDebuggingVersion.VS2015
	at com.microsoft.windowsazure.core.utils.EnumUtility.fromString(EnumUtility.java:43)
	at com.microsoft.azure.management.websites.WebSiteOperationsImpl.getConfiguration(WebSiteOperationsImpl.java:4264)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper.getWebSiteConfiguration(AzureSDKHelper.java:1940)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper.access$3400(AzureSDKHelper.java:173)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$36.execute(AzureSDKHelper.java:1003)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKHelper$36.execute(AzureSDKHelper.java:996)
	at com.microsoft.tooling.msservices.helpers.azure.AzureManagerImpl$10.execute(AzureManagerImpl.java:1465)
	at com.microsoft.tooling.msservices.helpers.auth.AADManagerImpl.request(AADManagerImpl.java:111)
	... 8 more

**Comment by martinsawicki** [comment]
this is the same issue as https://github.com/Microsoft/azure-tools-for-java/issues/25.
A minor update with a fix will be available within a day or two.
Root cause: the WebApp service on Azure recently started returning a new value for the remote config, which is not covered by the corresponding enum in the Azure SDK for Java and the enum constant recognition failure is not handled gracefully enough.

**Comment by martinsawicki** [comment]
released an update a couple of days ago that should address this issue.
