### ISSUE TITLE
ACR Explorer -> There is an error while opening the ACR explorer

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2718]
### Environment:

1. OS: Windows/Mac/Linux 
2. IDE: IntelliJ
2. ACR: An ACR without any repository and check the admin user enabled.

### Steps:
Right-click the ACR and choose Open ACR Explorer.

### Result:
The repository tab always shows `Loading...`  and an error is reported at the right-bottom side.
![image](https://user-images.githubusercontent.com/22470312/51729747-f0a19e00-20af-11e9-9016-7d44a938f2e5.png)

### Log:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'repos' of com/microsoft/intellij/helpers/containerregistry/ContainerRegistryPropertyView.listRepo must not be null
	at com.microsoft.intellij.helpers.containerregistry.ContainerRegistryPropertyView.$$$reportNull$$$0(ContainerRegistryPropertyView.java)
	at com.microsoft.intellij.helpers.containerregistry.ContainerRegistryPropertyView.listRepo(ContainerRegistryPropertyView.java)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryPropertyViewPresenter.lambda$null$9(ContainerRegistryPropertyViewPresenter.java:157)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bsaby** [comment]
- IntelliJ 18.3.x: Fixed and test passed.
- IntelliJ 18.2.x: **Repro**
![image](https://user-images.githubusercontent.com/22470312/51953695-4e4f3500-2478-11e9-9389-4ccd01d3169b.png)

**Comment by bsaby** [comment]
- IntelliJ 18.3.x: Fixed and the test passed.
- IntelliJ 18.2.x: **Repro**

**Comment by bsaby** [comment]
Build: 3.18.0(pre-release bits)
Fixed and the test passed.
