### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception updateSubscriptionWithProgressDialog: No subscription found in the account com.microsoft.azuretools.adauth.AuthException: No subscription found in the account

### ISSUE THREAD

**Issue by amirfrd** [microsoft/azure-tools-for-java#2739]
IntelliJ build version: 2018.1.5 IU-181.5281.24
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame[frame0,571,193,783x489,invalid,layout=java.awt.BorderLayout,title=Welcome to IntelliJ IDEA,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,3,26,777x460,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=777,height=460]],rootPaneCheckingEnabled=true]
```
Error message: 
```
IdeaLoggingEvent[message=updateSubscriptionWithProgressDialog: No subscription found in the account, throwable=com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.azuretools.ijidea.actions.SelectSubscriptionsAction$1.run(SelectSubscriptionsAction.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
