### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Component name collision: com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent and class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by clumsym76** [microsoft/azure-tools-for-java#2750]
IntelliJ build version: 2018.3.4 IU-183.5429.30
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.18.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,22,849x491,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Component name collision: com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent and class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:350)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponentInstance(ComponentManagerImpl.java:412)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$400(ComponentManagerImp

**Comment by wezhang** [comment]
@konjac , could you help to check this?

**Comment by t-rufang** [comment]
Hi clumsym76, we will close this bug since we can't repro it now. Feel free to reopen the bug if it still repros for you. It would be better if you can let us know the repro steps.
