### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.intellij.execution.actions.RunContextAction) with ID=RunClass java.lang.NullPointerException

### ISSUE THREAD

**Issue by spjoseph** [microsoft/azure-tools-for-java#2751]
IntelliJ build version: 2018.3.4 IU-183.5429.30
OS: Windows 8.1
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.18.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,30,1386x751,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.intellij.execution.actions.RunContextAction) with ID=RunClass, throwable=java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.common.SparkLocalRunConfigurableModel.<init>(SparkLocalRunConfigurableModel.java:84)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJobConfigurableModel.<init>(SparkBatchJobConfigurableModel.java:60)
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration.<init>(LivySparkBatchJobRunConfiguration.java:80)
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobConfigurationFactory.createTemplateConfiguration(LivySparkBatchJobConfigurationFactory.java:46)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:147)
	at com.intellij.exec

**Comment by t-rufang** [comment]
Close this bug since we can't repro it.
