### ISSUE TITLE
ACR Explorer always load when opning with empty repository

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2788]
### Environment:
1. OS: Windows/Mac/Linux
2. Eclipse: 2018-12 (4.10.0)
3. Bits: dev995
3. ACR: An ACR without any repository and check the admin user enabled.

### Steps:
Right-click the ACR and choose Open ACR Explorer.

### Result:
It is always loading.
![image](https://user-images.githubusercontent.com/22470312/53541149-7c956280-3b53-11e9-9003-21ed1f4274ec.png)
Error log:
```
java.lang.NullPointerException
	at com.microsoft.azuretools.azureexplorer.editors.container.ContainerRegistryExplorerEditor.fillList(ContainerRegistryExplorerEditor.java:707)
	at com.microsoft.azuretools.azureexplorer.editors.container.ContainerRegistryExplorerEditor.listRepo(ContainerRegistryExplorerEditor.java:563)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryPropertyViewPresenter.lambda$null$9(ContainerRegistryPropertyViewPresenter.java:157)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

```

### Expect:
![image](https://user-images.githubusercontent.com/22470312/53541167-8c14ab80-3b53-11e9-863d-a27c59842bcd.png)

Same root cause as #2718 ?

**Comment by bsaby** [comment]
Fixed and the test passed.
Build: develop1005
