### ISSUE TITLE
[Eclipse]Error occurred while stopping the running process of application insight project

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2789]
### Environment:
* OS: Windows/Mac/Linux
* Eclipse: 2018-12 (4.10.0)
* Bits: dev995
* Tomcat: 8.5.38/9.0.16

### Steps:
1. Create a web dynamic project
2. Right-click project and configure the AI
  [How to configure application insight in Eclipse](https://microsoft.sharepoint.com/teams/WPTFundamental/_layouts/15/WopiFrame.aspx?sourcedoc={42ae2c33-259b-459a-98b2-6bfc94b77f5c}&action=edit&wd=target%28Java%20Tools%2FAzure%20Java%20Toolkits%2FAzure%20java%20toolkits%28IDE%5C%29-manual.one%7C7faf569a-ea05-4b92-957a-626d02b04207%2F%5BEclipse%5DConfigure%20Application%20Insights%7C41efff04-e38a-4bfc-9904-5f48c3531cdd%2F%29)
3. Run the application
4. Stop the server after the artifact is deployed successfully

### Result:
Error occured.
![image](https://user-images.githubusercontent.com/22470312/53541761-486f7100-3b56-11e9-8f2e-15f406f7e925.png)

Click OK, report error directly.
Click Cancel, pop up again to ask user make a choice after a short while.

Error log:
```
INFO: Stopping ProtocolHandler ["http-nio-8080"]
Feb 28, 2019 4:41:34 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-nio-8009"]
Feb 28, 2019 4:41:34 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8080"]
Feb 28, 2019 4:41:34 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-nio-8009"]
Feb 28, 2019 4:41:35 AM org.apache.catalina.loader.WebappClassLoaderBase checkStateForResourceLoading
INFO: Illegal access: this web application instance has been stopped already. Could not load [java.util.zip.GZIPOutputStream]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.util.zip.GZIPOutputStream]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1384)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1372)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1224)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
	at com.microsoft.applicationinsights.internal.channel.common.GzipTelemetrySerializer.serialize(GzipTelemetrySerializer.java:65)
	at com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl$SendHandler.dispatch(TransmitterImpl.java:72)
	at com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl$ScheduledSendHandler.run(TransmitterImpl.java:95)
	at com.microsoft.applicationinsights.internal.channel.common.TransmitterImpl$1.run(TransmitterImpl.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Similar as #2122  in IntelliJ?

**Comment by bsaby** [comment]
Fixed and the test passed.
Build: develop1005
