### ISSUE TITLE
An error occurred while executing the maven goal provided by the plugin

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2803]
### Environment:
* OS: Windows/Mac/Linux
* IDE version
```
IntelliJ IDEA 2019.1 EAP (Ultimate Edition) Build #IU-191.5849.21, built on February 27, 2019
IntelliJ IDEA 2019.1 EAP (Community Edition) Build #IC-191.5849.21, built on February 27, 2019
```

* Bits: PR3012

### How to repro:
1. Import a spring boot project or create a maven web app project
2. Right click the project and Select `Run on Web App`
3. Fill in some configuration and click "Run"

### Result:
Failed execute the maven goal to build package and throw an error

![image](https://user-images.githubusercontent.com/22470312/53624968-cb6af700-3c3c-11e9-965b-8124c544b25f.png)

**Error screenshot**
![image](https://user-images.githubusercontent.com/22470312/53624970-cf971480-3c3c-11e9-8ef5-fa13e6493b91.png)

**Error log**
```
Access is allowed from event dispatch thread only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@66849666
Current thread: Thread[ApplicationImpl pooled thread 7,4,Idea Thread Group] 1248762912
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1316711922
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1128)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1117)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3266)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:348)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:201)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:171)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:63)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:951)
	at com.intellij.execution.impl.ConsoleViewImpl.lambda$createConsoleEditor$12(ConsoleViewImpl.java:929)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:970)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleEditor(ConsoleViewImpl.java:928)
	at com.intellij.execution.impl.ConsoleViewImpl.initConsoleEditor(ConsoleViewImpl.java:431)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:410)
	at com.intellij.build.CompositeView.addView(CompositeView.java:65)
	at com.intellij.build.BuildView.<init>(BuildView.java:79)
	at org.jetbrains.idea.maven.buildtool.BuildViewMavenConsole.createBuildView(BuildViewMavenConsole.java:155)
	at org.jetbrains.idea.maven.buildtool.BuildViewMavenConsole.<init>(BuildViewMavenConsole.java:72)
	at org.jetbrains.idea.maven.project.MavenConsole.createGuiMavenConsole(MavenConsole.java:44)
	at org.jetbrains.idea.maven.execution.MavenRunner.createConsole(MavenRunner.java:176)
	at org.jetbrains.idea.maven.execution.MavenRunner.lambda$runBatch$0(MavenRunner.java:131)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at org.jetbrains.idea.maven.execution.MavenRunner.runBatch(MavenRunner.java:129)
	at org.jetbrains.idea.maven.execution.MavenRunner.runBatch(MavenRunner.java:115)
	at org.jetbrains.idea.maven.tasks.MavenBeforeRunTasksProvider$1.run(MavenBeforeRunTasksProvider.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

This issue affects many features, including

- Run on Web app
- Run on Web App for Conatiners
- Push Image
- Docker Run

**Comment by Flanker32** [comment]
This seems to be an issue with IntelliJ new builds, here is the issue [link](https://youtrack.jetbrains.com/issue/IDEA-208029)

**Comment by Flanker32** [comment]
This was fixed in the latest IntelliJ build.
