### ISSUE TITLE
An error occurred while first pushing the image

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#2805]
### Environment:
* OS: Windows/Mac/Linux
* IDE version

```
IntelliJ IDEA 2019.1 EAP (Ultimate Edition) Build #IU-191.5849.21, built on February 27, 2019
IntelliJ IDEA 2019.1 EAP (Community Edition) Build #IC-191.5849.21, built on February 27, 2019
```
* Bits: PR3012

### How to repro:
1. New a web project in IntelliJ
2. Configure the atifact
2. Right click project and choose `Add Docker support`
2. Right click project and choose `Push Image`

### Result:
An error occurred while pushing the image at the first time.
```
java.lang.Throwable: Element component@RunManager.configuration.option.PrivateRegistryImageSetting.option.@name=password probably contains sensitive information (file: ~/IdeaProjects/helloworld1/.idea/workspace.xml)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.configurationStore.JbXmlOutputter.logSensitiveInformationError(JbXmlOutputter.kt:561)
	at com.intellij.configurationStore.JbXmlOutputter.checkIsElementContainsSensitiveInformation(JbXmlOutputter.kt:523)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:262)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.JbXmlOutputter.printContentRange(JbXmlOutputter.kt:341)
	at com.intellij.configurationStore.JbXmlOutputter.writeContent(JbXmlOutputter.kt:280)
	at com.intellij.configurationStore.JbXmlOutputter.printElement(JbXmlOutputter.kt:250)
	at com.intellij.configurationStore.XmlDataWriter.write$intellij_platform_configurationStore_impl(XmlElementStorage.kt:274)
	at com.intellij.configurationStore.StringDataWriter.write(XmlElementStorage.kt:421)
	at com.intellij.configurationStore.DataWriter$DefaultImpls.write$default(XmlElementStorage.kt:402)
	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$2$1.run(actions.kt:80)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.configurationStore.FileBasedStorageKt$doWrite$$inlined$runUndoTransparentWriteAction$2.run(actions.kt:16)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:377)
	at com.intellij.configurationStore.FileBasedStorageKt.doWrite(FileBasedStorage.kt:367)
	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:244)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:109)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession$SaveExecutor.save(XmlElementStorage.kt:166)
	at com.intellij.configurationStore.SaveExecutorKt.executeSave(SaveExecutor.kt:91)
	at com.intellij.configurationStore.SaveExecutorKt.saveSessions(SaveExecutor.kt:85)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$saveResult$1.invokeSuspend(ProjectSaveSessionProducerManager.kt:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher.dispatch(BaseAsyncExecutionSupport.kt:81)
	at com.intellij.openapi.application.async.RescheduleAttemptLimitAwareDispatcher.retryDispatch(RescheduleAttemptLimitAwareDispatcher.kt:29)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher$dispatch$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.application.async.AppUIExecutorImpl$inWriteAction$1.schedule(AppUIExecutorImpl.kt:116)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$SimpleConstraintDispatcher.dispatch(BaseAsyncExecutionSupport.kt:99)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher.dispatch(BaseAsyncExecutionSupport.kt:76)
	at com.intellij.openapi.application.async.RescheduleAttemptLimitAwareDispatcher.retryDispatch(RescheduleAttemptLimitAwareDispatcher.kt:29)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher$dispatch$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:377)
	at com.intellij.openapi.application.async.AppUIExecutorImpl$inUndoTransparentAction$1.schedule(AppUIExecutorImpl.kt:103)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$SimpleConstraintDispatcher.dispatch(BaseAsyncExecutionSupport.kt:99)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher.dispatch(BaseAsyncExecutionSupport.kt:76)
	at com.intellij.openapi.application.async.RescheduleAttemptLimitAwareDispatcher.retryDispatch(RescheduleAttemptLimitAwareDispatcher.kt:29)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher$dispatch$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.async.AppUIExecutorImpl$inTransaction$1.schedule(AppUIExecutorImpl.kt:90)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$SimpleConstraintDispatcher.dispatch(BaseAsyncExecutionSupport.kt:99)
	at com.intellij.openapi.application.async.BaseAsyncExecutionSupport$CompositeDispatcher.dispatch(BaseAsyncExecutionSupport.kt:76)
	at com.intellij.openapi.application.async.RescheduleAttemptLimitAwareDispatcher.dispatch(RescheduleAttemptLimitAwareDispatcher.kt:22)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:282)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:23)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:148)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager.saveWithAdditionalSaveSessions(ProjectSaveSessionProducerManager.kt:26)
	at com.intellij.configurationStore.ProjectStoreImpl$doSave$2$1.invokeSuspend(ProjectStoreImpl.kt:334)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.EventLoopBase.processNextEvent(EventLoop.kt:123)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:45)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.configurationStore.StoreUtil$Companion.saveSettings(storeUtil.kt:51)
	at com.intellij.configurationStore.StoreUtil.saveSettings(storeUtil.kt)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:330)
	at com.intellij.compiler.impl.CompileDriver.a(CompileDriver.java:376)
	at com.intellij.compiler.impl.CompileDriver.make(CompileDriver.java:94)
	at com.intellij.compiler.impl.CompileDriver.make(CompileDriver.java:89)
	at com.intellij.compiler.CompilerManagerImpl.make(CompilerManagerImpl.java:253)
	at com.intellij.task.impl.JpsProjectTaskRunner.a(JpsProjectTaskRunner.java:310)
	at com.intellij.task.impl.JpsProjectTaskRunner.c(JpsProjectTaskRunner.java:295)
	at com.intellij.task.impl.JpsProjectTaskRunner.run(JpsProjectTaskRunner.java:82)
	at com.intellij.task.impl.ProjectTaskManagerImpl.run(ProjectTaskManagerImpl.java:171)
	at com.intellij.packaging.impl.run.BuildArtifactsBeforeRunTaskProviderBase.a(BuildArtifactsBeforeRunTaskProviderBase.java:141)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:672)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:367)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by bsaby** [comment]
Fixed and the test passed,
Bits: PR3214
