### ISSUE TITLE
[IntelliJ][ReportedByUser] HDInsight Explorer

### ISSUE THREAD

**Issue by stevevd** [microsoft/azure-tools-for-java#2823]
IntelliJ build version: 2018.2.3 IC-182.4323.46
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.10.0-2018.2
Error message: 
```
com.microsoft.azure.hdinsight.sdk.common.HDIException: Failed to get default storage account name
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getDefaultStorageAccount(ClusterDetail.java:260)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getConfigurationInfo(ClusterDetail.java:226)
	at com.microsoft.azure.hdinsight.serverexplore.hdinsightnode.StorageAccountFolderNode.refreshItems(StorageAccountFolderNode.java:55)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:136)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(Appl

**Comment by t-rufang** [comment]
@stevevd Seems like you are using an old plugin version. If you update your IntelliJ to 2018.3.5 and update the plugin to the latest version, the issue should disappear. BTW, our latest plugin only support on the latest two IntelliJ version, which is IntelliJ 2018.3 and 2019.1EAP for now.

**Comment by t-rufang** [comment]
Close the issue since this is no reply from customer for a long time. Feel free to reopen the issue if it still repro for you. It would be better if you can let us know the repro steps.
