### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by jimvekemans** [Microsoft/azure-tools-for-java#2860]
IntelliJ build version: 2018.3.5 IU-183.5912.21
OS: Linux
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.18.0-2018.3
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:105)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.handleSubscriptionChange(AzureModule.java:220)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.access$100(AzureModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule$SignInOutListener.run(AzureModule.java:229)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:133)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:117)
	at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction$1.actionPerformed(SignInOutAction.java:46)
	at com.microsoft.tooling.m

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)
