### ISSUE TITLE
[IntelliJ2018.2][ReportedByUser] Uncaught Exception  com.intellij.openapi.util.InvalidDataException: Configuration is broken or not compatible

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2883]
Build: Dev 1033

Repro Steps:
1. Sign in
2. Right click on spark on cosmos account, click "Submit Spark on Cosmos Serverless Job"

Result:
Error

IntelliJ build version: 2018.2.7 IC-182.5107.41
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.19.0-2018.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1440x796,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
com.intellij.openapi.util.InvalidDataException: Configuration is broken or not compatible
	at com.microsoft.azure.hdinsight.spark.common.SparkSubmitModel.applyFromElement(SparkSubmitModel.java:317)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJobConfigurableModel.lambda$applyFromElement$0(SparkBatchJobConfigurableModel.java:102)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJobConfigurableModel.applyFromElement(SparkBatchJobConfigurableModel.java:102)
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration.readExternal(LivySparkBatchJobRunConfiguration.java:96)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:136)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:26)
	at com.intellij.execution.configurations.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:38)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:176)
	at com.intellij.execution.RunManager.createRunConfiguration(RunManager.kt:134)
	at com.microsoft.azure.cosmosspark.CosmosSparkClusterOpsCtrl.lambda$null$13(CosmosSparkClusterOpsCtrl.java:181)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.microsoft.azure.cosmosspark.CosmosSparkClusterOpsCtrl.lambda$new$14(CosmosSparkClusterOpsCtrl.java:181)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:224)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:652)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:665)
	at com.microsoft.intellij.rxjava.IdeaSchedulers.lambda$dispatchUIThread$4(IdeaSchedulers.java:79)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.schedule(ExecutorScheduler.java:79)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.schedule(OperatorObserveOn.java:188)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:163)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
	at com.microsoft.azure.cosmosspark.serverexplore.cosmossparknode.CosmosServerlessSparkSubmitAction.actionPerformed(CosmosServerlessSparkSubmitAction.java:54)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$createPopupMenuForNode$1(ServerExplorerToolWindowFactory.java:215)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.util.xmlb.XmlSerializationException: java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:102)
	at com.microsoft.azure.hdinsight.spark.common.SparkSubmitModel.applyFromElement(SparkSubmitModel.java:315)
	... 71 more
Caused by: java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
	at kotlin.collections.EmptyMap.clear(Maps.kt)
	at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:165)
	at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:142)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:41)
	at com.intellij.util.xmlb.TagBinding.deserialize(TagBinding.java:95)
	at com.intellij.util.xmlb.TagBinding.deserializeList(TagBinding.java:67)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:234)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:170)
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:96)
	... 72 more

**Comment by t-rufang** [comment]
Looking.

**Comment by jingyanjingyan** [comment]
Fix in PR 3155
