### ISSUE TITLE
Timeout error when shutting down/starting/restarting docker host

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#2932]
This issue cannot be stably reproduced, but the probability of occurrence is higher

### Environment:
OS: Win/Mac/Linux
JDK: 1.8
IntelliJ version:
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
	Build #IU-191.6183.62, built on March 21, 2019
	Licensed to IntelliJ IDEA Evaluator
	Expiration date: April 25, 2019
	JRE: 1.8.0_202-release-1483-b39 x86
	JVM: OpenJDK Server VM by JetBrains s.r.o
	Windows 10 10.0

IntelliJ IDEA 2019.1 (Community Edition)
	Build #IC-191.6183.62, built on March 21, 2019
	JRE: 1.8.0_202-release-1483-b39 x86
	JVM: OpenJDK Server VM by JetBrains s.r.o
```
### Repro steps:

1. Right-click the web project -> Azure -> Publish as Docker Container
2. After publised, right-click the docker host and choose Shutdown/Start/Restart

![image](https://user-images.githubusercontent.com/22470312/54987302-4f6f8f00-4fef-11e9-989e-7c43a11aa8ba.png)

### Result:
Timeout error occurred.
But there is no error  if operating this docker host under` Virtual Machines `node, 

LOG:
```
com.microsoft.azure.docker.model.AzureDockerException: Create Log In Instance: java.net.ConnectException: Connection timed out: connect
	at com.microsoft.azure.docker.ops.AzureDockerSSHOps.createLoginInstance(AzureDockerSSHOps.java:55)
	at com.microsoft.azure.docker.ops.AzureDockerImageOps.getImages(AzureDockerImageOps.java:167)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostNode.refreshDockerHostInstance(DockerHostNode.java:115)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostNode.access$000(DockerHostNode.java:46)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostNode$1$1.run(DockerHostNode.java:178)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
	at com.jcraft.jsch.Util.createSocket(Util.java:349)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.microsoft.azure.docker.ops.AzureDockerSSHOps.createLoginInstance(AzureDockerSSHOps.java:51)
	... 18 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.jcraft.jsch.Util.createSocket(Util.java:343)
	... 21 more

```

**Comment by Flanker32** [comment]
Didn't reproduce this issue, may related with azure service side.
For anyone who meets this problem, please also leave your comments here.

**Comment by EricZhangzf** [comment]
Can not repro it on 3.37.0
Maybe belongs to service issue
