### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error

### ISSUE THREAD

**Issue by sainatheluri** [Microsoft/azure-tools-for-java#2936]
IntelliJ build version: 2018.3.5 IC-183.5912.21
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.19.0-2018.3
Error message: 
```
java.lang.IllegalStateException: messageWithType.value must not be null
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchRemoteRunState$execute$$inlined$let$lambda$1.call(SparkBatchRemoteRunState.kt:73)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchRemoteRunState$execute$$inlined$let$lambda$1.call(SparkBatchRemoteRunState.kt:44)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteProcess.ctrlError(SparkBatchJobRemoteProcess.java:213)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteProcess.lambda$start$4(SparkBatchJobRemoteProcess.java:179)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorMe

**Comment by wezhang** [comment]
Thanks @sainatheluri !
