### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'

### ISSUE THREAD

**Issue by Stromweld** [Microsoft/azure-tools-for-java#2960]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x990,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:153)
	at com.intellij.execution.ExecutorRegistry.getInstance(ExecutorRegistry.java:14)
	at com.intellij.execution.executors.DefaultDebugExecutor.getDebugExecutorInstance(DefaultDebugExecutor.java:93)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJob

**Comment by wezhang** [comment]
Thanks @Stromweld ! Could you provide the steps to repro? (Dup #2983)

**Comment by Stromweld** [comment]
I installed the plugin and when trying to open a new project from version control using team services git > I get a login popup > then I login with my azure devops account information > I get a list of git repos from azure devops > I select a repo and click clone > I get the OAuth2.0 pop up again asking me to sign in > I sign in again > This OAuth dance happens 3 more times and then I get an error saying authentication failed for the url of the repo I'm trying to clone.

**Comment by wezhang** [comment]
Thanks @Stromweld !

**Comment by andxu** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  User feedback (#1831)
