### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file.

### ISSUE THREAD

**Issue by jarod7736** [microsoft/azure-tools-for-java#2970]
IntelliJ build version: 2018.3.5 IU-183.5912.21
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.20.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1914x1138,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at com.microsoft.azuretools.azurecommons.util.ParserXMLUtility.parseXMLFile(ParserXMLUtility.java:68)
	at com.microsoft.intellij.AzurePlugin.setValues(AzurePlugin.java:235)
	at com.microsoft.intellij.AzurePlugin.initializeTelemetry(AzurePlugin.java:164)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:144)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.ja

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file. (#2525)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: throwable=org.xml.sax.SAXParseException; Premature end of file.
