### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by anishpanthi** [microsoft/azure-tools-for-java#2975]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Error message: 
```
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:497)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.loadConvertedList(PagedListConverter.java:100)
	at com.microsoft.azure.management.resources.fluentcore.utils.PagedListConverter.convert(PagedListConverter.java:66)
	at com.microsoft.azure.management.appservice.implementation.WebAppsImpl.wrapList(WebAppsImpl.java:96)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listWebApps(AzureWebAppMvpModel.java:555)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listAllWebApps(AzureWebAppMvpModel.java:518)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModulePresenter.onModuleRefresh(WebAppModulePresenter.java:15)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModule.refreshItems(WebAppModule.java:63)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNod

**Comment by andxu** [comment]
@anishpanthi, apologize for the bad performance of listing web apps, it is an api from another team, we are in the progressing of keeping them changing this bad api.
