### ISSUE TITLE
[IntelliJ]Open job view get errors

### ISSUE THREAD

**Issue by jingyanjingyan** [Microsoft/azure-tools-for-java#2976]
Build: dev 1069

Repro Steps:
Click job node under this cluster
![image](https://user-images.githubusercontent.com/36756024/55526262-e38ec580-5683-11e9-905d-de6fa0f2468d.png)

Result:
get applications list error

com.microsoft.azure.hdinsight.sdk.common.HDIException: username is null, please call getConfigurationInfo first
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterDetail.getHttpUserName(ClusterDetail.java:171)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:416)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by t-rufang** [comment]
This issue should be fixed in the latest develop branch, please help verify.

**Comment by jingyanjingyan** [comment]
Fix in dev 1087
