### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/azure-tools-for-java#2979]
IntelliJ build version: 2018.2.6 IU-182.5107.16
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.16.0-2018.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: 574bbd41-a54a-4ea2-ac58-339c68eb0c00\r\nCorrelation ID: ee94886a-1336-4811-93bd-be79c9600a29\r\nTimestamp: 2019-04-04 07:37:28Z","error_codes":[90002],"timestamp":"2019-04-04 07:37:28Z","trace_id":"574bbd41-a54a-4ea2-ac58-339c68eb0c00","correlation_id":"ee94886a-1336-4811-93bd-be79c9600a29"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.list(ResourceGroupsInner.java:687)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsImpl.list(ResourceGroupsImpl.java:41)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesImpl.list(RegistriesImpl.java:55)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listRegistryBySubscriptionId(ContainerRegistryMvpModel.java:87)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listContainerRegistries(ContainerRegistryMvpModel.java:72)
	at com.micro

**Comment by t-rufang** [comment]
@sophiaso Could you try the latest plugin? BTW, you have to upgrade your IntelliJ to the latest [2019.1 version](https://www.jetbrains.com/idea/download/#section=windows) first so you can upgrade the toolkit to the latest version.

**Comment by sophiaso** [comment]
@t-rufang It's working after upgrading Intellij and plugin.

**Comment by t-rufang** [comment]
Great to see problem sovled, we will close the issue then.
