### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: Component name collision: com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent and class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by clumsym76** [microsoft/azure-tools-for-java#2980]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,2036x1648,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: Component name collision: com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent and class com.microsoft.azure.hdinsight.projects.HDInsightActionsComponent [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:368)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:68)
	at com.intellij.diagnostic.PluginExce

**Comment by wezhang** [comment]
Thanks @clumsym76 !

**Comment by t-rufang** [comment]
Duplicate with #2750
