### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'

### ISSUE THREAD

**Issue by GuyPaddock** [Microsoft/azure-tools-for-java#2981]
Recently upgraded to the 2019.1 release of IntelliJ and got an "IDE error" on startup:

IntelliJ build version: 2019.1 IU-191.6183.87
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,30,1536x801,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:153)
	at com.intellij.execution.ExecutorRegistry.getInstance(ExecutorRegistry.java:14)
	at com.intellij.execution.executors.DefaultDebugExecutor.getDebugExecutorInstance(DefaultDebugExecutor.java:93)

**Comment by wezhang** [comment]
Thanks @GuyPaddock ! Dup #2983

**Comment by andxu** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  User feedback (#1831)
