### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'

### ISSUE THREAD

**Issue by ejwinter** [Microsoft/azure-tools-for-java#2983]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Mac OS X
JDK: JetBrains s.r.o 11-internal
Plugin version: 3.20.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1036,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.execution.ExecutorRegistry'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:153)
	at com.intellij.execution.ExecutorRegistry.getInstance(ExecutorRegistry.java:14)
	at com.intellij.execution.executors.DefaultDebugExecutor.getDebugExecutorInstance(DefaultDebugExecutor.java:93)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebug

**Comment by wezhang** [comment]
Thanks @ejwinter ! Could you provide steps to repro?

**Comment by wezhang** [comment]
@v-jiche @jingyanjingyan could you help to repro this?

**Comment by ejwinter** [comment]
It was an auto generated submission by IntelliJ.  I was just restarting IntelliJ after an update.  Maybe things were in an inconsistent state.  I haven’t seen it again.

Thank you,
Eric

**Comment by wezhang** [comment]
Thanks @ejwinter ! We'll keep eyes on that!

**Comment by jingyanjingyan** [comment]
Not repro for now, will re-open if repro.

**Comment by andxu** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  User feedback (#1831)
