### ISSUE TITLE
[intelliJ]Get IDE Fatal Errors when Click jobs node in Azure Explorer.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3032]
Build:
azure-toolkit-for-intellij-2019.1.develop.1087.04-15-2019
Linux windows

Repro Steps:
1. Open Azure Explorer.
2. Expand HDInsight.
3. Click the jobs node of the clusters.

Result:
IDE Error Occurred.
![image](https://user-images.githubusercontent.com/35950097/56182615-89a7db80-6045-11e9-9ae4-d6765efb6547.png)
get applications list error

com.microsoft.azure.hdinsight.sdk.common.HDIException: Forbidden
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by t-rufang** [comment]
Hi @v-jiche   Which cluster are you using in this issue

**Comment by v-jiche** [comment]
The key is click the jobs node of multiple clusters.

**Comment by t-rufang** [comment]
Thanks! Could you please check if this issue happens in the previous release `v3.20.0` plugin?

**Comment by v-jiche** [comment]
Bug repros in the release v3.20.0 plugin.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748114
