### ISSUE TITLE
Can not import the authentication file to sign in azure subscription

### ISSUE THREAD

**Issue by shsushi** [Microsoft/azure-tools-for-java#304]
P0 Issue:
You can not import the authentication file to do automate sign in.

Expected:
User can use authentication file to successfully sign into subscription.

Repro:
1. Create a Java web application in IntelliJ.
2. Tools->Azure->Azure Sign In.
3. Choose **Automated** and Click **Browse** to import the authentication file(created by Azure Toolkit on Eclipse Neon) for your subscription account.
4. Then you will see the fatal IDE errors.
5. Tools->Azure, it shows Azure Sign Out now, which confuse the user.
<img width="490" alt="screen shot 2017-04-12 at 9 47 58 am" src="https://cloud.githubusercontent.com/assets/6917718/24969293/24d7ea9c-1f65-11e7-9f91-921a7c01c6fd.png">

OS: macOS Sierra (10.12.4)

Subscription Type: Enterprise

IDE: IntelliJ Ultimate 2017.1.1

Plugin: azure-toolkit-for-intellij.2017.267.04-11-2017.zip

Feature: Import Authentication File for Automated Sign In.

Errors Message:
Could not initialize class retrofit2.Platform

Stack Trace:
Could not initialize class retrofit2.Platform
java.lang.NoClassDefFoundError: Could not initialize class retrofit2.Platform
	at retrofit2.Retrofit$Builder.<init>(Retrofit.java:402)
	at com.microsoft.azure.RestClient$Builder.<init>(RestClient.java:144)
	at com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl.<init>(AzureConfigurableImpl.java:32)
	at com.microsoft.azure.management.Azure$ConfigurableImpl.<init>(Azure.java:167)
	at com.microsoft.azure.management.Azure$ConfigurableImpl.<init>(Azure.java:167)
	at com.microsoft.azure.management.Azure.configure(Azure.java:138)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.auth(ServicePrincipalAzureManager.java:83)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getTenants(ServicePrincipalAzureManager.java:140)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getSubscriptionsWithTenant(ServicePrincipalAzureManager.java:110)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateAccountSubscriptionList(SubscriptionManager.java:70)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(SubscriptionManagerPersist.java:64)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:55)
	at com.microsoft.azuretools.ijidea.actions.SelectSubscriptionsAction$1.run(SelectSubscriptionsAction.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vladimir-shcherbakov** [comment]
https://github.com/Microsoft/azure-tools-for-java-private/issues/238 duplicate.
