### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading elementsdatalake

### ISSUE THREAD

**Issue by leroylim20** [microsoft/azure-tools-for-java#3050]
IntelliJ build version: 2018.3.5 IU-183.5912.21
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.20.0-2018.3
Error message: 
```
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:122)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:113)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode.refreshItems(StorageNode.java:106)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.p

**Comment by andxu** [comment]
Duplicate as #2270
