### ISSUE TITLE
[intelliJ][Reader account]Error Loading Storage Accounts.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3055]
Build:
azure-toolkit-for-intellij-2019.1.develop.1097.04-17-2019

Repro Steps:
1. Sign in Azure with reader account.
2. Click Storage Accounts node.
3. Click a storage account randomly.
![image](https://user-images.githubusercontent.com/35950097/56284100-1afe7700-6146-11e9-9dfa-1d413f4637e8.png)
Result:
Error message pops up.
![image](https://user-images.githubusercontent.com/35950097/56283983-c8bd5600-6145-11e9-9950-9d14e14c1779.png)
```
com.microsoft.azure.CloudException: Status code 403, {"error":{"code":"AuthorizationFailed","message":"The client 'live.com#fangrui006@163.com' with object id 'a787728c-3e13-49d8-826c-437952960be2' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/7f31cba8-b597-4129-b158-8f21a7395bd0/resourceGroups/securitydata/providers/Microsoft.Storage/storageAccounts/7f1949eastasia'."}}: The client 'live.com#fangrui006@163.com' with object id 'a787728c-3e13-49d8-826c-437952960be2' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/7f31cba8-b597-4129-b158-8f21a7395bd0/resourceGroups/securitydata/providers/Microsoft.Storage/storageAccounts/7f1949eastasia'.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.listKeysDelegate(StorageAccountsInner.java:881)
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner.access$700(StorageAccountsInner.java:46)
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$29.call(StorageAccountsInner.java:868)
	at com.microsoft.azure.management.storage.implementation.StorageAccountsInner$29.call(StorageAccountsInner.java:864)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.DeferredScalarSubscriber.subscribeTo(DeferredScalarSubscriber.java:153)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:32)
	at rx.internal.operators.OnSubscribeTakeLastOne.call(OnSubscribeTakeLastOne.java:22)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.last(BlockingObservable.java:226)
	at com.microsoft.azure.management.storage.implementation.StorageAccountImpl.getKeys(StorageAccountImpl.java:198)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getConnectionString(StorageClientSDKManager.java:737)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode.refreshItems(StorageNode.java:106)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by v-jiche** [comment]
Bug repro in Build: azure-toolkit-for-intellij-2019.1.develop.1100.04-17-2019
OS: Linux windows

**Comment by t-rufang** [comment]
Hi @Flanker32 , this error happens when we refresh a storage account with Reader role permission. The exception is not captured so it drop to `Report to Microsoft` dialog. Could you help to take a look at this issue? BTW, the reason we start to test Reader role account is that HDInsight API change has some impacts on Reader role account.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1748113
