### ISSUE TITLE
[IntelliJ][Failure Debug][ReportedByUser] Azure Plugin for IntelliJ Error——Refresh errors caused by not being timely

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3056]
IntelliJ build version: 2019.1 IC-191.6183.87
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Build: azure-toolkit-for-intellij-2019.1.develop.1095.04-17-2019

Repro Steps:
1.Create a new project for failure debug
2.Link a cluster, eg. spark230-gen2-yan 
3.Create a new run configuration with linked spark230-gen2-yan ,the storage type keep the first one: Use interactive session to upload
4.Apply and ok
5.Unlink the cluster and wait for refreshing finshed
6.Open the config file again
7.You can see the cluster has changed and click apply and ok
8.CLICK the remotely run button

Result:
![image](https://user-images.githubusercontent.com/43333874/56285091-34161200-60cb-11e9-85a2-c832eabe3bf3.png)
![image](https://user-images.githubusercontent.com/43333874/56285104-3d06e380-60cb-11e9-82f5-46b053215fd1.png)
![image](https://user-images.githubusercontent.com/43333874/56285490-34fb7380-60cc-11e9-9845-b13894b294c1.png)

Error message: 
java.lang.NullPointerException
    at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobRemoteProcess.lambda$prepareArtifact$10(SparkBatchJobRemoteProcess.java:228)
    at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
    at rx.internal.operators.SingleLiftObservableOperator$WrapSubscriberIntoSingle.onError(SingleLiftObservableOperator.java:81)
    at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onError(SingleOnSubscribeMap.java:85)
    at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.lambda$deployArtifact$11(JobUtils.java:688)
    at rx.Single.subscribe(Single.java:1979)
    at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:45)
    at rx.internal.operators.SingleOnSubscribeMap.call(SingleOnSubscribeMap.java:30)
    at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:39)
    at rx.internal.operators.SingleToObservable.call(SingleToObservable.java:27)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
    at com.microsoft.intellij.rxjava.IdeaSchedulers$1.run(IdeaSchedulers.java:51)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by wezhang** [comment]
@v-xiaocw , there is a new change about this, could you try it again after build 1098?

**Comment by v-xiaocw** [comment]
I tried it again with build 1100 just now ,it still repro
[cid:image001.png@01D4F562.4D11F690]
