### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception get applications list error com.microsoft.azure.hdinsight.sdk.common.HDIException: Forbidden

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3073]
Build: 
https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.21.0/azure-toolkit-for-intellij-2019.1.106.04-19-2019.zip 

Repro Steps:
Expand hdinsight node and subnotes, like jobs and storage accounts

IntelliJ build version: 2019.1.1 IC-191.6707.31
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.21.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1440x796,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=get applications list error, throwable=com.microsoft.azure.hdinsight.sdk.common.HDIException: Forbidden
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter



get applications list error

com.microsoft.azure.hdinsight.sdk.common.HDIException: Forbidden
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by t-rufang** [comment]
Please paste idea.log info when you encounter this issue again.

**Comment by jingyanjingyan** [comment]
2019-04-30 07:50:06,165 [15206907]  ERROR - microsoft.intellij.AzurePlugin - OS: Windows 10 
2019-04-30 07:50:06,166 [15206908]  ERROR - microsoft.intellij.AzurePlugin - Plugin to blame: Azure Toolkit for IntelliJ version: 3.21.1-2019.1 
2019-04-30 07:50:06,166 [15206908]  ERROR - microsoft.intellij.AzurePlugin - Last Action: editRunConfigurations 
2019-04-30 07:50:06,884 [15207626]  ERROR - microsoft.intellij.AzurePlugin - get applications list error 
com.microsoft.azure.hdinsight.sdk.common.HDIException: Forbidden
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-30 07:50:06,885 [15207627]  ERROR - microsoft.intellij.AzurePlugin - IntelliJ IDEA 2019.1.2 Preview  Build #IC-191.7141.2 
2019-04-30 07:50:06,885 [15207627]  ERROR - microsoft.intellij.AzurePlugin - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-04-30 07:50:06,885 [15207627]  ERROR - microsoft.intellij.AzurePlugin - OS: Windows 10 
2019-04-30 07:50:06,885 [15207627]  ERROR - microsoft.intellij.AzurePlugin - Plugin to blame: Azure Toolkit for IntelliJ version: 3.21.1-2019.1 
2019-04-30 07:50:06,885 [15207627]  ERROR - microsoft.intellij.AzurePlugin - Last Action: editRunConfigurations 
2019-04-30 07:50:07,193 [15207935]   INFO - dea.updater.SdkComponentSource - File C:\Users\v-yajing\.android\repositories.cfg could not be loaded. 
2019-04-30 07:50:07,196 [15207938]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/addons_list-3.xml 
2019-04-30 07:50:07,699 [15208441]  ERROR - microsoft.intellij.AzurePlugin - get applications list error 
com.microsoft.azure.hdinsight.sdk.common.HDIException: - Authentication failed
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-30 07:50:07,699 [15208441]  ERROR - microsoft.intellij.AzurePlugin - IntelliJ IDEA 2019.1.2 Preview  Build #IC-191.7141.2 
2019-04-30 07:50:07,699 [15208441]  ERROR - microsoft.intellij.AzurePlugin - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-04-30 07:50:07,699 [15208441]  ERROR - microsoft.intellij.AzurePlugin - OS: Windows 10 
2019-04-30 07:50:07,699 [15208441]  ERROR - microsoft.intellij.AzurePlugin - Plugin to blame: Azure Toolkit for IntelliJ version: 3.21.1-2019.1 
2019-04-30 07:50:07,700 [15208442]  ERROR - microsoft.intellij.AzurePlugin - Last Action: editRunConfigurations 
2019-04-30 07:50:07,798 [15208540]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/repository2-1.xml 
2019-04-30 07:50:07,799 [15208541]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android/sys-img2-1.xml 
2019-04-30 07:50:07,800 [15208542]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/addon2-1.xml 
2019-04-30 07:50:07,800 [15208542]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-wear/sys-img2-1.xml 
2019-04-30 07:50:07,802 [15208544]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/extras/intel/addon2-1.xml 
2019-04-30 07:50:07,803 [15208545]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/google_apis_playstore/sys-img2-1.xml 
2019-04-30 07:50:07,803 [15208545]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/glass/addon2-1.xml 
2019-04-30 07:50:07,804 [15208546]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/google_apis/sys-img2-1.xml 
2019-04-30 07:50:07,804 [15208546]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-wear-cn/sys-img2-1.xml 
2019-04-30 07:50:07,804 [15208546]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-tv/sys-img2-1.xml 
2019-04-30 07:50:09,304 [15210046]  ERROR - microsoft.intellij.AzurePlugin - get applications list error 
com.microsoft.azure.hdinsight.sdk.common.HDIException: - Authentication failed
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-30 07:50:09,305 [15210047]  ERROR - microsoft.intellij.AzurePlugin - IntelliJ IDEA 2019.1.2 Preview  Build #IC-191.7141.2 
2019-04-30 07:50:09,305 [15210047]  ERROR - microsoft.intellij.AzurePlugin - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-04-30 07:50:09,305 [15210047]  ERROR - microsoft.intellij.AzurePlugin - OS: Windows 10 
2019-04-30 07:50:09,305 [15210047]  ERROR - microsoft.intellij.AzurePlugin - Plugin to blame: Azure Toolkit for IntelliJ version: 3.21.1-2019.1 
2019-04-30 07:50:09,305 [15210047]  ERROR - microsoft.intellij.AzurePlugin - Last Action: editRunConfigurations 
2019-04-30 07:50:10,180 [15210922]  ERROR - microsoft.intellij.AzurePlugin - get applications list error 
com.microsoft.azure.hdinsight.sdk.common.HDIException: - Authentication failed
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:427)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:146)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-30 07:50:10,181 [15210923]  ERROR - microsoft.intellij.AzurePlugin - IntelliJ IDEA 2019.1.2 Preview  Build #IC-191.7141.2 
2019-04-30 07:50:10,181 [15210923]  ERROR - microsoft.intellij.AzurePlugin - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-04-30 07:50:10,181 [15210923]  ERROR - microsoft.intellij.AzurePlugin - OS: Windows 10 
2019-04-30 07:50:10,182 [15210924]  ERROR - microsoft.intellij.AzurePlugin - Plugin to blame: Azure Toolkit for IntelliJ version: 3.21.1-2019.1 
2019-04-30 07:50:10,182 [15210924]  ERROR - microsoft.intellij.AzurePlugin - Last Action: editRunConfigurations 
2019-04-30 07:50:19,978 [15220720]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 144 ms

**Comment by t-rufang** [comment]
@jingyanjingyan Does this issue still repro in the latest plugin

**Comment by jingyanjingyan** [comment]
Repro with dev 1117

**Comment by t-rufang** [comment]
Thanks @jingyanjingyan could you help to provide the repro steps?
