### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by leroylim20** [microsoft/azure-tools-for-java#3085]
IntelliJ build version: 2019.1.1 IU-191.6707.61
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.20.0-2019.1
Additional Info: Occured when signing in
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,29,824x494,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:471)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at

**Comment by wezhang** [comment]
Thanks @leroylim20 ! Looks like some important call stacks are cut. If you have the err context, may I get the full one?

**Comment by andxu** [comment]
seems the detailed error is :
```
While loading class com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfiguration: Cannot inherit from final class [Plugin: com.microsoft.tooling.msservices.intellij.azure]
```

**Comment by andxu** [comment]
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.reflect.InvocationTargetException (#4413)
Close this issue due to duplicate error: SparkScalaLocalConsoleRunConfiguration: Cannot inherit from final class
