### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by jaideoAtParkar** [microsoft/azure-tools-for-java#3088]
IntelliJ build version: 2018.3.2 IC-183.4886.37
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.21.0-2018.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: bc7f778b-97b4-4f8a-b495-0a95de74af00\r\nCorrelation ID: 1cbc96c5-0583-4863-bc9b-5081e0587272\r\nTimestamp: 2019-04-29 12:54:33Z","error_codes":[90002],"timestamp":"2019-04-29 12:54:33Z","trace_id":"bc7f778b-97b4-4f8a-b495-0a95de74af00","correlation_id":"1cbc96c5-0583-4863-bc9b-5081e0587272"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1703)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at c

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Azure Explorer - Error Loading Web Apps (#3653)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.
