### ISSUE TITLE
Error during artifact deployment after configuring applcation insight in jdk11 environment

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3102]
### Environment:
```
1. OS: Windows10/Mac
2. Plugin version: Azure java toolkit for IntelliJ: 3.21.0
4. IntelliJ IDEA 2019.1.1 (Ultimate Edition)
   JRE: 11.0.2+9-b159.44 amd64
5. JDK: oracle jdk11.0.2
```

### Repro steps:

1. Create a web project
2. Right-click project and configure the AI
[how to configure application insight in IntelliJ](https://microsoft.sharepoint.com/teams/WPTFundamental/_layouts/OneNote.aspx?id=%2Fteams%2FWPTFundamental%2FShared%20Documents%2FAAPTServicing%2FAAPT%20Webtools%20Offshore%20Current%20Release&wd=target%28Java%20Tools%2FAzure%20Java%20Toolkits%2FAzure%20java%20toolkits%28IDE%5C%29-manual.one%7C7FAF569A-EA05-4B92-957A-626D02B04207%2F%5BIntelliJ%5DConfigure%20Application%20Insights%7C7A05FB47-67D3-4421-ACD0-46833E70E0FB%2F%29onenote:https://microsoft.sharepoint.com/teams/WPTFundamental/Shared%20Documents/AAPTServicing/AAPT%20Webtools%20Offshore%20Current%20Release/Java%20Tools/Azure%20Java%20Toolkits/Azure%20java%20toolkits(IDE)-manual.one#%5bIntelliJ%5dConfigure%20Application%20Insights&section-id={7FAF569A-EA05-4B92-957A-626D02B04207}&page-id={7A05FB47-67D3-4421-ACD0-46833E70E0FB}&end)
4. Run the application

### Result:
 Error during artifact deployment

Server log:
```
D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\bin\catalina.bat run
[2019-05-06 07:35:26,990] Artifact helloworld: Waiting for server connection to start artifact deployment...
Using CATALINA_BASE:   "C:\Users\v-erzha\.IntelliJIdea2019.1\system\tomcat\Unnamed_helloworld"
Using CATALINA_HOME:   "D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40"
Using CATALINA_TMPDIR: "D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\temp"
Using JRE_HOME:        "C:\Program Files\Java\jdk-11.0.3"
Using CLASSPATH:       "D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\bin\bootstrap.jar;D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\bin\tomcat-juli.jar"
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.40
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Apr 10 2019 14:31:19 UTC
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.40.0
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 10
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jdk-11.0.3
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.3+12-LTS
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\Users\v-erzha\.IntelliJIdea2019.1\system\tomcat\Unnamed_helloworld
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\Users\v-erzha\.IntelliJIdea2019.1\system\tomcat\Unnamed_helloworld\conf\logging.properties
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote=
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.password.file=C:\Users\v-erzha\.IntelliJIdea2019.1\system\tomcat\Unnamed_helloworld\jmxremote.password
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.access.file=C:\Users\v-erzha\.IntelliJIdea2019.1\system\tomcat\Unnamed_helloworld\jmxremote.access
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=127.0.0.1
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
06-May-2019 19:35:32.587 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\Users\v-erzha\.IntelliJIdea2019.1\system\tomcat\Unnamed_helloworld
06-May-2019 19:35:32.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40
06-May-2019 19:35:32.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\temp
06-May-2019 19:35:32.600 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Program Files\Java\jdk-11.0.3\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk-11.0.3\bin;C:\Program Files\Git\cmd;C:\Users\v-erzha\AppData\Local\Microsoft\WindowsApps;;.]
06-May-2019 19:35:32.663 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
06-May-2019 19:35:32.679 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-May-2019 19:35:32.694 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
06-May-2019 19:35:32.694 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-May-2019 19:35:32.694 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 605 ms
06-May-2019 19:35:32.772 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
06-May-2019 19:35:32.772 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.40
06-May-2019 19:35:32.850 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
06-May-2019 19:35:32.882 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
06-May-2019 19:35:32.882 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 179 ms
Connected to server
[2019-05-06 07:35:33,225] Artifact helloworld: Artifact is being deployed, please wait...
06-May-2019 19:35:34.382 WARNING [RMI TCP Connection(2)-127.0.0.1] org.apache.tomcat.util.descriptor.web.WebXml.setVersion Unknown version string [4.0]. Default version will be used.
06-May-2019 19:35:37.913 INFO [RMI TCP Connection(2)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
06-May-2019 19:35:38.085 WARNING [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [141] milliseconds.
06-May-2019 19:35:38.116 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
06-May-2019 19:35:38.116 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [/helloworld] startup failed due to previous errors
[2019-05-06 07:35:38,178] Artifact helloworld: Error during artifact deployment. See server log for details.
06-May-2019 19:35:42.866 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\webapps\manager]
06-May-2019 19:35:43.272 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [D:\apache-tomcat-8.5.40\apache-tomcat-8.5.40\webapps\manager] has finished in [422] ms

```
Tomcat Localhost Log:
```
06-May-2019 19:35:38.116 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [ApplicationInsightsWebFilter]
 java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(TelemetryConfigurationFactory.java:90)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(TelemetryConfigurationFactory.java:66)
	at com.microsoft.applicationinsights.internal.config.WebReflectionUtils.initialize(WebReflectionUtils.java:19)
	at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.<clinit>(WebRequestTrackingFilter.java:67)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:264)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4615)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1730)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:483)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:432)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at java.management/com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1406)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
	... 57 more


```
Tomcat Catalina Log:
```

06-May-2019 19:35:34.382 WARNING [RMI TCP Connection(2)-127.0.0.1] org.apache.tomcat.util.descriptor.web.WebXml.setVersion Unknown version string [4.0]. Default version will be used.
06-May-2019 19:35:38.085 WARNING [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [141] milliseconds.
06-May-2019 19:35:38.116 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
06-May-2019 19:35:38.116 SEVERE [RMI TCP Connection(2)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [/helloworld] startup failed due to previous errors

```

**Comment by andxu** [comment]
I together with Eric Zhang cannot reproduce this error(on java 11, tomcat 8.15 and windows)
