### ISSUE TITLE
A web app loading error occured while signing out

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3119]
### Environment:
```
OS: Windows10/Mac
Plugin version:
Azure java toolkit for IntelliJ: 3.22.0
Azure java toolkit for Eclipse: 3.15.0
JDK: oracle jdk8
```

### Repro steps:
1. Azure sign in
2. Refresh Web App node in Azure Explorer
3. After refreshing the web app, wait a while and sign out

### Result:
![image](https://user-images.githubusercontent.com/22470312/57504415-ef2a7780-7326-11e9-897d-81b82fb6b579.png)

Log:
```
java.lang.IllegalArgumentException: maxConcurrent > 0 required but it was 0
	at rx.internal.operators.OperatorMerge.instance(OperatorMerge.java:91)
	at rx.Observable.merge(Observable.java:2609)
	at rx.Observable.flatMap(Observable.java:6750)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.listAllWebApps(AzureWebAppMvpModel.java:519)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModulePresenter.onModuleRefresh(WebAppModulePresenter.java:15)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppModule.refreshItems(WebAppModule.java:63)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Then sign in again, error occurs
	
```
java.lang.NullPointerException
		at com.intellij.openapi.wm.impl.InternalDecorator.setTitleActions(InternalDecorator.java:284)
		at com.intellij.openapi.wm.impl.ToolWindowImpl.setTitleActions(ToolWindowImpl.java:311)
		at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$addToolbarItems$3(ServerExplorerToolWindowFactory.java:374)
		at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
		at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:150)
		at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:134)
		at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction$1.actionPerformed(SignInOutAction.java:46)
		at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:88)
		at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
		at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$createPopupMenuForNode$1(ServerExplorerToolWindowFactory.java:215)
		at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
		at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
		at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
		at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
		at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
		at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
		at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
		at java.awt.Component.processMouseEvent(Component.java:6550)
		at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
		at java.awt.Component.processEvent(Component.java:6315)
		at java.awt.Container.processEvent(Container.java:2239)
		at java.awt.Component.dispatchEventImpl(Component.java:4899)
		at java.awt.Container.dispatchEventImpl(Container.java:2297)
		at java.awt.Component.dispatchEvent(Component.java:4721)
		at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
		at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
		at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
		at java.awt.Container.dispatchEventImpl(Container.java:2283)
		at java.awt.Window.dispatchEventImpl(Window.java:2746)
		at java.awt.Component.dispatchEvent(Component.java:4721)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
		at java.awt.EventQueue.access$500(EventQueue.java:98)
		at java.awt.EventQueue$3.run(EventQueue.java:715)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
		at java.awt.EventQueue$4.run(EventQueue.java:739)
		at java.awt.EventQueue$4.run(EventQueue.java:737)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:686)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by bsaby** [comment]
Test Passed in Eclipse and IntelliJ.
Bits: 
- pre-release for Eclipse: 3.15.0
- pre-release for IntelliJ: 3.22.0
