### ISSUE TITLE
Sometimes, some resources cannot be loaded when creating vm

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#3127]
This issue cannot stable repro.

### Environment:
OS: Windows10
Eclipse: 2019-03
Plugin version: Azure java toolkit for Eclipse: 3.15.0
JDK: oracle jdk8/11
### Repro steps:
1. Azure sign in(device login or sp file login)
2. Don’t refresh any resource and right click `Virtual Machines` node in the Azure Explorer
3. Select `Create VM`
### Result:
Can't load some resources, shown as below:
Case1: Cannot load size
![image](https://user-images.githubusercontent.com/22470312/57608286-4cc8f900-759f-11e9-947f-0e3d2aff005c.png)

Case2: Cannot load existing resource group
![image](https://user-images.githubusercontent.com/22470312/57608377-6b2ef480-759f-11e9-866f-4d9d4fda25df.png)

**Comment by bsaby** [comment]
Sometimes, cannot load existing resource groups when creating a storage account in **IntelliJ**
This issue cannot stably repro.
LOG:
```
An error occurred when trying to load Subscriptions

null

java.lang.NullPointerException
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.loadGroups(CreateArmStorageAccountForm.java:484)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.fillRegions(CreateArmStorageAccountForm.java:479)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.loadRegions(CreateArmStorageAccountForm.java:471)
	at com.microsoft.intellij.forms.CreateArmStorageAccountForm.fillFields(CreateArmStorageAccountForm.java:364)
	at com.microsoft.intellij.serviceexplorer.azure.storagearm.CreateStorageAccountAction.actionPerformed(CreateStorageAccountAction.java:50)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:88)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$createPopupMenuForNode$1(ServerExplorerToolWindowFactory.java:215)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by EricZhangzf** [comment]
Can not repro it on 3.37.0
