### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Mirkelor** [microsoft/azure-tools-for-java#3136]
IntelliJ build version: 2019.1.2 IU-191.7141.44
OS: Linux
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.22.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,30,1021x498,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.intellij.openapi.wm.impl.InternalDecorator.setTitleActions(InternalDecorator.java:284)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setTitleActions(ToolWindowImpl.java:311)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$addToolbarItems$3(ServerExplorerToolWindowFactory.java:374)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:150)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:134)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onActionPerformed(AzureSignInAction.java:64)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.lambda$actionPerformed$0(AzureAnAction.java:64)
	at com.microsoft.az

**Comment by Flanker32** [comment]
Dup with #2414
