### ISSUE TITLE
[IntelliJ]Cannot open interactive console with reader role cluster

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3164]
Build: dev 1137

Repro steps:
1. Sign in with reader role account
2. Set up a HDInsight config with a reader role cluster
3. Start interactive console from tool menu

Result:
Exception:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.microsoft.azuretools.telemetrywrapper.EventUtil.executeWithLog(EventUtil.java:95)
	at com.microsoft.azuretools.telemetrywrapper.EventUtil.executeWithLog(EventUtil.java:122)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:686)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkConsoleActionDelegate.onActionPerformed(RunSparkConsoleActionDelegate.kt:56)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.lambda$actionPerformed$0(AzureAnAction.java:64)
	at com.microsoft.azuretools.telemetrywrapper.EventUtil.executeWithLog(EventUtil.java:89)
	... 52 more
Caused by: java.lang.IllegalArgumentException: Username may not be null
	at org.apache.http.util.Args.notNull(Args.java:54)
	at org.apache.http.auth.UsernamePasswordCredentials.<init>(UsernamePasswordCredentials.java:81)
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.<init>(HttpObservable.java:150)
	at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.Session.<init>(Session.java:100)
	at com.microsoft.azure.hdinsight.sdk.common.livy.interactive.SparkSession.<init>(SparkSession.java:37)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration.getState(SparkScalaLivyConsoleRunConfiguration.kt:77)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:35)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.runEnvironmentProfileWithCheckSettings(RunConfigurationActionUtils.kt:64)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runFromSetting(RunSparkScalaConsoleAction.kt:132)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.access$runFromSetting(RunSparkScalaConsoleAction.kt:50)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction$runExisting$1.invoke(RunSparkScalaConsoleAction.kt:110)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction$runExisting$1.invoke(RunSparkScalaConsoleAction.kt:50)
	at com.microsoft.intellij.util.ApplicationHelpersKt.runInReadAction(ApplicationHelpers.kt:42)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runExisting(RunSparkScalaConsoleAction.kt:109)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.actionPerformed(RunSparkScalaConsoleAction.kt:65)
	... 59 more
```

**Comment by t-rufang** [comment]
For HDInsight Reader role cluster, link cluster is required before using interactive console feature.

**Comment by wezhang** [comment]
`Caused by: java.lang.IllegalArgumentException: Username may not be null`

**Comment by wezhang** [comment]
We can ask user to link the cluster

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738940
