### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception updateSubscriptionWithProgressDialog com.microsoft.azuretools.adauth.AuthException: No subscription found in the account

### ISSUE THREAD

**Issue by JohanLander** [microsoft/azure-tools-for-java#3186]
IntelliJ build version: 2019.1.3 IC-191.7479.19
OS: Windows Server 2016
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.22.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,1384x961,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=updateSubscriptionWithProgressDialog, throwable=com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.azuretools.ijidea.actions.SelectSubscriptionsAction$1.run(SelectSubscriptionsAction.java:111)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi

**Comment by JohanLander** [comment]
try to connect to a SQL 2019 BDC on a Azure stack

**Comment by yucwan** [comment]
@JohanLander Hi Johan, sorry for the late response. Seems that you are trying to use this toolkit with on premise Azure Stack? This toolkit doesn't support that by design for now. For similar cases like government cloud, you can find [workarounds](https://github.com/microsoft/azure-tools-for-java/search?q=EnvironmentName&type=Issues). But I'm not sure whether this works on arbitrary Azure Stack, you may need to ask Azure Stack team for help. If you want to share more information with your use case, please send a e-mail to azure-java-tools@microsoft.com to talk with us directly.

**Comment by JohanLander** [comment]
yes correct  iam using a Azure stack... i will contact azure -java-tools@microsoft.com Thanks for your response !

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)
