### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@2b345601] - other than com.intellij.util.proxy.CommonProxy.ourInstance.

### ISSUE THREAD

**Issue by marisma-mhe** [microsoft/azure-tools-for-java#3187]
IntelliJ build version: 2019.1.3 IU-191.7479.19
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.22.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1200,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector@2b345601] - other than com.intellij.util.proxy.CommonProxy.ourInstance.
This will make some IDEA network calls fail.
Instead, methods of com.intellij.util.proxy.CommonProxy should be used for proxying.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.util.proxy.CommonProxy.isInstalledAssertion(CommonProxy.java:65)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:187)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.SystemDefaultRoutePlanner.determineProxy(SystemDefaultRoutePlanner.java:94)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.Defa

**Comment by wezhang** [comment]
+@zmssp, @Flanker32 looks like a telemetry sdk issue

**Comment by andxu** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.Throwable: ProxySelector.setDefault() was ch... (#2665)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: ProxySelector.setDefault() was changed to [com.btr.proxy.selector.whitelist.ProxyBypassListSelector
