### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by dilinipeirs** [microsoft/azure-tools-for-java#3191]
IntelliJ build version: 2019.1.2 IU-191.7141.44
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.23.0-2019.1
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:108)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.handleSubscriptionChange(AzureModule.java:227)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.access$100(AzureModule.java:48)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule$SignInOutListener.run(AzureModule.java:236)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:150)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:134)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onActionPerformed(AzureSignInActi

**Comment by Flanker32** [comment]
@dilinipeirs Thanks for your report, could you please share a bit more information like which login method did you use and is there any way to reproduce this issue?

**Comment by dilinipeirs** [comment]
Hi

I bought the Microsoft azure subscription for free from Microsoft Imagine (earlier Dreamspark) using my University email address. This was back in January 2019 and activated it by signing into my Microsoft account.

But now, in June, when I check in Microsoft Imagine site, it says that Microsoft Azure is not available anymore. But in the Github Education Pack, Microsoft Azure is still listed as a service a student can get from their University email adderss.

And when I try to sign into Azure from Azure Toolkit for IntelliJ, it says my account do not have any subscription.

Please advice me on this matter

Regards
Dilini Peiris

**Comment by yucwan** [comment]
@dilinipeirs This error message indicates that you have successfully sign in to your Microsoft account but having no subscription under it. Please try sign-in on [azure portal](https://portal.azure.com/) to verify your subscription information. If you can access Azure on portal, please respond, otherwise the problem should be about your account. Sorry that I'm not quite familiar with Imagine or Github Education Pack. You can ask for subscription support [here](https://azureforeducation.microsoft.com/en-us/institutions/Contact).

**Comment by Flanker32** [comment]
Duplicated with #3058

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)
