### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading storagelake2

### ISSUE THREAD

**Issue by gatchan00** [microsoft/azure-tools-for-java#3193]
IntelliJ build version: 2019.1 IC-191.6183.87
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.23.0-2019.1
Error message: 
```
java.util.NoSuchElementException: An error occurred while enumerating the result, check the original exception for details.
	at com.microsoft.azure.storage.core.LazySegmentedIterator.hasNext(LazySegmentedIterator.java:113)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:122)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.StorageClientSDKManager.getBlobContainers(StorageClientSDKManager.java:113)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode.refreshItems(StorageNode.java:119)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progre

**Comment by wezhang** [comment]
`at com.microsoft.tooling.msservices.serviceexplorer.azure.storage.StorageNode.refreshItems` + @Flanker32

**Comment by Flanker32** [comment]
As we have deprecated and remove storage explorer, close this issue
