### ISSUE TITLE
An error occurred while first time to click start streaming log

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/azure-tools-for-java#3195]
### Environment:

1. OS: Windows10/Mac/Linux
2. IntelliJ 2019.1.x/2018.3.x
3. Bits: PR/3491
4. JDK: Oracle JDK8/11

### Issue:
```
Access is allowed from event dispatch thread only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@30433c30
Current thread: Thread[ApplicationImpl pooled thread 30,4,Idea Thread Group] 1207337017
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 513476132
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1130)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1119)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeContent(ContentManagerImpl.java:193)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeContent(ContentManagerImpl.java:166)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeAllContents(ContentManagerImpl.java:273)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:529)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:354)
	at com.microsoft.intellij.helpers.webapp.WebAppStreamingLogConsoleViewProvider.getToolWindow(WebAppStreamingLogConsoleViewProvider.java:140)
	at com.microsoft.intellij.helpers.webapp.WebAppStreamingLogConsoleViewProvider.startStreamingLogs(WebAppStreamingLogConsoleViewProvider.java:58)
	at com.microsoft.intellij.serviceexplorer.azure.webapp.StartStreamingLogsAction$1.run(StartStreamingLogsAction.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Flanker32** [comment]
Fixed in latest build
