### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error

### ISSUE THREAD

**Issue by sainatheluri** [microsoft/azure-tools-for-java#3198]
IntelliJ build version: 2019.1.3 IC-191.7479.19
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.23.0-2019.1
Error message: 
```
java.net.UnknownHostException: xxxxxxxxx.azurehdinsight.net
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.h

**Comment by wezhang** [comment]
I suppose it is an user error: `java.net.UnknownHostException: xxxxxxxxx.azurehdinsight.net`

**Comment by lcadzy** [comment]
Repo steps:1.link hdi cluster 2. choose session upload 3.delete cluster 4.remote run 
job fails at uploading artifact stage
