### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error:Remotely run after switching cluster get error.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3230]
IntelliJ build version: 2019.1 IC-191.6183.87
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.23.0-2019.1
Build: dev 1156

Repro Steps:
1.Create a new project.
2.Create a configuration file 
3.Select the spark22blobhdi as the target cluster
4.Click remotely run
5.After the successful result ,switch the cluster,select the spark230-gen2-yan as the target cluster and close the config dialog quickly.
6.Click remotely run directly and quickly.
Result:
![image](https://user-images.githubusercontent.com/43333874/60714359-cb6f5200-9ecf-11e9-8b9b-3874e67e1d75.png)

Error message: 
```
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.common.ADLSGen2Deploy.lambda$deploy$0(ADLSGen2Deploy.java:78)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.call(OperatorOnErrorResumeNextViaFunction.java:53)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.call(OperatorOnErrorResumeNextViaFunction.java:50)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.O






java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.common.ADLSGen2Deploy.lambda$deploy$0(ADLSGen2Deploy.java:78)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.call(OperatorOnErrorResumeNextViaFunction.java:53)
	at

**Comment by t-rufang** [comment]
@lcadzy could you please help to take a look at this issue. Seems like it's gen2-related issue.

**Comment by v-xiaocw** [comment]
Fixed in dev build 1173
