### ISSUE TITLE
[IntelliJ]Local console with mocked files fails, with SBT project

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3244]
Build: artifacts/azure-toolkit-for-intellij-LATEST-EAP-SNAPSHOT.PR.3572.07-09-2019.zip
system: windows

Repro Steps:
1. Create a SBT project
2. Create a config file, like HDI config file
3. Start Local console from Tools
4. Click Yes when ask for mocked file
5. Auto fix twice when asked

Result:
Local console fails
"C:\Program Files\Java\jdk1.8.0_191\bin\java.exe" -Djline.terminal=NONE -javaagent:C:\Users\v-yajing\.ivy2\cache\org.jmockit\jmockit\jars\jmockit-1.34.jar -javaagent:C:\Users\v-yajing\.IdeaIC2019.2\config\plugins\azure-toolkit-for-intellij\lib\spark-localrun-mock-0.1.0.jar -javaagent:C:\Users\v-yajing\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-1\192.5587.17\lib\idea_rt.jar=57087:C:\Users\v-yajing\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-1\192.5587.17/bin -Dfile.encoding=UTF-8 -classpath C:\Users\v-yajing\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-1\192.5587.17\lib\idea_rt.jar com.intellij.rt.execution.CommandLineWrapper C:\Users\v-yajing\AppData\Local\Temp\idea_classpath2087136474 org.apache.spark.deploy.SparkSubmit --class org.apache.spark.repl.Main --name "Spark shell" spark-shell -usejavacp
java.lang.reflect.InvocationTargetException
FATAL ERROR in native method: processing of -javaagent failed
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:388)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.TypeNotPresentException: Type org.apache.hadoop.fs.FileSystem not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
	at java.lang.Class.getGenericSuperclass(Class.java:777)
	at mockit.MockUp.getTypeToFake(MockUp.java:165)
	at mockit.MockUp.<init>(MockUp.java:121)
	at com.microsoft.azure.hdinsight.spark.mock.SparkLocalConsoleMockFsAgent$1.<init>(SparkLocalConsoleMockFsAgent.java:38)
	at com.microsoft.azure.hdinsight.spark.mock.SparkLocalConsoleMockFsAgent.setUp(SparkLocalConsoleMockFsAgent.java:38)
	at com.microsoft.azure.hdinsight.spark.mock.SparkLocalConsoleMockFsAgent.premain(SparkLocalConsoleMockFsAgent.java:34)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FileSystem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 18 more
Exception in thread "main" 
Process finished with exit code 1

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738931
