### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by tjakopan** [microsoft/azure-tools-for-java#3276]
IntelliJ build version: 2019.1.3 IU-191.7479.19
OS: Linux
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.23.0-2019.1
Additional Info: The error occured after signing in and selecting the subscription.
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1920x983,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.intellij.openapi.wm.impl.InternalDecorator.setTitleActions(InternalDecorator.java:284)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setTitleActions(ToolWindowImpl.java:311)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.lambda$addToolbarItems$3(ServerExplorerToolWindowFactory.java:374)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:150)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:134)
	at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction$1.actionPerformed(SignInOutAction.java:46)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeAct

**Comment by Flanker32** [comment]
Dup with #2414
