### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IndexOutOfBoundsException: Index: 2, Size: 2

### ISSUE THREAD

**Issue by ghost4426** [microsoft/azure-tools-for-java#3281]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.24.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,30,824x494,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.intellij.ui.wizard.WizardModel.getNextFor(WizardModel.java:149)
	at com.intellij.ui.wizard.WizardStep.onNext(WizardStep.java:56)
	at com.microsoft.intellij.ui.components.AzureWizardStep.onNext(AzureWizardStep.java:75)
	at com.microsoft.intellij.docker.wizards.createhost.forms.AzureNewDockerLoginStep.onNext(AzureNewDockerLoginStep.java:559)
	at com.microsoft.intellij.docker.wizards.createhost.forms.AzureNewDockerLoginStep.onNext(AzureNewDockerLoginStep.java:46)
	at com.intellij.ui.wizard.WizardModel.next(WizardModel.java:60)
	at com.intellij.ui.wizard.WizardAction$Next.actionPerformed(WizardAction.java:33

**Comment by Flanker32** [comment]
We have deprecated the support for docker host, close this issue.
