### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by cafealternativo** [microsoft/azure-tools-for-java#3283]
IntelliJ build version: 2019.1.2 IC-191.7141.44
OS: Windows 10
JDK: JetBrains s.r.o 11.0.2
Plugin version: 3.23.0-2019.1
Additional Info: cannot disable "validate spark cluster ssl certificate"
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,30,1536x801,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.lang.NullPointerException
	at com.microsoft.azuretools.telemetrywrapper.EventUtil.executeWithLog(EventUtil.java:95)
	at com.microsoft.azuretools.telemetrywrapper.EventUtil.executeWithLog(EventUtil.java:122)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext

**Comment by t-rufang** [comment]
@cafealternativo Thanks for your feedback. Please upgrade your plugin to the latest version, which is v3.24.0-2019.1. Feel free to update in this issue if error remains.
