### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error creating Redis cache: No subscription found in the account com.microsoft.azuretools.adauth.AuthException: No subscription found in the account

### ISSUE THREAD

**Issue by u804311** [microsoft/azure-tools-for-java#3371]
IntelliJ build version: 2018.1.1 IU-181.4445.78
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.13.0-2018.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,30,1366x716,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error creating Redis cache: No subscription found in the account, throwable=com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.intellij.forms.CreateRedisCacheForm.initFormContents(CreateRedisCacheForm.java:257)
	at com.microsoft.intellij.forms.CreateRedisCacheForm.<init>(CreateRedisCacheForm.java:116)
	at com.microsoft.intellij.serviceexplorer.azure.rediscache.CreateRedisCacheAction.actionPerformed(CreateRedisCacheAction.java:48)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNodeActionEvent(NodeAction.java:60)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFa

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
