### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azuretools.adauth.AuthException: invalid_grant

### ISSUE THREAD

**Issue by andriyhuang** [microsoft/azure-tools-for-java#3390]
IntelliJ build version: 2019.2 IU-192.5728.98
OS: Windows 10
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.25.0-2019.2
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,3,0,777x489,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=777,height=489]]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azuretools.adauth.AuthException: invalid_grant
	at com.microsoft.azuretools.adauth.HttpHelper.sendPostRequestAndDeserializeJsonResponse(HttpHelper.java:88)
	at com.microsoft.azuretools.adauth.AuthContext.sendRequest(AuthContext.java:256)
	at com.microsoft.azuretools.adauth.AuthContext.access$100(AuthContext.java:46)
	at com.microsoft.azuretools.adauth.AuthContext$1.getTokenWithRefreshToken(AuthContext.java:245)
	at com.microsoft.azuretools.adauth.CacheDriver.refreshExpireEntry(CacheDriver.java:128)
	at com.microsoft.azuretools.adauth.CacheDriver.refreshEntryIfNecessary(CacheDriver.java:107)
	at com.microsoft.azuretools.adauth.CacheDriver.find(CacheDriver.java:55)
	at com.microsoft.azuretools.adauth.AuthContext.acquireTokenFromCache(AuthContext.java:213)
	at com.microsoft.azuretools.adauth.AuthContext.acqui

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
- Error when trying to connect to Microsoft Azrue with Eclipse Neon 3 (#356)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: invalid_grant
