### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by goias5** [microsoft/azure-tools-for-java#3423]
IntelliJ build version: 2019.1.3 IU-191.7479.19
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.23.0-2019.1
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: b9ce9ec9-e28c-4aac-b024-e442a4356a00\r\nCorrelation ID: 0f6add9d-1a89-4f29-8c08-56a75129e069\r\nTimestamp: 2019-08-19 01:47:49Z","error_codes":[90002],"timestamp":"2019-08-19 01:47:49Z","trace_id":"b9ce9ec9-e28c-4aac-b024-e442a4356a00","correlation_id":"0f6add9d-1a89-4f29-8c08-56a75129e069","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.redis.implementation.RedisInner.list(RedisInner.java:955)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLe

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Azure Explorer - Error Loading Web Apps (#3653)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.
