### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by mmoehler** [microsoft/azure-tools-for-java#3462]
IntelliJ build version: 2019.2 IU-192.5728.98
OS: Windows 10
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.25.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1049,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.azuretools.ijidea.ui.SurveyPopUpDialog$6.mouseDragged(SurveyPopUpDialog.java:182)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6699)
	at java.desktop/java.awt.Component.processEvent(Component.java:6420)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Window.processEvent(Window.java:2049)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.aw

**Comment by Flanker32** [comment]
@mmoehler Thanks for your report, could you please share a bit more infos about this issue? Like is there any way to reproduce it?
