### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10

### ISSUE THREAD

**Issue by starostinEgor** [microsoft/azure-tools-for-java#3478]
IntelliJ build version: 2019.2 IC-192.5728.98
OS: Windows 10
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.25.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1367x727,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at java.base/java.util.Vector.elementData(Vector.java:761)
	at java.base/java.util.Vector.elementAt(Vector.java:499)
	at java.desktop/javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:246)
	at java.desktop/javax.swing.tree.DefaultTreeModel.getChild(DefaultTreeModel.java:180)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.createNodeAt(VariableHeightLayoutCache.java:764)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:648)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4324)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeMo

**Comment by wezhang** [comment]
Thanks @starostinEgor ! Could you please help upgrade to v3.26 or later to see if the issue is still reproduced?
