### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: find: Unable to obtain authorization for this operation. (-60008)

### ISSUE THREAD

**Issue by alexcrownus** [microsoft/azure-tools-for-java#3499]
IntelliJ build version: 2019.2.1 IC-192.6262.58
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.26.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1680x943,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: find: Unable to obtain authorization for this operation. (-60008)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.microsoft.intellij.secure.IdeaSecureStore.loadPassword(IdeaSecureStore.java:53)
	at com.microsoft.azuretools.authmanage.BaseADAuthManager.loadFromSecureStore(BaseADAuthManager.java:131)
	at com.microsoft.azuretools.authmanage.DCAuthManager.tryRestoreSignIn(DCAuthManager.java:71)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.getAzureManager(AuthMethodManager.java:146)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.getAzureManager(AuthMethodManager.java:126)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.isSignedIn(AuthMethodManager.java:190)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.<init>(AzureSignInAction.java:55)

**Comment by wezhang** [comment]
@Flanker32 , could you help to check it?

**Comment by Flanker32** [comment]
@alexcrownus Thanks for your feedback, could you please offer a bit more information like how did you meet this error and is there any way to reproduce it?
