### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by kkedarisetti** [microsoft/azure-tools-for-java#3501]
IntelliJ build version: 2019.1 IU-191.6183.87
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.26.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1400x765,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkConsoleActionDelegate.actionPerformed(RunSparkConsoleActionDelegate.kt:59)
	at com.microsoft.azure.hdinsight.spark.run.action.SeqActions.onActionPerformed(SeqActions.kt:35)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:75)
Caused by: java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfigurationFactory.createConfiguration(SparkScalaLocalConsoleRunConfigurationFactory.kt:55)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runFromSetting(RunSparkScalaConsoleAction.kt:140)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.access$runFromSetting(RunSparkScalaConsoleAction.kt:52)

**Comment by wezhang** [comment]
@t-rufang , could you help to check it?
