### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by DaniVain** [microsoft/azure-tools-for-java#3531]
IntelliJ build version: 2019.2.2 IU-192.6603.28
OS: Windows 10
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.26.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1039,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.lang.Error: The process has been terminated
	at com.microsoft.intellij.runner.RunProcessHandler.println(RunProcessHandler.java:86)
	at com.microsoft.intellij.runner.RunProcessHandler.setText(RunProcessHandler.java:120)
	at com.microsoft.azuretools.utils.WebAppUtils.deployWebAppToWebContainer(WebAppUtils.java:403)
	at com.microsoft.azuretools.utils.WebAppUtils.deployArtifactsToAppService(WebAppUtils.

**Comment by Flanker32** [comment]
@DaniVain Thanks for your report, could you please provide a bit more information like when did this error occurs and is there any way to reproduce this issue?

**Comment by Flanker32** [comment]
Duplicated with #4102
