### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by nhhoangctu** [microsoft/azure-tools-for-java#3551]
IntelliJ build version: 2019.2.2 IU-192.6603.28
OS: Windows 10
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.27.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1330x680,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.microsoft.azure.management.appservice.implementation.KuduClient.warDeployAsync(KuduClient.java:170)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.warDeployAsync(WebAppImpl.java:223)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.warDeployAsync(WebAppImpl.java:206)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.warDeploy(WebAppImpl.java:214)
	at com.microsoft.azuretools.utils.WebAppUtils.deployWebAppToWebContainer(WebAppUtils.java:397)
	at com.microsoft.azuretools.utils.WebAppUtils.deployArtifactsToAppService(WebAppUtils.java:320)
	at com.microsoft.intellij.runner.webapp.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java

**Comment by wezhang** [comment]
Thanks @nhhoangctu ! @Flanker32 , could you please help to check it?

**Comment by nhhoangctu** [comment]
Please help me!

**Comment by Flanker32** [comment]
@nhhoangctu Thanks for your help, could you please provide a bit more information about the job? Like the runtime and pricingtier of the app service and the size of your project? Could the deployment work in other toolkits? Like the[ app service maven plugin](https://github.com/microsoft/azure-maven-plugins/tree/develop/azure-webapp-maven-plugin) or[ azure cli](https://docs.microsoft.com/en-us/azure/app-service/samples-cli)?

**Comment by nhhoangctu** [comment]
Hey @Flanker32 : To fix this issue. On the IDE (IntelIJ IDEA), I increase JVM memory :)

**Comment by Flanker32** [comment]
@nhhoangctu Thanks for your feedback! So shall we close this issue? Or could you please offer some infos about the project caused this issue so that we could dig deeper in this issue?
