### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file.

### ISSUE THREAD

**Issue by aa476822485** [microsoft/azure-tools-for-java#3575]
IntelliJ build version: 2019.2.2 IU-192.6603.28
OS: Windows 10
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.27.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1039,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=org.xml.sax.SAXParseException; Premature end of file.

	at com.microsoft.azuretools.azurecommons.util.ParserXMLUtility.parseXMLFile(ParserXMLUtility.java:68)
	at com.microsoft.intellij.AzurePlugin.setValues(AzurePlugin.java:252)
	at com.microsoft.intellij.AzurePlugin.initializeTelemetry(AzurePlugin.java:160)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:140)
```

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file. (#2525)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: throwable=org.xml.sax.SAXParseException; Premature end of file.
