### ISSUE TITLE
 Can't new an application Insights.

### ISSUE THREAD

**Issue by bsaby** [microsoft/azure-tools-for-java#359]
Eclipse Neon.3 and Eclipse Mars.2
Build used: artifacts/WindowsAzurePlugin4EJ.383.04-26-2017.zip

In Application Insights dialog, click **New**,
Input all infomation
Click OK
There is always an error dialog box, shown as below picture:
![image](https://cloud.githubusercontent.com/assets/22470312/25476868/1d0dae68-2b6e-11e7-8a68-f0085bed2a7e.png)

ERROR LOG:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.microsoft.applicationinsights.management.rest.client.RestClient.execute(RestClient.java:68)
	at com.microsoft.applicationinsights.management.rest.client.RestClient.executePut(RestClient.java:59)
	at com.microsoft.applicationinsights.management.rest.operations.CreateResourceGroupOperation.execute(CreateResourceGroupOperation.java:56)
	at com.microsoft.applicationinsights.management.rest.ApplicationInsightsManagementClient.createResourceGroup(ApplicationInsightsManagementClient.java:102)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKManager.createApplicationInsightsResource(AzureSDKManager.java:214)
	at com.microsoft.applicationinsights.preference.ApplicationInsightsNewDialog$5.run(ApplicationInsightsNewDialog.java:349)
	at com.microsoft.azuretools.core.azureexplorer.helpers.IDEHelperImpl$1.run(IDEHelperImpl.java:55)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by bsaby** [comment]
Mac OS
In Application Insights dialog, click New,
Input all infomation
Click OK
![image](https://cloud.githubusercontent.com/assets/22470312/25847045/fefa15b0-34e6-11e7-8248-19d93d833d6f.png)

**Comment by ZhengJun003** [comment]
Test in azure toolkits for eclipse 3.23.0, this issue is fixed.
