### ISSUE TITLE
An error dialog appears when Azure sign out using Interactive sign-in.

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#361]
Version:  IntelliJ 2017.1.2
Build used: artifacts/azure-toolkit-for-intellij.2017.385.04-27-2017.zip

The issue will be stable reproduced when the first time of azure Sign in.
Repro steps:

1. Open IntelliJ
2. Right click **Azure** and choose **Sign in**
3. Select  **Interactive** 
4. After sign in, right click **Azure** and choose **Sign out** 

The error dialog box appears.
![image](https://cloud.githubusercontent.com/assets/22470312/25517047/38a07a9a-2c20-11e7-838f-55aef1cfb64d.png)

**Comment by ryanmat** [comment]
Also getting Sign In error.  When trying to sign into my Azure account via the toolkit on IntelliJ via the Interactive option, immediately after entering my credentials I get either a null or could not initalize class retrofit2 error.  I have signed in perfectly fine before but for some reason, I'm getting this current error.  This is all while trying to deploy a simple Java Web App.

  
`Could not initialize class retrofit2.Platform
java.lang.NoClassDefFoundError: Could not initialize class retrofit2.Platform
	at retrofit2.Retrofit$Builder.<init>(Retrofit.java:402)
	at com.microsoft.rest.RestClient$Builder.<init>(RestClient.java:165)
	at com.microsoft.azure.management.resources.fluentcore.arm.implementation.AzureConfigurableImpl.<init>(AzureConfigurableImpl.java:34)
	at com.microsoft.azure.management.Azure$ConfigurableImpl.<init>(Azure.java:190)
	at com.microsoft.azure.management.Azure$ConfigurableImpl.<init>(Azure.java:190)
	at com.microsoft.azure.management.Azure.configure(Azure.java:161)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.authTid(AccessTokenAzureManager.java:133)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getTenants(AccessTokenAzureManager.java:118)
	at com.microsoft.azuretools.authmanage.AdAuthManager.signIn(AdAuthManager.java:84)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow$5.run(SignInWindow.java:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by vladimir-shcherbakov** [comment]
@ryanmat I created a new issue #363

**Comment by lenala** [comment]
Exception for the first screenshot:

AzureModelController.clearAll: set null to all the maps.
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at com.microsoft.azuretools.utils.AzureUIRefreshCore.removeAll(AzureUIRefreshCore.java:70)
	at com.microsoft.azuretools.utils.AzureModelController.clearAll(AzureModelController.java:93)
	at com.microsoft.azuretools.utils.AzureModelController.access$000(AzureModelController.java:54)
	at com.microsoft.azuretools.utils.AzureModelController$1.update(AzureModelController.java:60)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.notifyAllListeners(SubscriptionManager.java:110)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.cleanSubscriptions(SubscriptionManager.java:134)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.cleanSubscriptions(SubscriptionManagerPersist.java:75)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.cleanAll(AuthMethodManager.java:126)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.signOut(AuthMethodManager.java:120)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:98)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.actionPerformed(AzureSignInAction.java:58)
	at com.intellij.openapi.wm.impl.ToolWindowHeader$ActionButton.actionPerformed(ToolWindowHeader.java:548)
	at com.intellij.ui.InplaceButton.doClick(InplaceButton.java:108)
	at com.intellij.ui.InplaceButton$1.execute(InplaceButton.java:73)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.execute(BaseButtonBehavior.java:144)
	at com.intellij.util.ui.BaseButtonBehavior$MyMouseListener.mouseReleased(BaseButtonBehavior.java:127)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



or I also got:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.microsoft.azuretools.utils.AzureModelController.updateSubscriptionMaps(AzureModelController.java:260)
	at com.microsoft.azuretools.utils.AzureModelController.updateResourceGroupMaps(AzureModelController.java:292)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refreshFromAzure(WebappsModule.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:87)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:127)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by milismsft** [comment]
Fixed.

**Comment by davidliangze** [comment]
Test passed both in Eclipse and IntelliJ.

OS: Windows 10 Enterprise x64 ENU
IDE: Eclipse Neon 3/ IntelliJ 2017.1.2
Plugin Version:
Eclipse:WindowsAzurePlugin4EJ.409.05-01-2017
IntelliJ:azure-toolkit-for-intellij.2017.404.05-01-2017
