### ISSUE TITLE
An exception occurred while Azure sign-in using Automated:  New

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#362]
Version: IntelliJ 2017.1.2
Build used: artifacts/azure-toolkit-for-intellij.2017.385.04-27-2017.zip

The issue does not repro any time.
 Repro steps:

1. Start Intelli
2. Right click **Azure** and choose **Sign in**
3. Select **Automated** and click **New** in the Azure Sign In dialog
4. Select subscription: Java Dev Experience Tests with TTL = 7Days.
5. After Service Principal Status creation,click **OK**, then click **Sign in** in Azure Sign In dialog
6. Click **Select** in Select Subscriptions dialog

Error log:
[Correlation ID: e68fa209-6218-4742-bf09-c3549ba6b5c9] Request to acquire token failed.: {"error_description":"AADSTS70001: Application with identifier 'f64fa37b-dd61-43ba-99b0-392a74fb0d85' was not found in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47\r\nTrace ID: 02868955-174d-458a-83cc-a428f6530300\r\nCorrelation ID: e68fa209-6218-4742-bf09-c3549ba6b5c9\r\nTimestamp: 2017-04-28 08:34:03Z","error":"unauthorized_client"}
com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS70001: Application with identifier 'f64fa37b-dd61-43ba-99b0-392a74fb0d85' was not found in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47\r\nTrace ID: 02868955-174d-458a-83cc-a428f6530300\r\nCorrelation ID: e68fa209-6218-4742-bf09-c3549ba6b5c9\r\nTimestamp: 2017-04-28 08:34:03Z","error":"unauthorized_client"}
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:107)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:818)
	at com.microsoft.aad.adal4j.AuthenticationContext.access$100(AuthenticationContext.java:66)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:174)
	at com.microsoft.aad.adal4j.AuthenticationContext$1.call(AuthenticationContext.java:163)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vladimir-shcherbakov** [comment]
breaking commit: https://github.com/Microsoft/azure-tools-for-java-private/commit/14740e3568260f9a9e5a9a8cc5a30abdc77b7e56

**Comment by vladimir-shcherbakov** [comment]
Looks like it takes longer for just created AD App to be seen by an ADAL client.

**Comment by bsaby** [comment]
Using the Azure Public Cloud.

**Comment by bsaby** [comment]
Test passed.
Builds used:
artifacts/azure-toolkit-for-intellij.2017.405.05-01-2017.zip.
artifacts/WindowsAzurePlugin4EJ.410.05-01-2017.zip.
