### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: Must insert new content into body element-

### ISSUE THREAD

**Issue by ozgurarman** [microsoft/azure-tools-for-java#3640]
IntelliJ build version: 2019.2.2 IC-192.6603.28
OS: Windows Server 2016
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.27.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1400,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: Must insert new content into body element-

	at com.microsoft.azure.hdinsight.common.viewmodels.ComboBoxSelectionDelegated.setValueInDispatch(SwingComponentPropertyDelegated.kt:77)
	at com.microsoft.azure.hdinsight.common.viewmodels.SwingComponentPropertyDelegated$setValue$1.run(SwingComponentPropertyDelegated.kt:39)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.runEnvironmentProfileWithCheckSettings(RunConfigurationActionUtils.kt:48)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.submit(SparkSubmitJobAction.kt:114)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.onActionPerformed(SparkSubmitJobAction.kt:67)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:75)
```

**Comment by wezhang** [comment]
Thanks @ozgurarman !

**Comment by wezhang** [comment]
This is an exception thrown from `javax.swing.text.html.HTMLDocument`:
```java
        /**
         * Generates an initial batch of end <code>ElementSpecs</code>
         * in parseBuffer to position future inserts into the body.
         */
        private void generateEndsSpecsForMidInsert() {
            int           count = heightToElementWithName(HTML.Tag.BODY,
                                                   Math.max(0, offset - 1));
            boolean       joinNext = false;

            if (count == -1 && offset > 0) {
                count = heightToElementWithName(HTML.Tag.BODY, offset);
                if (count != -1) {
                    // Previous isn't in body, but current is. Have to
                    // do some end specs, followed by join next.
                    count = depthTo(offset - 1) - 1;
                    joinNext = true;
                }
            }
            if (count == -1) {
                throw new RuntimeException("Must insert new content into body element-");
            }
...
```

**Comment by fengshuaihu** [comment]
Please update to the latest version and try again, if you encounter this issue again, feel free to turn it on again
