### ISSUE TITLE
[IntelliJ][ReportedByUser] NPE at com.microsoft.azuretools.ijidea.ui.SurveyPopUpDialog.setLocationRelativeToIDE

### ISSUE THREAD

**Issue by goran-jordanov** [microsoft/azure-tools-for-java#3641]
IntelliJ build version: 2019.2.3 IU-192.6817.14
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.27.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException
Caused by: java.lang.NullPointerException
	at com.microsoft.azuretools.ijidea.ui.SurveyPopUpDialog.setLocationRelativeToIDE(SurveyPopUpDialog.java:170)
	at com.microsoft.azuretools.ijidea.ui.SurveyPopUpDialog.<init>(SurveyPopUpDialog.java:66)
	at com.microsoft.intellij.helpers.CustomerSurveyHelper.lambda$showFeedbackNotification$0(CustomerSurveyHelper.java:69)
```

**Comment by Flanker32** [comment]
@goran-jordanov Thanks for your feedback, this issue has been fixed and should be released with intellij-toolkit-v3.28.0
