### ISSUE TITLE
Intellij: on java.lang.ExceptionInInitializerError on sign in

### ISSUE THREAD

**Issue by Whoops** [Microsoft/azure-tools-for-java#365]
Just updated to 3.0.0-2017.1

When trying to sign in, I enter my credentials and the progress bar is briefly displayed. Afterwards it still shows as not signed in, but IntelliJ says the following exception has occurred:

```
null
java.lang.ExceptionInInitializerError
	at com.microsoft.azure.management.resources.implementation.ResourceManager$AuthenticatedImpl.<init>(ResourceManager.java:136)
	at com.microsoft.azure.management.resources.implementation.ResourceManager.authenticate(ResourceManager.java:67)
	at com.microsoft.azure.management.Azure$AuthenticatedImpl.<init>(Azure.java:258)
	at com.microsoft.azure.management.Azure$AuthenticatedImpl.<init>(Azure.java:251)
	at com.microsoft.azure.management.Azure.authenticate(Azure.java:143)
	at com.microsoft.azure.management.Azure$ConfigurableImpl.authenticate(Azure.java:193)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.authTid(AccessTokenAzureManager.java:133)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getTenants(AccessTokenAzureManager.java:118)
	at com.microsoft.azuretools.authmanage.AdAuthManager.signIn(AdAuthManager.java:84)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow$5.run(SignInWindow.java:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.AzureServiceClient.<clinit>(AzureServiceClient.java:74)
	... 24 more
```

**Comment by vladimir-shcherbakov** [comment]
@Whoops  What is your OS?

**Comment by vladimir-shcherbakov** [comment]
If it's Ubuntu - we are releasing a hotfix.
  
![ubuntuerror](https://cloud.githubusercontent.com/assets/6579928/25642343/0f50a0da-2f4e-11e7-93bf-02164dacc438.jpg)

**Comment by Whoops** [comment]
I'm on OS X (Sierra). Intellij just updated to 2017.1.2

**Comment by martinsawicki** [comment]
can you try if this staged release candidate works for you: (installing from ZIP) and reply here?
https://azuredownloads.blob.core.windows.net/azuretoolkitforintellij/v3.0.1/azure-toolkit-for-intellij.2017.zip
This issue has been very hard to reproduce on our end, we think we have a fix, but b/c we can't repro the original problem, we can't tell yet if this solves the problem. Thanks.

**Comment by Whoops** [comment]
I'd say you've found it, that RC worked! Thanks!

**Comment by martinsawicki** [comment]
ok, getting there.... someone else is still reporting this issue on Windows though, so not quite out of the woods yet...

**Comment by martinsawicki** [comment]
the updated plugin v3.0.1 has been pushed into the JetBrains plugin publishing pipeline.
this issue will be closed once we confirm its public availability.
