### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by goias5** [microsoft/azure-tools-for-java#3652]
IntelliJ build version: 2019.1.3 IU-191.7479.19
OS: Windows 7
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.27.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,30,824x494,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.lang.Error: The process has been terminated
	at com.microsoft.intellij.runner.RunProcessHandler.println(RunProcessHandler.java:86)
	at com.microsoft.intellij.runner.RunProcessHandler.setText(RunProcessHandler.java:120)
	at com.microsoft.azuretools.utils.WebAppUtils.deployArtifactsToAppService(WebAppUtils.java:324)
	at com.microsoft.intellij.runner.webapp.webappconfig.WebAppRunState.exe

**Comment by wezhang** [comment]
Thanks @goias5 ! @Flanker32 , could you help to check it?

**Comment by Flanker32** [comment]
@goias5 Thanks for your report, could you please share a bit more infos about this issue? Like is there any way to reproduce it?

**Comment by Flanker32** [comment]
Duplicated with #4102
