### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by git001** [microsoft/azure-tools-for-java#3657]
IntelliJ build version: 2019.2.3 IC-192.6817.14
OS: Linux
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.27.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,1,32,1398x967,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.ResourceImpl.withRegion(ResourceImpl.java:153)
	at com.microsoft.azure.management.appservice.implementation.AppServicePlanImpl.withRegion(AppServicePlanImpl.java:20)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.createWebAppWithPriv
```

Stack trace on 2019-10-11 ~13:25 :
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
	... 16 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at rx.exceptions.CompositeException.getCause(CompositeException.java:129)
	at java.base/java.lang.Throwable.printEnclosedStackTrace(Throwable.java:711)
	at java.base/java.lang.Throwable.printEnclosedStackTrace(Throwable.java:713)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:671)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:725)
	at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
	at com.intellij.idea.IdeaLogger.lambda$static$1(IdeaLogger.java:41)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:89)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:276)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.error(Category.java:322)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:117)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:170)
	at com.intellij.ide.plugins.MainRunner.processException(MainRunner.java:121)
	at com.intellij.ide.plugins.MainRunner$1.uncaughtException(MainRunner.java:44)
	at rx.internal.schedulers.ScheduledAction.signalError(ScheduledAction.java:68)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	... 6 more
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.ResourceImpl.withRegion(ResourceImpl.java:153)
	at com.microsoft.azure.management.appservice.implementation.AppServicePlanImpl.withRegion(AppServicePlanImpl.java:20)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.createWebAppWithPrivateRegistryImage(AzureWebAppMvpModel.java:300)
	at com.microsoft.intellij.runner.container.webapponlinux.WebAppOnLinuxDeployState.executeSteps(WebAppOnLinuxDeployState.java:114)
	at com.microsoft.intellij.runner.container.webapponlinux.WebAppOnLinuxDeployState.executeSteps(WebAppOnLinuxDeployState.java:53)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:70)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'errMsg' of com/microsoft/intellij/runner/container/webapponlinux/WebAppOnLinuxDeployState.onFail must not be null
	at com.microsoft.intellij.runner.container.webapponlinux.WebAppOnLinuxDeployState.$$$reportNull$$$0(WebAppOnLinuxDeployState.java)
	at com.microsoft.intellij.runner.container.webapponlinux.WebAppOnLinuxDeployState.onFail(WebAppOnLinuxDeployState.java)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$2(AzureRunProfileState.java:86)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	... 11 more
```

**Comment by git001** [comment]
I think it's the same as #3652

**Comment by wezhang** [comment]
Thanks @git001 ! @Flanker32 , could you help to check it?

**Comment by Flanker32** [comment]
@git001 Thanks for your report, and could you please share is there any way to reproduce this issue?
