### ISSUE TITLE
[IntelliJ][ReportedByUser] Error

### ISSUE THREAD

**Issue by gkoneru** [microsoft/azure-tools-for-java#3660]
IntelliJ build version: 2019.2.3 IU-192.6817.14
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.28.0-2019.2
Error message: 
```
rx.exceptions.CompositeException: 2 exceptions occurred. 
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:268)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:658)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:860)
	at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:656)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:568)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
	at rx.internal.operators.OperatorMapNotification$MapNotificationSubscriber.tryEmit(OperatorMapNotification.java:155)
	at rx.internal.operators.OperatorMapNotification$MapNotificationSubscriber.onCompleted(OperatorMapNotification.java:121)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onCompleted(OnSubscribeMap.java:97)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onCompleted(OperatorSubscribeOn.java:89)

**Comment by andxu** [comment]
Thanks @gkoneru l ! Looks like some important call stacks are cut. If you have the err context, may I get the full one?
