### ISSUE TITLE
[Intellij][Spark] Refresh cluster failure warning

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#3663]
The Azure explorer can refresh cluster, but run configuration dialog can't.

```
2019-10-15 15:12:00,395 [101310897]   WARN - arkClusterListRefreshableCombo - Refresh cluster failure 
com.microsoft.azuretools.adauth.AuthException: Can't get Arcadia workspaces since user doesn't sign in, please sign in by Azure Explorer.
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.getWorkSpacesRequest(ArcadiaSparkComputeManager.java:159)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.fetchWorkSpaces(ArcadiaSparkComputeManager.java:150)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.fetchClusters(ArcadiaSparkComputeManager.java:117)
	at com.microsoft.azure.hdinsight.spark.service.SparkClustersServices.<clinit>(SparkClustersServices.kt:47)
	at com.microsoft.azure.hdinsight.spark.ui.SparkClusterListRefreshableCombo$ViewModel.<init>(SparkClusterListRefreshableCombo.kt:137)
	at com.microsoft.azure.hdinsight.spark.ui.SparkClusterListRefreshableCombo$ViewModel.<init>(SparkClusterListRefreshableCombo.kt:119)
	at com.microsoft.azure.hdinsight.spark.ui.SparkClusterListRefreshableCombo.<init>(SparkClusterListRefreshableCombo.kt:190)
	at com.microsoft.azure.hdinsight.spark.ui.ArcadiaSparkClusterListRefreshableCombo.<init>(SparkClusterListRefreshableCombo.kt:237)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkSubmissionContentPanel$clustersSelection$2.invoke(ArcadiaSparkSubmissionContentPanel.kt:35)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkSubmissionContentPanel$clustersSelection$2.invoke(ArcadiaSparkSubmissionContentPanel.kt:34)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkSubmissionContentPanel.getClustersSelection(ArcadiaSparkSubmissionContentPanel.kt)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1$2.invoke(SparkSubmissionContentPanel.kt:480)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1$2.invoke(SparkSubmissionContentPanel.kt:80)
	at com.microsoft.intellij.forms.dsl.FormBuilder.row(FormBuilder.kt:84)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1.invoke(SparkSubmissionContentPanel.kt:480)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1.invoke(SparkSubmissionContentPanel.kt:80)
	at com.microsoft.intellij.forms.dsl.FormBuilderKt.panel(FormBuilder.kt:31)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2.invoke(SparkSubmissionContentPanel.kt:468)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2.invoke(SparkSubmissionContentPanel.kt:80)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.getSubmissionPanel(SparkSubmissionContentPanel.kt)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.getComponent(SparkSubmissionContentPanel.kt:503)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.setClusterSubmissionPanel(SparkBatchJobConfigurable.java:119)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.createUIComponents(SparkBatchJobConfigurable.java:71)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.$$$setupUI$$$(SparkBatchJobConfigurable.java)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.<init>(SparkBatchJobConfigurable.java:61)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkConfigurable.<init>(ArcadiaSparkConfigurable.kt:30)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkConfiguration.getConfigurationEditor(ArcadiaSparkConfiguration.kt:35)
	at com.intellij.execution.impl.ConfigurationSettingsEditor.<init>(ConfigurationSettingsEditor.java:197)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.<init>(ConfigurationSettingsEditorWrapper.java:49)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:68)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:105)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:863)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:894)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:934)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:907)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:61)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:32)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:401)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:353)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:512)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:566)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:769)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:707)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:432)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:28)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$null$4(ActionManagerImpl.java:1403)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecuteNow$5(ActionManagerImpl.java:1363)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:170)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:168)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:120)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:167)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:63)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecuteNow(ActionManagerImpl.java:1362)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecute$2(ActionManagerImpl.java:1346)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecute(ActionManagerImpl.java:1349)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction.performWhenButton(RunConfigurationsComboBoxAction.java:165)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction.access$000(RunConfigurationsComboBoxAction.java:35)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction$1.fireActionPerformed(RunConfigurationsComboBoxAction.java:142)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:349)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1.mousePressed(ComboBoxAction.java:172)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:769)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by wezhang** [comment]
Dup #3898
