### ISSUE TITLE
[intelliJ][Report to microsoft]Get error when refresh Azure node.

### ISSUE THREAD

**Issue by v-jiche** [microsoft/azure-tools-for-java#3712]
Build:
azure-toolkit-for-intellij-2019.2.develop.1282.10-31-2019.zip

Repro Steps:
1. Open Azure Explorer.
2. Right click Azure node then select refresh button.

Result:
Get error.
![image](https://user-images.githubusercontent.com/35950097/68018035-16a93e00-fcd3-11e9-91df-96f818754590.png)
java.lang.NullPointerException
	at com.microsoft.azuretools.utils.AzureModelController.lambda$null$0(AzureModelController.java:288)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by wezhang** [comment]
@Flanker32 , could you help check it?
