### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error

### ISSUE THREAD

**Issue by skhurana333** [microsoft/azure-tools-for-java#3726]
IntelliJ build version: 2018.3.6 IC-183.6156.11
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.23.0-2018.3
Error message: 
```
java.net.UnknownServiceException: Failed to get job Yarn application: Unknown service error after 2 retries
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.getSparkJobYarnApplication(SparkBatchJob.java:610)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$null$25(SparkBatchJob.java:926)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:104)
	at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
	at rx.internal.operators.OnSubscribeRedo.call(O

**Comment by andxu** [comment]
Duplicate with issue #3208
