### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception JobUtils set Response error java.io.IOException: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by ashwinsathyar** [microsoft/azure-tools-for-java#3728]
IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.28.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x517,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=JobUtils set Response error, throwable=java.io.IOException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.setResponse(JobUtils.java:129)
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.setResponse(JobUtils.java:122)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:67)
```

**Comment by lcadzy** [comment]
https://github.com/microsoft/azure-tools-for-java/pull/3729
