### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by sadatnfs** [microsoft/azure-tools-for-java#3749]
Getting this error when trying to refresh list of Spark Clusters

IntelliJ build version: 2019.2.4 IU-192.7142.36
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.29.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1155,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.microsoft.azuretools.ijidea.ui.WarningMessageForm.$$$setupUI$$$(WarningMessageForm.java)
	at com.microsoft.azuretools.ijidea.ui.WarningMessageForm.<init>(WarningMessageForm.java:48)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl$6$1.<init>(HDInsightHelperImpl.java:254)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl$6.run(HDInsightHelperImpl.java:254)
```

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception  java.lang.NullPointerException (#3814)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)

**Comment by t-rufang** [comment]
@skghukh This issue has been fixed in the latest release. You can try the new plugin by upgrading your IntelliJ to version `2020.1` and upgrade the plugin to version `v3.37.0`
