### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error populating subscriptions and resource groups. java.lang.NullPointerException

### ISSUE THREAD

**Issue by hichMEN** [microsoft/azure-tools-for-java#3766]
IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.29.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x517,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error populating subscriptions and resource groups., throwable=java.lang.NullPointerException
	at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.populateValues(ApplicationInsightsNewDialog.java:120)
	at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.init(ApplicationInsightsNewDialog.java:99)
	at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.<init>(ApplicationInsightsNewDialog.java:71)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel$1.run(AppInsightsMngmtPanel.java:234)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel.createNewDilaog(AppInsightsMngmtPanel.java:231)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel.lambda$newButtonListener$0(AppInsightsMngmtPanel.java:222)
```

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception Error populating subscriptions and resource groups. java.lang.NullPointerExcepti... (#1856)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.populateValues(ApplicationInsightsNewDialog.java:120)
