### ISSUE TITLE
[IntelliJ][SQL Server Big Data Cluster][ReportedByUser] Show the blank "Azure Plugin for IntelliJ Error" dialog.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3771]
**IntelliJ build version:** 2019.2.4 IC-192.7142.36
**OS:** Mac OS X
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** 3.29.0-2019.2 (Market build)

**Repro Steps:**

1. Open IntelliJ
2. Install the build
3. Link SQL Server Big Data Cluster(40.71.22.33:30443), _This cluster is my previously linked_
4. Submit job to this cluster
5. Check the results

**Results:** Show the blank error pops up.
![image](https://user-images.githubusercontent.com/40199316/69230752-d0a11500-0bc2-11ea-8601-84893f3e1687.png)

**Error message:** 
```
com.microsoft.azure.hdinsight.sdk.common.errorresponse.UnauthorizedHttpErrorStatus: 
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.classifyHttpError(HttpObservable.java:295)
	at com.microsoft.azure.hdinsight.sdk.common.HttpObservable.lambda$toStringOnlyOkResponse$1(HttpObservable.java:326)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:66)
	at rx.internal.operators.OnSubscribeUsing.call(OnSubscribeUsing.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.producers.SingleDelayedProducer.emit(SingleDelayedProducer.java:102)
	at rx.internal.producers.SingleDelayedProducer.setValue(SingleDelayedProducer.java:85)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.On

**Comment by lcadzy** [comment]
please reconnect ,seems this cluster has read timeout problem

**Comment by v-lanjli** [comment]
Error dialog pops up caused by cluster broke, Check ‘Advanced Info’ to display the error message.
Closed this issue.
