### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.intellij.helpers.containerregistry.ContainerRegistryPropertyViewProvider is not DumbAware.

### ISSUE THREAD

**Issue by ddimtirov** [microsoft/azure-tools-for-java#3781]
IntelliJ build version: 2019.3 IU-193.5233.57
OS: Windows 7
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.29.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,30,704x478,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.intellij.helpers.containerregistry.ContainerRegistryPropertyViewProvider is not DumbAware.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.microsoft.intellij.helpers.UIHelperImpl.openContainerRegistryPropertyView(UIHelperImpl.java:464)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryNode$ShowContainerRegistryPropertyAction.actionPerformed(ContainerRegistryNode.java:82)
	at com.microsoft.tooling.msservices.serviceexplorer.WrappedTelemetryNodeActionListener.actionPerformed(WrappedTelemetryNodeActionListener.java:41)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerforme

**Comment by Flanker32** [comment]
Fixed in the latest release
