### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception An error occurred while attempting to download Blob. java.io.IOException: The system cannot find the path specified

### ISSUE THREAD

**Issue by ddimtirov** [microsoft/azure-tools-for-java#3782]
IntelliJ build version: 2019.3 IU-193.5233.57
OS: Windows 7
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.29.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,30,704x486,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=An error occurred while attempting to download Blob., throwable=java.io.IOException: The system cannot find the path specified
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at com.microsoft.intellij.helpers.storage.BlobExplorerFileEditor$20.run(BlobExplorerFileEditor.java:597)
```

**Comment by andxu** [comment]
@ddimtirov, I am sorry to tell you that the storage function is deprecated and we don't offer the blob download now, you can use a more powerful tool:https://azure.microsoft.com/en-us/features/storage-explorer/#overview, thanks
