### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by bigmarvin** [microsoft/azure-tools-for-java#3790]
IntelliJ build version: 2019.3 IU-193.5233.102
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.30.0-2019.3
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,3,0,666x489,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=666,height=489]]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.StackOverflowError
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hd

**Comment by bigmarvin** [comment]
Intellij helped with the filing. Thanks!
