### ISSUE TITLE
[IntelliJ] All the toolkit function cause UI hangs when not logged in

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#3798]
[log.zip](https://github.com/microsoft/azure-tools-for-java/files/3915406/log.zip)

Updated plugin/Re-enabled plugin/Restart IntelliJ/Restarted PC and problem remains.
Login to azure solve the problem.
Logout and the problem can't be reproduced.

See attached file for IntelliJ logs and thread dumps for all the UI freeze

**Comment by andxu** [comment]
The reason for hang is calling heavy http access in UI thread:
```
	at java.base@11.0.3/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.3/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base@11.0.3/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base@11.0.3/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base@11.0.3/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base@11.0.3/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base@11.0.3/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base@11.0.3/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at java.base@11.0.3/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base@11.0.3/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base@11.0.3/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base@11.0.3/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base@11.0.3/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base@11.0.3/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
	at java.base@11.0.3/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base@11.0.3/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base@11.0.3/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at com.microsoft.azuretools.adauth.HttpHelper.sendPostRequestAndDeserializeJsonResponse(HttpHelper.java:61)
	at com.microsoft.azuretools.adauth.AuthContext.sendRequest(AuthContext.java:256)
	at com.microsoft.azuretools.adauth.AuthContext.access$100(AuthContext.java:46)
	at com.microsoft.azuretools.adauth.AuthContext$1.getTokenWithRefreshToken(AuthContext.java:245)
	at com.microsoft.azuretools.adauth.CacheDriver.refreshExpireEntry(CacheDriver.java:128)
	at com.microsoft.azuretools.adauth.CacheDriver.refreshEntryIfNecessary(CacheDriver.java:107)
	at com.microsoft.azuretools.adauth.CacheDriver.find(CacheDriver.java:55)
	at com.microsoft.azuretools.adauth.AuthContext.acquireTokenFromCache(AuthContext.java:213)
	at com.microsoft.azuretools.adauth.AuthContext.acquireToken(AuthContext.java:95)
	at com.microsoft.azuretools.authmanage.BaseADAuthManager.loadFromSecureStore(BaseADAuthManager.java:142)
	at com.microsoft.azuretools.authmanage.DCAuthManager.tryRestoreSignIn(DCAuthManager.java:71)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.getAzureManager(AuthMethodManager.java:148)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.getAzureManager(AuthMethodManager.java:128)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.isSignedIn(AuthMethodManager.java:192)
	at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction.getIcon(SignInOutAction.java:74)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.update(AzureSignInAction.java:90)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
```

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738834
