### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by davidanugo** [microsoft/azure-tools-for-java#3809]
IntelliJ build version: 2019.3 IU-193.5233.102
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.30.0-2019.3
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,0,22,777x460,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=777,height=460]]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.StackOverflowError
	at java.base/java.lang.StringBuffer.capacity(StringBuffer.java:209)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.micr

**Comment by wezhang** [comment]
Dup #3823
