### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.util.IncorrectOperationException: Sorry but parent: Project (Disposed) Github has already been disposed (see the cause for stacktrace) so the child: null 1008124201: running=false; canceled=false; task=null will never be disposed

### ISSUE THREAD

**Issue by gwdcodeteam** [microsoft/azure-tools-for-java#3850]
IntelliJ build version: 2018.3.4 IU-183.5429.30
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.23.0-2018.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,30,1536x801,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.util.IncorrectOperationException: Sorry but parent: Project (Disposed) Github has already been disposed (see the cause for stacktrace) so the child: null 1008124201: running=false; canceled=false; task=null will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:75)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:110)
	at com.intellij.openapi.

**Comment by Flanker32** [comment]
@gwdsss Thanks for your report and really sorry for the late reply, could you please provide a bit more information like how this issue occurs? Or could you please try our latest version of toolkit to see whether this issue could be reproduced?
