### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.intellij.helpers.webapp.WebAppPropertyViewProvider is not DumbAware.

### ISSUE THREAD

**Issue by ktprezes** [microsoft/azure-tools-for-java#3851]
IntelliJ build version: 2019.3 IU-193.5233.102
OS: Windows 8.1
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.30.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,31,2758x1851,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.intellij.helpers.webapp.WebAppPropertyViewProvider is not DumbAware.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.microsoft.intellij.helpers.UIHelperImpl.openWebAppPropertyView(UIHelperImpl.java:501)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapp.WebAppNode$2.actionPerformed(WebAppNode.java:102)
	at com.microsoft.tooling.msservices.serviceexplorer.WrappedTelemetryNodeActionListener.actionPerformed(WrappedTelemetryNodeActionListener.java:41)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListener.actionPerformedAsync(NodeActionListener.java:79)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeAction.fireNode

**Comment by Flanker32** [comment]
Fixed in the latest releasse
