### ISSUE TITLE
[IntelliJ][ReportedByUser][EAP193.1]In the console, IDE internal error occurred when using shortcut keys.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3864]
**IntelliJ build version:** 2019.3.1 IC-193.5662.53
**OS:** Windows 10/Mac
**JDK:** JetBrains s.r.o 11.0.5
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/11500112?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11114708.12-17-2019.zip
**Additional Info:** None
**Repeo Steps:**

1. Edit Configuration
2. Tools->Spark Console->Livy Console/Local Console
3. Input the command in console
4. Press Enter for the second line, or press delete the command
5. Check the results

**Current results:** IDE internal error occurred.

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1441x860,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor561.invoke(Unknown Source)
	at com.microsoft.azure.hdinsight.spark.console.SparkActionPromoterScalaDelegate.promote(SparkActionPromoterDelegate.kt:39)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean shouldPromote(com.intellij.openapi.actionSystem.AnAction, com.intellij.openapi.actionSystem.DataContext)' of abstract class org.jetbrains.plugins.scala.actions.SingleActionPromoterBase.
```
![image](https://user-images.githubusercontent.com/40199316/71149806-aba7cc80-226a-11ea-8721-ba378d206e64.png)
![IntelliJ ReportedByUser EAP Win  When input command in the console, an IDE internal error occurred](https://user-images.githubusercontent.com/40199316/71150392-5076d980-226c-11ea-8de7-cbd72802a21c.gif)

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://dev.azure.com/mseng/_apis/resources/Containers/11542533?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11138974.12-20-2019.zip)
Closed this issue.
