### ISSUE TITLE
[IntelliJ][EAP][ReportedByUser] Shortcuts (Ctrl+V) failed to paste and get an IDE internal error occurred in IntelliJ 193.1

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3869]
**IntelliJ build version:** 
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 984M
Cores: 4
Registry: 
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure
**OS:** Windows/Mac/Linux
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/11500112?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11114708.12-17-2019.zip

**Additional Info:** None

**Repro Steps:**

1. Install the IntelliJ IDEA 2019.3.1
2. Install the above plugin
3. Open or create a project
4. Open Configuration
5. Use shortcut keys (Ctrl+V) to paste the content you need to fill in
6. Check the results

**Current results:** Shortcuts failed to paste and an IDE internal error occurred.
**Parent component:** 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x498,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.microsoft.azure.hdinsight.spark.console.SparkActionPromoterScalaDelegate.promote(SparkActionPromoterDelegate.kt:39)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean shouldPromote(com.intellij.openapi.actionSystem.AnAction, com.intellij.openapi.actionSystem.DataContext)' of abstract class org.jetbrains.plugins.scala.actions.SingleActionPromoterBase.
```
![IntelliJ EAP ReportedByUser  Shortcuts failed to paste and an IDE internal error occurred in IntelliJ 193 1](https://user-images.githubusercontent.com/40199316/71165810-744a1780-228c-11ea-85b6-0e287421875c.gif)

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://dev.azure.com/mseng/_apis/resources/Containers/11542533?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11138974.12-20-2019.zip)
Closed this issue.
