### ISSUE TITLE
[IntelliJ][ReportedByUser][EAP193.1][Console]Press 'Ctrl+Enter' doesn't work in console, and get an IDE internal error occurred.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3875]
**IntelliJ build version:**
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 984M
Cores: 4
Registry:
Non-Bundled Plugins: org.intellij.scala, com.microsoft.tooling.msservices.intellij.azure
**OS:** Windows/Mac/Linux
**Plugin version:** https://dev.azure.com/mseng/_apis/resources/Containers/11500112?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11114708.12-17-2019.zip

**Repeo Steps:**

1. Edit Configuration
2. Tools->Spark Console->Livy Console/Local Console
3. Input the command in console
4. Press Ctrl + Enter
5. Check the results

**Current results:** Press 'Ctrl+Enter' doesn't work in console, and show IDE internal error occurred.

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1441x819,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.microsoft.azure.hdinsight.spark.console.SparkActionPromoterScalaDelegate.promote(SparkActionPromoterDelegate.kt:39)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean shouldPromote(com.intellij.openapi.actionSystem.AnAction, com.intellij.openapi.actionSystem.DataContext)' of abstract class org.jetbrains.plugins.scala.actions.SingleActionPromoterBase.
```
![IntelliJ ReportedByUser EAP193 1 Console Press 'Ctrl+Enter' doesn't work in console, and get an IDE internal error occurred](https://user-images.githubusercontent.com/40199316/71236557-3c011280-233a-11ea-8cb0-3beea32a3f3a.gif)

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://dev.azure.com/mseng/_apis/resources/Containers/11542533?itemPath=drop%2Fazure-toolkit-for-intellij-2019.3.develop.11138974.12-20-2019.zip)
Closed this issue.
