### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by MielHostens** [microsoft/azure-tools-for-java#3879]
IntelliJ build version: 2019.3.1 IC-193.5662.53
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.30.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x498,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.microsoft.azure.hdinsight.spark.console.SparkActionPromoterScalaDelegate.promote(SparkActionPromoterDelegate.kt:39)
Caused by: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract boolean shouldPromote(com.intellij.openapi.actionSystem.AnAction, com.intellij.openapi.actionSystem.DataContext)' of abstract class org.jetbrains.plugins.scala.actions.SingleActionPromoterBase.
```

**Comment by wezhang** [comment]
Thanks @MielHostens ! Fixed after 3.31.0. (Dup #3864)
