### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azuretools.adauth.AuthException: No subscription found in the account

### ISSUE THREAD

**Issue by redstarh** [microsoft/azure-tools-for-java#3888]
IntelliJ build version: 2019.3.1 IU-193.5662.53
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.31.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1400x978,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel.loadInfoFirstTime(AppInsightsMngmtPanel.java:139)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel.init(AppInsightsMngmtPanel.java:77)
	at com.microsoft.intellij.AzureConfigurable$AzureAbstractConfigurable.createComponent(AzureConfigurable.java:125)
```

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
