### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#3895]
Clicked refresh on Azure Explorer:

IntelliJ build version: 2019.2.4 IU-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.30.0-2019.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.list(ResourceGroupsInner.java:687)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsImpl.list(ResourceGroupsImpl.java:41)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesImpl.list(RegistriesImpl.java:55)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listRegistryBySubscriptionId(ContainerRegistryMvpModel.java:87)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listContainerRegistries(ContainerRegistryMvpModel.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModulePresenter.onModuleRefresh(ContainerRegistryModulePresenter.java:38)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModule.refreshItems(ContainerRegistryModule.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Refresh then sign out, pops error dialogs (#1643)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: unknown_user
