### ISSUE TITLE
[IntelliJ][Config]Synapse workspace cannot be listed.

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#3898]
Build: Bundle Build 192
OS: Mac/Windows/Linux
Repro Steps:
1.Install build
2.Sign in with Azure account
3.Select aII subscriptions
4.Refresh the Apache Spark on Synapse node
5.Create a new config file,select main class
6.Click target spark pool drop-down selection box

Result: Can not list synapse workspace
![image](https://user-images.githubusercontent.com/43333874/71714124-6682af00-2dc1-11ea-90cf-e3d89cae28f6.png)

```
2020-01-03 00:55:21,971 [8098689]   INFO - arkClusterListRefreshableCombo - Selected null, (you may get duplicated outputs for each subscriptions) 
2020-01-03 00:55:22,179 [8098897]   WARN - arkClusterListRefreshableCombo - Refresh cluster failure 
com.microsoft.azuretools.adauth.AuthException: Can't get Arcadia workspaces since user doesn't sign in, please sign in by Azure Explorer.
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.getWorkSpacesRequest(ArcadiaSparkComputeManager.java:166)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.fetchWorkSpaces(ArcadiaSparkComputeManager.java:153)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.fetchClusters(ArcadiaSparkComputeManager.java:120)
	at com.microsoft.azure.hdinsight.spark.service.SparkClustersServices.<clinit>(SparkClustersServices.kt:46)
	at com.microsoft.azure.hdinsight.spark.ui.SparkClusterListRefreshableCombo$ViewModel.<init>(SparkClusterListRefreshableCombo.kt:137)
	at com.microsoft.azure.hdinsight.spark.ui.SparkClusterListRefreshableCombo$ViewModel.<init>(SparkClusterListRefreshableCombo.kt:119)
	at com.microsoft.azure.hdinsight.spark.ui.SparkClusterListRefreshableCombo.<init>(SparkClusterListRefreshableCombo.kt:190)
	at com.microsoft.azure.hdinsight.spark.ui.ArcadiaSparkClusterListRefreshableCombo.<init>(SparkClusterListRefreshableCombo.kt:234)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkSubmissionContentPanel$clustersSelection$2.invoke(ArcadiaSparkSubmissionContentPanel.kt:35)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkSubmissionContentPanel$clustersSelection$2.invoke(ArcadiaSparkSubmissionContentPanel.kt:34)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkSubmissionContentPanel.getClustersSelection(ArcadiaSparkSubmissionContentPanel.kt)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1$2.invoke(SparkSubmissionContentPanel.kt:507)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1$2.invoke(SparkSubmissionContentPanel.kt:80)
	at com.microsoft.intellij.forms.dsl.FormBuilder.row(FormBuilder.kt:84)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1.invoke(SparkSubmissionContentPanel.kt:506)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2$formBuilder$1.invoke(SparkSubmissionContentPanel.kt:80)
	at com.microsoft.intellij.forms.dsl.FormBuilderKt.panel(FormBuilder.kt:31)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2.invoke(SparkSubmissionContentPanel.kt:494)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel$submissionPanel$2.invoke(SparkSubmissionContentPanel.kt:80)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.getSubmissionPanel(SparkSubmissionContentPanel.kt)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionContentPanel.getComponent(SparkSubmissionContentPanel.kt:538)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.setClusterSubmissionPanel(SparkBatchJobConfigurable.java:119)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.createUIComponents(SparkBatchJobConfigurable.java:71)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.$$$setupUI$$$(SparkBatchJobConfigurable.java)
	at com.microsoft.azure.hdinsight.spark.ui.SparkBatchJobConfigurable.<init>(SparkBatchJobConfigurable.java:61)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkConfigurable.<init>(ArcadiaSparkConfigurable.kt:30)
	at com.microsoft.azure.hdinsight.spark.run.configuration.ArcadiaSparkConfiguration.getConfigurationEditor(ArcadiaSparkConfiguration.kt:35)
	at com.intellij.execution.impl.ConfigurationSettingsEditor.<init>(ConfigurationSettingsEditor.java:197)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.<init>(ConfigurationSettingsEditorWrapper.java:49)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.<init>(SingleConfigurationConfigurable.java:68)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:105)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:863)
	at com.intellij.execution.impl.RunConfigurable.createNewConfiguration(RunConfigurable.kt:894)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:934)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$showAddPopup$popup$1.consume(RunConfigurable.kt:907)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:61)
	at com.intellij.execution.impl.NewRunConfigurationPopup$1.onChosen(NewRunConfigurationPopup.java:32)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:401)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:353)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:512)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:566)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:693)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:707)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:432)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1644)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:28)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$null$4(ActionManagerImpl.java:1403)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecuteNow$5(ActionManagerImpl.java:1363)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:170)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2464)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:222)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:174)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:167)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:63)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecuteNow(ActionManagerImpl.java:1362)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.lambda$tryToExecute$2(ActionManagerImpl.java:1346)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.tryToExecute(ActionManagerImpl.java:1349)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction.performWhenButton(RunConfigurationsComboBoxAction.java:165)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction.access$000(RunConfigurationsComboBoxAction.java:35)
	at com.intellij.execution.actions.RunConfigurationsComboBoxAction$1.fireActionPerformed(RunConfigurationsComboBoxAction.java:142)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.intellij.openapi.actionSystem.ex.ComboBoxAction$ComboBoxButton$1.mousePressed(ComboBoxAction.java:172)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6547)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by t-rufang** [comment]
Need Wei to help take a look at the Auth exception @wezhang

**Comment by wezhang** [comment]
Have to find a way to repro.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738882
