### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by LeftistTachyon** [microsoft/azure-tools-for-java#3904]
IntelliJ build version: 2019.3.1 IC-193.5662.53
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.31.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1367x728,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 6cf426a5-f5cc-490e-afcb-1adf40f5b400\r\nCorrelation ID: 25229350-39bf-4606-811a-b8b92cddc4b6\r\nTimestamp: 2020-01-06 03:01:50Z","error_codes":[90002],"timestamp":
```
stacktrace.kt:
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorNotImplementedException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 6cf426a5-f5cc-490e-afcb-1adf40f5b400\r\nCorrelation ID: 25229350-39bf-4606-811a-b8b92cddc4b6\r\nTimestamp: 2020-01-06 03:01:50Z","error_codes":[90002],"timestamp":"2020-01-06 03:01:50Z","trace_id":"6cf426a5-f5cc-490e-afcb-1adf40f5b400","correlation_id":"25229350-39bf-4606-811a-b8b92cddc4b6","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.observables.BlockingObservable$8.call(BlockingObservable.java:636)
	at rx.observables.BlockingObservable$8.call(BlockingObservable.java:633)
	at rx.observables.BlockingObservable$9.onError(BlockingObservable.java:667)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:132)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:531)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:659)
	at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:633)
	at com.microsoft.azure.docker.ops.utils.AzureDockerUtils$4.call(AzureDockerUtils.java:395)
	at com.microsoft.azure.docker.ops.utils.AzureDockerUtils$4.call(AzureDockerUtils.java:387)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 6cf426a5-f5cc-490e-afcb-1adf40f5b400\r\nCorrelation ID: 25229350-39bf-4606-811a-b8b92cddc4b6\r\nTimestamp: 2020-01-06 03:01:50Z","error_codes":[90002],"timestamp":"2020-01-06 03:01:50Z","trace_id":"6cf426a5-f5cc-490e-afcb-1adf40f5b400","correlation_id":"25229350-39bf-4606-811a-b8b92cddc4b6","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at com.microsoft.azuretools.adauth.AuthContext.sendRequest(AuthContext.java:260)
	at com.microsoft.azuretools.adauth.AuthContext.access$100(AuthContext.java:46)
	at com.microsoft.azuretools.adauth.AuthContext$1.getTokenWithRefreshToken(AuthContext.java:245)
	at com.microsoft.azuretools.adauth.CacheDriver.acquireTokenFromMrrt(CacheDriver.java:117)
	at com.microsoft.azuretools.adauth.CacheDriver.refreshEntryIfNecessary(CacheDriver.java:109)
	at com.microsoft.azuretools.adauth.CacheDriver.find(CacheDriver.java:55)
	at com.microsoft.azuretools.adauth.AuthContext.acquireTokenFromCache(AuthContext.java:213)
	at com.microsoft.azuretools.adauth.AuthContext.acquireToken(AuthContext.java:126)
	at com.microsoft.azuretools.authmanage.AdAuthManager.getAccessToken(AdAuthManager.java:73)
	at com.microsoft.azuretools.authmanage.RefreshableTokenCredentials.getToken(RefreshableTokenCredentials.java:65)
	at com.microsoft.azure.credentials.AzureTokenCredentials.getToken(AzureTokenCredentials.java:74)
	at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.azuretools.telemetry.TelemetryInterceptor.intercept(TelemetryInterceptor.java:46)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94)
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	... 10 more
Caused by: java.io.IOException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 6cf426a5-f5cc-490e-afcb-1adf40f5b400\r\nCorrelation ID: 25229350-39bf-4606-811a-b8b92cddc4b6\r\nTimestamp: 2020-01-06 03:01:50Z","error_codes":[90002],"timestamp":"2020-01-06 03:01:50Z","trace_id":"6cf426a5-f5cc-490e-afcb-1adf40f5b400","correlation_id":"25229350-39bf-4606-811a-b8b92cddc4b6","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at com.microsoft.azuretools.adauth.HttpHelper.sendPostRequestAndDeserializeJsonResponse(HttpHelper.java:92)
	at com.microsoft.azuretools.adauth.AuthContext.sendRequest(AuthContext.java:256)
	... 67 more
```

Came after or during #3900, #3901, #3902, and #3903.

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Azure Explorer - Error Loading Web Apps (#3653)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.
