### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by kserevena** [microsoft/azure-tools-for-java#3908]
IntelliJ build version: 2019.3.1 IU-193.5662.53
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.30.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1200,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.StackOverflowError
	at org.apache.log4j.helpers.PatternParser$DatePatternConverter.convert(PatternParser.java:440)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdins

**Comment by wezhang** [comment]
Thanks! Dup #3823
