### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 02c74ad9-1600-41f4-9ff1-318f6bd15fa6] Execution of class com.microsoft.aad.adal4j.AcquireDeviceCodeCallable failed. java.net.UnknownHostException: login.microsoftonline.com

### ISSUE THREAD

**Issue by DavidChenLiang** [microsoft/azure-tools-for-java#3915]
IntelliJ build version: 2019.3.1 IU-193.5662.53
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.31.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1282x681,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 02c74ad9-1600-41f4-9ff1-318f6bd15fa6] Execution of class com.microsoft.aad.adal4j.AcquireDeviceCodeCallable failed., throwable=java.net.UnknownHostException: login.microsoftonline.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at com.microsoft.aad.adal4j.HttpHelper.readResponseFromConnection(HttpHelper.java:77)
	at com.microsoft.aad.adal4j.HttpHelper.getResponse(HttpHelper.java:181)
	at com.microsoft.aad.adal4j.HttpHelper.executeGetRequest(HttpHelper.java:155)
	at com.microsoft.aad.adal4j.HttpHelper.executeHttpGet(HttpHelper.java:49)
	at com.microsoft.aad.adal4j.DeviceCodeRequest.execute(DeviceCodeRequest.java:54)
	at com.microsoft.aad.adal4j.AcquireDeviceCodeCallable.execute(AcquireDeviceCodeCallable.jav

**Comment by Flanker32** [comment]
@DavidChenLiang Thanks for your report and really sorry for the late reply, we are revisiting the old issues and could you please share a bit more information for this issue, like could it be reproduced? It seems to be an network issue from the log
