### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: c87a48e9-994e-4183-8fd5-5a27bd1ce9fc] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed. com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3926]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip

Get the error when sign in with esp account. It happen only once, after sign out/forget all accounts then sign in for the first time.

IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.31.0
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1441x819,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
[Correlation ID: c87a48e9-994e-4183-8fd5-5a27bd1ce9fc] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.
Trace ID: 0e5efaf1-bdd9-4d46-83f5-510c61663e00
Correlation ID: c87a48e9-994e-4183-8fd5-5a27bd1ce9fc
Timestamp: 2020-01-14 08:40:18Z
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:118)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jingyanjingyan** [comment]
Close since it is not easy to repro
