### ISSUE TITLE
[IntelliJ] [ESP] Submit job failed

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3928]
**Build:** https://dev.azure.com/mseng/_apis/resources/Containers/11855838?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11299072.01-14-2020.zip
**IntelliJ Version:** 2019.2
**OS:** Windows/Mac/Linux

**Repro Steps:**
Open IntelliJ and Install the build
Sign in with jejiang's (jejiang@hdicore.com) account
Submit job to ESP cluster, e.g. hibt03
Check the results

**Results:** Submit job failed.
![image](https://user-images.githubusercontent.com/40199316/72339499-4fb55400-3701-11ea-9c6a-50198137ea4e.png)
ERROR: The Spark job failed to start due to 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:721)
20/01/14 12:30:28 INFO ApplicationMaster: Deleting staging directory abfs://hibt03-2020-01-10t01-12-20-099z@hdicorehns.dfs.core.windows.net/user/jejiang/.sparkStaging/application_1578700871225_0013
20/01/14 12:30:28 INFO ShutdownHookManager: Shutdown hook called
20/01/14 12:30:28 INFO ShutdownHookManager: Deleting directory /mnt/resource/hadoop/yarn/local/usercache/jejiang/appcache/application_1578700871225_0013/spark-07de9ec8-fd1f-41a8-9041-e15d946bf852

Failing this attempt. Failing the application.

**Comment by v-lanjli** [comment]
Verified and fixed in this buils(https://dev.azure.com/mseng/_apis/resources/Containers/11893339?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11320565.01-17-2020.zip)
Closed this issue.
