### ISSUE TITLE
[IntelliJ][ESP][LinkCluster] Submit job failed to linked cluster

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3929]
**Build:** https://dev.azure.com/mseng/_apis/resources/Containers/11855838?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11299072.01-14-2020.zip
**IntelliJ Version:** 2019.2
**OS:** Windows/Mac/Linux

**Repro Steps:**

1. Open IntelliJ and Install the build
2. Sign in with omid's (omid@hdicore.com) account
3. Link an ESP cluster, e.g. hibt03, rootpath: abfs://abfs02-2019-05-29t00-42-51-925z@hdicorehns.dfs.core.windows.net
4. Submit job to this cluster

**Results:** Submit job failed.
![image](https://user-images.githubusercontent.com/40199316/72346209-6b742680-3710-11ea-975c-a2843f500451.png)

LOG: Caused by: Operation failed: "The specified path does not exist.", 404, HEAD, https://hdicorehns.dfs.core.windows.net/hibt03-2020-01-10t01-12-20-099z/user/omid/SparkSubmission/2020/01/14/116129c1-d768-4c73-9843-5dc21b32067b?upn=true&timeout=90
LOG: 	at org.apache.hadoop.fs.azurebfs.services.AbfsRestOperation.execute(AbfsRestOperation.java:135)
LOG: 	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getPathStatus(AbfsClient.java:355)
LOG: 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getFileStatus(AzureBlobFileSystemStore.java:474)
LOG: 	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:437)
LOG: 	... 31 more
LOG: 20/01/14 12:49:51 INFO ShutdownHookManager: Shutdown hook called
LOG: 20/01/14 12:49:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-0f9519d7-90d0-463c-94ce-95ba2c26b29a
LOG: java.lang.Exception: No YARN application is found with tag livy-batch-7-xbra1gpp in 120 seconds. Please check your cluster status, it is may be very busy.
LOG: org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:97)
ERROR: The Spark job failed to start due to 	at org.apache.hadoop.fs.azurebfs.services.AbfsClient.getPathStatus(AbfsClient.java:355)
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.getFileStatus(AzureBlobFileSystemStore.java:474)
	at org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.getFileStatus(AzureBlobFileSystem.java:437)
	... 31 more
20/01/14 12:49:51 INFO ShutdownHookManager: Shutdown hook called
20/01/14 12:49:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-0f9519d7-90d0-463c-94ce-95ba2c26b29a

stderr: 

YARN Diagnostics: 
java.lang.Exception: No YARN application is found with tag livy-batch-7-xbra1gpp in 120 seconds. Please check your cluster status, it is may be very busy.
org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:97)

**Comment by v-lanjli** [comment]
Verified and fixed in this build(https://dev.azure.com/mseng/_apis/resources/Containers/11893339?itemPath=drop%2Fazure-toolkit-for-intellij-2019.2.4.develop.11320565.01-17-2020.zip), closed this issue.
