### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading HDInsight

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3931]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11290224.01-13-2020.zip

Repro Steps:
Sign in omid account, wait for the azure explorer refreshing automatically

Result:
Get error

Note: Get the error only once time.

IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.31.0
Error message: 
```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:787)
	at java.base/java.util.ArrayList.add(ArrayList.java:512)
	at com.google.common.collect.ForwardingList.add(ForwardingList.java:65)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.add(ObservableList.java:73)
	at com.google.common.collect.ForwardingList.standardAdd(ForwardingList.java:134)
	at com.microsoft.tooling.msservices.helpers.collections.ObservableList.add(ObservableList.java:44)
	at com.microsoft.tooling.msservices.serviceexplorer.Node.addChildNode(Node.java:203)
	at com.microsoft.azure.hdinsight.serverexplore.HDInsightRootModuleImpl.lambda$refreshItems$0(HDInsightRootModuleImpl.java:69)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.microsoft.azure.hdinsight.serverexplore.HDInsightRootModuleImpl.refreshItems(HDInsightRootModuleImpl.java:69)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:158)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/36756024/72410919-a889f880-37a4-11ea-9db7-538590d4cebf.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738874
