### ISSUE TITLE
[IntelliJ][ReportedByUser][193]Get IDE Fatal Errors when Click jobs node in Azure Explorer

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#3954]
**IntelliJ build version:** 2019.3.1 IC-193.5662.53
**OS:** Mac\Win\Linux
**JDK:** JetBrains s.r.o 11.0.5
**Plugin version:** 3.32.0
**Additional Info:** None

**Repro Steps:**

1. Open Azure Explorer.
2. Expand HDInsight.
3. Click the jobs node of the clusters.

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1280x691,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: HIDE_DEFAULT_EDITOR is supported only for DumbAware providers; class com.microsoft.azure.hdinsight.jobs.framework.JobViewEditorProvider is not DumbAware.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl$1.run(HDInsightHelperImpl.java:116)
```

**Comment by Flanker32** [comment]
Fixed in the latest release
