### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor java.lang.StackOverflowError

### ISSUE THREAD

**Issue by abosvald** [microsoft/azure-tools-for-java#3961]
IntelliJ build version: 2019.3.1 IU-193.5662.53
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1680x921,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)

**Comment by wezhang** [comment]
Dup #4023
