### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by denz0x13** [microsoft/azure-tools-for-java#3962]
IntelliJ build version: 2019.3.1 IU-193.5662.53
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.31.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1384x815,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.StackOverflowError
	at com.intellij.diagnostic.IdeErrorsDialog.findPluginId(IdeErrorsDialog.java:899)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobD

**Comment by wezhang** [comment]
Thanks @denz0x13 ! Dup #3887
