### ISSUE TITLE
Can't refresh access token after a long time

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#3965]
```
2020-02-06 20:46:01,224 [276879794]   WARN - nsight.common.ClusterManagerEx - Error Refreshing HDInsight clusters. com.microsoft.azuretools.azurecommons.helpers.AzureCmdException: Error listing HDInsight clusters
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterOperationImpl.listCluster(ClusterOperationImpl.java:76)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterManager.lambda$null$1(ClusterManager.java:87)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Authorization is required, please sign out and sign in again
	at com.microsoft.azuretools.authmanage.DCAuthManager.getAccessToken(DCAuthManager.java:98)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getAccessToken(AccessTokenAzureManager.java:226)
	at com.microsoft.azuretools.sdkmanage.AzureManager.getAccessToken(AzureManager.java:57)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterOperationImpl.requestWithToken(ClusterOperationImpl.java:131)
	at com.microsoft.azure.hdinsight.sdk.cluster.ClusterOperationImpl.listCluster(ClusterOperationImpl.java:54)
	... 13 more
Caused by: com.microsoft.azuretools.adauth.AuthException: invalid_grant
	at com.microsoft.azuretools.adauth.AuthContext.sendRequest(AuthContext.java:260)
	at com.microsoft.azuretools.adauth.AuthContext.access$100(AuthContext.java:46)
	at com.microsoft.azuretools.adauth.AuthContext$1.getTokenWithRefreshToken(AuthContext.java:245)
	at com.microsoft.azuretools.adauth.CacheDriver.acquireTokenFromMrrt(CacheDriver.java:117)
	at com.microsoft.azuretools.adauth.CacheDriver.refreshEntryIfNecessary(CacheDriver.java:109)
	at com.microsoft.azuretools.adauth.CacheDriver.find(CacheDriver.java:55)
	at com.microsoft.azuretools.adauth.AuthContext.acquireTokenFromCache(AuthContext.java:213)
	at com.microsoft.azuretools.adauth.AuthContext.acquireToken(AuthContext.java:142)
	at com.microsoft.azuretools.authmanage.DCAuthManager.getAccessToken(DCAuthManager.java:93)
	... 17 more
Caused by: com.microsoft.azuretools.adauth.AuthException: invalid_grant
	at com.microsoft.azuretools.adauth.HttpHelper.sendPostRequestAndDeserializeJsonResponse(HttpHelper.java:88)
	at com.microsoft.azuretools.adauth.AuthContext.sendRequest(AuthContext.java:256)
	... 25 more
 
```

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
- Error when trying to connect to Microsoft Azrue with Eclipse Neon 3 (#356)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: invalid_grant
