### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.intellij.profiler.DefaultProfilerExecutorGroup java.lang.StackOverflowError

### ISSUE THREAD

**Issue by tmaskibail** [microsoft/azure-tools-for-java#3966]
IntelliJ build version: 2019.3.2 IU-193.6015.39
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1681x1020,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.intellij.profiler.DefaultProfilerExecutorGroup, throwable=java.lang.StackOverflowError
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at co

**Comment by wezhang** [comment]
Dup #4023
