### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor java.lang.StackOverflowError

### ISSUE THREAD

**Issue by ehabrefaat82** [microsoft/azure-tools-for-java#3969]
IntelliJ build version: 2019.3.2 IU-193.6015.39
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,0,22,777x460,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=777,height=460]]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError
	at com.intellij.util.lang.JarLoader.getResource(JarLoader.java:241)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecuto

**Comment by wezhang** [comment]
Dup #4023
