### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by smukherjee** [microsoft/azure-tools-for-java#3978]
IntelliJ build version: 2018.3.5 IU-183.5912.21
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.23.0-2018.3
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:108)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.handleSubscriptionChange(AzureModule.java:227)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.access$100(AzureModule.java:48)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule$SignInOutListener.run(AzureModule.java:236)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:150)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:134)
	at com.microsoft.intellij.serviceexplorer.azure.SignInOutAction$1.actionPerformed(SignInOu

**Comment by andxu** [comment]
Hi @smukherjee , can you install azure cli and login to azure cli with the same account and show us the result :
```
az account list
```

**Comment by smukherjee** [comment]
Hi,
Now with the new plugin i can see one subscription.. All the data below has
been changed. Please also find a document showing all the steps. Hopefully
you find it useful..

Thanks again for the plugin.

Sujoy
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "9cebxxxxxx994-xxxxe-xxx8-bxxxxxxxxxx",
    "id": "45xxxxxxxxxx-xxxe-3466xxxxx-xxxxxxxxxc56d",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Personal",
    "state": "Enabled",
    "tenantId": "1234567888890",
    "user": {
      "name": "myemailid",
      "type": "user"
    }
  },
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "asdasdklajs;fljk1231231234asdfasdf",
    "id": "asdfkasdfkasdjf;lj23412412341234",
    "isDefault": false,
    "managedByTenants": [],
    "name": "SITA – BI Portfolio – Development",
    "state": "Enabled",
    "tenantId": "123445454575889678976968969",
    "user": {
      "name": " myemailid",
      "type": "user"
    }
  }
]

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
