### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3984]
Build: Both bundle and only bit, on Windows.
ideaIC-bundle-win-x64-2019.2.4.develop.11507847.02-14-2020

Repro Steps:
1. Sign in
2. Create a synapse/spark on cosmos config
3. Sign out
4. Start livy interactive console

Result:
Error as below

IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_232-release
Plugin version: 3.32.0
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x998,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkConsoleActionDelegate.actionPerformed(RunSparkConsoleActionDelegate.kt:59)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:265)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:115)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	... 19 more
Caused by: java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: Can't get Synapse workspaces since user doesn't sign in, please sign in by Azure Explorer.
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:166)
	at com.microsoft.azure.projectarcadia.spark.console.ArcadiaSparkScalaLivyConsoleRunConfiguration.checkRunnerSettings(ArcadiaSparkScalaLivyConsoleRunConfiguration.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.checkRunnerSettings(RunConfigurationActionUtils.kt:88)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.getRunConfigurationError(RunConfigurationActionUtils.kt:93)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.runEnvironmentProfileWithCheckSettings(RunConfigurationActionUtils.kt:54)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.runEnvironmentProfileWithCheckSettings$default(RunConfigurationActionUtils.kt:43)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runFromSetting(RunSparkScalaConsoleAction.kt:144)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.access$runFromSetting(RunSparkScalaConsoleAction.kt:52)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction$runExisting$1.invoke(RunSparkScalaConsoleAction.kt:119)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction$runExisting$1.invoke(RunSparkScalaConsoleAction.kt:52)
	at com.microsoft.intellij.util.ApplicationHelpersKt.runInReadAction(ApplicationHelpers.kt:42)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.runExisting(RunSparkScalaConsoleAction.kt:118)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaConsoleAction.onActionPerformed(RunSparkScalaConsoleAction.kt:71)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:75)
	... 57 more
Caused by: com.microsoft.azuretools.adauth.AuthException: Can't get Synapse workspaces since user doesn't sign in, please sign in by Azure Explorer.
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.getWorkSpacesRequest(ArcadiaSparkComputeManager.java:166)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.fetchWorkSpaces(ArcadiaSparkComputeManager.java:153)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.fetchClusters(ArcadiaSparkComputeManager.java:120)
	at com.microsoft.azure.projectarcadia.common.ArcadiaSparkComputeManager.findCompute(ArcadiaSparkComputeManager.java:219)
	at com.microsoft.azure.projectarcadia.spark.console.ArcadiaSparkScalaLivyConsoleRunConfiguration.checkRunnerSettings(ArcadiaSparkScalaLivyConsoleRunConfiguration.kt:78)
	... 69 more

**Comment by jingyanjingyan** [comment]
In build:

Create a spark on cosmos config, sign out, start livy interactive console, i could get the error below. 
![image](https://user-images.githubusercontent.com/36756024/75522576-47ad3b80-5a45-11ea-8bef-dad19b852d2c.png)

Should we update the warning message like synapse?
![image](https://user-images.githubusercontent.com/36756024/75522710-92c74e80-5a45-11ea-9dd7-a72eef2a713d.png)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738869
