### ISSUE TITLE
[IntelliJ]Device log in get error when VPN is not stable

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#3989]
Build:

Repro Steps:
1. Device log in with VPN that is not stable

Result:
Get error 
```
[Correlation ID: 9c357d63-7898-48e7-97cb-688221ee7114] Execution of class com.microsoft.aad.adal4j.AcquireDeviceCodeCallable failed.

java.net.UnknownHostException: login.microsoftonline.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.microsoft.aad.adal4j.HttpHelper.readResponseFromConnection(HttpHelper.java:77)
	at com.microsoft.aad.adal4j.HttpHelper.getResponse(HttpHelper.java:181)
	at com.microsoft.aad.adal4j.HttpHelper.executeGetRequest(HttpHelper.java:155)
	at com.microsoft.aad.adal4j.HttpHelper.executeHttpGet(HttpHelper.java:49)
	at com.microsoft.aad.adal4j.DeviceCodeRequest.execute(DeviceCodeRequest.java:54)
	at com.microsoft.aad.adal4j.AcquireDeviceCodeCallable.execute(AcquireDeviceCodeCallable.java:42)
	at com.microsoft.aad.adal4j.AcquireDeviceCodeCallable.execute(AcquireDeviceCodeCallable.java:26)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wezhang** [comment]
@Flanker32 , could you help check this? Thanks!

**Comment by andxu** [comment]
It is not possible to login on a machine with login.microsoftonline.com not accessible.

**Comment by andxu** [comment]
Should well handle the error.

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738832
