### ISSUE TITLE
[Intellij.2017.VM]Create VM Error

### ISSUE THREAD

**Issue by jdneo** [microsoft/azure-tools-for-java#400]
Platform: Mac OS 10, Intellij 2017

<img width="720" alt="screen shot 2017-05-10 at 3 44 19 pm" src="https://cloud.githubusercontent.com/assets/6193897/25888152/94ba9ab0-3597-11e7-831f-147d4bdcfee9.png">

I tried to keep some text fields in the last setup page empty(shows above) and click finish, then I got this error dialog:

<img width="723" alt="screen shot 2017-05-10 at 3 38 44 pm" src="https://cloud.githubusercontent.com/assets/6193897/25888018/16f3395c-3597-11e7-9a75-6135ac9b4f42.png">

error log:
java.lang.NullPointerException
	at com.microsoft.azure.management.network.implementation.NicIPConfigurationImpl.subnetToAssociate(NicIPConfigurationImpl.java:286)
	at com.microsoft.azure.management.network.implementation.NicIPConfigurationImpl.ensureConfigurations(NicIPConfigurationImpl.java:247)
	at com.microsoft.azure.management.network.implementation.NetworkInterfaceImpl.beforeCreating(NetworkInterfaceImpl.java:479)
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupableParentResourceImpl.createResourceAsync(GroupableParentResourceImpl.java:52)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreateUpdateTask.executeAsync(CreateUpdateTask.java:56)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroupEntry.executeTaskAsync(TaskGroupEntry.java:77)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeTaskAsync(TaskGroup.java:208)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeReadyTasksAsync(TaskGroup.java:168)
	at com.microsoft.azure.management.resources.fluentcore.dag.TaskGroup.executeAsync(TaskGroup.java:108)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.executeTaskGroupAsyncStreaming(CreatableUpdatableImpl.java:157)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.createAsync(CreatableUpdatableImpl.java:108)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:118)
	at com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl.create(CreatableUpdatableImpl.java:28)
	at com.microsoft.tooling.msservices.helpers.azure.sdk.AzureSDKManager.createVirtualMachine(AzureSDKManager.java:188)
	at com.microsoft.intellij.wizards.createarmvm.SettingsStep$29.run(SettingsStep.java:791)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738852
