### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Access is allowed from event dispatch thread only. java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4018]
Build: azure-toolkit-for-intellij-2019.2.4.develop.11569707.02-24-2020

Repro Steps:
1. Create an HDInsight config with HIB cluster
2. Open config file, when the path refreshing, the error displays

Result:
Error

IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.32.0
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
Access is allowed from event dispatch thread only.

java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorNotImplementedException: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@39ed95f5
Current thread: Thread[RxComputationScheduler-8,6,Idea Thread Group] 2118597396
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2.4#IC-192.7142.36 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.4+10-b304.77 2019.2.4#IC-192.7142.36 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.4+10-b304.77,6,Idea Thread Group] 635754035
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:98)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:283)
	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:226)
	at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:375)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
	at rx.observers.SerializedObserver.onNext(SerializedObserver.java:91)
	at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
	at rx.internal.operators.OperatorDebounceWithTime$DebounceState.emit(OperatorDebounceWithTime.java:132)
	at rx.internal.operators.OperatorDebounceWithTime$1$1.call(OperatorDebounceWithTime.java:79)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@39ed95f5
Current thread: Thread[RxComputationScheduler-8,6,Idea Thread Group] 2118597396
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2.4#IC-192.7142.36 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.4+10-b304.77 2019.2.4#IC-192.7142.36 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.4+10-b304.77,6,Idea Thread Group] 635754035
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1068)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1057)
	at com.microsoft.azure.hdinsight.common.viewmodels.SwingComponentPropertyDelegated.setValue(SwingComponentPropertyDelegated.kt:41)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel.setCheckStatus(SparkSubmissionAdvancedConfigPanel.kt)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel.access$setCheckStatus$p(SparkSubmissionAdvancedConfigPanel.kt:205)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel$6.call(SparkSubmissionAdvancedConfigPanel.kt:225)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel$6.call(SparkSubmissionAdvancedConfigPanel.kt:205)
	at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:96)
	... 20 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: kotlin.Pair.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:188)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:98)
	... 20 more

**Comment by wezhang** [comment]
```
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@39ed95f5
Current thread: Thread[RxComputationScheduler-8,6,Idea Thread Group] 2118597396
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2.4#IC-192.7142.36 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.4+10-b304.77 2019.2.4#IC-192.7142.36 IDEA, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 11.0.4+10-b304.77,6,Idea Thread Group] 635754035
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1068)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1057)
	at com.microsoft.azure.hdinsight.common.viewmodels.SwingComponentPropertyDelegated.setValue(SwingComponentPropertyDelegated.kt:41)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel.setCheckStatus(SparkSubmissionAdvancedConfigPanel.kt)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel.access$setCheckStatus$p(SparkSubmissionAdvancedConfigPanel.kt:205)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel$6.call(SparkSubmissionAdvancedConfigPanel.kt:225)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel$6.call(SparkSubmissionAdvancedConfigPanel.kt:205)

```

**Comment by wezhang** [comment]
Dup #4031
