### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.jetbrains.python.debugger.concurrency.PyConcurrencyExecutor java.lang.StackOverflowError

### ISSUE THREAD

**Issue by mprabhakar2004** [microsoft/azure-tools-for-java#4023]
IntelliJ build version: 2019.3.3 IU-193.6494.35
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1680x937,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.jetbrains.python.debugger.concurrency.PyConcurrencyExecutor, throwable=java.lang.StackOverflowError
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at co

**Comment by wezhang** [comment]
Thanks @mprabhakar2004 ! Could you please share the steps to reproduce?

**Comment by mprabhakar2004** [comment]
Just launch intellij with preloaded project having some python file.

**Comment by wezhang** [comment]
@mprabhakar2004 , Since the exception callstack is filtered, could you help provide the following exception callstack in Report Issues dialog when you hit the issue again? Thanks!

**Comment by mprabhakar2004** [comment]
Sure
