### ISSUE TITLE
[IntelliJ][ReportedByUser] Get IDE Fatal Errors after enabled spark remote debug.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4031]
**IntelliJ build version:** 2019.2.4 IC-192.7142.36
**OS:** Windows 10
**JDK:** JetBrains s.r.o 11.0.4
**Plugin version:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11571266&view=artifacts&type=publishedArtifacts
**Additional Info:** None

**Repro Steps:**

1. Open the Edit Config 
2. Enabled spark remote debug
3. Check the results
![IDE error](https://user-images.githubusercontent.com/40199316/75271570-60e09d00-5837-11ea-8efd-7d2443d530cd.gif)

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1601x860,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=Access is allowed from event dispatch thread only., throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@77c69cc0
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@77c69cc0
	at com.microsoft.azure.hdinsight.common.viewmodels.SwingComponentPropertyDelegated.setValue(SwingComponentPropertyDelegated.kt:41)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigPanel$ViewModel.setCheckS

**Comment by v-lanjli** [comment]
Verified and fixed in this build (https://dev.azure.com/mseng/VSJava/_build/results?buildId=11614583&view=artifacts&type=publishedArtifacts)
Closed this issue.
