### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Services Explorer - Error Refresh resource manage module

### ISSUE THREAD

**Issue by sansemi** [microsoft/azure-tools-for-java#4051]
IntelliJ build version: 2019.3.3 IU-193.6494.35
OS: Windows 7
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.azuretools.utils.AzureModelController.updateSubscriptionMaps(AzureModelController.java:270)
	at com.microsoft.azuretools.core.mvp.model.AzureMvpModel.getResourceGroups(AzureMvpModel.java:128)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.arm.ResourceManagementModulePresenter.onModuleRefresh(ResourceManagementModulePresenter.java:47)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.arm.ResourceManagementModule.refreshItems(ResourceManagementModule.java:61)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:159)
	at com.intellij.openapi.progress.impl.CorePr

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Services - Error Getting Subscriptions (#2226)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
