### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4079]
Build: azure-toolkit-for-intellij-2019.3.develop.11618228.03-02-2020

Repro Steps:
1. Create a HDInsight config
2. Start livy interactive session console from tools menu

Result:
Get error
**Note: Local console result to one warning message and blocks too.**
![image](https://user-images.githubusercontent.com/36756024/75847561-87479f00-5e1a-11ea-8fef-c2896f4e2590.png)

IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.0
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: rx.exceptions.OnCompletedFailedException: The default module needs to be set in the local run tab of Run Configuration
	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:85)
	at rx.internal.operators.OnSubscribeRedo$4$1.onCompleted(OnSubscribeRedo.java:321)
	at rx.internal.operators.OperatorTakeWhile$2.onCompleted(OperatorTakeWhile.java:78)
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 22 more
Caused by: com.intellij.execution.ExecutionException: The default module needs to be set in the local run tab of Run Configuration
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration.getConsoleBuilder(SparkScalaLivyConsoleRunConfiguration.kt:65)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLivyConsoleRunConfiguration.getState(SparkScalaLivyConsoleRunConfiguration.kt:95)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:35)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils$runEnvironmentProfileWithCheckSettings$6.call(RunConfigurationActionUtils.kt:94)
	at rx.internal.util.ActionSubscriber.onCompleted(ActionSubscriber.java:49)
	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
	... 28 more
Caused by: com.intellij.execution.configurations.RuntimeConfigurationError: The default module needs to be set in the local run tab of Run Configuration
	... 36 more

**Comment by v-lanjli** [comment]
Veried and fixed in this build (https://dev.azure.com/mseng/VSJava/_build/results?buildId=11640620&view=artifacts&type=publishedArtifacts)
Closed this issue.
