### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#4081]
IntelliJ build version: 2019.2.4 IC-192.7142.36
OS: Windows 10
JDK: Oracle Corporation 1.8.0_241
Plugin version: 3.33.0
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,9,38,1920x1001,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.lambda$fetchLog$0(SparkJobLogInputStream.java:60)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.fetchLog(SparkJobLogInputStream.java:59)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.available(SparkJobLogInputStream.java:83)
Caused by: java.net.SocketTimeoutException: Read timed out
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:258)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:264)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getBatchSparkJobStatus(SparkBatchSubmissio

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738865
