### ISSUE TITLE
[IntelliJ][ESP] Can't start Livy interactive session.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4091]
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11640620&view=artifacts&type=publishedArtifacts
**IntelliJ Version:**: 192/193
**OS:** Win/Mac/Linux

**Repro Steps:**

1. Create a HDInsight Configration
2. Start livy interactive session console from tools menu

**Results:** Can't start Livy interactive session.

**Message:**
Can't start Livy interactive session: com.microsoft.azure.hdinsight.sdk.common.livy.interactive.exceptions.SessionNotStartException: Session HIBtest193 >> Spark Livy Interactive Session Console(Scala) is SHUTTING_DOWN. 20/03/05 12:48:51 INFO RequestHedgingRMFailoverProxyProvider: Looking for the active RM in [rm1, rm2]... ; 20/03/05 12:48:51 INFO RequestHedgingRMFailoverProxyProvider: Found active RM [rm1] ; 20/03/05 12:48:51 INFO Client: Requesting a new application from cluster with 2 NodeManagers ; 20/03/05 12:48:51 INFO Configuration: found resource resource-types.xml at file:/etc/hadoop/3.1.2.2-1/0/resource-types.xml ; 20/03/05 12:48:51 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (51200 MB per container) ; 20/03/05 12:48:51 INFO Client: Will allocate AM container, with 4480 MB memory including 384 MB overhead ; 20/03/05 12:48:51 INFO Client: Setting up container launch context for our AM ; 20/03/05 12:48:51 INFO Client: Setting up the launch environment for our AM container ; 20/03/05 12:48:51 INFO Client: Preparing resources for our AM container ; 
YARN Diagnostics:  ; 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730) ; 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:150) ; 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195) ; 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86) ; 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:937) ; 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:946) ; 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) ; 20/03/05 12:48:52 INFO ShutdownHookManager: Shutdown hook called ; 20/03/05 12:48:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-19ddf90c-7e7e-44ba-919d-5d4361cfd53d ; 
YARN Diagnostics: 

![image](https://user-images.githubusercontent.com/40199316/75983443-88b0be80-5f23-11ea-84f9-c22eb77f94c0.png)

**Comment by v-lanjli** [comment]
Use this cluster (zhwe04hib) to verified and fixed this issue.
