### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor java.lang.StackOverflowError

### ISSUE THREAD

**Issue by wangmiao1981** [microsoft/azure-tools-for-java#4099]
IntelliJ build version: 2019.3.3 IU-193.6494.35
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1604x911,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:319)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at co

**Comment by wezhang** [comment]
Dup #4023
