### ISSUE TITLE
After importing publish setting file getting exception on MAC.

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#41]
Steps:
1. Updated IntelliJ on MAC
2. Installed Azure tool kit plugin.
3. Import publish settings file in Azure Explorer.
4. Selected one of the subscription (un-selected everything else).
5. Got following exception, IntelliJ is asking that whether I should disable plugin.

I am not signed in Azure Explorer yet. Clicking on manage subscription brings back the dialog for choosing subscription. Closing the dialog does nothing.
 Below is the exception content.

Timed out while waiting for cloud services, please try again
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.microsoftopentechnologies.azurecommons.deploy.tasks.LoadingHostedServicesTask.call(LoadingHostedServicesTask.java:68)
	at com.microsoftopentechnologies.azurecommons.deploy.tasks.LoadingHostedServicesTask.call(LoadingHostedServicesTask.java:38)
	at com.microsoftopentechnologies.azurecommons.deploy.tasks.LoadingTask.doTask(LoadingTask.java:58)
	at com.microsoftopentechnologies.azurecommons.deploy.tasks.LoadingTask.run(LoadingTask.java:69)
	at com.microsoftopentechnologies.azurecommons.deploy.tasks.LoadingTaskRunner.run(LoadingTaskRunner.java:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martinsawicki** [comment]
publish settings support is getting removed

**Comment by lenala** [comment]
This functionality was removed for the new release.
