### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by jaxongir** [microsoft/azure-tools-for-java#4101]
IntelliJ build version: 2019.3.3 IU-193.6494.35
OS: Linux
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.0-2019.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: ca5d8060-af4b-494c-b8dd-c719e0960b01\r\nCorrelation ID: 0ec00fd0-15a8-47a9-8c19-264a9d445487\r\nTimestamp: 2020-03-10 10:06:04Z","error_codes":[90002],"timestamp":"2020-03-10 10:06:04Z","trace_id":"ca5d8060-af4b-494c-b8dd-c719e0960b01","correlation_id":"0ec00fd0-15a8-47a9-8c19-264a9d445487","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1847)
	at com.microsoft.azure.management.resources.fluentcore.

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  MS Azure Explorer - Error Loading Web Apps (#3653)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant.
