### ISSUE TITLE
[IntelliJ][2020.1 EAP]Creating project with bundle build failed

### ISSUE THREAD

**Issue by v-xiaocw** [microsoft/azure-tools-for-java#4105]
Build: ideaIC-bundle-win-x64-LATEST-EAP-SNAPSHOT.develop.11679560.03-11-2020
Repro Steps:
1.Download, unzip and run bundle build
2.Click the button: Create new project

Result: Can't create project
```
2020-03-11 00:02:56,698 [   5529]  ERROR - tellij.psi.stubs.StubIndexImpl - IntelliJ IDEA 2020.1 EAP  Build #IC-201.6073.9
2020-03-11 00:02:56,699 [   5530]  ERROR - tellij.psi.stubs.StubIndexImpl - JDK: 1.8.0_221; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation
2020-03-11 00:02:56,716 [   5547]  ERROR - tellij.psi.stubs.StubIndexImpl - OS: Windows 10
2020-03-11 00:02:56,716 [   5547]  ERROR - tellij.psi.stubs.StubIndexImpl - Last Action:
2020-03-11 00:03:21,935 [  30766]  ERROR - llij.ide.plugins.PluginManager - null
java.lang.ExceptionInInitializerError
        at org.jetbrains.bsp.project.BspSyntheticModuleType.<init>(bspModuleType.scala:10)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.intellij.util.pico.InstantiatingComponentAdapter.newInstance(CachingConstructorInjectionComponentAdapter.java:294)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:103)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:97)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiateClass(AbstractExtensionPointBean.java:92)
        at com.intellij.openapi.module.ModuleTypeEP.getModuleType(ModuleTypeEP.java:47)
        at com.intellij.openapi.module.impl.ModuleTypeManagerImpl.getRegisteredTypes(ModuleTypeManagerImpl.java:47)
        at com.intellij.ide.util.projectWizard.ModuleBuilder.getAllBuilders(ModuleBuilder.java:63)
        at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:251)
        at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:103)
        at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:51)
        at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:40)
        at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:21)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:443)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:428)
        at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:46)
        at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:143)
        at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:55)
        at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:331)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
        at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.diagnostic.PluginException: While loading class org.jetbrains.bsp.BspBundle: org/jetbrains/bsp/BspBundle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: org.intellij.scala]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
        at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.jetbrains.bsp.project.BspSyntheticModuleType$.<init>(bspModuleType.scala:21)
        at org.jetbrains.bsp.project.BspSyntheticModuleType$.<clinit>(bspModuleType.scala)
        ... 66 more
Caused by: java.lang.UnsupportedClassVersionError: org/jetbrains/bsp/BspBundle has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
        at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
        at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
        ... 71 more
2020-03-11 00:03:21,936 [  30767]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1 EAP  Build #IC-201.6073.9
2020-03-11 00:03:21,940 [  30771]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_221; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation
2020-03-11 00:03:21,940 [  30771]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10
2020-03-11 00:03:21,941 [  30772]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Scala version: 2020.1.12
2020-03-11 00:03:21,941 [  30772]  ERROR - llij.ide.plugins.PluginManager - Last Action: WelcomeScreen.CreateNewProject
2020-03-11 00:04:41,391 [ 110222]  ERROR - llij.ide.plugins.PluginManager - Could not initialize class org.jetbrains.bsp.project.BspSyntheticModuleType$
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.bsp.project.BspSyntheticModuleType$
        at org.jetbrains.bsp.project.BspSyntheticModuleType.<init>(bspModuleType.scala:10)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.intellij.util.pico.InstantiatingComponentAdapter.newInstance(CachingConstructorInjectionComponentAdapter.java:294)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:103)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:97)
        at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiateClass(AbstractExtensionPointBean.java:92)
        at com.intellij.openapi.module.ModuleTypeEP.getModuleType(ModuleTypeEP.java:47)
        at com.intellij.openapi.module.impl.ModuleTypeManagerImpl.getRegisteredTypes(ModuleTypeManagerImpl.java:47)
        at com.intellij.ide.util.projectWizard.ModuleBuilder.getAllBuilders(ModuleBuilder.java:63)
        at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:251)
        at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:103)
        at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:51)
        at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:40)
        at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:21)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:443)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:428)
        at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:46)
        at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:143)
        at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:55)
        at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:331)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
        at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2020-03-11 00:04:41,392 [ 110223]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1 EAP  Build #IC-201.6073.9
2020-03-11 00:04:41,397 [ 110228]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_221; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation
2020-03-11 00:04:41,397 [ 110228]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10
2020-03-11 00:04:41,398 [ 110229]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Scala version: 2020.1.12
2020-03-11 00:04:41,398 [ 110229]  ERROR - llij.ide.plugins.PluginManager - Last Action: WelcomeScreen.CreateNewProject

```

**Comment by t-rufang** [comment]
Fixed in #4265

**Comment by t-rufang** [comment]
@v-xiaocw Could you help help verify the fix?

**Comment by v-xiaocw** [comment]
Verified and Fixed in  build ideaIC-bundle-win-x64-LATEST-EAP-SNAPSHOT.develop.12182746.05-21-2020 @t-rufang  Thanks a lot!
