### ISSUE TITLE
[IntelliJ][2020.1 EAP] This error "Error running: unknown error" will show every second time of submit job.

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4106]
**IntelliJ Version:** IntelliJ 2020.1 EAP
**Build:** https://dev.azure.com/mseng/VSJava/_build/results?buildId=11679560&view=artifacts&type=publishedArtifacts

**Repro Step:**

1. Create a application. (Spark on Cosmos/Spark on HDInsight)
2. Submit this job

**Results:** 
1. Error running: unknown error
![image](https://user-images.githubusercontent.com/40199316/76392841-55e84980-63ad-11ea-915c-c066a1299230.png)
![image](https://user-images.githubusercontent.com/40199316/76440426-cec0c300-63f8-11ea-800d-20db2a7e20bd.png)

2. After displaying this error, clicking the stop button has no effect.
![Clicking the stop button does not work](https://user-images.githubusercontent.com/40199316/76442850-7b507400-63fc-11ea-9984-ece21626c081.gif)

**Logs:**
```
2020-03-25 16:09:06,356 [9742966]   INFO - .ScalaCompilerReferenceService - [compiler indices] onCompilationStart. active indexing phases: 1 
2020-03-25 16:09:06,823 [9743433]   INFO - .ScalaCompilerReferenceService - [compiler indices] startIndexing. clean build: false 
2020-03-25 16:09:10,151 [9746761]   INFO - .ScalaCompilerReferenceService - [compiler indices] finishIndexing. 
2020-03-25 16:09:10,273 [9746883]   INFO - lij.compiler.impl.CompilerUtil - 	COMPILATION FINISHED (BUILD PROCESS); Errors: 0; warnings: 0 took 9488 ms: 0 min 9sec 
2020-03-25 16:09:10,274 [9746884]   INFO - .ScalaCompilerReferenceService - [compiler indices] startIndexing. clean build: false 
2020-03-25 16:09:10,338 [9746948]   INFO - s.CompilerReferenceServiceBase - backward reference index reader is opened 
2020-03-25 16:09:10,477 [9747087]   WARN - xecution.runners.ExecutionUtil - Execution error without description 
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.ui.SparkJobLogConsoleView$1.getFirstComponent(SparkJobLogConsoleView.java:106)
	at java.desktop/javax.swing.SortingFocusTraversalPolicy.getDefaultComponent(SortingFocusTraversalPolicy.java:571)
	at com.intellij.ui.content.impl.ContentImpl.getPreferredFocusableComponent(ContentImpl.java:92)
	at com.intellij.execution.ui.layout.impl.GridImpl$Placeholder$1.getContent(GridImpl.java:242)
	at com.intellij.execution.ui.layout.impl.GridImpl$Placeholder$1.getDefaultComponent(GridImpl.java:222)
	at com.intellij.openapi.wm.ex.IdeFocusTraversalPolicy.getPreferredFocusedComponent(IdeFocusTraversalPolicy.java:104)
	at com.intellij.openapi.wm.ex.IdeFocusTraversalPolicy.getPreferredFocusedComponent(IdeFocusTraversalPolicy.java:128)
	at com.intellij.openapi.wm.ex.IdeFocusTraversalPolicy.getPreferredFocusedComponent(IdeFocusTraversalPolicy.java:128)
	at com.intellij.openapi.wm.ex.IdeFocusTraversalPolicy.getPreferredFocusedComponent(IdeFocusTraversalPolicy.java:72)
	at com.intellij.openapi.wm.ex.IdeFocusTraversalPolicy.getPreferredFocusedComponent(IdeFocusTraversalPolicy.java:28)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.getFocusTargetFor(FocusManagerImpl.java:387)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.getFocusTargetFor(IdeFocusManagerImpl.java:31)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getToFocus(JBTabsImpl.java:936)
	at com.intellij.ui.tabs.impl.JBTabsImpl.requestFocusInWindow(JBTabsImpl.java:958)
	at java.desktop/java.awt.Component.removeNotify(Component.java:7222)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2847)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4809)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeNotify(JBTabsImpl.java:717)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4809)
	at com.intellij.execution.ui.layout.impl.RunnerContentUi$MyComponent.removeNotify(RunnerContentUi.java:1559)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4809)
	at java.desktop/java.awt.Container.removeAll(Container.java:1322)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.ensureSelectedContentVisible(ToolWindowContentUi.java:210)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.access$400(ToolWindowContentUi.java:46)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1.selectionChanged(ToolWindowContentUi.java:120)
	at jdk.internal.reflect.GeneratedMethodAccessor294.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy94.selectionChanged(Unknown Source)
	at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:579)
	at com.intellij.ui.content.impl.ContentManagerImpl.removeFromSelection(ContentManagerImpl.java:416)
	at com.intellij.ui.content.impl.ContentManagerImpl$1.run(ContentManagerImpl.java:484)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:503)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:454)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:443)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:521)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:526)
	at com.intellij.execution.ui.RunContentManagerImpl.showRunContent(RunContentManagerImpl.kt:278)
	at com.intellij.execution.ui.RunContentManagerImpl.showRunContent(RunContentManagerImpl.kt:343)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2$1.run(ExecutionManagerImpl.kt:220)
	at com.intellij.ui.AppUIUtil.invokeLaterIfProjectAlive(AppUIUtil.java:195)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2.accept(ExecutionManagerImpl.kt:210)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2.accept(ExecutionManagerImpl.kt:60)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:348)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:317)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:209)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:832)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:311)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:832)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by wezhang** [comment]
@v-lanjli , could you help to repro it? Thanks!

**Comment by v-lanjli** [comment]
#4179 same issue.

**Comment by t-rufang** [comment]
Duplicate with #4179
