### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by eliasalabssie** [microsoft/azure-tools-for-java#4122]
IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.1-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1367x728,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.lang.Error: The process has been terminated
	at com.microsoft.intellij.runner.RunProcessHandler.println(RunProcessHandler.java:86)
	at com.microsoft.intellij.runner.RunProcessHandler.setText(RunProcessHandler.java:120)
	at com.microsoft.azuretools.utils.WebAppUtils.deployWebAppToWebContainer(WebAppUtils.java:383)
	at com.microso

**Comment by eliasalabssie** [comment]
This is a spring boot web application and I am trying to deploy it from intellige idea using azure toolkit, but after trying for long period of time,  it is giving me this error and i don't know what is going on. I had deployed web app with the same procedure but doesn't work this time.  I will appreciate any help

**Comment by eliasalabssie** [comment]
I solved my issues
