### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 1a869a49-81f8-42bd-8ba4-f65ecc9fd6c8] Execution of class com.microsoft.aad.adal4j.AcquireDeviceCodeCallable failed. javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by ssanbeg** [microsoft/azure-tools-for-java#4127]
IntelliJ build version: 2019.3.3 IU-193.6494.35
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.1-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1440x855,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 1a869a49-81f8-42bd-8ba4-f65ecc9fd6c8] Execution of class com.microsoft.aad.adal4j.AcquireDeviceCodeCallable failed., throwable=javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at com.microsoft.aad.adal4j.HttpHelper.readResponseFromConnection(HttpHelper.java:77)
	at com.microsoft.aad.adal4j.HttpHelper.getResponse(HttpHelper.java:181)
	at com.microsoft.aad.adal4j.HttpHelper.executeGetRequest(HttpHelper.java:155)
	at c

**Comment by Flanker32** [comment]
@ssanbeg Thanks a lot for your report and really sorry for the late reply, could you please share a bit more information like how this issue occurs and is there any way to reproduce this issue?

**Comment by mlabisi** [comment]
Hi @Flanker32, I know this issue has been closed, but I'm getting this error while trying to sign in to the Azure Toolkit for Rider on Windows! I shared a screenshot of the error I got in an open issue. https://github.com/JetBrains/azure-tools-for-intellij/issues/332#issuecomment-665958536
