### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NoSuchMethodError: 'java.lang.String com.microsoft.azure.management.storage.SkuName.name()'

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4134]
IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.1
https://dev.azure.com/mseng/VSJava/_build/results?buildId=11721960&view=artifacts&type=publishedArtifacts
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1601x860,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NoSuchMethodError: 'java.lang.String com.microsoft.azure.management.storage.SkuName.name()'
	at com.microsoft.azure.docker.ops.utils.AzureDockerUtils.getStorageAccounts(AzureDockerUtils.java:258)
	at com.microsoft.azure.docker.ops.utils.AzureDockerUtils.refreshDockerStorageAccountDetails(AzureDockerUtils.java:474)
	at com.microsoft.azure.docker.AzureDockerHostsManager.refreshDockerStorageAccountDetails(AzureDockerHostsManager.java:222)
	at com.microsoft.azure.docker.AzureDockerHostsManager.forceRefreshSubscriptions(AzureDockerHostsManager.java:283)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostModule.refreshFromAzure(DockerHostModule.java:108)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run

**Comment by Flanker32** [comment]
Fixed in #4161
