### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception get applications list error com.microsoft.azure.hdinsight.sdk.common.HDIException: Bad Gateway

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4135]
IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.33.1
https://dev.azure.com/mseng/VSJava/_build/results?buildId=11721960&view=artifacts&type=publishedArtifacts
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1601x860,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=get applications list error, throwable=com.microsoft.azure.hdinsight.sdk.common.HDIException: Bad Gateway
	at com.microsoft.azure.hdinsight.spark.jobs.JobUtils.getEntity(JobUtils.java:445)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkRestEntity(SparkRestUtil.java:148)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkRestUtil.getSparkApplications(SparkRestUtil.java:58)
	at com.microsoft.azure.hdinsight.spark.jobs.SparkJobHttpHandler.handle(SparkJobHttpHandler.java:54)
```

**Comment by wezhang** [comment]
Backend issue
