### ISSUE TITLE
Create webapp with Win, it will become unresponsive

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4158]
#### Environment
```
OS: Mac & Win
Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IC2019.3.4-jre11 & IU 2019.3.3 - jre8
```

#### Repro steps
1. Right click your webapp to select Azure
2. Select Deploy to Azure and create new webapp with windows os
when your click OK, it will no responding with error
![image](https://user-images.githubusercontent.com/44559777/77064058-b31d7400-6a19-11ea-885d-057c4642898f.png)
java.lang.NoSuchMethodError: 'com.microsoft.azure.management.appservice.WebApp$DefinitionStages$WithCreate com.microsoft.azure.management.appservice.WebApp$DefinitionStages$WithNewAppServicePlan.withNewWindowsPlan(com.microsoft.azure.management.resources.fluentcore.model.Creatable)'
    at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.withCreateNewWindowsServicePlan(AzureWebAppMvpModel.java:217)
    at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.createWebAppOnWindows(AzureWebAppMvpModel.java:144)
    at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.createWebApp(AzureWebAppMvpModel.java:97)
    at com.microsoft.intellij.runner.webapp.webappconfig.slimui.creation.WebAppCreationDialog$7.lambda$run$1(WebAppCreationDialog.java:447)
    at com.microsoft.azuretools.telemetrywrapper.EventUtil.executeWithLog(EventUtil.java:121)
    at com.microsoft.intellij.runner.webapp.webappconfig.slimui.creation.WebAppCreationDialog$7.run(WebAppCreationDialog.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
    at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
    at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)

#### NOTE:
- If you create webapp with Linux OS
During creation, if you click `Cancel` button, the `Cancel `button doesn't work,
![image](https://user-images.githubusercontent.com/44559777/77064243-1b6c5580-6a1a-11ea-99e7-a2ba4ef1dde8.png)
and 
- add new function whether it is Win or Linux, the `Cancel` button doesn't work too.

**Comment by Flanker32** [comment]
Fixed in #4161
