### ISSUE TITLE
DockHost can not be refreshing

### ISSUE THREAD

**Issue by EricZhangzf** [microsoft/azure-tools-for-java#4159]
#### Environment
```
OS: Mac & Win
Plugins Version : Azure java toolkit for IntelliJ: 3.34.0
IDE Version: IC2019.3.4-jre11 & IU 2019.3.3-jre8
```

#### Repro steps
Refreshing DockHost will no responding.

#### Result
![image](https://user-images.githubusercontent.com/44559777/77064568-abaa9a80-6a1a-11ea-901f-5ac9491abb71.png)
java.lang.NoSuchMethodError: 'java.lang.String com.microsoft.azure.management.storage.SkuName.name()'
    at com.microsoft.azure.docker.ops.utils.AzureDockerUtils.getStorageAccounts(AzureDockerUtils.java:258)
    at com.microsoft.azure.docker.ops.utils.AzureDockerUtils.refreshDockerStorageAccountDetails(AzureDockerUtils.java:474)
    at com.microsoft.azure.docker.AzureDockerHostsManager.refreshDockerStorageAccountDetails(AzureDockerHostsManager.java:222)
    at com.microsoft.azure.docker.AzureDockerHostsManager.forceRefreshSubscriptions(AzureDockerHostsManager.java:283)
    at com.microsoft.tooling.msservices.serviceexplorer.azure.docker.DockerHostModule.refreshFromAzure(DockerHostModule.java:108)
    at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:92)
    at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:160)
    at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:159)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by EricZhangzf** [comment]
Test Pass
