### ISSUE TITLE
[Intellij] UI Frozen when switching to Azure Explorer tool window

### ISSUE THREAD

**Issue by wezhang** [microsoft/azure-tools-for-java#4172]
Thread dump files attached:

[threadDump-20200324-093123.txt](https://github.com/microsoft/azure-tools-for-java/files/4372663/threadDump-20200324-093123.txt)
[threadDump-20200324-093118.txt](https://github.com/microsoft/azure-tools-for-java/files/4372664/threadDump-20200324-093118.txt)

Here is the root cause, AccessTokenAzureManager.getTenants blocking in Event Dispatch Thread:
```
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	at rx.observables.BlockingObservable.singleOrDefault(BlockingObservable.java:372)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getTenants(AccessTokenAzureManager.java:182)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getSubscriptionsWithTenant(AccessTokenAzureManager.java:145)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(SubscriptionManagerPersist.java:78)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:91)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:114)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.<init>(AzureModule.java:85)
	at com.microsoft.intellij.serviceexplorer.azure.AzureModuleImpl.<init>(AzureModuleImpl.java:29)
	at com.microsoft.intellij.components.ServerExplorerToolWindowFactory.createToolWindowContent(ServerExplorerToolWindowFactory.java:91)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:534)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:358)
	at com.intellij.ide.actions.ResizeToolWindowAction.<init>(ResizeToolWindowAction.java:45)
	at com.intellij.ide.actions.ResizeToolWindowAction$Left.<init>(ResizeToolWindowAction.java:197)
```

**Comment by andxu** [comment]
Thank @wezhang  for the info, we will fix it

**Comment by andxu** [comment]
@wezhang I cannot reproduce this issue, please comment here if you still encounter this issue.

**Comment by wezhang** [comment]
I can still repro it from rerun IntelliJ IDEA with signed in. Refer to the snapshot:

![issue-4172](https://user-images.githubusercontent.com/7385667/84491174-b81b5800-acd6-11ea-91d5-72f7c864ce07.gif)

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738831
