### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Function App(Preview)

### ISSUE THREAD

**Issue by Lamisi** [microsoft/azure-tools-for-java#4218]
IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.34.0-2019.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1840)
	at com.microsoft.azuretools.core.mvp.model.function.AzureFunctionMvpModel.listFunctionsInSubscription(AzureFunctionMvpModel.java:181)
	at com.microsoft.azuretools.core.mvp.model.function.AzureFunctionMvpModel.lambda$null$0(AzureFunctionMvpModel.java:126)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Schedule

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Refresh then sign out, pops error dialogs (#1643)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: com.microsoft.azuretools.adauth.AuthException: unknown_user
