### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Function App(Preview)

### ISSUE THREAD

**Issue by mike-mwangi** [microsoft/azure-tools-for-java#4243]
IntelliJ build version: 2019.3.4 IU-193.6911.18
OS: Linux
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.34.0-2019.3
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'a46229c7-21d1-417d-a1cb-1857a07d2765' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: f9978d85-01e2-4c69-acaa-f7416ce80e00\r\nCorrelation ID: 98fac8f2-986f-4807-becf-6b0e387f0187\r\nTimestamp: 2020-04-07 10:53:27Z","error_codes":[90002],"timestamp":"2020-04-07 10:53:27Z","trace_id":"f9978d85-01e2-4c69-acaa-f7416ce80e00","correlation_id":"98fac8f2-986f-4807-becf-6b0e387f0187","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1840)
	at

**Comment by andxu** [comment]
Dup as https://github.com/microsoft/azure-tools-for-java/issues/4245
