### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Plugin for IntelliJ Error pop up when submit job to Spark on Cosmos

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4268]
IntelliJ build version: 2020.1 IC-201.6668.60
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: https://dev.azure.com/mseng/VSJava/_build/results?buildId=11874541&view=artifacts&type=publishedArtifacts

![Azure Plugin for IntelliJ Error](https://user-images.githubusercontent.com/40199316/78858913-546b7900-7a60-11ea-9139-747a40bac631.gif)
using this clusster~
![image](https://user-images.githubusercontent.com/40199316/78859871-4408cd80-7a63-11ea-8729-e8f47b572618.png)

Error message: 
```
org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.createBatchSparkJob(SparkBatchSubmission.java:335)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.createBatchJob(SparkBatchJob.java:396)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$submit$38(SparkBatchJob.java:1111)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
- [Spark on ADL] Submit fail (#1957)

**Comment by wezhang** [comment]
A transient backend issue.
