### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by AdalWay** [microsoft/azure-tools-for-java#4318]
IntelliJ build version: 2020.1 IU-201.6668.121
OS: Linux
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.35.0-2020.1
Error message: 
```
com.microsoft.azure.CloudException: Status code 400, {"error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.Cache'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web'."}}: The operation is not permitted for namespace 'Microsoft.Cache'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build

**Comment by Flanker32** [comment]
@AdalWay Thanks for your report and really sorry for the late response, could you please share a bit more information like how this issue occurs and is there any stable way to reproduce this issue?
