### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.BootstrapMethodError: bootstrap method initialization exception

### ISSUE THREAD

**Issue by v-lanjli** [microsoft/azure-tools-for-java#4327]
**IntelliJ build version:** 2020.1/2019.3
**OS:** Mac/Win
**JDK:** JetBrains s.r.o 11.0.6
**Plugin version:** Market Build
**Additional Info:** None
**Repro Steps:**

1. Open IntelliJ and sign in to Azure
2. Expand Apache Spark on Cosmos node

![Uncaught Exception](https://user-images.githubusercontent.com/40199316/79965844-20ac3c80-84bf-11ea-914f-65b10c52eaf3.gif)

**Parent component:** 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1280x691,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
**Error message:** 
```
IdeaLoggingEvent[message=null, throwable=java.lang.BootstrapMethodError: bootstrap method initialization exception
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog.isAllFieldsLegal(CosmosSparkProvisionDialog.java:309)
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog.access$100(CosmosSparkProvisionDialog.java:67)
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog$2.textChanged(CosmosSparkProvisionDialog.java:180)
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog.lambda$setData$5(CosmosSparkProvisionDialog.java:237)
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog.setData(CosmosSparkProvisionDialog.java:233)
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog.setData(CosmosSparkProvisionDialog.java:67)
	at com.microsoft.azure.cosmosspark.serverexplore.ui.CosmosSparkProvisionDialog$3.

**Comment by t-rufang** [comment]
@v-lanjli This should already be fixed with the latest develop branch, could you help verify it?
