### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by pandkai** [microsoft/azure-tools-for-java#4366]
IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.36.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1787x959,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.io.IOException: Cannot run program "func" (in directory "/Users/kaipande/IdeaProjects/azure-function-examples/target/azure-functions/azure-function-examples-1589100925288"): error=2, No such file or directory
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:120)

**Comment by Flanker32** [comment]
@pandkai Thanks for your report and sorry for the late reply, could you please help us check whether `/Users/kaipande/IdeaProjects/azure-function-examples/target/azure-functions/azure-function-examples-1589100925288` exist in your local machine? And could you please share the function core tools version? So that we could know whether its an compile issue or func issue.

**Comment by Flanker32** [comment]
#Duplicated with #4384
