### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file.

### ISSUE THREAD

**Issue by jayarajjg** [microsoft/azure-tools-for-java#4374]
IntelliJ build version: 2019.2.1 IU-192.6262.58
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.3
Plugin version: 3.25.0-2019.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,22,933x494,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
	at com.microsoft.azuretools.azurecommons.util.ParserXMLUtility.parseXMLFile(ParserXMLUtility.java:68)
	at com.microsoft.intellij.AzurePlugin.setValues(AzurePlugin.java:252)
	at com.microsoft.intellij.AzurePlugin.initializeTelemetry(AzurePlugin.java:160)
	at com.microsoft.intellij.AzurePlugin.initComponent(AzurePlugin.java:140)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
	at

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception Error org.xml.sax.SAXParseException; Premature end of file. (#2525)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate error: throwable=org.xml.sax.SAXParseException; Premature end of file.
