### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by AdalWay** [microsoft/azure-tools-for-java#4395]
IntelliJ build version: 2020.1.1 IU-201.7223.91
OS: Linux
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.36.0-2020.1
Error message: 
```
com.microsoft.azure.CloudException: Status code 400, {"error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.Cache'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web'."}}: The operation is not permitted for namespace 'Microsoft.Cache'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,microsoft.support,microsoft.visualstudio,Microsoft.Web'.
	at jdk.internal.reflect.GeneratedConstructorAccessor1511.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
	at com.microsoft.azure.management.redis.implementation.RedisInner.listDelegate(RedisInner.java

**Comment by Flanker32** [comment]
@AdalWay Thanks a lot for your report, could this issue be stable reproduced? and could you please provides a bit more information like your authentication method?

**Comment by Flanker32** [comment]
Duplicated with #4318
