### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception onEditDockerHostAction com.microsoft.azure.docker.model.AzureDockerException: Async operation failed with provisioning state: Failed

### ISSUE THREAD

**Issue by finblok** [microsoft/azure-tools-for-java#4396]
IntelliJ build version: 2019.1.3 IU-191.7479.19
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.28.0-2019.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,30,1187x698,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=onEditDockerHostAction, throwable=com.microsoft.azure.docker.model.AzureDockerException: Async operation failed with provisioning state: Failed
	at com.microsoft.azure.docker.ops.AzureDockerVMOps.updateDockerHostVM(AzureDockerVMOps.java:84)
	at com.microsoft.intellij.docker.utils.AzureDockerUIResources$4.run(AzureDockerUIResources.java:396)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:158)
Caused by: com.microsoft.azure.CloudException: Async operation failed with provisioning state: Failed: Could not resolve storage account 'rgabikodemodiag'. Please ensure it was created through the Storage Resource Provider in the same location as the compute resource.
	at com.microsoft.azure.PollingState.throwCloudExceptionIfInFailedState(PollingState.java:541)
	at

**Comment by Flanker32** [comment]
@finblok Thanks for your report, could you please share how this issue occurs and could it be reproduced?
