### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by juliocarismendi** [microsoft/azure-tools-for-java#4413]
IntelliJ build version: 2020.1.1 IU-201.7223.91
OS: Linux
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.36.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1920x1043,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkConsoleActionDelegate.actionPerformed(RunSparkConsoleActionDelegate.kt:59)
	at com.microsoft.azure.hdinsight.spark.run.action.SeqActions.onActionPerformed(SeqActions.kt:35)
	at com.microsoft.azuretools.ijidea.utility.AzureAnAction.actionPerformed(AzureAnAction.java:75)
Caused by: com.intellij.diagnostic.PluginException: While loading class com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfiguration: Cannot inherit from final class [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfigurationFactory.createTemplateConfiguration(SparkScalaLocalConsoleRunConfigurationFactory.kt:35)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfigur

**Comment by wezhang** [comment]
Repro at org.intellij.scala:2020.1.36

**Comment by jingyanjingyan** [comment]
Repro with azure-toolkit-for-intellij-2020.1.develop.12240382.05-29-2020.zip + Scala 2020.1.36

**Comment by t-rufang** [comment]
@jingyanjingyan Can you try the build in the latest [bug fix PR](https://dev.azure.com/mseng/VSJava/_build/results?buildId=12312377&view=artifacts&type=publishedArtifacts)?

**Comment by jingyanjingyan** [comment]
Fix in the private build, close
