### ISSUE TITLE
Cannot docker run

### ISSUE THREAD

**Issue by pl07** [microsoft/azure-tools-for-java#4417]
#### Environment:
OS: Win
Plugins Version: Azure java toolkit for IntelliJ: 3.37.0
IDE Version: IU2019.3-jre11
#### Repro steps:
1. Right click your project select Azure > Docker run
#### Result:
![image](https://user-images.githubusercontent.com/46642771/83216311-8ca75200-a19b-11ea-90f4-d73bb77757c9.png)
Error logs:
```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableList com.spotify.docker.client.messages.Container.ports()'
	at com.microsoft.intellij.runner.container.dockerhost.DockerHostRunState.executeSteps(DockerHostRunState.java:151)
	at com.microsoft.intellij.runner.container.dockerhost.DockerHostRunState.executeSteps(DockerHostRunState.java:55)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:70)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
```

#### Expected:
![image](https://user-images.githubusercontent.com/46642771/83216127-1acf0880-a19b-11ea-9f4b-365fe91dce5d.png)

**Comment by pl07** [comment]
Test pass
