### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor java.lang.StackOverflowError

### ISSUE THREAD

**Issue by sofiealberius** [microsoft/azure-tools-for-java#4425]
IntelliJ build version: 2019.3.2 IU-193.6015.39
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,2048x1107,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError
	at com.intellij.execution.ExecutorRegistryImpl.initExecutor(ExecutorRegistryImpl.java:89)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecu... (#4005)

**Comment by vscjavaci** [comment]
(Experimental duplicate detection)
Thanks for submitting this issue. Please check if it is already covered by an existing one:
-  Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecu... (#3961)

**Comment by vscjavaci** [comment]
Close this issue due to duplicate, error: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError

**Comment by vscjavaci** [comment]
Close this issue due to duplicate, error: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError
