### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: Not signed in. Can't send out the request.

### ISSUE THREAD

**Issue by jingyanjingyan** [microsoft/azure-tools-for-java#4432]
IntelliJ build version: 2019.3.4 IC-193.6911.18
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.37.0
Additional Info: None

Repro Steps:
1. Sign in with microsoft account
2. Double click on Azure Spark on Azure Synapse

Result:
Error

Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1441x819,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: Not signed in. Can't send out the request.
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.singleOrDefault(BlockingObservable.java:372)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.lambda$fetchLog$0(SparkJobLogInputStream.java:60)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.fetchLog(SparkJobLogInputStream.java:59)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.available(SparkJobLogInputStream.java:83)
	at java.base/sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:363)
	at java.base/sun.nio.cs.StreamDecoder.implReady(StreamDecoder.java:371)
	at java.base/sun.nio.cs.StreamDecoder.ready(StreamDecoder.java:185)
	at java.base/java.io.InputStreamReader.ready(InputStreamReader.java:196)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:102)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:67)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:160)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.azuretools.adauth.AuthException: Not signed in. Can't send out the request.
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchEspMfaSubmission.getAccessToken(SparkBatchEspMfaSubmission.java:52)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchEspMfaSubmission.getHttpClient(SparkBatchEspMfaSubmission.java:64)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:259)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getBatchSparkJobStatus(SparkBatchSubmission.java:343)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJob.lambda$getSparkJobApplicationIdObservable$11(SparkBatchJob.java:650)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
	... 19 more

**Comment by jingyanjingyan** [comment]
transient issue, not repro now
