### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-tools-for-java#4445]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.37.0-2020.1
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesInner.listByResourceGroup(RegistriesInner.java:995)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesImpl$1.listNextGroup(RegistriesImpl.java:58)
	at com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupPagedList.nextPage(GroupPagedList.java:41)
	at com.microsoft.azure.PagedList.cachePage(PagedList.java:62)
	at com.microsoft.azure.PagedList.loadNextPage(PagedList.java:104)
	at com.microsoft.azure.PagedList$ListItr.next(PagedList.java:172)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listRegistryBySubscriptionId(ContainerRegistryMvpModel.java:87)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listContainerRegistries(ContainerRegistryMvpModel.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModu

**Comment by andxu** [comment]
Seems duplicate to an existing one:
-  Refresh then sign out, pops error dialogs (#1643)
