### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by quackerjeff** [microsoft/azure-tools-for-java#4449]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.37.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1913x950,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.lang.NullPointerException
	at com.microsoft.intellij.runner.functions.core.FunctionUtils.lambda$getBinding$7(FunctionUtils.java:333)
	at com.microsoft.intellij.runner.functions.core.FunctionUtils.getBinding(FunctionUtils.java:334)
	at com.microsoft.intellij.runner.functions.core.FunctionUtils.parseAnnotations(FunctionUtils.java:320)
	at com.microsoft.intelli

**Comment by Flanker32** [comment]
@quackerjeff Thanks for your report, we will looking into this issue soon, by the way, could you please share your function annotation with us, which may help us find the issues soon.

**Comment by andxu** [comment]
@quackerjeff Are you using CustomBinding? If so, we are not supporting it now. If not, would you mind share you annotation class with us? Like 
```
@FunctionName("hello")
  public HttpResponseMessage<String> helloFunction(
    @HttpTrigger(name = "req",
                  methods = {HttpMethod.GET},
                  authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<String>> request
  ) {
     ....
  }
```
