### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by villacak** [microsoft/azure-tools-for-java#4450]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Windows Server 2016
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.37.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1841x992,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: unknown_user
	at com.microsoft.azure.docker.ops.utils.AzureDockerUtils$4.call(AzureDockerUtils.java:398)
	at com.microsoft.azure.docker.ops.utils.AzureDockerUtils$4.call(AzureDockerUtils.java:390)
Caused by: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at com.microsoft.azuretools.adauth.AuthContext.acquireToken(AuthContext.java:146)
	at com.microsoft.azuretools.authmanage.DCAuthManager.getAccessToken(DCAuthManager.java:92)
	at com.microsoft.azuretools.sdkmanage.AccessTokenAzureManager.getAccessToken(AccessTokenAzureManager.java:247)
	at com.microsoft.azure

**Comment by Flanker32** [comment]
@villacak Thanks a lot for your report, this seems to be an authentication issues, could you please help us check the authentication status and could this issue be reproduced after relogin?

**Comment by andxu** [comment]
@Flanker32 I met this issue recently, unknown_user should not be able to reproduce everytime.

**Comment by andxu** [comment]
Duplicate as #1643
