### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by villacak** [microsoft/azure-tools-for-java#4453]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Windows Server 2016
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.37.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1841x992,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.lang.Error: The process has been terminated
	at com.microsoft.intellij.runner.RunProcessHandler.println(RunProcessHandler.java:91)
	at com.microsoft.intellij.runner.RunProcessHandler.setText(RunProcessHandler.java:125)
	at com.microsoft.intellij.runner.functions.deploy.FunctionDeploymentState.onSuccess(FunctionDeploymentState.java

**Comment by andxu** [comment]
@Flanker32, Please check the error: "The process has been terminated"

**Comment by Flanker32** [comment]
Duplicated with #4102
