### ISSUE TITLE
Should not report NPE when func isnot available in PATH 

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-tools-for-java#4457]
```
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 17 more
Caused by: java.lang.NullPointerException
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.onFail(FunctionRunState.java:232)
	at com.microsoft.intellij.runner.AzureRunProfileState.onFail(AzureRunProfileState.java:97)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$2(AzureRunProfileState.java:86)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
```

**Comment by andxu** [comment]
In mac, there is a known issue of empty PATH, in this case the func is not available, but we shall not report NPE. Please point the link to our [FAQ](https://github.com/microsoft/azure-tools-for-java/wiki/FAQ)
See issue:#4312

**Comment by vscjavaci** [comment]
Track internal issue by AB#1738823
