### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by sudoom** [microsoft/azure-tools-for-java#4459]
IntelliJ build version: 2020.1.2 IC-201.7846.76
OS: Linux
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.38.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,29,1080x652,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at com.microsoft.azuretools.ijidea.ui.DeviceLoginWindow.lambda$new$0(DeviceLoginWindow.java:81)
	at com.microsoft.azuretools.ijidea.ui.DeviceLoginUI.buildAndShow(DeviceLoginUI.java:49)
	at com.microsoft.azuretools.ijidea.ui.DeviceLoginUI.lambda$authenticate$0(DeviceLoginUI.java:42)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.deviceLoginAsync(SignInWindow.java:199)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.doDeviceLogin(SignInWindow.java:185)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.doOKAction(SignInWindow.java:354)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.go(SignInWindow.java:92)
	at com.micr

**Comment by andxu** [comment]
hi @sudoom, thank you for using our tools, will you mind to tell the results to the following script in your terminal?
KDE:     *which kde-open*
GNOME:   *which gnome-open*
Any X-server system: *which xdg-open*
