### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Executor with context action id: "RunClass" was already registered!

### ISSUE THREAD

**Issue by sheldonrobinson** [microsoft/azure-tools-for-java#4491]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,1,0,666x488,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=666,height=488]]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:107)
```

**Comment by andxu** [comment]
Hi @sheldonrobinson, can you see this error again?
