### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by haresh-bhuriya-guavus** [microsoft/azure-tools-for-java#4493]
IntelliJ build version: 2020.1.2 IC-201.7846.29
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.38.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,22,824x478,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:200)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azuretools.authmanage.AuthMethodManager$LazyHolder
	at com.microsoft.azuretools.authmanage.AuthMethodManager.getInstance(AuthMethodManager.java:66)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.<init>(AzureSignInAction.java:56)
```

**Comment by Flanker32** [comment]
Fixed in #4533
