### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  retrofit2.adapter.rxjava.HttpException: HTTP 404 Not Found

### ISSUE THREAD

**Issue by jay80110** [microsoft/azure-tools-for-java#4498]
IntelliJ build version: 2020.1.1 IU-201.7223.91
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.39.0-2020.1
Additional Info: My IDE was idle.  I may have lost my VPN connection and/or gotten a session timeout on my Azure login.  I don't know if that would cause this error, but it is not a very user-friendly error message if that's the case.
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1028x975,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=retrofit2.adapter.rxjava.HttpException: HTTP 404 Not Found
	at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:54)
	at com.microsoft.azure.management.appservice.implementation.FunctionAppImpl.listFunctionKeys(FunctionAppImpl.java:455)
	at com.microsoft.azuretools.core.mvp.model.function.FunctionAppWrapper.listFunctionKeys(FunctionAppWrapper.java:67)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.function.SubFunctionNode.getFunctionHttpTriggerUrl(SubFunctionNode.java:165)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.function.SubFunctionNode.triggerHttpTrigger(SubFunctionNode.java:141)

**Comment by Flanker32** [comment]
@jay80110 Thanks for your report, azure toolkit will call function host to get the key and build function trigger url, it seems that the request was break as network issues, could you see the function triggers in portal? And could you please try again without VPN connection?
