### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by sathishjayapal** [microsoft/azure-tools-for-java#4499]
IntelliJ build version: 2020.1.1 IU-201.7223.91
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.39.0-2020.1
Error message: 
```
com.microsoft.azure.CloudException: Status code 400, {"error":{"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.ContainerRegistry'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Billing,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,Microsoft.Subscription,microsoft.support,microsoft.visualstudio,Microsoft.Web'."}}: The operation is not permitted for namespace 'Microsoft.ContainerRegistry'. List of permitted provider namespaces is 'Microsoft.Authorization,Microsoft.Billing,Microsoft.Features,microsoft.insights,Microsoft.NotificationHubs,Microsoft.Resources,Microsoft.Sql,Microsoft.Subscription,microsoft.support,microsoft.visualstudio,Microsoft.Web'.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.microsoft.re

**Comment by Flanker32** [comment]
@sathishjayapal Thanks for your report, this seems to be an authentication issues, could you please share how this issue occurs and is it stable reproduced; besides, could the same job be done in portal or other tooling like azure cli.
