### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Executor with context action id: "RunClass" was already registered!

### ISSUE THREAD

**Issue by trikiomar712** [microsoft/azure-tools-for-java#4513]
IntelliJ build version: 2020.1.4 IU-201.8743.12
OS: Linux
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,2,32,1366x707,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:107)
```

**Comment by andxu** [comment]
Duplicate as 4491
