### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Cannot add an action twice: Builder (Implements Builder Design Pattern)

### ISSUE THREAD

**Issue by lsiem** [microsoft/azure-tools-for-java#4514]
IntelliJ build version: 2020.1.3 IU-201.8538.31
OS: Linux
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,2,28,1920x1052,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Cannot add an action twice: Builder (Implements Builder Design Pattern)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:107)
```

**Comment by andxu** [comment]
Hi @lsiem, we cannot reproduce it now, can you repro it now on version 3.59.0?
