### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by harshalbawale** [microsoft/azure-tools-for-java#4518]
IntelliJ build version: 2020.1 IU-201.6668.121
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.39.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x506,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.ExceptionInInitializerError
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:91)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.microsoft.intellij.ui.messages.messages, locale en_IN
	at com.microsoft.intellij.ui.messages.AzureBundle.message(AzureBundle.java:33)
	at com.microsoft.azure.hdinsight.common.HDInsightHelperImpl.<clinit>(HDInsightHelperImpl.java:57)
Caused by: java.lang.RuntimeException: fuck_the_regulations/db
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting DES/CBC/PKCS5Padding
```

**Comment by wezhang** [comment]
Thanks! It's an i18n related feature issue.
