### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by ibandare** [microsoft/azure-tools-for-java#4521]
IntelliJ build version: 2020.1.4 IU-201.8743.12
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Error message: 
```
java.lang.RuntimeException: java.io.IOException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2020-05-18T07:22:34.0560000Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2020-06-05T11:20:59.0000000Z'.\r\nTrace ID: 54674c13-8e25-4e26-9477-d33e5beab400\r\nCorrelation ID: 2db77dbd-5dca-4842-b26f-5fec4564c60d\r\nTimestamp: 2020-07-28 19:06:51Z","error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50173"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.

**Comment by Flanker32** [comment]
@ibandare Thanks for your report, it seems that you have changed the password and need to re-login, could you please try log out and sign in again with new credential?

**Comment by ibandare** [comment]
@Flanker32, thanks, it worked after singing out!
