### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by ennisa-ire** [microsoft/azure-tools-for-java#4525]
IntelliJ build version: 2020.2 IU-202.6397.94
OS: Linux
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,1,26,1920x1151,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.microsoft.azure.management.appservice.implementation.KuduClient.warDeployAsync(KuduClient.java:170)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.warDeployAsync(WebAppImpl.java:205)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.warDeployAsync(WebAppImpl.java:188)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.warDeploy(WebAppImpl.java:196)
	at com.microsoft.azuretools.utils.WebAppUtils.deployWebAppToWebContainer(WebAppUtils.java:377)
	at com.microsoft.azuretools.utils.WebAppUtils.deployArtifactsToAppService(WebAppUtils.java:317)
	at com.microsoft.intellij.runner.webapp.we

**Comment by Flanker32** [comment]
@ennisa-ire Thanks for your report, this is an out of memory issue, could you please increase memory heap and try again? You may get the guidance [here](https://www.jetbrains.com/help/idea/increasing-memory-heap.html)
