### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by mitesh293** [microsoft/azure-tools-for-java#4527]
IntelliJ build version: 2020.1.1 IU-201.7223.91
OS: Windows 7
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.39.0-2020.1
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 03bf81aa-66d4-473d-bcd2-91614d060700\r\nCorrelation ID: df6926a6-86e9-4590-9ab8-2be4b2bca031\r\nTimestamp: 2020-08-02 13:44:24Z","error_codes":[90002],"timestamp":"2020-08-02 13:44:24Z","trace_id":"03bf81aa-66d4-473d-bcd2-91614d060700","correlation_id":"df6926a6-86e9-4590-9ab8-2be4b2bca031","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.redis.implementation.RedisInner.list(RedisInner.java:955)
	at com.microsoft.azure.managem

**Comment by Flanker32** [comment]
@mitesh293 Thanks for your report, it may caused by the credential is out of date, could you please re-login and try again? Besides, could you please share your authentication method, like `Azure Cli` `Device Login` or `Service Principal`?
