### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by dancingfrog** [microsoft/azure-tools-for-java#4531]
IntelliJ build version: 2020.1.2 IE-201.7846.105
OS: Linux
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.39.0-2020.1
Error message: 
```
java.lang.RuntimeException: java.io.IOException: com.microsoft.aad.adal4j.AdalClaimsChallengeException: {"error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: 87c16ed9-f60c-40e5-95c5-00e84a3be400\r\nCorrelation ID: 5b2c05f1-b6cc-45d9-92cb-0b033f0b4212\r\nTimestamp: 2020-08-03 15:13:33Z","error":"interaction_required","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50076"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.AzureCliAzureManager.getSubscriptionsWithTenant(AzureCliAzureManager.java:135)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(Subscriptio

**Comment by andxu** [comment]
hi @dancingfrog , seems your azure cli credential has some problem due to external changes,   would you please tell us the result of the following command:
```az account show
az webapp list
```

**Comment by dancingfrog** [comment]
$ az webapp list
```
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.
Trace ID: 2e029392-6019-45c5-80f4-2d4f71823700
Correlation ID: c9220246-81a4-418a-98e9-be2c2a9f95e0
Timestamp: 2020-08-18 21:53:03Z
```

**Comment by dancingfrog** [comment]
I went into the Azure portal and created a new subscription. How do I configure the az cli with the new subscription id?

**Comment by andxu** [comment]
@dancingfrog , you can switch it by `az login`, in the pop up web page , choose "Use another account", and login the email related to the new subscription, if you have one single account(email) with multiple subscriptions, you can change the subscription with 'az account set --subscription <place your subs guid here>'

![image](https://user-images.githubusercontent.com/17075863/93734219-ee883d80-fc0a-11ea-872f-25e61b754bc1.png)

**Comment by andxu** [comment]
To get rid of the error `Due to a configuration change made by your administrator, or because you moved to a new...`, use `az login`
