### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by ListenToATree** [microsoft/azure-tools-for-java#4532]
IntelliJ build version: 2020.2 IU-202.6397.94
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x964,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
Caused by: java.io.IOException: Cannot run program "func" (in directory "/Users/mingli/IdeaProjects/azure-function-examples/target/azure-functions/azure-function-examples-1596612498166"): error=2, No such file or directory
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:120)

**Comment by ListenToATree** [comment]
Hello, I was following the guide from "Quickstart: Create an Azure Functions project using IntelliJ IDEA"(https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/quickstart-functions).
But I failed to run it locally. Thank you for any help.

**Comment by Flanker32** [comment]
@ListenToATree Thanks for your report, there are some issues in mac which make IntelliJ plugins may get empty PATH so the toolkit can not get the function core tools to run function locally, could you please try the workaround in the [guidance](https://github.com/microsoft/azure-tools-for-java/wiki/FAQ) and try again?
