### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by roryp** [microsoft/azure-tools-for-java#4535]
IntelliJ build version: 2020.2 IU-202.6397.94
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0-2020.2
Error message: 
```
java.lang.RuntimeException: Cannot reconnect.
	at org.jetbrains.idea.maven.server.RemoteObjectWrapper.performCancelable(RemoteObjectWrapper.java:98)
	at org.jetbrains.idea.maven.server.MavenEmbedderWrapper.evaluateEffectivePom(MavenEmbedderWrapper.java:124)
	at com.microsoft.intellij.util.MavenUtils.evaluateEffectivePom(MavenUtils.java:70)
	at com.microsoft.intellij.util.MavenUtils.getSpringBootFinalJarPath(MavenUtils.java:44)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:123)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:64)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:71)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base

**Comment by yucwan** [comment]
It happened when trying to re-deploy an app to azure spring cloud

**Comment by andxu** [comment]
hi @roryp, it seems there is an issue with you maven local cache, could you please try to delete all files at <HOME>/.m2 and retry?
