### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#4536]
IntelliJ build version: 2019.3.3 IC-193.6494.35
OS: Windows 10
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.35.0-2019.3
Error message: 
```
com.microsoft.azure.CloudException: Async operation failed with provisioning state: Failed: 112405: Failed to wait deployment instances ready.
	at com.microsoft.azure.PollingState.throwCloudExceptionIfInFailedState(PollingState.java:541)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:203)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:200)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubsc

**Comment by yucwan** [comment]
My case is actually caused by wrong default jar file 
![image](https://user-images.githubusercontent.com/49381248/89626213-a10a7800-d8cb-11ea-8130-b45d91fa711d.png)

**Comment by andxu** [comment]
We shall add the main class verification at the deploy UI

**Comment by andxu** [comment]
Category: "Validation in more scenarios"

**Comment by wangmingliang-ms** [comment]
can you try the latest version?
