### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by bluewateralgarve** [microsoft/azure-tools-for-java#4544]
IntelliJ build version: 2020.2 IC-202.6397.94
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0-2020.2
Error message: 
```
java.lang.RuntimeException: java.io.IOException: java.net.UnknownHostException: login.microsoftonline.com
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getTenants(ServicePrincipalAzureManager.java:187)
	at com.microsoft.azuretools.sdkmanage.ServicePrincipalAzureManager.getSubscriptionsWithTenant(ServicePrincipalAzureManager.java:161)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(SubscriptionManagerPersist.java:78)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:90)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:75)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:119)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.<init>(Azure

**Comment by andxu** [comment]
@bluewateralgarve, you are temporarily dropped from network,  could you tell me whether you can reproduce this error? Could you please provide us the result for the following command?
`ping login.microsoftonline.com`

**Comment by andxu** [comment]
Improve error handing
