### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by vivekmenon222** [microsoft/azure-tools-for-java#4546]
IntelliJ build version: 2019.3 IU-193.5233.102
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.31.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.StackOverflowError
	at org.apache.log4j.helpers.ISO8601DateFormat.format(ISO8601DateFormat.java:67)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:104)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebu

**Comment by wezhang** [comment]
Dup #4023, fixed in v3.33.0
