### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by James-S-Wood** [microsoft/azure-tools-for-java#4558]
IntelliJ build version: 2020.2 IC-202.6397.94
OS: Linux
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,41,824x495,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at com.microsoft.azuretools.ijidea.ui.DeviceLoginWindow.lambda$new$0(DeviceLoginWindow.java:81)
	at com.microsoft.azuretools.ijidea.ui.DeviceLoginUI.buildAndShow(DeviceLoginUI.java:49)
	at com.microsoft.azuretools.ijidea.ui.DeviceLoginUI.lambda$authenticate$0(DeviceLoginUI.java:42)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.doLogin(SignInWindow.java:299)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.doDeviceLogin(SignInWindow.java:285)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.doOKAction(SignInWindow.java:197)
	at com.microsoft.azuretools.ijidea.ui.SignInWindow.go(SignInWindow.java:146)

**Comment by andxu** [comment]
Improve the error handling.

**Comment by wangmingliang-ms** [comment]
intellij plugin for Azure uses java `Desktop` API to launch the default browser to open url. but the `Desktop` API is not well supported in some platforms.
