### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by jimmurmac** [microsoft/azure-tools-for-java#4565]
IntelliJ build version: 2020.2 IU-202.6397.94
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.40.0-2020.2
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,2,0,666x488,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=666,height=488]]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.microsoft.intellij.wizards.functions.module.FunctionsModuleInfoStep.<clinit>(FunctionsModuleInfoStep.java:46)
	at com.microsoft.intellij.wizards.functions.module.FunctionsModuleBuilder.createWizardSteps(FunctionsModuleBuilder.java:96)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory PluginClassLoader[PluginDescriptor(name=Azure Toolkit for IntelliJ, id=com.microsoft.tooling.msservices.intellij.azure, path=C:\Users\jimmu\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\azure-toolkit-for-intellij, version=3.40.0-2020.2)] com.intellij.ide.plugins.cl.PluginClassLoader@58dfba1
```

**Comment by andxu** [comment]
hi @@jimmurmac, seems this issue is opened long time ago, can you now use azure functions feature in 3.59.0?
