### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by ibandare** [microsoft/azure-tools-for-java#4581]
IntelliJ build version: 2020.2.1 IU-202.6948.69
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.41.1-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1859x1080,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.runner.functions.FunctionRunConfigurationProducer.setupConfigurationFromContext(FunctionRunConfigurationProducer.java:91)
	at com.microsoft.intellij.runner.functions.FunctionRunConfigurationProducer.setupConfigurationFromContext(FunctionRunConfigurationProducer.java:47)
```

**Comment by Flanker32** [comment]
@ibandare Thanks for your report, issue should be fixed in the latest [release](https://github.com/microsoft/azure-tools-for-java/releases/tag/azure-intellij-toolkit-v3.42.0), could you update the toolkit and try again? Thanks!
