### ISSUE TITLE
[情报][用户报告]部署失败

### ISSUE THREAD

**Issue by wangkun370** [microsoft/azure-tools-for-java#4591]
IntelliJ build version: 2020.2 IU-202.6397.94
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.42.0-2020.2
Error message: 
```
com.microsoft.azure.common.exceptions.AzureExecutionException: Main class cannot be found in D:\Project\hellospring\target\hellospring-0.0.1-SNAPSHOT.jar, which is required for spring cloud app.
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.validateSpringCloudAppArtifact(SpringCloudDeploymentState.java:204)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:128)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:64)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:71)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAda

**Comment by Flanker32** [comment]
@wangkun370 Thanks for your report, Azure Spring Cloud required the artifact to be runnable, which should have Main class specified in MANIFEST, for spring boot project, please use `spring-boot-maven-plugin` for packaging and try again.
