### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by clifficious** [microsoft/azure-tools-for-java#4599]
IntelliJ build version: 2020.2.2 IU-202.7319.50
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.42.0-2020.2
Error message: 
```
java.lang.IllegalStateException: Duplicate key client-runtime (attempted merging values 1.6.13 and 2.0.2)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.getSpringAppDependencies(SpringCloudDeploymentState.java:26

Not sure what to do with this error. 
Pops up when trying to deploy my Spring Boot app to Azure Spring Cloud.

Thanks for any help

**Comment by Flanker32** [comment]
@clifficious Thanks for your report, the issue has been fixed in #4613
