### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by scanpratik** [microsoft/azure-tools-for-java#4605]
IntelliJ build version: 2020.2.2 IU-202.7319.50
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.42.0-2020.2
Error message: 
```
java.lang.RuntimeException: java.io.IOException: com.microsoft.aad.adal4j.AuthenticationException: {"error_description":"AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2020-06-06T12:30:46.6737143Z and was inactive for 90.00:00:00.\r\nTrace ID: 45b4a175-be05-4544-aa30-91596edb3a00\r\nCorrelation ID: f99ce434-9d75-4593-8640-0c22d744c21f\r\nTimestamp: 2020-09-21 11:22:17Z","error":"invalid_grant","error_uri":"https:\/\/login.microsoftonline.com\/error?code=700082"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.AzureCliAzureManager.getSubscriptionsWithTenant(AzureCliAzureManager.java:136)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateAccountSubscriptionList(SubscriptionManager.java:105)
	at com.microsoft.azuretools.aut

**Comment by andxu** [comment]
@scanpratik , could you please login azure cli again: 
```
az login
```
and then try to sign-in in intellij plugin?
