### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Web Apps

### ISSUE THREAD

**Issue by MexxonRoggenbuck** [microsoft/azure-tools-for-java#4609]
IntelliJ build version: 2020.2.2 IU-202.7319.50
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.42.0-2020.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: AD Auth token endpoint returned HTTP status code 400. Error info: {"error":"invalid_request","error_description":"AADSTS90002: Tenant '4d77a907-f31c-4f84-97b3-26dfea54ac46' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 606878d8-30e7-46f2-832a-377484297a00\r\nCorrelation ID: 33c5d13c-8cfe-4d5f-a13e-9f3197836828\r\nTimestamp: 2020-09-22 12:45:45Z","error_codes":[90002],"timestamp":"2020-09-22 12:45:45Z","trace_id":"606878d8-30e7-46f2-832a-377484297a00","correlation_id":"33c5d13c-8cfe-4d5f-a13e-9f3197836828","error_uri":"https://login.microsoftonline.com/error?code=90002"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.list(WebAppsInner.java:1840)

**Comment by andxu** [comment]
@MexxonRoggenbuck , can you tell us which login method are you using? azure cli or device login or service principle.
If azure cli, can you run the following two commands for us:
```
az cloud show
az account show
az webapp list  --query "[].{hostName: defaultHostName, state: state}"
```
