### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by TonyGregg** [microsoft/azure-tools-for-java#4612]
IntelliJ build version: 2020.2.2 IC-202.7319.50
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.42.0-2020.2
Error message: 
```
java.lang.RuntimeException: java.io.IOException: com.microsoft.aad.adal4j.AdalClaimsChallengeException: {"error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'.\r\nTrace ID: 59569eab-a440-4c40-a907-4f356ae87800\r\nCorrelation ID: 83fef4bb-a51c-4e5e-8e63-32289f41bd78\r\nTimestamp: 2020-09-23 20:44:41Z","error":"interaction_required","error_uri":"https:\/\/login.microsoftonline.com\/error?code=50076"}
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.TenantsInner.list(TenantsInner.java:77)
	at com.microsoft.azure.management.resources.implementation.TenantsImpl.list(TenantsImpl.java:36)
	at com.microsoft.azuretools.sdkmanage.AzureCliAzureManager.getSubscriptionsWithTenant(AzureCliAzureManager.java:136)
	at com.microsoft.azuretools.authmanage.SubscriptionManagerPersist.updateAccountSubscriptionList(Subsc

**Comment by TonyGregg** [comment]
Duplicate of what I originally reported
