### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by musa-pro** [microsoft/azure-tools-for-java#4615]
IntelliJ build version: 2020.2.2 IC-202.7319.50
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.42.0-2020.2
Error message: 
```
java.lang.RuntimeException: com.microsoft.azuretools.adauth.AuthException: unknown_user
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.redis.implementation.RedisInner.list(RedisInner.java:955)
	at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheModulePresenter.onModuleRefresh(RedisCacheModulePresenter.java:53)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheModule.refreshItems(RedisCacheModule.java:50)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:96)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:164)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:159)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.pr

**Comment by andxu** [comment]
Hi @musa-pro , we have redesign  the logic for redis, could you take a try at the latest version 3.59.0 and verify whether this error occurs?

![image](https://user-images.githubusercontent.com/17075863/144183382-ae500f84-9ee0-4c49-8943-5161b8e857e7.png)
