### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Spring Cloud(Preview)

### ISSUE THREAD

**Issue by prafullkotecha** [microsoft/azure-tools-for-java#4629]
IntelliJ build version: 2020.2.2 IU-202.7319.50
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.43.0-2020.2
Error message: 
```
java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.appplatform.v2019_05_01_preview.implementation.ServicesInner.list(ServicesInner.java:1400)
	at com.microsoft.azuretools.core.mvp.model.springcloud.AzureSpringCloudMvpModel.listAllSpringCloudClustersBySubscription(AzureSpringCloudMvpModel.java:91)
	at com.microsoft.azuretools.core.mvp.model.springcloud.AzureSpringCloudMvpModel.lambda$null$0(AzureSpringCloudMvpModel.java:77)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

**Comment by andxu** [comment]
We need to handle the SocketTimeoutException which is very common in remote api call.

**Comment by andxu** [comment]
HI @prafullkotecha, can you list azure spring cloud clusters now at 3.59.0?
