### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Executor with context action id: "RunClass" was already registered!

### ISSUE THREAD

**Issue by rumbarum** [microsoft/azure-tools-for-java#4630]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.38.0-2020.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1920,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:107)
```

**Comment by andxu** [comment]
Dup as #4491
