### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by jnovotny** [microsoft/azure-tools-for-java#4632]
IntelliJ build version: 2020.2.2 IU-202.7319.50
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.43.0-2020.2
Error message: 
```
com.microsoft.azure.CloudException: Deployment cannot be updated in the current state: Creating: Deployment cannot be updated in the current state: Creating
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscribeSingle.java:81)
	at rx.internal.operators.OnSubscribeSingle.call(OnSubscrib

**Comment by jnovotny** [comment]
Hmmm maybe it was network error... tried again and seemed to work
