### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.openapi.util.WriteExternalException: Can't export Spark submit model to XML element

### ISSUE THREAD

**Issue by nathangithubhub** [microsoft/azure-tools-for-java#4638]
IntelliJ build version: 2019.3.4 IC-193.6911.18
OS: Windows 10
JDK: JetBrains s.r.o 11.0.6
Plugin version: 3.35.0-2019.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1400,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.openapi.util.WriteExternalException: Can't export Spark submit model to XML element
	at com.microsoft.azure.hdinsight.spark.common.SparkSubmitModel.exportToElement(SparkSubmitModel.java:327)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchJobConfigurableModel.exportToElement(SparkBatchJobConfigurableModel.java:88)
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration.writeExternal(LivySparkBatchJobRunConfiguration.java:129)
	at com.microsoft.azure.hdinsight.spark.uihelper.InteractiveTableModel.setValueAt(InteractiveTableModel.java:114)
	at com.microsoft.azure.hdinsight.spark.run.action.RunConfigurationActionUtils.runEnvironmentProfileWithCheckSettings(RunConfigurationActionUtils.kt:56)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.submit(SparkSubmitJobAction.kt:114)
	at com.microsoft

**Comment by wezhang** [comment]
@nathangithubhub , could you help do the following check:
1. Is there any invisible characters in Spark run configuration fields (such as: #2058)?
2. Upgrade to the most new version plugin and try again.

Thanks!

**Comment by fengshuaihu** [comment]
Please update to the latest version and try again, if you encounter this issue again, feel free to turn it on again
