### ISSUE TITLE
[IntelliJ][ReportedByUser] Error

### ISSUE THREAD

**Issue by Bruce-G-Zhu** [microsoft/azure-tools-for-java#4666]
IntelliJ build version: 2020.1.4 IU-201.8743.12
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.43.0-2020.1
Error message: 
```
com.microsoft.azure.CloudException: The client 'bruce.g.zhu@pwc.com' with object id '94884a18-7334-4456-b593-c359afe3ed03' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/write' over scope '/subscriptions/32cdfde2-03d0-43b0-8f45-ce0aec7794ef/resourceGroups/ACT_Dev/providers/Microsoft.Storage/storageAccounts/storageacountactde9191' or the scope is invalid. If access was recently granted, please refresh your credentials.: The client 'bruce.g.zhu@pwc.com' with object id '94884a18-7334-4456-b593-c359afe3ed03' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/write' over scope '/subscriptions/32cdfde2-03d0-43b0-8f45-ce0aec7794ef/resourceGroups/ACT_Dev/providers/Microsoft.Storage/storageAccounts/storageacountactde9191' or the scope is invalid. If access was recently granted, please refresh your credentials.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:771)
	at com.microsoft.azure.AzureClient.access$100(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:160)
	at com.microsoft.azure.AzureClient$3.call(AzureClient.java:157)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.

**Comment by Bruce-G-Zhu** [comment]
Resolved
