### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Services - Error Getting Subscriptions

### ISSUE THREAD

**Issue by dbercier** [microsoft/azure-tools-for-java#4678]
IntelliJ build version: 2018.3.4 IC-183.5429.30
OS: Windows 10
JDK: JetBrains s.r.o 1.8.0_152-release
Plugin version: 3.23.0-2018.3
Error message: 
```
com.microsoft.azuretools.adauth.AuthException: No subscription found in the account
	at com.microsoft.azuretools.authmanage.SubscriptionManager.doSetSubscriptionDetails(SubscriptionManager.java:122)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.updateSubscriptionDetailsIfNull(SubscriptionManager.java:92)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.composeName(AzureModule.java:108)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.handleSubscriptionChange(AzureModule.java:227)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule.access$100(AzureModule.java:48)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureModule$SignInOutListener.run(AzureModule.java:236)
	at com.microsoft.azuretools.authmanage.AuthMethodManager.notifySignInEventListener(AuthMethodManager.java:97)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.doSignIn(AzureSignInAction.java:150)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onAzureSignIn(AzureSignInAction.java:134)
	at com.microsoft.azuretools.ijidea.actions.AzureSignInAction.onActionPerformed(AzureSignInActi

**Comment by dbercier** [comment]
I really need help here. I need this to work so I can work on Azure Functions for my team. I am using VPN which is required or access to my compnay's Azure account but I am able to sign in successfully when the browser challenge pops up. Then the plugin apparently tries to pull the subscriptions list, which there are 6 existing, it says there are no subscriptions and fails with the above error. A coworker told me that he was able to get the parallel plugin to work in Eclipse with everything else the same and when he tries IntelliJ he gets the same error I am getting. So this is specific to the plugin for IntelliJ.. Please help.

**Comment by Flanker32** [comment]
@dbercier Thanks for your report. Could you please update the plugin(which may need update the IntelliJ version) and try again? We have fixed many authentication issues and provide new Azure CLI auth in the new version, here is the [change log](https://github.com/microsoft/azure-tools-for-java/blob/develop/CHANGELOG.md).
