### ISSUE TITLE
[IntelliJ][ReportedByUser] Error occurs on signing in

### ISSUE THREAD

**Issue by Myslyvchuk** [microsoft/azure-tools-for-java#4684]
IntelliJ build version: 2020.2.3 IU-202.7660.26
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.44.0-2020.2
Error message: 
```
com.microsoft.azuretools.exception.AzureRuntimeException: Failed to get access token by Azure CLI command.
	at com.microsoft.azuretools.sdkmanage.AzureCliAzureManager.getAccessTokenViaCli(AzureCliAzureManager.java:195)
	at com.microsoft.azuretools.sdkmanage.AzureCliAzureManager.getAccessToken(AzureCliAzureManager.java:93)
	at com.microsoft.azuretools.authmanage.RefreshableTokenCredentials.getToken(RefreshableTokenCredentials.java:64)
	at com.microsoft.azure.credentials.AzureTokenCredentials.getToken(AzureTokenCredentials.java:74)
	at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:40)

**Comment by wangmingliang-ms** [comment]
Hi, did you installed `Azure CLI`? and had you logged in with `Azure CLI`?  refer [Sign in with the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli)
if yes, can you try
```shell
az account get-access-token
```
in shell and check if the output is something like
```json
{
  "accessToken": "<secret_token>",
  "expiresOn": "2020-10-30 11:14:58.851593",
  "subscription": "dad45786-32e5-4ef3-b90e-8e0838fbadb6",
  "tenant": "<your_tenent_id>",
  "tokenType": "Bearer"
}
```
