### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by ravasconcelos** [microsoft/azure-tools-for-java#4691]
IntelliJ build version: 2020.2.3 IU-202.7660.26
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.44.0-2020.2
Error message: 
```
java.lang.RuntimeException: Cannot reconnect.
	at org.jetbrains.idea.maven.server.RemoteObjectWrapper.performCancelable(RemoteObjectWrapper.java:98)
	at org.jetbrains.idea.maven.server.MavenEmbedderWrapper.evaluateEffectivePom(MavenEmbedderWrapper.java:124)
	at com.microsoft.intellij.util.MavenUtils.evaluateEffectivePom(MavenUtils.java:86)
	at com.microsoft.intellij.util.MavenUtils.getSpringBootFinalJarFilePath(MavenUtils.java:61)
	at com.microsoft.intellij.ui.components.AzureArtifactManager.getFileForDeployment(AzureArtifactManager.java:86)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:118)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:64)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:71)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedTh

**Comment by andxu** [comment]
hi @ravasconcelos, this is caused by intellij maven plugin(official plugin provided by intellij), can you try to evaluate the effective pom at maven window and if it successes, can you then try to deploy the spring cloud again(please tell me the result, thanks)? 

![image](https://user-images.githubusercontent.com/17075863/97649004-2cda0d80-1a91-11eb-83b5-28509e735e6c.png)


> DE launches Maven import in a separate java process and communicates with it using java RMI calls which work via local loopback interface (localhost). To access the loopback interface the localhost hostname is used. When IDE is unable to establish connection to a localhost this error occurs. There could be several causes why localhost is not accessible

https://intellij-support.jetbrains.com/hc/en-us/articles/360014262940-Unable-to-import-Maven-project-import-fails-with-error-Cannot-reconnect

**Comment by ravasconcelos** [comment]
Thank you @andxu.
This issue happened again today. I tried to show the effective POM and I got the same exception.
Restarting IntelliJ fixed the issue.
