### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: Can't get progress

### ISSUE THREAD

**Issue by yucwan** [microsoft/azure-tools-for-java#4716]
IntelliJ build version: 2020.2.1 IC-202.6948.69
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.44.0-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2049x1112,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: Can't get progress
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:232)
Caused by: java.util.concurrent.ExecutionException: com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=demo2, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\yucwan\Documents\vswroks\demo2 (2)\demo2) has already been disposed (see the cause for stacktrace) so the child: null 569787945: running=false; canceled=false; task=null will never be disposed
Caused by: com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=demo2, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\yucwan\Documents\vswroks\demo2 (2)\demo2) has already been disposed (see the

**Comment by yucwan** [comment]
deploying a gradle project to azure web apps

**Comment by yucwan** [comment]
java.lang.RuntimeException: Can't get progress
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:232)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=demo2, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\yucwan\Documents\vswroks\demo2 (2)\demo2) has already been disposed (see the cause for stacktrace) so the child: null 569787945: running=false; canceled=false; task=null will never be disposed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:229)
	... 8 more
Caused by: com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=demo2, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\yucwan\Documents\vswroks\demo2 (2)\demo2) has already been disposed (see the cause for stacktrace) so the child: null 569787945: running=false; canceled=false; task=null will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:65)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:70)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:95)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:43)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:35)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:31)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.lambda$runProcessWithProgressAsynchronously$2(ProgressManagerImpl.java:108)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.util.concurrency.PlainEdtExecutor.execute(PlainEdtExecutor.java:15)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runAsynchronously(CoreProgressManager.java:360)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:347)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2.run(IDEHelperImpl.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by andxu** [comment]
Hi @yucwan , can you reproduce this error? If not, we shall close this issue.
