### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Redis Caches

### ISSUE THREAD

**Issue by mlianghua** [microsoft/azure-tools-for-java#4737]
IntelliJ build version: 2020.2.3 IU-202.7660.26
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.44.0-2020.2
Error message: 
```
com.microsoft.azure.CloudException: Status code 403, {"error":{"code":"AuthorizationFailed","message":"The client 'live.com#mlianghua@gmail.com' with object id '03bc4786-f662-4285-b563-5816ba1e9560' does not have authorization to perform action 'Microsoft.Cache/Redis/read' over scope '/subscriptions/41f6d14d-ece1-46e4-942c-02c00d67f7d6' or the scope is invalid. If access was recently granted, please refresh your credentials."}}: The client 'live.com#mlianghua@gmail.com' with object id '03bc4786-f662-4285-b563-5816ba1e9560' does not have authorization to perform action 'Microsoft.Cache/Redis/read' over scope '/subscriptions/41f6d14d-ece1-46e4-942c-02c00d67f7d6' or the scope is invalid. If access was recently granted, please refresh your credentials.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java

**Comment by andxu** [comment]
Hi @mlianghua , can you try to login using azure cli:
```bash
az login
az account set -s "your subscription id"
az redis list
```
seems your account don't have privilege to list redis in the subscription
