### ISSUE TITLE
[Travis CI] fail to build intellij idea plugin

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/azure-tools-for-java#474]
Same command works in local machine.

```
$ ./gradlew buildPlugin --project-dir PluginsAndFeatures/azure-toolkit-for-intellij -s
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2017.1/ideaIU-2017.1.pom
Download https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2017.1/ideaIU-2017.1.zip
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'azure-toolkit-for-intellij'.
> Invalid type of downloaded plugin: /tmp/intellij5417665913016820454/scala-intellij-bin-2017.1.15.zip?updateId=33637&pluginId=1347
* Try:
Run with --info or --debug option to get more log output.
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'azure-toolkit-for-intellij'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:648)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:126)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:207)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:204)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:146)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.tooling.BuildException: Invalid type of downloaded plugin: /tmp/intellij5417665913016820454/scala-intellij-bin-2017.1.15.zip?updateId=33637&pluginId=1347
	at org.jetbrains.intellij.dependency.PluginDependencyManager.downloadPlugin(PluginDependencyManager.groovy:125)
	at org.jetbrains.intellij.dependency.PluginDependencyManager.resolve(PluginDependencyManager.groovy:53)
	at org.jetbrains.intellij.dependency.PluginDependencyManager$resolve.call(Unknown Source)
	at org.jetbrains.intellij.dependency.PluginDependencyManager$resolve.call(Unknown Source)
	at org.jetbrains.intellij.IntelliJPlugin$_configurePluginDependencies_closure3.doCall(IntelliJPlugin.groovy:153)
	at org.jetbrains.intellij.IntelliJPlugin.configurePluginDependencies(IntelliJPlugin.groovy:137)
	at org.jetbrains.intellij.IntelliJPlugin.configureProjectAfterEvaluate(IntelliJPlugin.groovy:103)
	at org.jetbrains.intellij.IntelliJPlugin$_configureTasks_closure2.doCall(IntelliJPlugin.groovy:90)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:221)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:145)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:315)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:225)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:138)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:35)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy21.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:82)
	... 56 more
BUILD FAILED
Total time: 1 mins 36.074 secs
The command "./gradlew buildPlugin --project-dir PluginsAndFeatures/azure-toolkit-for-intellij -s" exited with 1.

```

**Comment by Eskibear** [comment]
Moreover, in a clean environment, gradle build in Intellij IDEA fails with error message:
```
Error:Invalid type of downloaded plugin: /var/folders/k4/4rfgfkjx64g0qmr3js7xp00w0000gn/T/intellij2988488121738707872/scala-intellij-bin-2017.1.15.zip?updateId=33637&pluginId=1347
```
Same as TravisCI. I don't know why Jenkins works well.

FYI

**Comment by adashen** [comment]
@voidfunction seems the scala package issue, can you have a look?

**Comment by voidfunction** [comment]
@adashen @Eskibear Seems Scala package issue. I will see what I can do.

**Comment by voidfunction** [comment]
bug of gradle intellij plugin. details in: https://github.com/JetBrains/gradle-intellij-plugin/issues/201
`Invalid type of downloaded plugin: /var/folders/k4/4rfgfkjx64g0qmr3js7xp00w0000gn/T/intellij2988488121738707872/scala-intellij-bin-2017.1.15.zip?updateId=33637&pluginId=1347`
`download` file name should end with `.zip` or `.jar`. But actually the file name is  `/tmp/intellij5757369558789368310/scala-intellij-bin-2017.1.15.zip?updateId=33637&pluginId=1347`, So we get an exception here.
     
        if (Utils.isJarFile(download)) {
            def artifactFile = new File(cacheDirectory, download.name)
            def move = Files.move(download.toPath(), artifactFile.toPath(), StandardCopyOption.REPLACE_EXISTING)
            return externalPluginDependency(move.toFile(), channel)
        } else if (Utils.isZipFile(download)) {
            return externalPluginDependency(extractZip(id, version, download, cacheDirectory), channel)
        }
        throw new BuildException("Invalid type of downloaded plugin: $download", null)

**Comment by adashen** [comment]
close as fixed
