### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by villacak** [microsoft/azure-tools-for-java#4743]
IntelliJ build version: 2020.2.3 IU-202.7660.26
OS: Windows Server 2016
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.45.0-2020.2
Error message: 
```
com.microsoft.azure.CloudException: Async operation failed with provisioning state: Failed: 112404: Failed to wait for deployment instances to be ready. Please check the application log (see https://aka.ms/azure-spring-cloud-doc-log), and try again later.
	at com.microsoft.azure.PollingState.throwCloudExceptionIfInFailedState(PollingState.java:541)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:203)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:200)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)

**Comment by Flanker32** [comment]
@zmssp Could you please help look this issue?

**Comment by zmssp** [comment]
From the error message, we can see the deployment is failed. 
In most cases, it is caused by **bad jar**, the application cannot start normarlly.
Suggests customer to check their application log.
Or customer could provide their resourceid, app name, then we take a look

**Comment by andxu** [comment]
We shall add validation for bad jar when the jar doesn't contain main class in manifest.
