### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by zaj-e** [microsoft/azure-tools-for-java#4775]
IntelliJ build version: 2020.2.4 IU-202.8194.7
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9
Plugin version: 3.45.1-2020.2
Error message: 
```
com.microsoft.azure.CloudException: Async operation failed with provisioning state: Failed: 112404: Failed to wait for deployment instances to be ready. Please check the application log (see https://aka.ms/azure-spring-cloud-doc-log), and try again later.
	at com.microsoft.azure.PollingState.throwCloudExceptionIfInFailedState(PollingState.java:541)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:203)
	at com.microsoft.azure.AzureClient$5.call(AzureClient.java:200)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:244)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:511)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:466)
	at

**Comment by andxu** [comment]
Duplicate as #4743
