### ISSUE TITLE
[IntelliJ][ReportedByUser] Deployed failed

### ISSUE THREAD

**Issue by dlange-insight** [microsoft/azure-tools-for-java#4789]
IntelliJ build version: 2020.2.1 IU-202.6948.69
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.8
Plugin version: 3.45.1-2020.2
Error message: 
```
java.lang.RuntimeException: Cannot reconnect.
	at org.jetbrains.idea.maven.server.RemoteObjectWrapper.performCancelable(RemoteObjectWrapper.java:98)
	at org.jetbrains.idea.maven.server.MavenEmbedderWrapper.evaluateEffectivePom(MavenEmbedderWrapper.java:124)
	at com.microsoft.intellij.util.MavenUtils.evaluateEffectivePom(MavenUtils.java:86)
	at com.microsoft.intellij.util.MavenUtils.getSpringBootFinalJarFilePath(MavenUtils.java:61)
	at com.microsoft.intellij.ui.components.AzureArtifactManager.getFileForDeployment(AzureArtifactManager.java:86)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:118)
	at com.microsoft.intellij.runner.springcloud.deploy.SpringCloudDeploymentState.executeSteps(SpringCloudDeploymentState.java:64)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:71)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadSche

**Comment by andxu** [comment]
Dup as #4535, could you please try to follow the actions described at https://stackoverflow.com/questions/30615067/intellij-idea-maven-cannot-reconnect-error to delete maven caches?

**Comment by andxu** [comment]
Duplicate as #4691
