### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Files

### ISSUE THREAD

**Issue by BillLupoTR** [microsoft/azure-tools-for-java#4810]
IntelliJ build version: 2020.1.4 IC-201.8743.12
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.45.1-2020.1
Error message: 
```
retrofit2.adapter.rxjava.HttpException: HTTP 404 Not Found
	at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:54)
	at retrofit2.adapter.rxjava.BodyOnSubscribe$BodySubscriber.onNext(BodyOnSubscribe.java:39)
	at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
	at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
	at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
	at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:36)
	at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:28)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.

**Comment by andxu** [comment]
Hi @BillLupoTR , would you mind telling me what are you doing when you see this error? listing files in azure explorer?
can you reproduce this bug in latest release 3.59.0?
