### ISSUE TITLE
[Intellij]Failed to save settings. Please restart IntelliJ IDEA

### ISSUE THREAD

**Issue by wezhang** [Microsoft/azure-tools-for-java#492]
```
Unable to save settings
				Failed to save settings. Please restart IntelliJ IDEA
				java.lang.RuntimeException: java.lang.Exception: Cannot get RunManager component state
					at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:176)
					at com.intellij.util.lang.CompoundRuntimeException.throwIfNotEmpty(CompoundRuntimeException.java:148)
					at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:200)
					at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:46)
					at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:352)
					at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:137)
					at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:125)
					at com.intellij.ide.SaveAndSyncHandlerImpl$2.lambda$onFrameDeactivated$0(SaveAndSyncHandlerImpl.java:94)
					at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)... (show balloon)

```

**Comment by djlan** [comment]
Cannot repro, close it for now.
