### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception An error occurred when trying to load Virtual Machinesload details of all selected subscriptions com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: load details of all selected subscriptions

### ISSUE THREAD

**Issue by Raphael909** [microsoft/azure-tools-for-java#4944]
IntelliJ build version: 2020.3.2 IU-203.7148.57
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.49.0-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1674x1026,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=An error occurred when trying to load Virtual Machines
load details of all selected subscriptions, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: load details of all selected subscriptions
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:41)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSelectedSubscriptionDetails(SubscriptionManager.java:64)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.vmarm.VMArmModule.refreshItems(VMArmModule.java:54)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:86)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$1.run(Ref

**Comment by andxu** [comment]
Hi @Raphael909, we have refactored the auth code since 3.52.0,  can you try to sign in using our latest bit: 3.59.0 and tell us whether or not you can sign-in?
