### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by BeliliFahem** [microsoft/azure-tools-for-java#4946]
IntelliJ build version: 2020.3.2 IU-203.7148.57
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.49.0-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1920x1027,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at com.microsoft.azure.toolkit.intellij.appservice.subscription.SubscriptionComboBox.<init>(SubscriptionComboBox.java:21)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceInfoAdvancedPanel.$$$setupUI$$$(AppServiceInfoAdvancedPanel.java)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceInfoAdvancedPanel.<init>(AppServiceInfoAdvancedPanel.java:68)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppConfigFormPanelAdvance.createUIComponents(WebAppConfigFormPanelAdvance.java:70)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppConfigFormPanelAdvance.$$$setupUI$$$(WebAppConfigFormPanelAdvance.java)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppConfigFormPanelAdvance.<in

**Comment by andxu** [comment]
Fixed in '3.58.1'
