### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.toolkit.intellij.function.action.RunFunctionAction) with ID=Actions.RunFunction com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: check if project(E-Com) is a valid function project

### ISSUE THREAD

**Issue by harry12345678910** [microsoft/azure-tools-for-java#5010]
IntelliJ build version: 2020.3.2 IU-203.7148.57
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9.1
Plugin version: 3.49.1-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.toolkit.intellij.function.action.RunFunctionAction) with ID=Actions.RunFunction, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: check if project(E-Com) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:41)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.isFunctionProject(FunctionUtils.java:154)
	at com.microsoft.azure.toolkit.intellij.function.action.RunFunctionAction.update(RunFunctionAction.java:49)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.azure.toolkit.intellij.function.runner.core.F

**Comment by andxu** [comment]
Duplicate as #4631
