### ISSUE TITLE
[IntelliJ][ReportedByUser] Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by faustool** [microsoft/azure-tools-for-java#5042]
[az-stacktrace.txt](https://github.com/microsoft/azure-tools-for-java/files/6182013/az-stacktrace.txt)
IntelliJ build version: 2020.3.3 IU-203.7717.56
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.49.1-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: (full stacktrace is attached)
```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
```

**Comment by Flanker32** [comment]
@faustool Thanks for your report, could you please share some more infos like when this issue occurs and is there any way to reproduce it? By the way, it seems that the link has been expired, could you please help upload the log again? Many Thanks!

**Comment by faustool** [comment]
Hi!

This happens when the plugin tries to list the subscriptions available for
my account.

I'll try to reproduce the problem again and reattach the full log.

**Comment by andxu** [comment]
Hi @ faustool, could you try this article?
https://mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/
