### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: get details of all cached subscriptions

### ISSUE THREAD

**Issue by jaintitanium** [microsoft/azure-tools-for-java#5053]
IntelliJ build version: 2020.3.3 IU-203.7717.56
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.49.1-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,6,0,824x513,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: get details of all cached subscriptions
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:41)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:56)
	at com.microsoft.intellij.util.AzureLoginHelper.ensureAzureSubsAvailable(AzureLoginHelper.java:28)
	at com.microsoft.azure.toolkit.intellij.common.AzureRunConfigurationBase.checkAzurePreconditions(AzureRunConfigurationBase.java:84)
	at com.microsoft.azure.toolkit.intellij.webapp.runner.webappconfig.WebAppConfiguration.validate(WebAppConfiguration.java:69)
	at com.microsoft.azure.toolkit.intellij.common.AzureSettingsEditor.applyEditorTo(AzureSettingsEditor.java:25)
	at com.microsoft.azure.toolk

**Comment by andxu** [comment]
#5052 is a duplicate bug

**Comment by StefanLadwig** [comment]
I have the same problem, when I login with Azure CLI. Any ideas or workarounds?

**Comment by andxu** [comment]
Hi @StefanLadwig , can you login azure toolkit for intellij using azure cli at latest version 3.59.0?
![image](https://user-images.githubusercontent.com/17075863/144206589-a8b57c29-bac1-41e2-aec7-f6401fd2b3d2.png)
