### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by alonsoir** [microsoft/azure-tools-for-java#5059]
IntelliJ build version: 2020.3.3 IC-203.7717.56
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.50.0-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,28,824x500,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.runner.LinkAzureServiceBeforeRunProvider.getModuleName(LinkAzureServiceBeforeRunProvider.java:120)
	at com.microsoft.intellij.runner.LinkAzureServiceBeforeRunProvider.executeTask(LinkAzureServiceBeforeRunProvider.java:83)
	at com.microsoft.intellij.runner.LinkAzureServiceBeforeRunProvider.executeTask(LinkAzureServiceBeforeRunProvider.java:38)
```

**Comment by Flanker32** [comment]
Close the issue as it has been fixed in toolkit v3.51.0
