### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 2be44fe3-a6c1-4e4b-906d-1aca8809fa5f] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed. com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.

### ISSUE THREAD

**Issue by BharathKanagala** [microsoft/azure-tools-for-java#5070]
IntelliJ build version: 2020.3.3 IC-203.7717.56
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.49.1-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 2be44fe3-a6c1-4e4b-906d-1aca8809fa5f] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed., throwable=com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.
Trace ID: 986d3b30-262f-4f07-a5b7-7a8004c31702
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:118)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallabl

**Comment by Flanker32** [comment]
@BharathKanagala Thanks for your report, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/5076
