### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: dd2a601f-0c62-4eae-99ef-b36f2215fc21] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed. com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.

### ISSUE THREAD

**Issue by AnimalFarm0101** [microsoft/azure-tools-for-java#5076]
IntelliJ build version: 2020.3.3 IU-203.7717.56
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.49.1-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,22,824x484,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: dd2a601f-0c62-4eae-99ef-b36f2215fc21] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed., throwable=com.microsoft.aad.adal4j.AuthenticationException: AADSTS70016: OAuth 2.0 device flow error. Authorization is pending. Continue polling.
Trace ID: cfe0018a-1a7e-4361-a217-b3cd04cd6200
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:118)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(Acq

**Comment by Flanker32** [comment]
@AnimalFarm0101 Thanks for your report and really sorry for the late response. Could this issue be stable reproduced in your machine? Besides, could you please help upgrade to the latest toolkit and see whether the issue still exists?
