### ISSUE TITLE
[IntelliJ 2017] Failed to show Web Apps list

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/azure-tools-for-java#508]
Steps:
1. open Azure Explorer
2. click the 'Wep Apps' node

Actual:
Failed to show Web Apps list. Try again, it is able to show.

```
○ Comment:
Error updating webapps cache: Task java.util.concurrent.FutureTask@24902ce6 rejected from java.util.concurrent.ThreadPoolExecutor@78fd8c61[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
○ Detail:
Error updating webapps cache: Task java.util.concurrent.FutureTask@24902ce6 rejected from java.util.concurrent.ThreadPoolExecutor@78fd8c61[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
rx.exceptions.OnErrorNotImplementedException: Task java.util.concurrent.FutureTask@24902ce6 rejected from java.util.concurrent.ThreadPoolExecutor@78fd8c61[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
    at rx.observables.BlockingObservable$8.call(BlockingObservable.java:641)
    at rx.observables.BlockingObservable$8.call(BlockingObservable.java:638)
    at rx.observables.BlockingObservable$9.onError(BlockingObservable.java:674)
    at rx.internal.operators.NotificationLite.accept(NotificationLite.java:132)
    at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:534)
    at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:666)
    at rx.observables.BlockingObservable.subscribe(BlockingObservable.java:638)
    at com.microsoft.azuretools.utils.AzureModelController.updateResGrDependency(AzureModelController.java:209)
    at com.microsoft.azuretools.utils.AzureModelController.updateResourceGroupMaps(AzureModelController.java:309)
    at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refreshItems(WebappsModule.java:55)
    at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:89)
    at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:127)
    at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@24902ce6 rejected from java.util.concurrent.ThreadPoolExecutor@78fd8c61[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
    at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase.postRunAsync(AcquireTokenHandlerBase.java:146)
    at com.microsoft.azuretools.adauth.AcquireTokenHandlerBase.run(AcquireTokenHandlerBase.java:104)
    at com.microsoft.azuretools.adauth.AuthContext.acquireToken(AuthContext.java:58)
    at com.microsoft.azuretools.authmanage.AdAuthManager.getAccessToken(AdAuthManager.java:65)
    at com.microsoft.azuretools.authmanage.RefreshableTokenCredentials.getToken(RefreshableTokenCredentials.java:64)
    at com.microsoft.azure.credentials.AzureTokenCredentials.getToken(AzureTokenCredentials.java:39)
    at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:36)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
    at com.microsoft.azuretools.telemetry.TelemetryInterceptor.intercept(TelemetryInterceptor.java:46)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
    at okhttp3.RealCall.execute(RealCall.java:57)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
    at rx.Subscriber.setProducer(Subscriber.java:211)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
    at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
    at rx.Observable.unsafeSubscribe(Observable.java:10142)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:10238)
    at rx.Observable.subscribe(Observable.java:10205)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
    at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
    at com.microsoft.azure.management.appservice.implementation.AppServicePlansInner.listByResourceGroup(AppServicePlansInner.java:442)
    at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.listByResourceGroup(TopLevelModifiableResourcesImpl.java:121)
    at com.microsoft.azuretools.utils.AzureModelController$4$1.call(AzureModelController.java:200)
    at com.microsoft.azuretools.utils.AzureModelController$4$1.call(AzureModelController.java:196)
    at rx.Observable.unsafeSubscribe(Observable.java:10142)
    at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
    at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    ... 3 more


java.lang.NullPointerException
    at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.fillWebappsNodes(WebappsModule.java:83)
    at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.access$000(WebappsModule.java:38)
    at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule$1.run(WebappsModule.java:62)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![image](https://cloud.githubusercontent.com/assets/1050213/26292815/8e179cb4-3eeb-11e7-9bae-5319a3047aa9.png)
![image](https://cloud.githubusercontent.com/assets/1050213/26292818/94979b0c-3eeb-11e7-8124-555ee2d1c2be.png)

**Comment by adashen** [comment]
@bsaby please help to verify whether it is regression

**Comment by davidliangze** [comment]
Do not reproduce in released version and daily.9. build on IntelliJ 2017 [Linux].
