### ISSUE TITLE
[IntelliJ][ReportedByUser] MS Azure Explorer - Error Loading Container Registries

### ISSUE THREAD

**Issue by haomiaolucky** [microsoft/azure-tools-for-java#5085]
IntelliJ build version: 2019.2.4 IU-192.7142.36
OS: Windows 10
JDK: JetBrains s.r.o 11.0.4
Plugin version: 3.33.1-2019.2
Error message: 
```
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsInner.list(ResourceGroupsInner.java:687)
	at com.microsoft.azure.management.resources.implementation.ResourceGroupsImpl.list(ResourceGroupsImpl.java:41)
	at com.microsoft.azure.management.containerregistry.implementation.RegistriesImpl.list(RegistriesImpl.java:55)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listRegistryBySubscriptionId(ContainerRegistryMvpModel.java:87)
	at com.microsoft.azuretools.core.mvp.model.container.ContainerRegistryMvpModel.listContainerRegistries(ContainerRegistryMvpModel.java:72)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.ContainerRegistryModulePresenter.onModuleRefresh(ContainerRegistryModulePresenter.java:38)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.container.Contain

**Comment by andxu** [comment]
hi @haomiaolucky , have you used a proxy?

**Comment by andxu** [comment]
Hi @haomiaolucky , could you try this article, and tell us whether you can solve this problem?
https://mkyong.com/webservices/jax-ws/suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target/
