### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.

### ISSUE THREAD

**Issue by serpensalbus** [microsoft/azure-tools-for-java#5107]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.51.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1918x949,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.setAttribute(Unknown Source)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.WorkspaceTaggingService.getAzureSDKEntities_aroundBody2(WorkspaceTaggingService.java:81)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.WorkspaceTaggingService$AjcClosure3.run(WorkspaceTaggingService.java:1)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.lambda$readCache$0(CacheManager.java:121)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.readCache(CacheManager.java:118)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.ajc$inlineAccessMethod$com_microsoft_azure_toolkit_lib_common_cache_CacheManager$com_microsoft_a

**Comment by Flanker32** [comment]
@serpensalbus Thanks for your report, could you please try to use "No Proxy" setting as a workaround: Settings (Preferences on macOS) | Appearance & Behavior | System Settings | HTTP Proxy | No proxy.

refers https://youtrack.jetbrains.com/issue/IDEA-266146

**Comment by serpensalbus** [comment]
That solved the problem! The cause seems to be the update of IDEA in general. Thanks!
