### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=GEP, containerState=DISPOSE_COMPLETED, componentStore=E:\Projects\GEP) (disposed)

### ISSUE THREAD

**Issue by crichey** [microsoft/azure-tools-for-java#5115]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.51.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1401,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=GEP, containerState=DISPOSE_COMPLETED, componentStore=E:\Projects\GEP) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:203)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.trackProjectDependencies(WorkspaceTaggingActivity.java:40)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$0(WorkspaceTaggingActivity.java:35)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$1(WorkspaceTaggingActivity.java:35)

**Comment by Flanker32** [comment]
@crichey Thanks a lot for your report , we will fix the issue asap, tracking [here](https://github.com/microsoft/azure-tools-for-java/issues/5121)
