### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=mobilegateway, containerState=DISPOSE_COMPLETED, componentStore=/Users/sabareeshsubramani/IdeaProjects/mobile-gateway) (disposed)

### ISSUE THREAD

**Issue by sabareeshkkanan** [microsoft/azure-tools-for-java#5120]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.51.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1920x1027,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=mobilegateway, containerState=DISPOSE_COMPLETED, componentStore=/Users/sabareeshsubramani/IdeaProjects/mobile-gateway) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:203)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.trackProjectDependencies(WorkspaceTaggingActivity.java:40)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$0(WorkspaceTaggingActivity.java:35)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActi

**Comment by Flanker32** [comment]
@sabareeshkkanan Thanks a lot for your report , we will fix the issue asap, tracking [here](https://github.com/microsoft/azure-tools-for-java/issues/5121)
