### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=java, containerState=DISPOSE_COMPLETED, componentStore=/home/gerard/repos/powerbi/java) (disposed)

### ISSUE THREAD

**Issue by gerardv** [microsoft/azure-tools-for-java#5121]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Linux
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.51.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,37,919x616,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=java, containerState=DISPOSE_COMPLETED, componentStore=/home/gerard/repos/powerbi/java) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:203)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.trackProjectDependencies(WorkspaceTaggingActivity.java:40)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$0(WorkspaceTaggingActivity.java:35)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lamb

**Comment by Flanker32** [comment]
@gerardv Thanks for your report, we will fix the issue soon.
