### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=schedules, containerState=DISPOSE_COMPLETED, componentStore=D:\schedulesGit\Inbound) (disposed)

### ISSUE THREAD

**Issue by junketer** [microsoft/azure-tools-for-java#5168]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.51.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=schedules, containerState=DISPOSE_COMPLETED, componentStore=D:\schedulesGit\Inbound) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:203)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.trackProjectDependencies(WorkspaceTaggingActivity.java:40)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$0(WorkspaceTaggingActivity.java:35)
	at com.microsoft.azure.toolkit.intellij.azuresdk.dependencesurvey.activity.WorkspaceTaggingActivity.lambda$runActivity$1(WorkspaceTagg

**Comment by Flanker32** [comment]
@junketer Thanks a lot for your report , we have fixed this issue and will release the new version soon., tracking [here](https://github.com/microsoft/azure-tools-for-java/issues/5121)
