### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by raniemi** [microsoft/azure-tools-for-java#5187]
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,28,824x492,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.microsoft.intellij.ui.SignInWindow.fromAccountEntity(SignInWindow.java:367)
	at com.microsoft.intellij.ui.SignInWindow.lambda$doDeviceLogin$22(SignInWindow.java:339)
```

**Comment by andxu** [comment]
Fixed in https://github.com/microsoft/azure-tools-for-java/pull/5159
