### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: e57a74e0-1b61-4e88-94b8-868911de679c] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed. java.lang.InterruptedException: sleep interrupted

### ISSUE THREAD

**Issue by craze-ding** [microsoft/azure-tools-for-java#5195]
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: e57a74e0-1b61-4e88-94b8-868911de679c] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed., throwable=java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.acquireTokenWithDeviceCode(AcquireTokenByDeviceCodeFlowSupplier.java:62)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:27)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
```

**Comment by andxu** [comment]
This error is not affecting the functionality. Please ignore it.

**Comment by Flanker32** [comment]
Close the issue as it will not break the experience
