### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: f7e91303-9f2a-4c83-86eb-d860dbfe3084] Execution of class com.microsoft.aad.msal4j.AccountsSupplier failed. com.microsoft.aad.msal4j.MsalClientException: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: login.microsoftonline.com

### ISSUE THREAD

**Issue by MehrdadDehghani** [microsoft/azure-tools-for-java#5197]
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1582x862,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: f7e91303-9f2a-4c83-86eb-d860dbfe3084] Execution of class com.microsoft.aad.msal4j.AccountsSupplier failed., throwable=com.microsoft.aad.msal4j.MsalClientException: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: login.microsoftonline.com
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:68)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:157)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvide

**Comment by Flanker32** [comment]
@MehrdadDehghani Thanks for your report and really sorry for the late response. Could this issue be stable reproduced in your machine? Besides, could you please help upgrade to the latest toolkit and see whether the issue still exists?
