### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 06dd6a42-9a7c-4ac8-80ca-f76bbaaa064f] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed. com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.

### ISSUE THREAD

**Issue by suryamgm** [microsoft/azure-tools-for-java#5203]
IntelliJ build version: 2021.1.1 IC-211.7142.45
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,28,841x516,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 06dd6a42-9a7c-4ac8-80ca-f76bbaaa064f] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed., throwable=com.microsoft.aad.msal4j.MsalInteractionRequiredException: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.
Trace ID: b91d4ada-8f71-4a12-8988-cfab16391901
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:37)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:96)
	at com.microsoft.aad.msal4j.TokenRequestEx

**Comment by wangmingliang-ms** [comment]
Azure identity SDK should cause this bug, it's upgraded in our plugin.
can you try the latest version?
