### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by MySelfSivaKrishna** [microsoft/azure-tools-for-java#5206]
#### Setup

IntelliJ build version: 2021.1.1 IC-211.7142.45
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1

####  Describe the bug

A clear and concise description of what the bug is, including expected behavior and actual behavior

i am not able login to azure toolkit for intellij
####  To Reproduce

Steps to reproduce the bug

1) when i try to sign in,using azure toolkit for intellij ,
2)i am not able to login

#### Exception or Stack Trace

Add the exception log and stack trace if available.

May 12, 2021 8:40:40 AM com.microsoft.intellij.AzureActionsListener initLoggerFileHandler
INFO: === Log session started ===
May 12, 2021 9:11:44 AM com.microsoft.azure.toolkit.lib.common.exception.AzureExceptionHandler handleException
WARNING: caught an error in AzureExceptionHandler
rx.exceptions.OnErrorNotImplementedException: Cannot login due to error
	at rx.functions.Actions$NotImplemented.call(Actions.java:576)
	at rx.functions.Actions$NotImplemented.call(Actions.java:572)
	at rx.Single$11.onError(Single.java:1794)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:224)
	at rx.internal.operators.SingleOperatorOnErrorResumeNext$2.onError(SingleOperatorOnErrorResumeNext.java:71)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onError(SingleOnSubscribeMap.java:85)
	at rx.internal.operators.SingleDoOnEvent$SingleDoOnEventSubscriber.onError(SingleDoOnEvent.java:76)
	at rx.Single$2$1.onError(Single.java:692)
	at rx.internal.operators.SingleOnSubscribeMap$MapSubscriber.onError(SingleOnSubscribeMap.java:85)
	at rx.internal.operators.SingleDoOnEvent$SingleDoOnEventSubscriber.onError(SingleDoOnEvent.java:76)
	at rx.internal.operators.OnSubscribeSingle$1.onError(OnSubscribeSingle.java:64)
	at rx.internal.operators.OnSubscribeCreate$BaseEmitter.onError(OnSubscribeCreate.java:109)
	at rx.internal.operators.OnSubscribeCreate$BufferEmitter.drain(OnSubscribeCreate.java:355)
	at rx.internal.operators.OnSubscribeCreate$BufferEmitter.onError(OnSubscribeCreate.java:306)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:362)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:85)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:357)
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager$3.run(IntellijAzureTaskManager.java:90)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: Cannot login due to error
	at com.microsoft.intellij.actions.AzureSignInAction.lambda$doSignIn$5(AzureSignInAction.java:150)
	at rx.internal.operators.SingleOperatorOnErrorResumeNext$2.onError(SingleOperatorOnErrorResumeNext.java:69)
	... 30 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary
	at com.microsoft.aad.msal4jextensions.persistence.mac.KeyChainAccessor.read(KeyChainAccessor.java:49)
	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.beforeCacheAccess(PersistenceTokenCacheAccessAspect.java:125)
	at com.azure.identity.implementation.PersistentTokenCacheImpl.beforeCacheAccess(PersistentTokenCacheImpl.java:68)
	at com.microsoft.aad.msal4j.TokenCache$CacheAspect.<init>(TokenCache.java:165)
	at com.microsoft.aad.msal4j.TokenCache.saveTokens(TokenCache.java:182)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:123)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.acquireTokenWithAuthorizationCode(AcquireTokenByInteractiveFlowSupplier.java:166)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:39)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

#### Screenshots

Add screenshots to help explain your problem if available.

**Comment by MySelfSivaKrishna** [comment]
i replaced the bundled plugin with older version ( Azure Toolkit for IntelliJ 3.51.0-2021.1),it started working now.

**Comment by andxu** [comment]
Can you switch to use azure cli temporary: install azure cli and login through `az login`?

**Comment by andxu** [comment]
Opened an issue at microsoft-authentication-extensions-for-java: https://github.com/AzureAD/microsoft-authentication-extensions-for-java/issues/31

**Comment by andxu** [comment]
Hi @MySelfSivaKrishna, can you take a try of the following code in your idea:
create a simple java project(maven or gradle) and add this dependency : https://mvnrepository.com/artifact/com.microsoft.azure/msal4j-persistence-extension/1.1.0
```java
package com.example.sample;

import com.microsoft.aad.msal4jextensions.persistence.mac.ISecurityLibrary;

public class App {
    public static void main(String[] args) {
        ISecurityLibrary.library.CFRelease(null);
    }
}

```
