### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with device code

### ISSUE THREAD

**Issue by Krishnas455** [microsoft/azure-tools-for-java#5264]
IntelliJ build version: 2020.3.3 IU-203.7717.56
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2020.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1440x847,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with device code
Caused by: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with device code
		at com.microsoft.intellij.ui.SignInWindow.doDeviceLogin(SignInWindow.java:350)
		at com.microsoft.intellij.ui.SignInWindow.doLogin(SignInWindow.java:207)
		at com.microsoft.intellij.ui.SignInWindow.lambda$login$6(SignInWindow.java:185)
		at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:359)
		at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:85)

**Comment by Flanker32** [comment]
@Krishnas455 Thanks for your report and really sorry for the late response, could you please upgrade to the latest toolkit and see whether the issue could be reproduced?
