### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 6ec2a519-3f29-4112-8c52-f3adfb8ef108] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed. com.microsoft.aad.msal4j.MsalClientException: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: connection timed out: login.microsoftonline.com/20.190.155.131:443

### ISSUE THREAD

**Issue by manojs-kr** [microsoft/azure-tools-for-java#5278]
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.52.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,28,824x481,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 6ec2a519-3f29-4112-8c52-f3adfb8ef108] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed., throwable=com.microsoft.aad.msal4j.MsalClientException: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: connection timed out: login.microsoftonline.com/20.190.155.131:443
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:68)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest

**Comment by andxu** [comment]
hi @manojs-kr, Can you try to login using device code again?
Seems your network is bad and cannot connect to login.microsoftonline.com
