### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by dnwiebe** [microsoft/azure-tools-for-java#5439]
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Linux
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,37,2200x808,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=Driver, containerState=DISPOSE_COMPLETED, componentStore=/home/dnwiebe/Documents/Workspaces/SkyL/SmartTrade/Driver) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=Driver, containerState=DISPOSE_COMPLETED, componentStore=/home/dnwiebe/Documents/Workspaces/SkyL/SmartTrade/Driver) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)

**Comment by wangmingliang-ms** [comment]
fixed by https://github.com/microsoft/azure-tools-for-java/pull/5447/files#diff-2363a88a020a024967ef886103d5b79fbf3f0ba0cb91984f4000e5117b8c06aaR27-R29
