### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by torabTech** [microsoft/azure-tools-for-java#5441]
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x900,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS., throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:157)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache

**Comment by andxu** [comment]
Duplicate as #6048
