### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by raw34** [microsoft/azure-tools-for-java#5444]
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,28,910x484,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: load Azure SDK meta data from github
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: load Azure SDK meta data from github
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:77)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService.getAzureSDKEntities_aroundBody2(AzureSdkLibraryService.java:158)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.AzureSdkLibraryService$AjcClosure3.run(AzureSdkLibraryService.java:1)
	at com.microsoft.azure.toolkit.l

**Comment by Flanker32** [comment]
The issue has been fixed in https://github.com/microsoft/azure-tools-for-java/pull/5447, please upgrade to the latest toolkit once you meet the same issue
