### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group Idea Thread Group failed with an uncaught exception reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 4 queries 

### ISSUE THREAD

**Issue by guitarsheng** [microsoft/azure-tools-for-java#5451]
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.53.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1502x961,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group Idea Thread Group failed with an uncaught exception, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 4 queries 
Caused by: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: failed to resolve 'management.azure.com' after 4 queries 
		at com.microsoft.azure.toolkit.lib.auth.AzureAccount.getSubscription_aroundBody2(AzureAccount.java:278)
		at com.microsoft.azure.toolkit.lib.auth.AzureAccount$AjcClosure3.run(AzureAccount.java:1)
		at com.microsoft.az

**Comment by Flanker32** [comment]
@guitarsheng Thanks for your report and sorry for the late response, could this issue be stable reproduced? By the way, could you please upgrade to the latest toolkit and see whether the issue still exists?
