### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by irivintiranjit** [microsoft/azure-tools-for-java#5460]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x513,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=spring-app, containerState=DISPOSE_COMPLETED, componentStore=D:\JavaMaterial\spring-app) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=spring-app, containerState=DISPOSE_COMPLETED, componentStore=D:\JavaMaterial\spring-app) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)
	at com.microsoft.azure.toolkit.intellij.azuresdk.enforcer.AzureSdkE

**Comment by wangmingliang-ms** [comment]
same as #5439
