### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: AZURE_FUNCTION_SUPPORT-Deploy Functions_ backoffice_DKBoFeePayment_ factoryName_ Deploy Functions.xml com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.microsoft.azure.toolkit.intellij.function.runner.deploy.FunctionDeployModel$DeprecatedDeployModel

### ISSUE THREAD

**Issue by capkmd** [microsoft/azure-tools-for-java#5494]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: Reopen Inttellij
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: AZURE_FUNCTION_SUPPORT-Deploy Functions_ backoffice_DKBoFeePayment_ factoryName_ Deploy Functions.xml, throwable=com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.microsoft.azure.toolkit.intellij.function.runner.deploy.FunctionDeployModel$DeprecatedDeployModel
	at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:58)
	at com.microsoft.azure.toolkit.intellij.function.runner.deploy.FunctionDeployConfiguration.lambda$readExternal$1(FunctionDeployConfiguration.java:155)
	at com.microsoft.azure.toolkit.intellij.function.runner.deploy.

**Comment by Flanker32** [comment]
@capkmd Thanks for your report, we make some changes to function deployment run configuration and this should be the issue when convert old function configuration to new one. Could you please try create a new configuration and try deploy again?
