### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: org/jetbrains/idea/maven/utils/MavenProcessCanceledException [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by sashwinee** [microsoft/azure-tools-for-java#5498]
IntelliJ build version: 2020.1.2 IU-201.7846.76
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.7
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x507,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: org/jetbrains/idea/maven/utils/MavenProcessCanceledException [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:200)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:101)
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/idea/maven/utils/MavenProcessCanceledException
Caused by: java.lang.ClassNotFoundException: org.jetbrains.idea.maven.utils.MavenProcessCanceledException
```

**Comment by Flanker32** [comment]
@sashwinee Thanks for your report and sorry for the late response. Is there any way to reproduce this issue? Besides, could you please upgrade to the latest toolkit and see whether the issue still exists?
