### ISSUE TITLE
Eclipse - Configure Application Insights - missing file's error

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#550]
Repro steps:
Right click project and choose Configure Application Insights...
Choose a insight
Run project
![image](https://cloud.githubusercontent.com/assets/22470312/26389067/9499983a-408a-11e7-9730-942667bf3a9e.png)

**Comment by adashen** [comment]
Please verify on the release build

**Comment by bsaby** [comment]
Build:artifacts/WindowsAzurePlugin4EJ.release.5.05-24-2017.zip
Before configuration, the project can run successfully.
After Insight configuration,while running  project, web page displays 404 error.
![image](https://cloud.githubusercontent.com/assets/22470312/26392590/c2e7eaac-4099-11e7-81a0-36e1aad2a18c.png)

Error log:
Exception in getClasspathEntries
java.lang.NullPointerException
	at com.microsoft.azuretools.wasdkjava.ui.classpath.ClasspathContainer.getClasspathEntries(ClasspathContainer.java:111)
	at org.eclipse.jst.j2ee.classpathdep.ClasspathDependencyUtil.getComponentClasspathDependencies(ClasspathDependencyUtil.java:395)
	at org.eclipse.jst.j2ee.internal.classpathdep.ClasspathDependencyValidator.validateInJob(ClasspathDependencyValidator.java:165)
	at org.eclipse.wst.validation.internal.operations.ValidatorJob.run(ValidatorJob.java:78)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by bsaby** [comment]
Test passed, using artifacts/WindowsAzurePlugin4EJ.develop.daily.13.05-24-2017.zip.
