### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: get details of all cached subscriptions

### ISSUE THREAD

**Issue by surajhosakotee** [microsoft/azure-tools-for-java#5526]
IntelliJ build version: 2020.2.4 IC-202.8194.7
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.9
Plugin version: 3.49.1-2020.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x507,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: get details of all cached subscriptions
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:41)
	at com.microsoft.azuretools.authmanage.SubscriptionManager.getSubscriptionDetails(SubscriptionManager.java:56)
	at com.microsoft.intellij.util.AzureLoginHelper.ensureAzureSubsAvailable(AzureLoginHelper.java:28)
	at com.microsoft.azure.toolkit.intellij.common.AzureRunConfigurationBase.checkAzurePreconditions(AzureRunConfigurationBase.java:84)
	at com.microsoft.azure.toolkit.intellij.springcloud.runner.deploy.SpringCloudDeployConfiguration.validate(SpringCloudDeployConfiguration.java:215)
	at com.microsoft.azure.toolkit.intellij.common.AzureSettingsEditor.applyEditorTo(AzureSettingsEditor.java:25)
	at com.m

**Comment by andxu** [comment]
The version you used is out of date, please upgrade it.
