### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by rzaragozasolis** [microsoft/azure-tools-for-java#5551]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,1920x1313,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS., throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.getSubscription_aroundBody2(AzureAccount.java:280)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount$AjcClosure3.run(AzureAccount.java:1)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.lambda$readCache$0(CacheManager.java:121)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.readCache(CacheManager.java:118)
	at com.microsoft.azure.toolkit.lib.common.cache.CacheManager.ajc$i

**Comment by andxu** [comment]
Dup as #5441
