### ISSUE TITLE
[Intellij2016 &2017] It says 'Unable to open debugger port (localhost:63602): java.io.IOException "handshake failed' when you remote debug

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#556]
I used spark2withblob to test it.
1. configure debug and set ssh wrong password.
2. Configure debug and set ssh right password.
Then it shows when you debug:
Error running mytestdbg: Unable to open debugger port (localhost:63602): java.io.IOException "handshake failed - connection prematurally closed"

**Comment by wezhang** [comment]
reproduced

**Comment by wezhang** [comment]
The `maximum allowed retries number: 0` may be root cause:

```
17/05/25 00:32:17 WARN Client: Failed to connect to server: hn0-spark2.2fg5l30kxmeenl5iiu3fcxxvdc.cx.internal.cloudapp.net/10.0.0.15:8050: retries get failed due to exceeded maximum allowed retries number: 0 java.net.ConnectException: Connection refused at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206) at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531) at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495) at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:650) at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:745) at org.apache.hadoop.ipc.Client$Connection.access$3200(Client.java:397) at org.apache.hadoop.ipc.Client.getConnection(Client.java:1618) at org.apache.hadoop.ipc.Client.call(Client.java:1449) at org.apache.hadoop.ipc.Client.call(Client.java:1396) at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233) at com.sun.proxy.$Proxy11.getClusterMetrics(Unknown Source) at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getClusterMetrics(ApplicationClientProtocolPBClientImpl.java:206) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:278) at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:194) at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:176) at com.sun.proxy.$Proxy12.getClusterMetrics(Unknown Source) at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getYarnClusterMetrics(YarnClientImpl.java:506) at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:154) at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:154) at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54) at org.apache.spark.deploy.yarn.Client.logInfo(Client.scala:60) at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:153) at org.apache.spark.deploy.yarn.Client.run(Client.scala:1186) at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1245) at org.apache.spark.deploy.yarn.Client.main(Client.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736) at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185) at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210) at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124) at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) 17/05/25 00:32:17 INFO ConfiguredRMFailoverProxyProvider: Failing over to rm2
```

**Comment by wezhang** [comment]
root cause is the ssh server password is expired:

```
You are required to change your password immediately (password aged)

<...>

WARNING: Your password has expired.
```

Change the password and no problems found.

**Comment by ruoxinCheng** [comment]
Yes, verified it.
