### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.

### ISSUE THREAD

**Issue by is4ii4s** [microsoft/azure-tools-for-java#5562]
IntelliJ build version: 2021.1.3 IC-211.7628.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1200,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
Caused by: rx.exceptions.OnErrorNotImplementedException: Already disposed: Project(name=saladereuniao, containerState=DISPOSE_COMPLETED, componentStore=/Users/isaias.souza/java-workspace/projetos/saladereuniao) (disposed)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=saladereuniao, containerState=DISPOSE_COMPLETED, componentStore=/Users/isaias.souza/java-workspace/projetos/saladereuniao) (disposed)
	at com.microsoft.azure.toolkit.intellij.azuresdk.service.ProjectLibraryService.getProjectLibraries(ProjectLibraryService.java:27)
	at com.microsoft.azure.toolkit.intellij.

**Comment by andxu** [comment]
Duplicate and fix, see #5439
