### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Setting properties with null kind is unsupported

### ISSUE THREAD

**Issue by tgpmoraes** [microsoft/azure-tools-for-java#5567]
IntelliJ build version: 2021.1.3 IC-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.54.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,7,0,824x512,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Setting properties with null kind is unsupported
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfiguration$fixDependence$1.invoke(SparkScalaLocalConsoleRunConfiguration.kt:241)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfiguration$fixDependence$1.invoke(SparkScalaLocalConsoleRunConfiguration.kt:59)
	at com.microsoft.intellij.util.ApplicationHelpersKt$runInWriteAction$1.compute(ApplicationHelpers.kt:34)
	at com.microsoft.intellij.util.ApplicationHelpersKt.runInWriteAction(ApplicationHelpers.kt:34)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRunConfiguration.fixDependence(SparkScalaLocalConsoleRunConfiguration.kt:231)
	at com.microsoft.azure.hdinsight.spark.console.SparkScalaLocalConsoleRu

**Comment by wezhang** [comment]
Thanks! I suppose it's fixed by #5438  and v3.59.0, if you hit it again. Feel free to reopen this, please.
