### ISSUE TITLE
test case failed

### ISSUE THREAD

**Issue by voidfunction** [Microsoft/azure-tools-for-java#563]
details http://vscjavaci.cloudapp.net/job/AzureToolsManager_PR/135/consoleFull

`
Scenario: getSparkDriverHost negative integration test with responses for failed jobs  Time elapsed: 0.004 sec  <<< ERROR!
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:311)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:299)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:94)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:248)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:243)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:94)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:98)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchRemoteDebugJobScenario.mockLivyService(SparkBatchRemoteDebugJobScenario.java:167)
	at ✽.Given setup a mock livy service for GET request 'http://127.0.0.1:9876/batch/9' to return '{"id":9,"state":"starting","appId":"application_1492415936046_0015","appInfo":{"driverLogUrl":"http://127.0.0.1:9876/yarnui/10.0.0.15/node/containerlogs/container_e02_1492415936046_0015_01_000001/livy","sparkUiUrl":"https://spkdbg.azurehdinsight.net/yarnui/hn/proxy/application_1492415936046_0015/"},"log":["\t ApplicationMaster RPC port: -1","\t queue: default","\t start time: 1492569369011","\t final status: UNDEFINED","\t tracking URL: https://spkdbg.azurehdinsight.net/yarnui/hn/proxy/application_1492415936046_0015/","\t user: livy","17/04/19 02:36:09 INFO ShutdownHookManager: Shutdown hook called","17/04/19 02:36:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-1984dc9d-acd4-4648-9104-398431590f8e","YARN Diagnostics:","AM container is launched, waiting for AM container to Register with RM"]}' with status code 200(com/microsoft/azure/hdinsight/spark/common/SparkBatchRemoteDebugJobScenario.feature:63)

Running com.microsoft.azure.hdinsight.common.logger.UILoggerAppenderTest
Feature: UI Logger Appender for log4j test`

**Comment by wezhang** [comment]
Can't reproduce in my local machine.
