### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project(aep-mbo-azure-functions)

### ISSUE THREAD

**Issue by ethancheah-arvato** [microsoft/azure-tools-for-java#5708]
IntelliJ build version: 2021.2 IU-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.55.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,958x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project(aep-mbo-azure-functions)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:77)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.listFunctionModules(FunctionUtils.java:138)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.ui.FunctionRunPanel.fillModules(FunctionRunPanel.java:157)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.ui.FunctionRunPanel.<init>(FunctionRunPanel.java:73)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.FunctionRunSettingEditor.<init>(FunctionRunSettingEditor.java:22)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.FunctionRunConfiguration.getC

**Comment by Flanker32** [comment]
@ethancheah-arvato Thanks for your report, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/6120
