### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: add new Azure resource connector

### ISSUE THREAD

**Issue by seanb4t** [microsoft/azure-tools-for-java#5719]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.55.1-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,28,2163x1798,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: add new Azure resource connector
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:77)
	at com.microsoft.azure.toolkit.intellij.connector.explorer.ConnectorToolWindow$AddAction.actionPerformed(ConnectorToolWindow.java:120)
Caused by: com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.intellij.appservice.subscription.SubscriptionComboBox.<init>(SubscriptionComboBox.java:23)
	at com.microsoft.azure.toolkit.intellij.connector.database.DatabaseResourcePanel.$$$

**Comment by wangmingliang-ms** [comment]
fixed in latest version
