### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by sureshputla** [microsoft/azure-tools-for-java#5760]
IntelliJ build version: 2021.2.1 IC-212.5080.55
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1330x680,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.intellij.common.component.SubscriptionComboBox.<init>(SubscriptionComboBox.java:23)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceInfoAdvancedPanel.$$$setupUI$$$(AppServiceInfoAdvancedPanel.java)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceInfoAdvancedPanel.<init>(AppServiceInfoAdvancedPanel.java:76)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppConfigFormPanelAdvance.createUIComponents(WebAppConfigFormPanelAdvance.java:70)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppConfig

**Comment by Flanker32** [comment]
@sureshputla Thanks for your report! The issue should be fixed in #5954, could you please upgrade to the latest toolkit and retry the feature?
