### ISSUE TITLE
[IntelliJ][ReportedByUser] Customer Issues

### ISSUE THREAD

**Issue by decifris** [microsoft/azure-tools-for-java#5761]
#### Setup

IntelliJ build version: 2021.2 IC-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2

####  Describe the bug

I'm using the example repo of Spring Cloud Functions in azure and running the app using mvn from cmd works fine, running the app from the "run function" doesn't work properly. Seems like it doesn't package the spring stuff, while the azure functions alone work fine. If I run the function and go to the api url, gives me 500 error and an error of "cannot find class" or "nullpointerexception" etc... like this:
`System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure
Exception: NullPointerException: Cannot invoke "org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(Object)" because "function" is null
Stack: java.lang.reflect.InvocationTargetException`

####  To Reproduce

Just run the example repository from [here](https://github.com/Azure-Samples/hello-spring-function-azure) and use the azure tool of intellij

#### Exception or Stack Trace

One of the errors I get:
`System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure
Exception: NullPointerException: Cannot invoke "org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(Object)" because "function" is null
Stack: java.lang.reflect.InvocationTargetException`

**Comment by andxu** [comment]
Same issue as https://github.com/microsoft/azure-gradle-plugins/issues/113, the root cause is the jar built by spring boot plugin is not a common jar, it will have classes in `BOOT-INF/classes`

**Comment by andxu** [comment]
Currently we are investigating and will fix it ASAP, it seams caused by a minor difference between the jar we generated and maven generated

**Comment by hskims** [comment]
IntelliJ build version: IU-212.5284.40
OS: Windows 10
JDK: openjdk version "15" 2020-09-15 / OpenJDK Runtime Environment (build 15+36-1562)
plugin version: 3.57.1-2021.2

Has this issue been fixed? The issue is still appearing.
#5828 said it was fixed, and it seems to have been applied to plugins as well. But it still appears to be happening. 

```
2021-10-05T01:29:14.560Z] System.Private.CoreLib: Exception while executing function: Functions.reportListFunc. System.Private.CoreLib: Result: Failure
Exception: NullPointerException: Cannot invoke "org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(Object)" because "function" is null
Stack: java.lang.reflect.InvocationTargetException
[2021-10-05T01:29:14.560Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-10-05T01:29:14.560Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[2021-10-05T01:29:14.561Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-10-05T01:29:14.561Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2021-10-05T01:29:14.561Z] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2021-10-05T01:29:14.561Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-10-05T01:29:14.561Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-10-05T01:29:14.561Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[2021-10-05T01:29:14.561Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[2021-10-05T01:29:14.561Z] 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by andxu** [comment]
Hi @decifris, can you reproduce this issue on latest bit : 3.59.0?
