### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group Idea Thread Group failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(springcloud-app-20210830140627) from config

### ISSUE THREAD

**Issue by tedyoung** [microsoft/azure-tools-for-java#5763]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,22,1920x1035,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group Idea Thread Group failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(springcloud-app-20210830140627) from config
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.execute(SpringCloudDeploymentConfigurationState.java:96)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$0(SpringCloudDeploymentConfigurationState.java:69)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: creat

**Comment by Flanker32** [comment]
@tedyoung Thanks for your report and sorry for the late response, could you please share us is there any way to reproduce this issue, besides, could you please upgrade to the latest version and try again?
