### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by smokeelow** [microsoft/azure-tools-for-java#5768]
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.getRunConfigurationFromDataContext(SparkSubmitJobAction.kt:84)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.update(SparkSubmitJobAction.kt:78)
```

**Comment by fengshuaihu** [comment]
This problem no longer occurs in the latest version. If this issue still bothers you, the notification can be disabled at Help | Find Action | Registry | ide.slow.operations.assertion.
