### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by bdhaliwalvl** [microsoft/azure-tools-for-java#5792]
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x963,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@5ea6046e,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.intellij.common.component.SubscriptionComboBox.<init>(SubscriptionComboBox.java:23)
	at com.microsoft.azure.toolkit.intellij.connector.database.DatabaseResourcePanel.$$$setupUI$$$(DatabaseResourcePanel.java)
	at com.microsoft.azure.toolkit.intellij.connector.database.DatabaseResourcePanel.<init>(DatabaseResourcePanel.java:67)
	at com.microsoft.azure.toolkit.intellij.connector.database.MySQLDatabaseResourcePanel.<init>(MySQLDatabaseResourcePanel.java:27)
	at com.microsoft.azure.toolkit.intellij.con

**Comment by Flanker32** [comment]
@bdhaliwalvl Thanks for your report! The issue should be fixed in https://github.com/microsoft/azure-tools-for-java/pull/5954, could you please upgrade to the latest toolkit and retry the feature?
