### ISSUE TITLE
java.lang.NullPointerException just while clicking on Web Apps item in Azure explorer

### ISSUE THREAD

**Issue by hovsepm** [Microsoft/azure-tools-for-java#58]
![image](https://cloud.githubusercontent.com/assets/7052173/23077835/f425087e-f4fa-11e6-851e-c8aba967eb6f.png)

Stack Trace:
java.lang.NullPointerException
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.fillWebappsNodes(WebappsModule.java:94)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappsModule.refreshItems(WebappsModule.java:64)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.refreshItems(RefreshableNode.java:76)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode$2.run(RefreshableNode.java:110)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martinsawicki** [comment]
@bsaby , we have not been able to repro it ourselves, so maybe as you test the explorer, you can see if you run into this?

**Comment by bsaby** [comment]
This issue is caused by a webapp exists in the Azure Explorer list but does not exist on portal.
The same reason as issue #77

**Comment by lenala** [comment]
Cannot repro the reported above exception, but I get NullPointerException when trying to delete already deleted resource. Reported an issue in SDK: https://github.com/Azure/azure-sdk-for-java/issues/1520

**Comment by bsaby** [comment]
Cannot repro the above exception in artifacts/WindowsAzurePlugin4EJ.95.zip.
