### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: add new Azure resource connector

### ISSUE THREAD

**Issue by WoozChucky** [microsoft/azure-tools-for-java#5812]
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1080,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: add new Azure resource connector
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.connector.explorer.ResourceConnectorTree$ModuleNode$AddAction.actionPerformed(ResourceConnectorTree.java:122)
Caused by: com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:67)
	at com.microsoft.azure.toolkit.intellij.common.component.SubscriptionComboBox.<init>(SubscriptionComboBox.java:23)
	at com.microsoft.azure.toolkit.intellij.connector.database.

**Comment by andxu** [comment]
Dup as #5802
