### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by shin6949** [microsoft/azure-tools-for-java#5821]
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1356,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@7df0f97b,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=java.lang.IllegalStateException: closed
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:274)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessage.getCause(AzureMessage.java:113)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessage.getCause(IntellijAzureMessage.java:69)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessage.getContent(AzureMessage.java:67)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessage.getContent(IntellijAzureMessage.java:62)
	at com.microsoft.azure.toolkit.intellij.common.messager.NotificationMessage.getContent(IntellijAzureMessage.java:159)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager.showNotification(IntellijAzur

**Comment by Flanker32** [comment]
@shin6949 Thanks for your report, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/5959
