### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(webdemo) from config

### ISSUE THREAD

**Issue by MikeDodaro** [microsoft/azure-tools-for-java#5838]
IntelliJ build version: 2021.2 IC-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1384x992,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(webdemo) from config
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.execute(SpringCloudDeploymentConfigurationState.java:96)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$0(SpringCloudDeploymentConfigurationState.java:69)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(web

**Comment by Flanker32** [comment]
@MikeDodaro Thanks for your report, could this issue be stable reproduced? And could you please try upgrade to the latest toolkit and try again?
