### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Cannot add an action twice: Builder (Implements Builder Design Pattern)

### ISSUE THREAD

**Issue by ydlkdevops** [microsoft/azure-tools-for-java#5840]
IntelliJ build version: 2021.2 IU-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Cannot add an action twice: Builder (Implements Builder Design Pattern)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.registerAction(IntellijAzureActionManager.java:54)
	at com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor.registerActions(ResourceCommonActionsContributor.java:43)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.lambda$register$0(IntellijAzureActionManager.java:47)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.register(IntellijAzureActionManager.java:47)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:127)
```

**Comment by wangmingliang-ms** [comment]
does this error still occurs in the latest version(3.57.0)?
