### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: !connector|connection.prepare_before_run!

### ISSUE THREAD

**Issue by Dewin** [microsoft/azure-tools-for-java#5901]
IntelliJ build version: 2021.2.2 IU-212.5284.40
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1400,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: !connector|connection.prepare_before_run!
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.connector.Connection.prepareBeforeRun(Connection.java:93)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyBeforeRunTask.lambda$execute$1(ConnectionRunnerForRunConfiguration.java:78)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration$MyBeforeRunTask.execute(ConnectionRunnerForRunConfiguration.java:78)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.executeTask(ConnectionRunnerForRunConfiguration.java:59)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunCon

**Comment by wangmingliang-ms** [comment]
please update to latest version
