### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by kanakisn** [microsoft/azure-tools-for-java#5930]
IntelliJ build version: 2021.2.2 IU-212.5284.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1009,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@d259920,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.lambda$subscriptionListener$0(ApplicationInsightsNewDialog.java:101)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:178)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.lambda$setItems$5(AzureComboBox.java:228)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel.lambda$createNewDilaog$3(AppInsightsMngmtPanel.java:221)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:371)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:87)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.jav

**Comment by wangmingliang-ms** [comment]
the class was removed, this issue should have been fixed in the latest versions.
