### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: run function app locally

### ISSUE THREAD

**Issue by SNY019** [microsoft/azure-tools-for-java#5935]
IntelliJ build version: 2021.2 IU-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.55.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: run function app locally
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:77)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:122)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:63)
	at com.microsoft.azure.toolkit.intellij.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:55)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: run function CLI command from staging folder(azure-functions13381915933733267727)

**Comment by Flanker32** [comment]
@SNY019  Thanks for your report, could you please help provide the full stack traces? Besides, could this issue be stable reproduced? If so, could you please help share the repro steps?
