### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(springcloud-app-20211018200610) from config

### ISSUE THREAD

**Issue by kevinmic99** [microsoft/azure-tools-for-java#5940]
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1388x926,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@5f2c9d5e,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(springcloud-app-20211018200610) from config
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.execute(SpringCloudDeploymentConfigurationState.java:96)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$0(SpringCloudDeploymentConfigurationState.java:69)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException

**Comment by Flanker32** [comment]
@v-kevinmic3 Thanks for your report, could you please help share the full error stack for this issue? And is there any way to reproduce it?
