### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [id:b4ffdeb1, L:/172.22.46.197:58291 - R:gate-zrh.swissre.com/172.22.1.4:8080] Error was received while reading the incoming data. The connection will be closed. java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-5

### ISSUE THREAD

**Issue by maria-ind** [microsoft/azure-tools-for-java#5959]
IntelliJ build version: 2021.1.1 IU-211.7142.45
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.57.1-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[id:b4ffdeb1, L:/172.22.46.197:58291 - R:gate-zrh.swissre.com/172.22.1.4:8080] Error was received while reading the incoming data. The connection will be closed., throwable=java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-5
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessage.getCause(AzureMessage.java:108)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureHtmlMessag

**Comment by wangmingliang-ms** [comment]
@maria-ind thanks for reporting, we upgrade reactor (from which this bug sourced) in last sprints, so this bug should have been eliminated, Can you help confirm withthe latest version?

**Comment by maria-ind** [comment]
Hello Wang,
Yes, never had this error again. Please close the ticket

**Comment by wangmingliang-ms** [comment]
thanks
