### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTokenImpl #XML  because: parent is null

### ISSUE THREAD

**Issue by slindenberg** [microsoft/azure-tools-for-java#6025]
IntelliJ build version: 2021.2 IU-212.4746.92
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1004,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction, id=SparkJobDebug) with text=SparkJobDebug, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.xml.XmlTokenImpl #XML  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.xml.XmlTokenImpl:XML_COMMENT_CHARACTERS
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfig

**Comment by wezhang** [comment]
Thanks! Dup #5762
