### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by MironAtHome** [microsoft/azure-tools-for-java#6026]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.AzurePlugin.isFirstInstallationByVersion(AzurePlugin.java:355)
	at com.microsoft.intellij.AzurePlugin.runActivity(AzurePlugin.java:117)
```

**Comment by andxu** [comment]
Fixed in #6180
