### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception: Cannot create class com.intellij.protobuf.lang.PbParserDefinition

### ISSUE THREAD

**Issue by yoricsv** [microsoft/azure-tools-for-java#6028]
IntelliJ build version: 2021.2.3 IC-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.57.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot create class com.intellij.protobuf.lang.PbParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Protocol Buffers, id=idea.plugin.protoeditor, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.2\plugins\protoedi

**Comment by Flanker32** [comment]
Error message : Uncaught Exception java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.intellij.diagnostic.PluginException: Cannot create class com.intellij.protobuf.lang.PbParserDefinition (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Protocol Buffers, id=idea.plugin.protoeditor, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.2\plugins\protoeditor, version=212.5080.8, package=com.intellij.protobuf), packagePrefix=com.intellij.protobuf., instanceId=163, state=active))

**Comment by wangmingliang-ms** [comment]
this exception should be caused by HDInsight according to the stack trace:
```
at com.intellij.execution.actions.ConfigurationContext.getConfigurationsFromContext(ConfigurationContext.java:413)
at com.intellij.execution.actions.ConfigurationContext.findPreferredConfiguration(ConfigurationContext.java:292)
at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:285)
at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.getRunConfigurationFromDataContext(SparkSubmitJobAction.kt:84)
at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.update(SparkSubmitJobAction.kt:78)
```
