### ISSUE TITLE
[IntelliJ][ReportedByUser] Cannot sign in from IntelliJ 2021.2.3

### ISSUE THREAD

**Issue by sveine** [microsoft/azure-tools-for-java#6033]
#### Setup

IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2

####  Describe the bug

Cannot sign in to Azure Explorer.

Tried to solve it by:
* Restarted my PC
* Tried OAuth 2.0 and Device login
* Tried to sign in with different browsers: Firefox, Edge, Chrome (cache was cleared)
* Deleted folder .AzureToolsForIntelliJ
* Started IntelliJ with no AppData\Roaming\JetBrains\IntelliJIdea2021.2
* Reinstalled this plugin

Other info:
* I can sign in to azure explorer in Rider.
* I can also sign in using same version of IntelliJ on another PC, same user account.
* I have been using Azure Explorer in IntelliJ previously on this PC 

#### Exception or Stack Trace

nov. 02, 2021 11:25:19 A.M. com.microsoft.intellij.AzureActionsListener initLoggerFileHandler
INFO: === Log session started ===
nov. 02, 2021 11:31:00 A.M. com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager show
WARNING: caught an error by messager
com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException: Failed to acquire token with Interactive Browser Authentication.
	at com.microsoft.intellij.actions.AzureSignInAction.call(AzureSignInAction.java:349)
	at com.microsoft.intellij.actions.AzureSignInAction.doLogin(AzureSignInAction.java:325)
	at com.microsoft.intellij.actions.AzureSignInAction.lambda$loginNonDeviceCodeSingle$16(AzureSignInAction.java:284)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:371)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:87)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:369)
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager$1.run(IntellijAzureTaskManager.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.azure.core.exception.ClientAuthenticationException: Failed to acquire token with Interactive Browser Authentication.
	at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithBrowserInteraction$40(IdentityClient.java:803)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3488)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:76)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at com.microsoft.intellij.actions.AzureSignInAction.checkCanceled(AzureSignInAction.java:358)
		at com.microsoft.intellij.actions.AzureSignInAction.lambda$doLogin$21(AzureSignInAction.java:325)
		at com.microsoft.intellij.actions.AzureSignInAction.call(AzureSignInAction.java:344)
		at com.microsoft.intellij.actions.AzureSignInAction.doLogin(AzureSignInAction.java:325)
		at com.microsoft.intellij.actions.AzureSignInAction.lambda$loginNonDeviceCodeSingle$16(AzureSignInAction.java:284)
		at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:371)
		at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:87)
		at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:369)
		at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager$1.run(IntellijAzureTaskManager.java:60)
		at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
		at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
		at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
		at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
		at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
		at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
		at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.sun.jna.platform.win32.Win32Exception: Key not valid for use in specified state.
	at com.sun.jna.platform.win32.Crypt32Util.cryptUnprotectData(Crypt32Util.java:144)
	at com.sun.jna.platform.win32.Crypt32Util.cryptUnprotectData(Crypt32Util.java:117)
	at com.sun.jna.platform.win32.Crypt32Util.cryptUnprotectData(Crypt32Util.java:104)
	at com.microsoft.aad.msal4jextensions.persistence.CacheFileAccessor.read(CacheFileAccessor.java:46)
	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.beforeCacheAccess(PersistenceTokenCacheAccessAspect.java:125)
	at com.azure.identity.implementation.PersistentTokenCacheImpl.beforeCacheAccess(PersistentTokenCacheImpl.java:68)
	at com.microsoft.aad.msal4j.TokenCache$CacheAspect.<init>(TokenCache.java:165)
	at com.microsoft.aad.msal4j.TokenCache.saveTokens(TokenCache.java:182)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:123)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.acquireTokenWithAuthorizationCode(AcquireTokenByInteractiveFlowSupplier.java:179)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:39)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 6 more

**Comment by Flanker32** [comment]
@sveine Thanks a lot for your report, it seems that there are some issues in your local identity cache, which was used by our toolkit for authentication. Could you please help try backup and delete the identity cache (in `{user_home}\AppData\local\.IdentityService`) and try again?

**Comment by sveine** [comment]
And thanks a double lot to you @Flanker32 :-) Your solution worked!
