### ISSUE TITLE
[IntelliJ][ReportedByUser] Azure Services Explorer - Error Refresh resource manage module

### ISSUE THREAD

**Issue by souvikdaskiit** [microsoft/azure-tools-for-java#6034]
IntelliJ build version: 2019.1.1 IC-191.6707.61
OS: Mac OS X
JDK: JetBrains s.r.o 1.8.0_202-release
Plugin version: 3.28.0-2019.1
Error message: 
```
java.lang.NullPointerException
	at com.microsoft.azuretools.utils.AzureModelController.lambda$null$0(AzureModelController.java:288)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Flanker32** [comment]
@souvikdaskiit Thanks for your report, this issue should be fixed in https://github.com/microsoft/azure-tools-for-java/pull/4479, could you please upgrade to the latest toolkit and try again?
