### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot get children Microsoft Tools java.nio.file.InvalidPathException: Illegal char <:> at index 16: Active code page: 65001

### ISSUE THREAD

**Issue by balin998** [microsoft/azure-tools-for-java#6054]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot get children Microsoft Tools, throwable=java.nio.file.InvalidPathException: Illegal char <:> at index 16: Active code page: 65001
C:\Users\admin\scoop\persist\nodejs\bin\node_modules\azure-functions-core-tools\bin
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.findFuncInNpm(FunctionCliResolver.java:84)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolveInner(FunctionCliResolver.java:64)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolve(FunctionCliResolver.java:31)
	at com.microsoft.azure.toolkit.lib.function.FunctionCoreToolsCombobox.reset(FunctionCoreToolsCombobox.java:102)
	at com.microsoft.azure.toolkit.lib.function.FunctionCoreToolsCombobox.<init>(FunctionCoreToolsCombobox.java:68)

**Comment by Flanker32** [comment]
@balin998 Thanks for your report, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/6090
