### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.nio.file.InvalidPathException: Illegal char <:> at index 16: Active code page: 1252

### ISSUE THREAD

**Issue by phongdeptr** [microsoft/azure-tools-for-java#6090]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.58.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.nio.file.InvalidPathException: Illegal char <:> at index 16: Active code page: 1252
C:\Users\ADMIN\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.findFuncInNpm(FunctionCliResolver.java:84)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolveInner(FunctionCliResolver.java:64)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolve(FunctionCliResolver.java:31)
	at com.microsoft.azure.toolkit.lib.function.FunctionCoreToolsCombobox.reset(FunctionCoreToolsCombobox.java:102)
	at com.microsoft.azure.toolkit.lib.function.FunctionCoreToolsCombobox.<init>(FunctionCoreToolsCombobox.java:68)
	at com.microsoft.intellij.ui.AzurePanel.createUIComponents(AzurePanel.java:

**Comment by andxu** [comment]
fixed in https://github.com/microsoft/azure-maven-plugins/pull/1863
