### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(flowspace) from config

### ISSUE THREAD

**Issue by katlehoSebiloane** [microsoft/azure-tools-for-java#6100]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1079,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(flowspace) from config
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.execute(SpringCloudDeploymentConfigurationState.java:96)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$0(SpringCloudDeploymentConfigurationState.java:69)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app

**Comment by Flanker32** [comment]
Please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/6099
