### ISSUE TITLE
[IntelliJ][ReportedByUser] AzureOperationException: list all function modules in project

### ISSUE THREAD

**Issue by capkmd** [microsoft/azure-tools-for-java#6120]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for ActionGroup(com.intellij.execution.actions.RunContextAction, id=RunClass) with text=Run context configuration, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project(backoffice)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.listFunctionModules(FunctionUtils.java:140)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.getFunctionModuleByName(FunctionUtils.java:152)
	at com.microsoft.azure.toolkit.intellij.function.runner.localrun.FunctionRunConfiguration.getMo

**Comment by Flanker32** [comment]
@capkmd Thanks for your report, could you please help provide a bit more info like the full error stack? Many thanks!

**Comment by Flanker32** [comment]
Error Message: Uncaught Exception update failed for ActionGroup(com.intellij.execution.actions.RunContextAction, id=RunClass) with text=Run context configuration com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project
