### ISSUE TITLE
Error "Failed to proceed, java.io.IOException: error=2, No such file or directory " with docker file

### ISSUE THREAD

**Issue by yuyully** [microsoft/azure-tools-for-java#6135]
Repro steps:

On Mac + IntelliJ 2021.2/2021.3, right click the project and select Add docker support > Docker run/Push image or other action with docker file, get the following error

Error:
Azure: Failed to proceed, java.io.IOException: error=2, No such file or directory (show balloon)

Error stack:
```
2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR - com.spotify.docker.client.exceptions.DockerException: java.io.IOException: Cannot run program "docker-credential-desktop": error=2, No such file or directory

2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR -     at com.spotify.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild(ConfigFileRegistryAuthSupplier.java:108)

2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR -     at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1488)

2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR -     at com.microsoft.azure.toolkit.intellij.webapp.docker.utils.DockerUtil.buildImage(DockerUtil.java:98)

2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR -     at com.microsoft.azure.toolkit.intellij.webapp.docker.dockerhost.DockerHostRunState.executeSteps(DockerHostRunState.java:118)

2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR -     at com.microsoft.azure.toolkit.intellij.webapp.docker.dockerhost.DockerHostRunState.executeSteps(DockerHostRunState.java:44)

2021-11-23 15:41:25,102 [ 614970]   INFO -  STDERR -     at com.microsoft.azure.toolkit.intellij.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:55)
```

**Comment by yuyully** [comment]
Resolution:

Open ~/.docker/config.json > Update `credsStore` to `credStore`

**Comment by Flanker32** [comment]
@v-yuyul Thanks a lot for your report, and glad to see the issue has been fixed.
