### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.LeafPsiElement #JSON  because: parent is null

### ISSUE THREAD

**Issue by pasimoes** [microsoft/azure-tools-for-java#6136]
IntelliJ build version: 2021.2.3 IE-212.5457.63
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.58.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2022x1377,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@11910a98,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.LeafPsiElement #JSON  because: parent is null
invalidated at: see attachment; com.intellij.psi.impl.source.tree.LeafPsiElement:DOUBLE_QUOTED_STRING
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:80)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.ac

**Comment by wezhang** [comment]
Thanks! Dup #5762
