### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception java.lang.AssertionError: cluster(employee-management-portal) not exist

### ISSUE THREAD

**Issue by developerdhairya** [microsoft/azure-tools-for-java#6157]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Linux
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.59.0-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,24,1920x1015,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=java.lang.AssertionError: cluster(employee-management-portal) not exist
	at com.microsoft.azure.toolkit.lib.springcloud.SpringCloudApp.create(SpringCloudApp.java:157)
	at com.microsoft.azure.toolkit.lib.springcloud.task.DeploySpringCloudAppTask.lambda$initTasks$1(DeploySpringCloudAppTask.java:86)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.springcloud.task.DeploySpringCloudAppTask.lambda$execute$4(DeploySpringCloudAppTask.java:106)
	at com.microsoft.azure.toolkit.lib.springcloud.task.DeploySpringCloudAppTask.execute(DeploySpringCloudAppTask.java:106)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.execute(Spri

**Comment by Flanker32** [comment]
@developerdhairya Thanks for your report, it seems that there are some issues with the spring cloud cluster, is the cluster a new create one or the cluster was removed during deployment?

**Comment by developerdhairya** [comment]
It is a new one

**Comment by wangmingliang-ms** [comment]
@developerdhairya  thanks for your report. 
**Did you delete the spring cloud cluster(service) at that time?** or **Is the spring cloud service(cluster) completely created at that time?**
It seems the spring cloud service(cluster) `employee-management-portal` is deleted/being deleted when you create a new spring cloud app in it. or the spring cloud service(cluster) is still creating.  (the process of provisioning/creating a spring cloud service is time-consuming, it may take a few minutes).
Anyway, we'll investigate this issue and turn this exception into readable messages at least.

**Comment by developerdhairya** [comment]
great!

**Comment by developerdhairya** [comment]
"Did you delete the spring cloud cluster(service) at that time?"
=> Yes I did
