### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by andrelemos** [microsoft/azure-tools-for-java#6195]
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,7,0,786x593,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.ui.ApplicationInsightsNewDialog.lambda$subscriptionListener$0(ApplicationInsightsNewDialog.java:101)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:165)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setValue(AzureComboBox.java:130)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setValue(AzureComboBox.java:120)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setSelectedItem(AzureComboBox.java:175)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:150)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.lambda$setItems$5(AzureComboBox.java:208)
	at com.microsoft.intellij.ui.AppInsightsMngmtPanel.lambda$createNewDilaog$3(AppInsightsMngmtPanel.java:221)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(Az

**Comment by Flanker32** [comment]
@andrelemos Thanks for your report, the issue should be fixed in https://github.com/microsoft/azure-maven-plugins/pull/1858/files, we will release the fix in the next intellij toolkit release

**Comment by Flanker32** [comment]
@andrelemos Thanks for your report, fix for this issue has been released, could you please help upgrade to the latest version and see whether this issue could be reproduced?
