### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for ActionGroup(com.intellij.execution.actions.RunContextAction, id=RunClass) with text=Run context configuration com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project(hager-migration-edaitem-backend-interceptor)

### ISSUE THREAD

**Issue by ToBeKedge** [microsoft/azure-tools-for-java#6199]
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for ActionGroup(com.intellij.execution.actions.RunContextAction, id=RunClass) with text=Run context configuration, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: list all function modules in project(hager-migration-edaitem-backend-interceptor)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.listFunctionModules(FunctionUtils.java:143)
	at com.microsoft.azure.toolkit.intellij.function.runner.core.FunctionUtils.getFunctionModuleByName(FunctionUtils.java:155)
	at com.microsoft.azure.toolkit.intellij.fu

**Comment by wangmingliang-ms** [comment]
We cannot reproduce this exception. 
The telemetry data shows this exception hasn't appeared in the last 2 months.
so, I believe it should have been resolved.

**Comment by wangmingliang-ms** [comment]
close as the bug is not reproduceable and this issue is no longer active, feel free to reopen it when you encounter it again.
