### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Details: Current thread: Thread[ApplicationImpl pooled thread 118,4,main] 569883145Dispatch thread: false; isDispatchThread(): falseSystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1856215913 java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())

### ISSUE THREAD

**Issue by IanCharrett-Dykes-tomtom** [microsoft/azure-tools-for-java#6219]
IntelliJ build version: 2021.3 IC-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1160,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Details: Current thread: Thread[ApplicationImpl pooled thread 118,4,main] 569883145
Dispatch thread: false; isDispatchThread(): false
	at com.microsoft.azure.hdinsight.spark.run.configuration.LivySparkBatchJobRunConfiguration.getState(LivySparkBatchJobRunConfiguration.java:376)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebuggerRunner.lambda$execute$9(SparkBatchJobDebuggerRunner.java:254)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugProcessHandler._init_$lambda-0(SparkBatchJobDebugProcessHandler.kt:48)

**Comment by fengshuaihu** [comment]
We have fixed this problem in version 3.72.0, please try to update the latest version. Feel free to reopen it when you encounter this error again.
