### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ahan-mgm** [microsoft/azure-tools-for-java#6272]
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.59.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x1000,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@737575c2,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS., throwable=java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:157)
	at com.microsoft.aad.msal4j.AadInstanceDi

**Comment by Flanker32** [comment]
@ahan-mgm Thanks for your report. Currently we did not re-produce the issue but we found a similar issue in netty/netty#11380, and we have upgrade the netty in toolkit [v3.60.0](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij), could you please upgrade the toolkit to v3.60.0 and try again? If the issue still reproduced, could you please share the steps to repro the issue?

**Comment by Flanker32** [comment]
Track the issue in https://github.com/microsoft/azure-tools-for-java/issues/6048
