### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception cannot create configurable component java.lang.NullPointerException

### ISSUE THREAD

**Issue by Lindont** [microsoft/azure-tools-for-java#6294]
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.60.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=cannot create configurable component, throwable=java.lang.NullPointerException
	at com.microsoft.intellij.ui.AzurePanel.setData(AzurePanel.java:95)
	at com.microsoft.intellij.ui.AzurePanel.init(AzurePanel.java:87)
	at com.microsoft.intellij.AzureConfigurable$AzureAbstractConfigurable.createComponent(AzureConfigurable.java:108)
```

**Comment by wangmingliang-ms** [comment]
fixed, can you please upgrade to v3.60.1.
