### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by raghurambodapati007** [microsoft/azure-tools-for-java#6317]
IntelliJ build version: 2021.1 IU-211.6693.111
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.58.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1281x680,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:60)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:60)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceInfoBasicPanel.init(AppServiceInfoBasicPanel.java:67)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceInfoBasicPanel.<init>(AppServiceInfoBasicPanel.java:63)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppCreationDialog.createUIComponents(WebAppCreationDialog.java:62)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppCreationDialog.$$$setupUI$$$(WebAppCreationDialog.java)
	at com.microsoft.azure.toolkit.intellij.webapp.WebAppCreationDialog.<init>(WebAppCreationDialog.

**Comment by wangmingliang-ms** [comment]
As it says, "you are not signed in".
we add a fix to catch this kind of exception and show it as Notification, can you try with the latest version?
