### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: net.seesharpsoft.intellij.plugins.psv.PsvFileType@68d98ab4 already registered

### ISSUE THREAD

**Issue by sharsu** [microsoft/azure-tools-for-java#6319]
IntelliJ build version: 2021.3.1 IC-213.6461.79
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.60.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,2560x1376,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: net.seesharpsoft.intellij.plugins.psv.PsvFileType@68d98ab4 already registered
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.getRunConfigurationFromDataContext(SparkSubmitJobAction.kt:85)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.update(SparkSubmitJobAction.kt:78)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: net.seesharpsoft.intellij.plugins.psv.PsvFileType@68d98ab4 already registered
Caused by: java.lang.IllegalArgumentException: net.seesharpsoft.intellij.plugins.psv.PsvFileType@68d98ab4 already registered
```

**Comment by fengshuaihu** [comment]
We have removed this feature in the latest version, please update the latest version
