### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Executor with context action id: "RunClass" was already registered!

### ISSUE THREAD

**Issue by priyankanaikgaonkar** [microsoft/azure-tools-for-java#6323]
IntelliJ build version: 2021.2.2 IU-212.5284.40
OS: Windows Server 2016
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.60.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Executor with context action id: "RunClass" was already registered!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.registerAction(IntellijAzureActionManager.java:55)
	at com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor.registerActions(ResourceCommonActionsContributor.java:50)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.lambda$register$0(IntellijAzureActionManager.java:48)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.register(IntellijAzureActionManager.java:48)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:130)
```

**Comment by wangmingliang-ms** [comment]
Hi, @priyankanaikgaonkar , thanks for report. but I am not able to reproduce this bug.
is this bug stably reproduceable on your machine, do you know how to reproduce it?
