### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: AZURE_FUNCTION_SUPPORT-Deploy Functions_ comman-functions_comman-functions_ factoryName_ Deploy Functions.xml com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployModel$DeprecatedDeployModel

### ISSUE THREAD

**Issue by chetan-galgali** [microsoft/azure-tools-for-java#6335]
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.60.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x980,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@13001d2c,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: AZURE_FUNCTION_SUPPORT-Deploy Functions_ comman-functions_comman-functions_ factoryName_ Deploy Functions.xml, throwable=com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployModel$DeprecatedDeployModel
	at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:58)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeployConfiguration.lambda$readExternal$1(FunctionDeployConfiguration.java:155)
	at com.microsoft.azure.toolkit.in

**Comment by akaroml** [comment]
@wezhang  please take a look.

**Comment by Flanker32** [comment]
Please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/6412
