### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception com.intellij.ide.ui.UITheme$1@5b3f3ba0 cannot patch icon path java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by davidmnoriega** [microsoft/azure-tools-for-java#6364]
IntelliJ build version: 2021.3.1 IC-213.6461.79
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.0-2021.3
Additional Info: Reboot after plugin upgrade, currently loaded project does not use azure
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2049x1112,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=com.intellij.ide.ui.UITheme$1@5b3f3ba0 cannot patch icon path, throwable=java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.loadIcon(AzureIcons.java:95)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.lambda$doGetIcon$1(AzureIcons.java:77)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.doGetIcon(AzureIcons.java:77)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.getIcon(AzureIcons.java:68)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper.applyView(IntellijAzureActionManager.java:114)

**Comment by Flanker32** [comment]
@davidmnoriega Thanks for your report, we will fix this issue and release the fix soon.

**Comment by Flanker32** [comment]
@davidmnoriega We've released the hot fix for this issue, could you please upgrade to the latest 3.61.1 and try again? Many thanks!

**Comment by davidmnoriega** [comment]
It's fixed 👍
