### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception com.intellij.ide.ui.UITheme$1@304a9d7b cannot patch icon path java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by boubaca** [microsoft/azure-tools-for-java#6365]
IntelliJ build version: 2021.3.2 RC IU-213.6777.38
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1512x848,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@200fcd33,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=com.intellij.ide.ui.UITheme$1@304a9d7b cannot patch icon path, throwable=java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.loadIcon(AzureIcons.java:95)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.lambda$doGetIcon$1(AzureIcons.java:77)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.doGetIcon(AzureIcons.java:77)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.getIcon(AzureIcons.java:68)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper.applyView(IntellijAzureActionManager.java:114)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActio

**Comment by Flanker32** [comment]
@boubaca Thanks for your report, please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/6364
