### ISSUE TITLE
Opening IntelliJ IDEA settings takes 60+ seconds with Azure Toolkit plug-in enabled

### ISSUE THREAD

**Issue by CrazyCoder** [microsoft/azure-tools-for-java#6370]
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.lang.Thread@51bd2938
	at java.base@11.0.13/java.lang.Object.wait(Native Method)
	at java.base@11.0.13/java.lang.Thread.join(Thread.java:1300)
	at java.base@11.0.13/java.lang.Thread.join(Thread.java:1375)
	at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:288)
	at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:180)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:381)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at com.microsoft.azure.toolkit.lib.common.utils.CommandUtils.executeCommandAndGetOutput(CommandUtils.java:90)
	at com.microsoft.azure.toolkit.lib.common.utils.CommandUtils.executeCommandAndGetOutput(CommandUtils.java:73)
	at com.microsoft.azure.toolkit.lib.common.utils.CommandUtils.exec(CommandUtils.java:65)
	at com.microsoft.azure.toolkit.lib.common.utils.CommandUtils.exec(CommandUtils.java:48)
	at com.microsoft.azure.toolkit.lib.common.utils.CommandUtils.exec(CommandUtils.java:44)
	at com.microsoft.azure.toolkit.lib.common.utils.CommandUtils.exec(CommandUtils.java:36)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.findFuncInNpm(FunctionCliResolver.java:82)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolveInner(FunctionCliResolver.java:64)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolve(FunctionCliResolver.java:31)
	at com.microsoft.azure.toolkit.lib.legacy.function.FunctionCoreToolsCombobox.reset(FunctionCoreToolsCombobox.java:112)
	at com.microsoft.azure.toolkit.lib.legacy.function.FunctionCoreToolsCombobox.<init>(FunctionCoreToolsCombobox.java:72)
	at com.microsoft.intellij.ui.AzurePanel.createUIComponents(AzurePanel.java:234)
	at com.microsoft.intellij.ui.AzurePanel.$$$setupUI$$$(AzurePanel.java)
	at com.microsoft.intellij.ui.AzurePanel.<init>(AzurePanel.java:57)
	at com.microsoft.intellij.AzureConfigurable.buildConfigurables(AzureConfigurable.java:40)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:87)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:299)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:149)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:111)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:115)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:53)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:50)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:37)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:573)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$7675/0x0000000803f0cc40.run(Unknown Source)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:456)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:224)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.ide.IdeEventQueue$$Lambda$447/0x0000000800582040.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.ide.IdeEventQueue$$Lambda$446/0x0000000800583040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.13/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

This was reported to IntelliJ IDEA support team with the following comment:

> Opening the settings dialog takes around a minute every time. It seems to have something to do with the "Azure Toolkit for IntelliJ" as when disabling this plugin, opening the dialog is quick again. However generally the plugin does work, and also doesn't hamper the IDE for a collegue.
> I tried uinstalling, reinstalling the plugin but was not successful in getting settings to be quick again.

**Comment by Flanker32** [comment]
@CrazyCoder Thanks for your report, could you please help share the version of IntelliJ and toolkit? Could the issue be reproduced after upgrade to the latest?

**Comment by CrazyCoder** [comment]
IntelliJ IDEA 2021.3.1, 3.61.1-2021.3 plug-in version (latest).

**Comment by wangmingliang-ms** [comment]
Thank you very much.
this fix would be included in the coming v3.62.0

**Comment by Flanker32** [comment]
@CrazyCoder Thanks for your help, toolkit v3.62.0 has been released with fix for this issue, could you please upgrade to the latest version and try again?

**Comment by CrazyCoder** [comment]
> @CrazyCoder Thanks for your help, toolkit v3.62.0 has been released with fix for this issue, could you please upgrade to the latest version and try again?

Thanks for the fix. I'm not the original reporter, just forwarded the details from the support ticket.
