### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Error java.lang.IllegalArgumentException: Last unit does not have enough valid bits

### ISSUE THREAD

**Issue by qayyumshabbir** [microsoft/azure-tools-for-java#6371]
IntelliJ build version: 2021.3.1 IC-213.6461.79
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.60.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1010,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@12b173dd,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Error, throwable=java.lang.IllegalArgumentException: Last unit does not have enough valid bits
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:766)
	at com.microsoft.intellij.AzureSettings.loadAppInsights(AzureSettings.java:47)
	at com.microsoft.intellij.AzurePlugin.initializeAIRegistry(AzurePlugin.java:177)
	at com.microsoft.intellij.AzurePlugin.runActivity(AzurePlugin.java:112)
```

**Comment by wangmingliang-ms** [comment]
Hi, @qayyumshabbir , thanks for reporting, but I am not able to reproduce this bug.
Is this bug stably reproduceable on your own machine? Can you tell us how to reproduce it?
