### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalStateException: Recursive update

### ISSUE THREAD

**Issue by Rajat775** [microsoft/azure-tools-for-java#6372]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.61.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@649a21f9,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1167)
	at com.microsoft.intellij.AzurePlugin.lambda$initializeWhatsNew$1(AzurePlugin.java:158)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:383)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:87)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:381)
```

**Comment by wangmingliang-ms** [comment]
hi, @Rajat775 , thanks for reporting, but I am not able to reproduce this bug.
Is this bug stably reproduceable on your own machine? Can you tell us how to reproduce it?
