### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by Rasmus-Kibshede** [microsoft/azure-tools-for-java#6375]
IntelliJ build version: 2021.2.1 IU-212.5080.55
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.61.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1400,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.exception.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:61)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:61)
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.AppServiceInfoBasicPanel.init(AppServiceInfoBasicPanel.java:64)
	at com.microsoft.azure.toolkit.intellij.legacy.appservice.AppServiceInfoBasicPanel.<init>(AppServiceInfoBasicPanel.java:60)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.WebAppCreationDialog.createUIComponents(WebAppCreationDialog.java:62)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.WebAppCreationDialog.$$$setupUI$$$(WebAppCreationDialog.java)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.WebAppCreationDialog.

**Comment by Flanker32** [comment]
@Rasmus-Kibshede Thanks for your report, it seems that the web app creation dialog is opened without sign in, could you please [sign in Azure](https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/sign-in-instructions) first and try again?
