### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction, id=Actions.SubmitSparkApplicationAction) with text=Submit Apache Spark Application java.lang.VerifyError: Expecting a stackmap frame at branch target 2352

### ISSUE THREAD

**Issue by atanas-mavrov** [microsoft/azure-tools-for-java#6378]
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,29,2560x1365,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction, id=Actions.SubmitSparkApplicationAction) with text=Submit Apache Spark Application, throwable=java.lang.VerifyError: Expecting a stackmap frame at branch target 2352
Exception Details:
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.getRunConfigurationFromDataContext(SparkSubmitJobAction.kt:85)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.update(SparkSubmitJobAction.kt:78)
```

**Comment by fengshuaihu** [comment]
This problem does not occur in the latest version, you can update the latest version and try again
