### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: prepare before run configuration

### ISSUE THREAD

**Issue by andreiPsarev** [microsoft/azure-tools-for-java#6411]
IntelliJ build version: 2021.3.2 IC-213.6777.52
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: prepare before run configuration
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:77)
	at com.microsoft.azure.toolkit.intellij.connector.Connection.prepareBeforeRun(Connection.java:96)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.lambda$executeTask$0(ConnectionRunnerForRunConfiguration.java:87)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.executeTask(ConnectionRunnerForRunConfiguration.java:87)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectionRunnerForRunConfiguration.executeTask(ConnectionRunnerForRunConfiguration.java:43)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: !storage.get_connection_string.account

**Comment by wangmingliang-ms** [comment]
this bug is fixed in the latest v3.62.0, can you try it and help confirm?
