### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@45b9e392 java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/tobiassuhrborg/Library/Caches/JetBrains/IntelliJIdea2021.3/caches/names.dat

### ISSUE THREAD

**Issue by TobiasSuhrborg** [microsoft/azure-tools-for-java#6441]
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.61.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1512x874,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@3e404075,flags=961,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=provider: de.plushnikov.intellij.plugin.provider.LombokAugmentProvider@45b9e392, throwable=java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/tobiassuhrborg/Library/Caches/JetBrains/IntelliJIdea2021.3/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.core.FunctionUtils.isFunctionClassAnnotated(FunctionUtils.java:203)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.FunctionRunConfigurationProducer.getAzureFunctionMethods(FunctionRunConfigurationProducer.java

**Comment by Flanker32** [comment]
@TobiasSuhrborg Thanks for your report, we will investigate this issue soon, could you please help share some more info like could this issue be stable reproduced and how to reproduce it?

**Comment by wangmingliang-ms** [comment]
Duplicate of #9861
