### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: /opt/idea-IC-213.6461.79/jbr/lib/libjcef.so: libgbm.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by assafepstein** [microsoft/azure-tools-for-java#6467]
IntelliJ build version: 2021.3.1 IC-213.6461.79
OS: Linux
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.62.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,38,59,1844x983,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: /opt/idea-IC-213.6461.79/jbr/lib/libjcef.so: libgbm.so.1: cannot open shared object file: No such file or directory
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewAction.lambda$doShow$2(WhatsNewAction.java:79)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:383)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:87)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:381)
	at com.m

**Comment by wangmingliang-ms** [comment]
Thanks for reporting, is this bug stably reproducible? can you share with us how to reproduce it.?
