### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException

### ISSUE THREAD

**Issue by srimunugoti** [microsoft/azure-tools-for-java#6478]
IntelliJ build version: 2021.3.2 IC-213.6777.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.62.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x790,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@7ee88ff3,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException
	at com.intellij.packaging.elements.PackagingElement.update(PackagingElement.java:136)
	at com.microsoft.azure.hdinsight.projects.HDInsightModuleBuilder.lambda$moduleCreated$0(HDInsightModuleBuilder.java:136)
```

**Comment by fengshuaihu** [comment]
We have updated the functionality of this place, you can upgrade to the latest and try. Feel free to reopen it when you encounter this error again.
