### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception com.intellij.ide.ui.UITheme$1@4e38d975 cannot patch icon path java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by Ryaryu** [microsoft/azure-tools-for-java#6537]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Linux
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,24,1920x1055,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=com.intellij.ide.ui.UITheme$1@4e38d975 cannot patch icon path, throwable=java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.loadIcon(AzureIcons.java:98)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.lambda$doGetIcon$1(AzureIcons.java:80)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.doGetIcon(AzureIcons.java:80)
	at com.microsoft.azure.toolkit.intellij.common.AzureIcons.getIcon(AzureIcons.java:71)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper.applyView(IntellijAzureActionManager.java:142)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager$AnActionWrapper.

**Comment by Flanker32** [comment]
@Ryaryu Thanks for your report, we have released toolkit v3.63.1 to fix this issue, could you please upgrade to the latest version and try again? If you meet any problems, please feel free to open this issue or comment in https://github.com/microsoft/azure-tools-for-java/issues/6533
