### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: /opt/idea/jbr/lib/libjcef.so: libatk-1.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cedricgouge** [microsoft/azure-tools-for-java#6552]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Linux
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1369,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: /opt/idea/jbr/lib/libjcef.so: libatk-1.0.so.0: cannot open shared object file: No such file or directory
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewAction.lambda$doShow$2(WhatsNewAction.java:79)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:118)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:96)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationContext.run(AzureOperationContext.java:81)
	at com.microsoft.azure.tool

**Comment by wangmingliang-ms** [comment]
this should be external issue of IntelliJ itself, anyway, we didn't see this exception in last 2 months according to our telemetry data. so I believe it should have been fixed by IntelliJ. feel free to reopen this issue if you encounter it again.

**Comment by wangmingliang-ms** [comment]
close as the bug is not reproduceable and this issue is no longer active, feel free to reopen it when you encounter it again.
