### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Conflicting component name 'FileTypeManager': class com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl and class com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl (componentManager=Application (containerState=PRE_INIT) )

### ISSUE THREAD

**Issue by ghost** [microsoft/azure-tools-for-java#6598]
IntelliJ build version: 2022.1 IU-221.5080.210
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Conflicting component name 'FileTypeManager': class com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl and class com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl (componentManager=Application (containerState=PRE_INIT) )
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.function.CreateFunctionAction.isAvailable(CreateFunctionAction.java:162)
```

**Comment by wangmingliang-ms** [comment]
Did you encounter this error recently? 
This should be an issue of IntelliJ itself, which should be the same issue as https://youtrack.jetbrains.com/issue/IDEA-293462.
