### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=FirstBlockProject, containerState=DISPOSE_COMPLETED, componentStore=/Users/nicolaskoriakos/Desktop/Code/Study/First Block/FirstBlockProject) (disposed)

### ISSUE THREAD

**Issue by NrodriguezKoriakos** [microsoft/azure-tools-for-java#6602]
IntelliJ build version: 2022.1 IC-221.5080.210
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.63.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1728x1080,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=FirstBlockProject, containerState=DISPOSE_COMPLETED, componentStore=/Users/nicolaskoriakos/Desktop/Code/Study/First Block/FirstBlockProject) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:190)
	at com.microsoft.azure.toolkit.intellij.common.survey.SurveyPopUpDialog.<init>(SurveyPopUpDialog.java:65)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.showSurveyPopup(CustomerSurveyManager.java:77)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.lambda$takeSurvey$0(Cus

**Comment by wangmingliang-ms** [comment]
this bug should have been fixed in the latest 3.64.0, can you try?
