### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/xxxxx/Library/Caches/JetBrains/IdeaIC2021.3/caches/names.dat

### ISSUE THREAD

**Issue by mskopp** [microsoft/azure-tools-for-java#6603]
IntelliJ build version: 2021.3.2 IC-213.6777.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.62.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2048x1127,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@11ff06c6,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/xxxxx/Library/Caches/JetBrains/IdeaIC2021.3/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.microsoft.intellij.util.PluginUtil.getModulePath(PluginUtil.java:92)
	at com.microsoft.intellij.AzurePlugin.initializeAIRegistry(AzurePlugin.java:181)
	at com.microsoft.intellij.AzurePlugin.runActivity(AzurePlugin.java:112)
Caused by: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/xxxxx/Library/Caches/JetBrains/IdeaIC2021.3/caches

**Comment by wangmingliang-ms** [comment]
This should be an issue of IntelliJ itself. anyway, we didn't see this exception after 3.66.0 according to our telemetry data, so I believe it has been fixed by IntelliJ. can you try upgrade your ide and the plugin to the latest and try?

**Comment by mskopp** [comment]
It didn't reoccurred on the last months…
