### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@617efdf1 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@4631116c java.lang.ArrayIndexOutOfBoundsException: 411 > 386

### ISSUE THREAD

**Issue by jolySoft** [microsoft/azure-tools-for-java#6634]
IntelliJ build version: 2022.1.1 IU-221.5591.52
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.64.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1789x1002,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@617efdf1 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@4631116c, throwable=java.lang.ArrayIndexOutOfBoundsException: 411 > 386
	at java.base/java.util.Vector.insertElementAt(Vector.java:620)
	at com.microsoft.azure.toolkit.intellij.common.component.Tree$TreeNode.clearChildren(Tree.java:210)
	at com.microsoft.intellij.ui.ServerExplorerToolWindowFactory.lambda$createToolWindowContent

**Comment by wangmingliang-ms** [comment]
Duplicate of #9450
