### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for ActionGroup(com.intellij.execution.lineMarker.LineMarkerActionWrapper) with text=Run context configuration com.microsoft.azure.toolkit.lib.common.operation.OperationException

### ISSUE THREAD

**Issue by AniKumari24** [microsoft/azure-tools-for-java#6643]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.64.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for ActionGroup(com.intellij.execution.lineMarker.LineMarkerActionWrapper) with text=Run context configuration, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:99)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:382)
	at com.microsof

**Comment by wangmingliang-ms** [comment]
This issue should have been fixed in newer versions; we haven't observed this error in the last 2 months.
Can you try the newer versions?

**Comment by wangmingliang-ms** [comment]
close as the bug is not reproduceable and this issue is no longer active, feel free to reopen it when you encounter it again.
