### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot get children Microsoft Tools java.nio.file.InvalidPathException: Illegal char <:> at index 5: 活动代码页: 936

### ISSUE THREAD

**Issue by water160** [microsoft/azure-tools-for-java#6644]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.56.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1250x744,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot get children Microsoft Tools, throwable=java.nio.file.InvalidPathException: Illegal char <:> at index 5: 活动代码页: 936
C:\Users\z00520494\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.findFuncInNpm(FunctionCliResolver.java:84)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolveInner(FunctionCliResolver.java:64)
	at com.microsoft.azure.toolkit.lib.appservice.utils.FunctionCliResolver.resolve(FunctionCliResolver.java:31)
	at com.microsoft.azure.toolkit.lib.function.FunctionCoreToolsCombobox.reset(FunctionCoreToolsCombobox.java:102)
	at com.microsoft.azur

**Comment by ivywei0125** [comment]
@water160 Would you please provide more info?

**Comment by wangmingliang-ms** [comment]
close as the bug is not reproduceable and this issue is no longer active, feel free to reopen it when you encounter it again.
