### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception error occurs when evaluate template(${module.getName()}) with bindings({nameFromResourceId=org.codehaus.groovy.runtime.MethodClosure@6774af81, module=null, _this_=null, out=java.io.PrintWriter@50db14d7}) java.lang.NullPointerException: Cannot invoke method getName() on null object

### ISSUE THREAD

**Issue by prshnt** [microsoft/azure-tools-for-java#6658]
IntelliJ build version: 2022.1.1 IU-221.5591.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.64.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2467x1415,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@6fd4fdb5,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=error occurs when evaluate template(${module.getName()}) with bindings({nameFromResourceId=org.codehaus.groovy.runtime.MethodClosure@6774af81, module=null, _this_=null, out=java.io.PrintWriter@50db14d7}), throwable=java.lang.NullPointerException: Cannot invoke method getName() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at com.microsoft.azure.toolkit.lib.common.utils.aspect.ExpressionUtils.render(ExpressionUtils.java:49)
	at com.microsoft.azure.toolkit.lib.common.utils.aspect.ExpressionUtils.interpret(ExpressionUtil

**Comment by wangmingliang-ms** [comment]
Hi, this problem should have been fixed in the latest v3.66.0, can you try it?
