### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor java.lang.StackOverflowError

### ISSUE THREAD

**Issue by sofiealberius** [microsoft/azure-tools-for-java#6665]
IntelliJ build version: 2019.3.2 IU-193.6015.39
OS: Mac OS X
JDK: JetBrains s.r.o 11.0.5
Plugin version: 3.32.0-2019.3
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,0,22,972x575,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=972,height=575]]
```
Error message: 
```
IdeaLoggingEvent[message=executor initialization failed: com.intellij.execution.executors.DefaultRunExecutor, throwable=java.lang.StackOverflowError
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.java:109)
	at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebugExecutor.equals(SparkBatchJobDebugExecutor.j

**Comment by wangmingliang-ms** [comment]
Hi, @sofiealberius  can you upgrade the plugin to newer and try again?
