### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot read scheme C:\Users\.....\AppData\Roaming\JetBrains\IdeaIC2022.1\keymaps\Default copy.xml com.fasterxml.aalto.WFCException: Illegal character (NULL, unicode 0) encountered: not valid in any content

### ISSUE THREAD

**Issue by Mr-Ibulu** [microsoft/azure-tools-for-java#6688]
IntelliJ build version: 2022.1.2 IC-221.5787.30
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.65.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1050,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot read scheme C:\Users\.....\AppData\Roaming\JetBrains\IdeaIC2022.1\keymaps\Default copy.xml, throwable=com.fasterxml.aalto.WFCException: Illegal character (NULL, unicode 0) encountered: not valid in any content
 at [row,col {unknown-source}]: [1,2]
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.registerAction(IntellijAzureActionManager.java:64)
	at com.microsoft.azure.toolkit.ide.common.action.ResourceCommonActionsContributor.registerActions(ResourceCommonActionsContributor.java:68)
	at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.lambda$register$0(IntellijAzureActionManager.java:57

**Comment by wangmingliang-ms** [comment]
thanks for reporting, this should be an issue of IntelliJ itself, can you provide more details in this issue https://youtrack.jetbrains.com/issue/IDEA-295742?
