### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NoClassDefFoundError: Could not initialize class com.intellij.psi.impl.java.stubs.index.JavaStubIndexKeys

### ISSUE THREAD

**Issue by sreejithp5** [microsoft/azure-tools-for-java#6709]
IntelliJ build version: 2022.1.2 IC-221.5787.30
OS: Windows Server 2019
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.65.2-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,0,1246x633,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NoClassDefFoundError: Could not initialize class com.intellij.psi.impl.java.stubs.index.JavaStubIndexKeys
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.getKey(JavaFullClassNameIndex.java:29)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.getRunConfigurationFromDataContext(SparkSubmitJobAction.kt:85)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.update(SparkSubmitJobAction.kt:78)
```

**Comment by fengshuaihu** [comment]
We have removed this feature in the latest version, please update the latest version
