### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.openapi.util.TraceableDisposable$DisposalException:         Library LibraryId(name=#1, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=sblmessageloader))) already disposed:

### ISSUE THREAD

**Issue by AniKumari24** [microsoft/azure-tools-for-java#6710]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.64.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.openapi.util.TraceableDisposable$DisposalException:         Library LibraryId(name=#1, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=sblmessageloader))) already disposed:
        Library id: LibraryId(name=#1, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=sblmessageloader)))
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.isSparkContext(SparkContextUtils.kt:55)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfigurationAction.update(SparkRunConfigurationAction.kt:70

**Comment by fengshuaihu** [comment]
Please update to the latest version and try again, if you encounter this issue again, feel free to turn it on again
