### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by nilscodes** [microsoft/azure-tools-for-java#6730]
IntelliJ build version: 2022.1.1 IU-221.5591.52
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.65.2-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.azure.toolkit.lib.springcloud.config.SpringCloudDeploymentConfig.fromDeployment(SpringCloudDeploymentConfig.java:87)
	at com.microsoft.azure.toolkit.lib.springcloud.config.SpringCloudAppConfig.fromApp(SpringCloudAppConfig.java:56)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationPanel.getValue(SpringCloudDeploymentConfigurationPanel.java:143)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfiguration$Editor.applyEditorTo(SpringCloudDeploymentConfiguration.java:173)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfiguration$Editor.applyEditorTo(SpringCloudDeploymentConfiguration.java:140)
```

**Comment by wangmingliang-ms** [comment]
thanks for reporting, this bug will be fixed in the coming v3.66.0.
