### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalArgumentException: Cannot find subscription with id '685ba005-af8d-4b04-8f16-a7bf38b2eb5a'

### ISSUE THREAD

**Issue by silenceJialuo** [microsoft/azure-tools-for-java#6739]
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.66.0-2021.3-SNAPSHOT.20220622060741
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x518,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalArgumentException: Cannot find subscription with id '685ba005-af8d-4b04-8f16-a7bf38b2eb5a'
	at com.microsoft.azure.toolkit.lib.auth.Account.lambda$getSubscription$15(Account.java:258)
	at com.microsoft.azure.toolkit.lib.auth.Account.getSubscription(Account.java:258)
	at com.microsoft.azure.toolkit.ide.common.favorite.FavoriteNodeView.getTips(FavoriteNodeView.java:37)
	at com.microsoft.azure.toolkit.intellij.common.component.TreeUtils.renderMyTreeNode(TreeUtils.java:175)
	at com.microsoft.intellij.ui.ServerExplorerToolWindowFactory$NodeTreeCellRenderer.customizeCellRenderer(ServerExplorerToolWindowFactory.java:380)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.expandNodeAfterLoading(RefreshableNode.java:118)
	at com.microsoft.tooling.msservices.ser

**Comment by wangmingliang-ms** [comment]
this issue should have been fixed in v3.67.0. We haven't observed this exception since that. Feel free to reopen this issue if you encounter it again.
