### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/rajatsingh.r/Library/Caches/JetBrains/IntelliJIdea2021.2/caches/names.dat

### ISSUE THREAD

**Issue by Rajat775** [microsoft/azure-tools-for-java#6757]
IntelliJ build version: 2021.2.3 IU-212.5457.46
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.12
Plugin version: 3.63.1-2021.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x940,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@6c784ea4,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/rajatsingh.r/Library/Caches/JetBrains/IntelliJIdea2021.2/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.getRunConfigurationFromDataContext(SparkSubmitJobAction.kt:85)
	at com.microsoft.azure.hdinsight.spark.actions.SparkSubmitJobAction.update(SparkSubmitJobAction.kt:78)
Caused by: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/rajatsingh.r/Library/Caches/JetBrains/IntelliJIdea2021.2/c

**Comment by fengshuaihu** [comment]
We have removed this feature in the latest version, please update the latest version
