### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group Idea Thread Group failed with an uncaught exception com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(tip-parking-management) from config

### ISSUE THREAD

**Issue by Zarasuto** [microsoft/azure-tools-for-java#6769]
IntelliJ build version: 2021.1.3 IU-211.7628.21
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.58.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,824x512,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group Idea Thread Group failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.common.operation.AzureOperationException: create or update Spring Cloud app(tip-parking-management) from config
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:81)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.execute(SpringCloudDeploymentConfigurationState.java:96)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.lambda$execute$0(SpringCloudDeploymentConfigurationState.java:69)
Caused by: com.microsoft.azure.toolkit.lib.common.operat

**Comment by wangmingliang-ms** [comment]
Hi, @Zarasuto thanks for reporting issue to us. we'll investigate what is wrong, but at the same time, 
**can you try upgrading the plugin to the latest v3.66.1 to check if this issue is reproduceable?**

**Comment by wangmingliang-ms** [comment]
close as the bug is not reproduceable and this issue is no longer active, feel free to reopen it when you encounter it again.
