### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException

### ISSUE THREAD

**Issue by sagarpoudel-kroger** [microsoft/azure-tools-for-java#6770]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.66.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1120,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:99)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:382)
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager.doRead(IntellijAzureTaskManager.java:27)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$2(AzureTaskManager.java:392)
	at com.microsoft.azure.toolkit.lib.common.task.Az

**Comment by Flanker32** [comment]
@sagarpoudel-kroger Thanks for your report and sorry for the late response, could you please help share some more info like the repro steps and logs for this issue? You may get the log with `Help` -> `Show log in explorer` in IntelliJ

**Comment by wangmingliang-ms** [comment]
close as not reproduceable because lack of information
