### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.concurrent.CompletionException: com.microsoft.azure.toolkit.lib.common.operation.OperationException: init plugin

### ISSUE THREAD

**Issue by eddy090907** [microsoft/azure-tools-for-java#6775]
IntelliJ build version: 2021.3.3 IC-213.7172.25
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.66.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x834,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.concurrent.CompletionException: com.microsoft.azure.toolkit.lib.common.operation.OperationException: init plugin
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
Caused by: com.microsoft.azure.toolkit.lib.common.operation.OperationException: init plugin
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:172)
Caused by: java.lang.AssertionError: com.intellij.ide.ui.UITheme$1@43df23f0 cannot patch icon path
	at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.loadIcon(IntelliJAzureIcons.java:109

**Comment by wangmingliang-ms** [comment]
this issue should have been fixed in later versions than v3.66.1. can you try?
