### ISSUE TITLE
[Intellij2017+2016]The application insights configuration failed

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#678]
Afetr configuration
EXPEXT:
![image](https://user-images.githubusercontent.com/22470312/27315275-51b8e008-55ab-11e7-81df-197feb05b9c7.png)
RESULT:
No fix option, and error during atifact deployment.

Server Log:
Connected to server
[2017-06-19 08:02:21,884] Artifact helloworld2: Artifact is being deployed, please wait...
19-Jun-2017 20:02:23.025 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
19-Jun-2017 20:02:23.040 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[2017-06-19 08:02:23,056] Artifact helloworld2: Error during artifact deployment. See server log for details.
19-Jun-2017 20:02:31.869 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\webapps\manager]
19-Jun-2017 20:02:31.978 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\webapps\manager] has finished in [93] ms
C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\catalina.bat stop
Using CATALINA_BASE:   "C:\Users\v-sunxi\.IntelliJIdea2017.1\system\tomcat\Unnamed_helloworld2"
Using CATALINA_HOME:   "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15"
Using CATALINA_TMPDIR: "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\temp"
Using JRE_HOME:        "C:\Program Files\Java\jdk1.8.0_131"
Using CLASSPATH:       "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\bootstrap.jar;C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\tomcat-juli.jar"
19-Jun-2017 20:03:02.112 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
19-Jun-2017 20:03:02.112 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:03:02.206 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8009"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-8009"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8009"]
Disconnected from server

**Comment by adashen** [comment]
More logs?

**Comment by bsaby** [comment]
**Server Log:**
:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\catalina.bat run
[2017-06-19 08:02:17,712] Artifact helloworld2: Server is not connected. Deploy is not available.
Using CATALINA_BASE:   "C:\Users\v-sunxi\.IntelliJIdea2017.1\system\tomcat\Unnamed_helloworld2"
Using CATALINA_HOME:   "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15"
Using CATALINA_TMPDIR: "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\temp"
Using JRE_HOME:        "C:\Program Files\Java\jdk1.8.0_131"
Using CLASSPATH:       "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\bootstrap.jar;C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\tomcat-juli.jar"
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.15
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 5 2017 11:03:04 UTC
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.15.0
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 10
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jdk1.8.0_131\jre
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_131-b11
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\Users\v-sunxi\.IntelliJIdea2017.1\system\tomcat\Unnamed_helloworld2
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\Users\v-sunxi\.IntelliJIdea2017.1\system\tomcat\Unnamed_helloworld2\conf\logging.properties
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote=
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=1099
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=127.0.0.1
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\Users\v-sunxi\.IntelliJIdea2017.1\system\tomcat\Unnamed_helloworld2
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\temp
19-Jun-2017 20:02:20.322 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Program Files\Java\jdk1.8.0_131\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\v-sunxi\AppData\Local\Microsoft\WindowsApps;.]
19-Jun-2017 20:02:21.728 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:02:21.759 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
19-Jun-2017 20:02:21.759 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
19-Jun-2017 20:02:21.775 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
19-Jun-2017 20:02:21.775 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2284 ms
19-Jun-2017 20:02:21.837 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
19-Jun-2017 20:02:21.837 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.15
19-Jun-2017 20:02:21.855 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:02:21.869 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
19-Jun-2017 20:02:21.869 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 102 ms
Connected to server
[2017-06-19 08:02:21,884] Artifact helloworld2: Artifact is being deployed, please wait...
19-Jun-2017 20:02:23.025 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
19-Jun-2017 20:02:23.040 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[2017-06-19 08:02:23,056] Artifact helloworld2: Error during artifact deployment. See server log for details.
19-Jun-2017 20:02:31.869 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\webapps\manager]
19-Jun-2017 20:02:31.978 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\webapps\manager] has finished in [93] ms
C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\catalina.bat stop
Using CATALINA_BASE:   "C:\Users\v-sunxi\.IntelliJIdea2017.1\system\tomcat\Unnamed_helloworld2"
Using CATALINA_HOME:   "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15"
Using CATALINA_TMPDIR: "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\temp"
Using JRE_HOME:        "C:\Program Files\Java\jdk1.8.0_131"
Using CLASSPATH:       "C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\bootstrap.jar;C:\Users\v-sunxi\Desktop\apache-tomcat-8.5.15\bin\tomcat-juli.jar"
19-Jun-2017 20:03:02.112 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
19-Jun-2017 20:03:02.112 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:03:02.206 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8009"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-8009"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
19-Jun-2017 20:03:02.284 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-8009"]
Disconnected from server


**Tomcat Localhost Log:**
19-Jun-2017 20:02:23.025 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [ApplicationInsightsWebFilter]
 java.lang.ClassNotFoundException: com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:512)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:493)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:119)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:264)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4590)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1702)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:482)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


**Tomcat Catalina Log:**
19-Jun-2017 20:02:23.040 SEVERE [RMI TCP Connection(5)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors

**Comment by adashen** [comment]
the hard coded azure version is not updated to 1.1.0
