### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.openapi.util.TraceableDisposable$DisposalException:         Library LibraryId(name=Gradle: kaptGeneratedClasses, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=dtf-gateway.test))) already disposed:

### ISSUE THREAD

**Issue by rupeshitpatekar** [microsoft/azure-tools-for-java#6784]
IntelliJ build version: 2022.1.1 IC-221.5591.52
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.66.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1002,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@747a933e,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.openapi.util.TraceableDisposable$DisposalException:         Library LibraryId(name=Gradle: kaptGeneratedClasses, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=dtf-gateway.test))) already disposed:
        Library id: LibraryId(name=Gradle: kaptGeneratedClasses, tableId=ModuleLibraryTableId(moduleId=ModuleId(name=dtf-gateway.test)))
	at com.microsoft.azure.toolkit.intellij.function.CreateFunctionAction.isAvailable(CreateFunctionAction.java:168)
	at com.microsoft.azure.toolkit.intellij.function.CreateFunctionAction.isAvailable(CreateFunctionAction.java:168)
```

**Comment by Flanker32** [comment]
@rupeshitpatekar Thanks for your report and sorry for the late response, we will investigate and fix this issue soon

**Comment by Flanker32** [comment]
@rupeshitpatekar Thanks a lot for your help, the issue should be resolved in the latest toolkit, could you please upgrade to v3.68.0 and try again?
