### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=Tester, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\Anish.LAPTOP-15QOCMV9\Documents\Kinetix\workspace\Tester) (disposed)

### ISSUE THREAD

**Issue by spxxf** [microsoft/azure-tools-for-java#6790]
IntelliJ build version: 2022.1.3 IC-221.5921.22
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.66.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1410,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=Tester, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\Anish.LAPTOP-15QOCMV9\Documents\Kinetix\workspace\Tester) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.getMessageBus(ComponentManagerImpl.kt:190)
	at com.microsoft.azure.toolkit.intellij.common.survey.SurveyPopUpDialog.<init>(SurveyPopUpDialog.java:65)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.showSurveyPopup(CustomerSurveyManager.java:77)
	at com.microsoft.azure.toolkit.intellij.common.survey.CustomerSurveyManager.lambda$takeSurvey$0(CustomerSurveyManager.java

**Comment by Flanker32** [comment]
@spxxf Thanks for your report and sorry for the late response, we will investigate and fix this issue soon
