### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: setup run configuration for Azure Functions

### ISSUE THREAD

**Issue by theosib-amazon** [microsoft/azure-tools-for-java#6813]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.66.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1095,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.UIUtil$1@15449392,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: setup run configuration for Azure Functions
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.FunctionRunConfigurationProducer.setupConfigurationFromContext(FunctionRunConfigurationProducer.java:84)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.FunctionRunConfigurationProducer.setupConfigurationFromContext(FunctionRunConfigurationProducer.java:32)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.FunctionRunConfigurationProducer.getAzureFunctionMethods(Functio

**Comment by Flanker32** [comment]
@theosib-amazon thanks for your report and sorry for the late reply, we will investigate this issue soon. If possible, could you please help share the repro steps for this issue?

**Comment by theosib-amazon** [comment]
Sorry, I don't have repro steps. If I recall correctly, this occurred randomly after I woke my laptop from sleep.

**Comment by Flanker32** [comment]
@theosib-amazon Thanks for your message, we are investigating this issue and will update here once we get some updates
