### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot init toolwindow com.microsoft.intellij.ui.ServerExplorerToolWindowFactory@253f0ba1 com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize Azure explorer

### ISSUE THREAD

**Issue by tri-discovermarket** [microsoft/azure-tools-for-java#6824]
IntelliJ build version: 2021.3.3 IC-213.7172.25
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.66.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot init toolwindow com.microsoft.intellij.ui.ServerExplorerToolWindowFactory@253f0ba1, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize Azure explorer
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.intellij.ui.ServerExplorerToolWindowFactory.createToolWindowContent(ServerExplorerToolWindowFactory.java:164)
Caused by: java.lang.NullPointerException
	at com.microsoft.tooling.msservices.serviceexplorer.Node.initActions(Node.java:313)
	at com.microsoft.tooling.msservices.serviceexplorer.Node.loadActions(Node.java:281)
	at com.microsoft.tooling.msservices

**Comment by Flanker32** [comment]
@tri-discovermarket Thanks a lot for your report and sorry for the issue. Could this issue be stable reproduced? If so, could you please help share the repro steps for this issue? 
Besides, could you please help share the log for toolkit? You may get it by `Help` -> `Show Log in Explorer` in IntelliJ
