### ISSUE TITLE
Create new VM flow -> Choosing Publishers with no Offers does not clear up Sku & Version

### ISSUE THREAD

**Issue by anudeepsharma** [Microsoft/azure-tools-for-java#69]
1. Click a VM in Azure Explorer.
2. Choose a subscription.
3. On Select Image dialog, choose a location, then custom image.
4. Select a publisher with offers, Sku and version available.
5. Select a publisher like Microsoft.VisualStudio.Services.
This does not have any offer, sku, version available, so we are not clearing the information. Next button is disabled so we don't know what is wrong.

Expected - Option 1 -> Don't show publishers with no images in the drop down. (Preferred)
Option 2 ->  Clear the information, let user know that this publisher has nothing to offer.

**Comment by lenala** [comment]
This is done.

Option 1 cannot be implemented because it involves separate Azure SDK call for each publisher, which takes too long.
Implemented Option 2, now Sku combobox and Version list are properly cleaned.

**Comment by bsaby** [comment]
Select a publisher like Microsoft.VisualStudio.Services.
Sku combobox and Version list have been cleaned.
But the next button is not available and an exception occurs

![image](https://cloud.githubusercontent.com/assets/22470312/24686364/00351784-19e6-11e7-8976-141cf55b308a.png)

**Error log**
null
java.lang.NullPointerException
	at com.microsoft.intellij.wizards.createarmvm.SelectImageStep$15.run(SelectImageStep.java:381)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lenala** [comment]
I could not repro the exception, but I added additional check, so now it should be gone. Please verify.

**Comment by bsaby** [comment]
The exception is not repro, using artifacts/azure-toolkit-for-intellij.2017.218.04-05-2017.zip.
Do we expect that the virtual machine with a Publisher which has nothing to offer can not be created?

**Comment by martinsawicki** [comment]
it is possible in Azure to have PUblishers with nothing to offer As long as we keep the Next button disabled when  no offer is selected, this is as expected., DOes this help clarify?

**Comment by bsaby** [comment]
Yes, test passed and issue closed.
