### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot select using PAC java.lang.NullPointerException

### ISSUE THREAD

**Issue by sachin7796** [microsoft/azure-tools-for-java#7017]
IntelliJ build version: 2021.1.2 IU-211.7442.40
OS: Mac OS X
JDK: JetBrains s.r.o. 11.0.11
Plugin version: 3.58.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,0,28,849x484,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot select using PAC, throwable=java.lang.NullPointerException
	at com.github.markusbernhardt.proxy.search.desktop.osx.OsxProxySearchStrategy.getProxySelector(OsxProxySearchStrategy.java:117)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.SystemDefaultRoutePlanner.determineProxy(SystemDefaultRoutePlanner.java:94)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:78)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.microsoft.applicationinsights.core.dependencies.http.impl.cli

**Comment by Flanker32** [comment]
@sachin7796 Thanks for your report and really sorry for the late response. Could you please share the steps to repro the issue if possible. Besides, could you please upgrade to the latest version and see whether the issue could be reproduced?
