### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by suepuc** [microsoft/azure-tools-for-java#7020]
IntelliJ build version: 2022.2 IU-222.3345.118
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.69.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.action.DeployWebAppAction.execute(DeployWebAppAction.java:44)
	at com.microsoft.azure.toolkit.intellij.appservice.AppServiceIntelliJActionsContributor.lambda$registerHandlers$21(AppServiceIntelliJActionsContributor.java:116)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:95)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservabl

**Comment by wangmingliang-ms** [comment]
this issue is fixed in latest release, feel free to reopen it if you get this error again
