### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException

### ISSUE THREAD

**Issue by CharlesSSantana** [microsoft/azure-tools-for-java#7081]
IntelliJ build version: 2021.3.2 IC-213.6777.52
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.66.2-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:99)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:382)
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager.doRead(IntellijAzureTaskManager.java:27)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$2(AzureTaskManager.java:392)
	at com.microsoft.azure.to

**Comment by vovan-** [comment]
The same issue, IDEA won't start until plugin is uninstalled.
Though OS is MacOs Ventura
