### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: peer

### ISSUE THREAD

**Issue by dev-leticia-costa** [microsoft/azure-tools-for-java#7113]
IntelliJ build version: 2022.2.3 IC-222.4345.14
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.70.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: peer
	at java.desktop/sun.awt.windows.WInputMethod.openCandidateWindow(Native Method)
	at com.microsoft.azure.toolkit.intellij.connector.ModuleConnectorAction.actionPerformed(ModuleConnectorAction.java:27)
```

**Comment by wangmingliang-ms** [comment]
this should be an external issue related to https://youtrack.jetbrains.com/issue/MPS-31538 and https://youtrack.jetbrains.com/issue/DEXP-474087/peer.
