### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: java.net.UnknownHostException: testing-mm.azurehdinsight.net

### ISSUE THREAD

**Issue by hernanubi** [microsoft/azure-tools-for-java#7151]
IntelliJ build version: 2022.2.3 IC-222.4345.14
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.70.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: java.net.UnknownHostException: testing-mm.azurehdinsight.net
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.lambda$fetchLog$0(SparkJobLogInputStream.java:43)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.fetchLog(SparkJobLogInputStream.java:42)
	at com.microsoft.azure.hdinsight.spark.run.SparkJobLogInputStream.available(SparkJobLogInputStream.java:66)
Caused by: java.net.UnknownHostException: testing-mm.azurehdinsight.net
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:247)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getHttpResponseViaGet(SparkBatchSubmission.java:253)
	at com.microsoft.azure.hdinsight.spark.common.SparkBatchSubmission.getBatchSparkJobS

**Comment by v-jiezhang3** [comment]
This bug may be caused by the network environment and cannot be reproduced.
