### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: 446 ms to call on EDT AzureSignInAction#update@ToolwindowTitle (com.microsoft.intellij.actions.AzureSignInAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by MarkOginkInfoSupport** [microsoft/azure-tools-for-java#7185]
IntelliJ build version: 2022.3 IU-223.7571.182
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.71.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1393,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: 446 ms to call on EDT AzureSignInAction#update@ToolwindowTitle (com.microsoft.intellij.actions.AzureSignInAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.loadIcon(IntelliJAzureIcons.java:119)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons.lambda$doGetIcon$2(IntelliJAzureIcons.java:97)
		at com.microsoft.azure.toolkit.intellij.common.IntelliJAzureIcons$$Lambda$133

**Comment by wangmingliang-ms** [comment]
this issue should have been fixed in the latest v3.77.0. Feel free to reopen it if you encounter this problem again.
