### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.azure.resourcemanager.appplatform.models.SpringAppDeployment.instances()" is null

### ISSUE THREAD

**Issue by alejandraJA** [microsoft/azure-tools-for-java#7199]
IntelliJ build version: 2022.3 IU-223.7571.182
OS: Windows Server 2022
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.71.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1367x728,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.azure.resourcemanager.appplatform.models.SpringAppDeployment.instances()" is null
	at com.microsoft.azure.toolkit.lib.springcloud.SpringCloudDeployment.getInstanceNum(SpringCloudDeployment.java:200)
	at com.microsoft.azure.toolkit.lib.springcloud.config.SpringCloudDeploymentConfig.fromDeployment(SpringCloudDeploymentConfig.java:86)
	at com.microsoft.azure.toolkit.lib.springcloud.config.SpringCloudAppConfig.fromApp(SpringCloudAppConfig.java:56)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationPanel.getValue(SpringCloudDeploymentConfigurationPanel.java:143)
	at com.microsoft.azure.toolkit.intellij

**Comment by wangmingliang-ms** [comment]
close this issue as it should have been fixed since v3.72.0. feel free to reopen this issue if it reappears.
