### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'ph-pbm-pricing-batch-v1.service.main' (disposed)

### ISSUE THREAD

**Issue by saurabhssahu** [microsoft/azure-tools-for-java#7201]
IntelliJ build version: 2022.1.4 IC-221.6008.13
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.67.0-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1287x632,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=update failed for AnAction(com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction, id=SparkJobRun) with text=SparkJobRun, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Module: 'ph-pbm-pricing-batch-v1.service.main' (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkState(ComponentManagerImpl.kt:183)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findMainMethod(SparkContextUtils.kt:89)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:82)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(S

**Comment by fengshuaihu** [comment]
Please update to the latest version and try again, if you encounter this issue again, feel free to turn it on again
