### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: /home/jamie/IDEs/idea-IU-221.5921.22/jbr/lib/libjcef.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)

### ISSUE THREAD

**Issue by jamie-codez** [microsoft/azure-tools-for-java#7242]
IntelliJ build version: 2022.1.3 IU-221.5921.22
OS: Linux
JDK: JetBrains s.r.o. 11.0.15
Plugin version: 3.70.1-2022.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,1400x963,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: /home/jamie/IDEs/idea-IU-221.5921.22/jbr/lib/libjcef.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewAction.lambda$doShow$2(WhatsNewAction.java:81)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:102)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInO

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/6673
