### ISSUE TITLE
eclipse azure plugin stopped working

### ISSUE THREAD

**Issue by takada-norimasa** [microsoft/azure-tools-for-java#7273]
(1) NullPointerException occurs when signing in to App Service deployment in Azure Toolkit for Eclipse, and sign-in becomes impossible.
(2) If you perform the same operation again, the Eclipse process will always fail to acquire a lock for another thread and fail to acquire lock.
[ｴﾗｰ.zip](https://github.com/microsoft/azure-tools-for-java/files/10564127/default.zip)
![タイトルなし](https://user-images.githubusercontent.com/124223131/216213074-6eae3019-3842-474c-9cbe-66241c5c66bf.png)

**Comment by Flanker32** [comment]
@takada-norimasa Thanks a lot for your report and sorry for the trouble. Could you please help share the version of Azure Toolkit as well as Eclipse? Besides, could you please help share the log of workspace if possible, you may find it `your_workspace/.metadata/.log`

**Comment by takada-norimasa** [comment]
[log.zip](https://github.com/microsoft/azure-tools-for-java/files/10565686/log.zip)

**Comment by Flanker32** [comment]
@takada-norimasa Thanks for your quick response. Azure Toolkit leverage msal for authentication and it seems that there are some exception to save token in your machine. Could you please try backup and remove the loca msal cache in `{user_home}\AppData\Local\.IdentityService` and try sign in again? (Note: this will remove your authentication status for other Azure tooling like Azure CLI/Visual Studio as well)

Besides, if you have Azure Cli in your machine, you may also try sign in with Azure Cli as a workaround.

```
Caused by: com.microsoft.aad.msal4jextensions.CacheFileLockAcquisitionException: pid:1744 thread:135 failed to acquire lock
	at com.microsoft.aad.msal4jextensions.CrossProcessCacheFileLock.lock(CrossProcessCacheFileLock.java:129)
	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.beforeCacheAccess(PersistenceTokenCacheAccessAspect.java:115)
	at com.azure.identity.implementation.PersistentTokenCacheImpl.beforeCacheAccess(PersistentTokenCacheImpl.java:68)
	at com.microsoft.aad.msal4j.TokenCache$CacheAspect.<init>(TokenCache.java:164)
	at com.microsoft.aad.msal4j.TokenCache.saveTokens(TokenCache.java:181)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:131)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.acquireTokenWithAuthorizationCode(AcquireTokenByInteractiveFlowSupplier.java:185)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:39)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```
```
Caused by: com.sun.jna.platform.win32.Win32Exception: 指定された状態で使用するには無効なキーです。
	at com.sun.jna.platform.win32.Crypt32Util.cryptUnprotectData(Crypt32Util.java:144)
	at com.sun.jna.platform.win32.Crypt32Util.cryptUnprotectData(Crypt32Util.java:117)
	at com.sun.jna.platform.win32.Crypt32Util.cryptUnprotectData(Crypt32Util.java:104)
	at com.microsoft.aad.msal4jextensions.persistence.CacheFileAccessor.read(CacheFileAccessor.java:46)
	at com.microsoft.aad.msal4jextensions.PersistenceTokenCacheAccessAspect.beforeCacheAccess(PersistenceTokenCacheAccessAspect.java:125)
	at com.azure.identity.implementation.PersistentTokenCacheImpl.beforeCacheAccess(PersistentTokenCacheImpl.java:68)
	at com.microsoft.aad.msal4j.TokenCache$CacheAspect.<init>(TokenCache.java:164)
	at com.microsoft.aad.msal4j.TokenCache.saveTokens(TokenCache.java:181)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:131)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.acquireTokenWithAuthorizationCode(AcquireTokenByInteractiveFlowSupplier.java:185)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:39)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```

**Comment by takada-norimasa** [comment]
I was able to log in. Thank you very much.

**Comment by Flanker32** [comment]
@takada-norimasa Glad to see the issue was resolved, please feel free to re-open it if you have any further requests
