### ISSUE TITLE
[IntelliJ] Runner Debug is not registered, sometimes it throws.

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#733]
Runner Debug is not registered
java.lang.Throwable
                at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
                at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.java:450)
                at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.java:355)
                at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:364)
                at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
                at com.microsoft.azure.hdinsight.spark.run.SparkBatchJobDebuggerRunner.lambda$startDebuggerObservable$7(SparkBatchJobDebuggerRunner.java:267)
                at rx.internal.operators.SingleFromEmitter.call(SingleFromEmitter.java:48)
                at rx.internal.operators.SingleFromEmitter.call(SingleFromEmitter.java:34)
                at rx.Single.subscribe(Single.java:1876)
                at rx.Single$13$1.call(Single.java:1948)
                at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
                at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
                at java.lang.Thread.run(Thread.java:745)

**Comment by wezhang** [comment]
can't repro
