### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files

### ISSUE THREAD

**Issue by madejusz** [microsoft/azure-tools-for-java#7374]
IntelliJ build version: 2022.3.3 RC IU-223.8836.35
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.74.1-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2561x1392,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:42)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:32)
```

**Comment by wangmingliang-ms** [comment]
close as this bug have been fixed since 3.75.0, feel free to reopen this issue if it reappears.
