### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files

### ISSUE THREAD

**Issue by paulschuberth** [microsoft/azure-tools-for-java#7378]
IntelliJ build version: 2022.3.3 IU-223.8836.41
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.74.1-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1575,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize editor highlighter for Bicep files
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:42)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.microsoft.azure.toolkit.intellij.bicep.highlight.BicepEditorHighlighterProvider.getEditorHighlighter(BicepEditorHighlighterProvider.java:32)
```

**Comment by paulschuberth** [comment]
Duplicate of #7374
