### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException

### ISSUE THREAD

**Issue by krishna-rawat-hp** [microsoft/azure-tools-for-java#7380]
IntelliJ build version: 2021.1 IC-211.6693.111
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.10
Plugin version: 3.58.0-2021.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x673,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessage.getCause(AzureMessage.java:106)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureHtmlMessage.getCause(AzureHtmlMessage.java:48)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessage.getContent(AzureMessage.java:68)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureHtmlMessage.getContent(AzureHtmlMessage.java:41)
	at com.microsoft.azure.toolkit.intellij.common.messager.NotificationMessage.getContent(IntellijAzureMessage.java:71)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager.showNotification(IntellijAzureMessager.java:94)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager.show(IntellijAzureMessager.java:76)
	at com.microsoft.azure.toolkit.lib.common.messager.IAzureMessager.error(IAzureMessager.java:52)
	at com.microsoft.azure.toolkit.lib.common.messager.IA

**Comment by wangmingliang-ms** [comment]
@krishna-rawat-hp this problem was fixed in later versions, can you upgrade to the latest and try again?
