### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: no jcef in java.library.path: /usr/local/cuda-11.0/lib64::/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib

### ISSUE THREAD

**Issue by fanghostt** [microsoft/azure-tools-for-java#7439]
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Linux
JDK: Private Build 17.0.6
Plugin version: 3.75.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,86,2382x1652,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: no jcef in java.library.path: /usr/local/cuda-11.0/lib64::/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewAction.lambda$doShow$2(WhatsNewAction.java:80)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:102)

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7570
