### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by EthanRMcElree** [microsoft/azure-tools-for-java#7440]
IntelliJ build version: 2022.2.1 IU-222.3739.54
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.3
Plugin version: 3.74.1-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,0,1246x633,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:54)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:54)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.slimui.WebAppDeployConfigurationPanel.lambda$setValue$20(WebAppDeployConfigurationPanel.java:277)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.slimui.WebAppDeployConfigurationPanel.setValue(WebAppDeployConfigurationPanel.java:276)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.slimui.WebAppSlimSettingPanel.resetFromConfig(WebAppSlimSettingPanel.java:143)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.slimui.WebAppSlimSettingPanel.resetFromConfig(WebAppSlimSettingP

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9483
