### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize Azure explorer

### ISSUE THREAD

**Issue by SCP-King** [microsoft/azure-tools-for-java#7444]
IntelliJ build version: 2022.3.2 IU-223.8617.56
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.75.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x824,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: initialize Azure explorer
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.intellij.ui.ServerExplorerToolWindowFactory.createToolWindowContent(ServerExplorerToolWindowFactory.java:166)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "com.microsoft.tooling.msservices.serviceexplorer.Node.node2Actions" is null
	at com.microsoft.tooling.msservices.serviceexplorer.Node.initActions(Node.java:317)
	at com.microsoft.tooling.msservices.serviceexplorer.Node.loadActions(Node.java:285)
	at com.microsoft.tooling.msservices.serviceexplorer.RefreshableNode.loadAct

**Comment by Flanker32** [comment]
Issue has been fixed in https://github.com/microsoft/azure-tools-for-java/pull/7451/files
