### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: Assertion failed

### ISSUE THREAD

**Issue by YoganandaGit** [microsoft/azure-tools-for-java#7479]
IntelliJ build version: 2022.3.3 IU-223.8836.41
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.75.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:254)
	at com.microsoft.azure.toolkit.ide.guidance.GuidanceViewManager.lambda$openCourseView$0(GuidanceViewManager.java:39)
```

**Comment by wangmingliang-ms** [comment]
this issue is fixed in latest release, feel free to reopen it if you get this error again
