### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception unexpected failure in initializing client. java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. More info: https://aka.ms/cosmosdb-tsg-service-unavailable-java

### ISSUE THREAD

**Issue by vinkarkhanis** [microsoft/azure-tools-for-java#7507]
IntelliJ build version: 2023.1.1 IC-231.8770.65
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=unexpected failure in initializing client., throwable=java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. More info: https://aka.ms/cosmosdb-tsg-service-unavailable-java
	at com.azure.cosmos.implementation.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:476)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.getCosmosClient(SqlCosmosDBAccount.java:95)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.updateAdditionalProperties(SqlCosmosDBAccount.java:79)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.updateAdditionalProperties(SqlCosmosDBAccount.java

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8383
