### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/cody.zwiefelhofer/Library/Caches/JetBrains/IntelliJIdea2022.3/index/frameworkdetectionindex/.perFileVersion/indexed_versions/indexed_versions

### ISSUE THREAD

**Issue by codyzwief** [microsoft/azure-tools-for-java#7625]
IntelliJ build version: 2022.3 IU-223.7571.182
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.71.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1814x946,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@3b76d8a0,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/cody.zwiefelhofer/Library/Caches/JetBrains/IntelliJIdea2022.3/index/frameworkdetectionindex/.perFileVersion/indexed_versions/indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findJavaMainClass(SparkContextUtils.kt:94)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:83)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7157
