### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/bass/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat

### ISSUE THREAD

**Issue by BSluijs** [microsoft/azure-tools-for-java#7627]
IntelliJ build version: 2023.1.2 IU-231.9011.34
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2777x1174,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/bass/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.microsoft.azure.toolkit.intellij.bicep.BicepEditorNotificationProvider.collectNotificationData(BicepEditorNotificationProvider.java:36)
Caused by: com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/bass/Library/Caches/JetBrains/IntelliJIdea2023.1/caches/names.dat
```

**Comment by Flanker32** [comment]
@BSluijs Thanks for your report and sorry for the trouble, could this issue be stable reproduced? If so, could you please help provide the steps to reproduce this issue?
