### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by Kotsiubynskyi** [microsoft/azure-tools-for-java#7638]
IntelliJ build version: 2023.1.2 IU-231.9011.34
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1981x1152,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.intellij.legacy.function.FunctionAppCreationDialog.createUIComponents(FunctionAppCreationDialog.java:66)
	at com.microsoft.azure.toolkit.intellij.legacy.function.FunctionAppCreationDialog.$$$setupUI$$$(FunctionAppCreationDialog.java)
	at com.microsoft.azure.toolkit.intellij.legacy.function.FunctionAppCreationDialog.<init>(FunctionAppCreationDialog.java:38)
	at com.microsoft.azure.toolkit.intellij.legacy.function.FunctionAppComboBox.createResource(FunctionAppComboBox.java:35)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox$

**Comment by Flanker32** [comment]
@Kotsiubynskyi Thanks for your report, to create a function app, you need to sign in with your azure account first. You may do it with `Tools` -> `Azure` -> `Azure Sign In...`
