### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.operation.OperationException: start listening to instance ({0})

### ISSUE THREAD

**Issue by HariKiran9** [microsoft/azure-tools-for-java#7643]
IntelliJ build version: 2022.3.3 IC-223.8836.41
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x753,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.operation.OperationException: start listening to instance ({0})
Caused by: com.microsoft.azure.toolkit.lib.common.operation.OperationException: start listening to instance ({0})
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.common.component.SenderReceiverPanel.execute(SenderReceiverPanel.java:119)
Caused by: reactor.core.Ex

**Comment by Flanker32** [comment]
@HariKiran9 Thanks a lot for your report, could you please provide a bit more information? Like the steps to reproduce this issue?
