### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: generate environment variables for resource (...)

### ISSUE THREAD

**Issue by akaroml** [microsoft/azure-tools-for-java#7656]
IntelliJ build version: 2023.1.2 IC-231.9011.34
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.78.0-2023.1-BETA.20230629025803
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1415,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@f8755dd,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: generate environment variables for resource ()
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.Profile.generateEnvLines(Profile.java:138)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.Profile.lambda$addConnectionToDotEnv$4(Profile.java:176)
Caused by: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException: storageAccounts '' does not exist.
	at com.microsoft.azure.toolkit.intellij.connector.AzureServiceResource.initEnv(AzureServiceRes

**Comment by akaroml** [comment]
"storageAccounts '' does not exist", from the error message, the exception should not be exposed as unhandled, because it's handleable.
