### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception RunFunctionAction#update@ProjectViewPopup (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(backend) is a valid function project

### ISSUE THREAD

**Issue by volsky** [microsoft/azure-tools-for-java#7666]
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Linux
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,37,2560x1376,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=RunFunctionAction#update@ProjectViewPopup (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(backend) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.core.FunctionUtils.isFunctionProject(FunctionUtils.java:189

**Comment by Flanker32** [comment]
@volsky  Thanks for your report and sorry for the late response, this issue should be resolved in the latest toolkit (v3.78.1), could you please upgrade to the latest toolkit and try again?
