### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.IllegalArgumentException: 'null' in roots: [null]

### ISSUE THREAD

**Issue by avbtrifork** [microsoft/azure-tools-for-java#7677]
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2331x1400,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.IllegalArgumentException: 'null' in roots: [null]
	at com.intellij.openapi.fileChooser.FileChooserDescriptor.withRoots(FileChooserDescriptor.java:167)
	at com.microsoft.azure.toolkit.intellij.facet.AzureFacetEditorPanel.createUIComponents(AzureFacetEditorPanel.java:42)
	at com.microsoft.azure.toolkit.intellij.facet.AzureFacetEditorPanel.$$$setupUI$$$(AzureFacetEditorPanel.java)
	at com.microsoft.azure.toolkit.intellij.facet.AzureFacetEditorPanel.<init>(AzureFacetEditorPanel.java:23)
	at com.microsoft.azure.toolkit.intellij.facet.AzureFacetEditorTab.<init>(AzureFacetEditorTab.java:35)
	at com.microsoft.azure.toolkit.intellij.facet.AzureFacetConfiguration.createEditorTabs(AzureFacetConfiguration.java:62)
```

**Comment by wangmingliang-ms** [comment]
thanks for reporting, this will be fixed in next release.
