### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(discos-storage) is a valid function project

### ISSUE THREAD

**Issue by antonikozielewski-tomtom** [microsoft/azure-tools-for-java#7681]
IntelliJ build version: 2023.1.3 IU-231.9161.38
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1410,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(discos-storage) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit

**Comment by Flanker32** [comment]
@antonikozielewski-tomtom  Thanks for your report and sorry for the late response, this issue should be resolved in the latest toolkit (v3.78.1), could you please upgrade to the latest toolkit and try again?
