### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 79256125-db20-4aca-8297-54d8660d7da0] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed. java.lang.InterruptedException: sleep interrupted

### ISSUE THREAD

**Issue by AryanChaurasiaCorpseed** [microsoft/azure-tools-for-java#7682]
IntelliJ build version: 2022.2.2 IU-222.4167.29
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.4
Plugin version: 3.75.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1281x984,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 79256125-db20-4aca-8297-54d8660d7da0] Execution of class com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier failed., throwable=java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.acquireTokenWithDeviceCode(AcquireTokenByDeviceCodeFlowSupplier.java:62)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:27)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
```

**Comment by Flanker32** [comment]
@AryanChaurasiaCorpseed Thanks for your report and sorry for the late response. It seems to be an authentication issue of device code login, could this issue be stable reproduced? If so, would you mind share the full error stack with us?
Besides, as a workaround, could you please try other methods like OAuth or Azure Cli?
