### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception RunFunctionAction#update@GoToAction (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(Analytics) is a valid function project

### ISSUE THREAD

**Issue by rdahagam0984** [microsoft/azure-tools-for-java#7683]
IntelliJ build version: 2022.3.3 IC-223.8836.41
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=RunFunctionAction#update@GoToAction (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(Analytics) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.core.FunctionUtils.isFunctionProject(FunctionUtils.java:189)

**Comment by Flanker32** [comment]
@rdahagam0984  Thanks for your report and sorry for the late response, this issue should be resolved in the latest toolkit (v3.78.1), could you please upgrade to the latest toolkit and try again?
