### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(pingpong) is a valid function project

### ISSUE THREAD

**Issue by aborschenko-bidgely** [microsoft/azure-tools-for-java#7688]
IntelliJ build version: 2023.1.4 IU-231.9225.16
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x966,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@ffe3c16,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(pingpong) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.t

**Comment by Flanker32** [comment]
@aborschenko-bidgely  Thanks for your report and sorry for the late response, this issue should be resolved in the latest toolkit (v3.78.1), could you please upgrade to the latest toolkit and try again?
