### ISSUE TITLE
stopping web app from azure explorer throws error

### ISSUE THREAD

**Issue by arroyc** [Microsoft/azure-tools-for-java#77]
It's saying resource not found, but how did it show up in the list
![image](https://cloud.githubusercontent.com/assets/16231002/23078735/c34db4e0-f4fe-11e6-85c1-ec86acaff3e6.png)

{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/webapp-170217103240' under resource group 'rg-webapp-170217103240' was not found."}}
com.microsoft.rest.ServiceException: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/webapp-170217103240' under resource group 'rg-webapp-170217103240' was not found."}}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:150)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.stopDelegate(WebAppsInner.java:22197)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.access$18600(WebAppsInner.java:49)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$759.call(WebAppsInner.java:22187)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner$759.call(WebAppsInner.java:22183)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:342)
	at com.microsoft.azure.management.appservice.implementation.WebAppsInner.stop(WebAppsInner.java:22130)
	at com.microsoft.azure.management.appservice.implementation.WebAppImpl.stop(WebAppImpl.java:189)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappNode$1$1.run(WebappNode.java:78)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martinsawicki** [comment]
not sure how to repro... (I can't repro)
Mona - sending it to you so you can play with it some more and see if we have any issues with WebApp stop and delete in the latest builds. if not then pls close.

**Comment by bsaby** [comment]
This issue is caused by a webapp exists in the Azure Explorer list but does not exist on portal.

Repro the issue used artifacts/azure-toolkit-for-intellij.229.zip.
repro steps:
1.Deploy Web App with 3rd party JDK and new resource group
3. After deploy successfully, right click the web app choose **Delete**
4. Delete will failed, right click the web app choose **Stop**

In Azure explorer of intelliJ, it will prompt delete failed and the webapp won't disappear in the list. But  in protal, the webapp has been deleted.

**Error log for deleting failed**
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at java.util.AbstractCollection.remove(AbstractCollection.java:293)
	at com.microsoft.azuretools.utils.AzureModelController.removeWebAppFromExistingResourceGroup(AzureModelController.java:313)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.webapps.WebappNode$DeleteWebAppAction.azureNodeAction(WebappNode.java:128)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.AzureNodeActionListener.actionPerformed(AzureNodeActionListener.java:54)
	at com.microsoft.tooling.msservices.serviceexplorer.NodeActionListenerAsync$1.run(NodeActionListenerAsync.java:56)
	at com.microsoft.intellij.helpers.IDEHelperImpl$2$1.run(IDEHelperImpl.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bsaby** [comment]
Not repro in artifacts/azure-toolkit-for-intellij.36.zip.
