### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: 13500 ms to call on EDT ServerExplorerToolWindowFactory$RefreshAllAction#update@ToolwindowTitle (com.microsoft.intellij.ui.ServerExplorerToolWindowFactory$RefreshAllAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by goldensignal** [microsoft/azure-tools-for-java#7702]
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.76.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1673x1356,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@1e871682,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: 13500 ms to call on EDT ServerExplorerToolWindowFactory$RefreshAllAction#update@ToolwindowTitle (com.microsoft.intellij.ui.ServerExplorerToolWindowFactory$RefreshAllAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
		at com.microsoft.azure.toolkit.lib.auth.Account.getSelectedSubscriptions(Account.java:227)
		at com.microsoft.azure.toolkit.lib.auth.Account.isLoggedInCompletely(Account.jav

**Comment by Flanker32** [comment]
@goldensignal Thanks for your report and sorry for the late response. This issue should be resolved in our latest release (v3.78.1). Could you please upgrade to the latest version and see whether this issue could be reproduced?
