### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by manishk-flalottery** [microsoft/azure-tools-for-java#7703]
IntelliJ build version: 2023.1.4 IU-231.9225.16
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.78.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationException
	at <REDACTED: user-file-path>$Itr.checkForComodification(ArrayList.java:1013)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.action.DeployWebAppAction.lambda$runConfiguration$2(DeployWebAppAction.java:74)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:117)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.execute(AzureOperationAspect.java:108)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$0(AzureTaskManager.java:384)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:85)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$runInObservable$1(AzureTaskManager.java:382)
```

**Comment by manishk-flalottery** [comment]
IntelliJ Ultimate Issues

**Comment by Flanker32** [comment]
@MANISHK-GITHUB Thanks a lot for your report and sorry for the late response. This seems to be an UX render issue of IntelliJ, could you please help provide the repro steps if the issue could be reproduced? Many thanks!
