### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: 28448d3e-4332-4ccb-ac7b-19a3a15f7a9e] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed. com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server

### ISSUE THREAD

**Issue by hakdogan** [microsoft/azure-tools-for-java#7708]
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.78.1-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x875,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@162568fe,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: 28448d3e-4332-4ccb-ac7b-19a3a15f7a9e] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed., throwable=com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResult

**Comment by Flanker32** [comment]
@hakdogan Thanks for your report and sorry for the late response. It seems to be an authentication issue, could you please try sign-in again and see whether this issue could be reproduced? If so, could you please share the authentication method and error stack for us for error investigation? Many thanks!

**Comment by hakdogan** [comment]
Hi @Flanker32,

Actually, this report occurred when I try some test drives about Azure KeyVault on my local. It has not happened after making some changes.  The bad news is that I don't have the history of my steps at the moment. So, I don't have any more details about this for now. 

Sorry for this.
