### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception RunFunctionAction#update@GoToAction (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(SeeWhosOnAdminService.java) is a valid function project

### ISSUE THREAD

**Issue by sarojpradhan** [microsoft/azure-tools-for-java#7715]
IntelliJ build version: 2022.3.2 IU-223.8617.56
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1016,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@7efd0905,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=RunFunctionAction#update@GoToAction (com.microsoft.azure.toolkit.intellij.legacy.function.action.RunFunctionAction), actionId=Actions.RunFunction, text='Run Function', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(SeeWhosOnAdminService.java) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.core.Function

**Comment by Flanker32** [comment]
@sarojpradhan  Thanks for your report and sorry for the late response, this issue should be resolved in the latest toolkit (v3.78.1), could you please upgrade to the latest toolkit and try again?
