### ISSUE TITLE
[Eclipse+IU2017]Redis cache:The error message for deleted redis cache should be more specific

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#774]
BUild: Daily76
OS: All
Repro step:
1.create redis Cache A
2.delete A on portal
3.right click A in the plugin window, open redis explorer
4.the error window pop out
EXPEXT: The error message should be more specific

![image](https://user-images.githubusercontent.com/22470312/28513386-95cc25a0-7088-11e7-8109-720cf5f5c944.png)

Log:
!MESSAGE Cannot get Redis Cache's information.
!STACK 0
java.lang.NullPointerException
at com.microsoft.azuretools.core.mvp.model.rediscache.RedisConnectionPools.connect(RedisConnectionPools.java:94)
at com.microsoft.azuretools.core.mvp.model.rediscache.RedisConnectionPools.getJedis(RedisConnectionPools.java:69)
at com.microsoft.azuretools.core.mvp.model.rediscache.RedisExplorerMvpModel.getDbNumber(RedisExplorerMvpModel.java:66)
at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisExplorerPresenter.lambda$0(RedisExplorerPresenter.java:63)
at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
at rx.Observable.unsafeSubscribe(Observable.java:10142)
at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
@jdneo

**Comment by jdneo** [comment]
@bsaby Fixed, please help verify it in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
Build: dev319
Eclipse
![image](https://user-images.githubusercontent.com/22470312/29402926-502fd822-8369-11e7-9734-30ccd22da56d.png)
IntelliJ
![image](https://user-images.githubusercontent.com/22470312/29402951-5d6cc41e-8369-11e7-9896-fbcc65f6f3de.png)
