### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot process toolwindow Resource Connections java.lang.RuntimeException: VFS name enumerator corrupted: nameId(=3896051) is not found in enumerator (=null)

### ISSUE THREAD

**Issue by conceptiveconsulting** [microsoft/azure-tools-for-java#7821]
IntelliJ build version: 2023.1.2 IU-231.9011.34
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot process toolwindow Resource Connections, throwable=java.lang.RuntimeException: VFS name enumerator corrupted: nameId(=3896051) is not found in enumerator (=null)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.cacheData(FileNameCache.java:70)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.lambda$new$0(AzureModule.java:59)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.<init>(AzureModule.java:59)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.lambda$from$12(AzureModule.java:207)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.from(AzureModule.java:207)
	at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.list(Az

**Comment by wangmingliang-ms** [comment]
please update the plugin to the latest.
