### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException: Cannot load property.

### ISSUE THREAD

**Issue by alihirv** [microsoft/azure-tools-for-java#7834]
IntelliJ build version: 2022.3.3 IC-223.8836.41
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1442x853,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@7f92a429,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException: Cannot load property.
	at com.microsoft.azure.toolkit.ide.common.store.DefaultMachineStore.load(DefaultMachineStore.java:67)
	at com.microsoft.azure.toolkit.ide.common.store.DefaultMachineStore.<init>(DefaultMachineStore.java:29)
	at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:134)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
	at com.microsoft.azure.toolkit.lib.common.utils.JsonUtils.fromJson(JsonUtils.java:49)
	at com.microsoft.azure.toolkit.ide.common.store.DefaultMachineStore.load(DefaultMachineStore.java:62)
```

**Comment by Flanker32** [comment]
@alihirv Thanks for your report and sorry for the late response. We are working on this issue and will update here once we get any updates. 
If the issue is still reproduced in your machine, as a workaround, could you please try cleaning up the toolkit storage and restart IntelliJ? The storage file should locate in `${user_home}\AppData\Roaming\JetBrains\${your_intellij_version}\options\azure-data.xml`
