### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Function app (mgitrigger-230914145449)

### ISSUE THREAD

**Issue by dcase-uscold** [microsoft/azure-tools-for-java#7858]
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.2-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x985,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Function app (mgitrigger-230914145449)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:555)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:265)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.getOrTemp(AbstractAzResourceModule.java:333)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.ui.FunctionDeploymentPanel.getResourceId(FunctionDeploymentPanel.java:322)
	at

**Comment by dcase-uscold** [comment]
I don't know what I am doing.
