### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "javax.swing.JRootPane.getClientProperty(Object)" because "rootpane" is null

### ISSUE THREAD

**Issue by dcase-uscold** [microsoft/azure-tools-for-java#7859]
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.2-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1678x1080,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "javax.swing.JRootPane.getClientProperty(Object)" because "rootpane" is null
	at <REDACTED: user-file-path>(CPlatformWindow.java:487)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectorDialog.onResourceOrConsumerTypeChanged(ConnectorDialog.java:143)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:191)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.lambda$setValue$2(AzureComboBox.java:153)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setValue(AzureComboBox.java:142)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setValue(AzureComboBox.java:138)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureCom

**Comment by Flanker32** [comment]
@dcase-uscold Thank you for reporting this issue and we are sorry for the trouble. We are working on fixing this issue as soon as possible. We will keep you updated on the progress of this issue here.
