### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load App Service plan (sp-app-eatstime-230917232407)

### ISSUE THREAD

**Issue by hlleee** [microsoft/azure-tools-for-java#7860]
IntelliJ build version: 2023.2.1 IU-232.9559.62
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.2-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x863,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load App Service plan (sp-app-eatstime-230917232407)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:555)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:265)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.getOrDraft(AbstractAzResourceModule.java:324)
	at com.microsoft.azure.toolkit.lib.appservice.config.AppServicePlanConfig.toResource(AppServicePlanConfig.java:61)
	at co

**Comment by Flanker32** [comment]
@hlleee Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
