### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.diagnostic.PluginException: 826 ms to call on EDT ApplicationInsightsAction#update@GoToAction (com.microsoft.intellij.actions.ApplicationInsightsAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]

### ISSUE THREAD

**Issue by mrinalgupta1097** [microsoft/azure-tools-for-java#7864]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.2-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x673,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.diagnostic.PluginException: 826 ms to call on EDT ApplicationInsightsAction#update@GoToAction (com.microsoft.intellij.actions.ApplicationInsightsAction). Revise AnAction.getActionUpdateThread property [Plugin: com.microsoft.tooling.msservices.intellij.azure]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
		at com.microsoft.intellij.actions.ApplicationInsightsAction.update(ApplicationInsightsAction.java:32)
		at com.microsoft.intellij.actions.ApplicationInsightsAction.update(ApplicationInsightsAction.java:32)
```

**Comment by Flanker32** [comment]
@mrinalgupta1097 
Thank you for reporting this issue and we apologize for the delayed response. We have fixed this issue in our latest release. Could you please update to toolkit v3.81.0 and check if the issue is resolved?
