### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   [Correlation ID: 373cf1b6-b2a5-406e-9386-4b228d0cfd5b] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.

### ISSUE THREAD

**Issue by Serendipity426** [microsoft/azure-tools-for-java#7871]
IntelliJ build version: 2023.2 IU-232.8660.185
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.80.2-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1384x992,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  [Correlation ID: 373cf1b6-b2a5-406e-9386-4b228d0cfd5b] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed.
  com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)

**Comment by Flanker32** [comment]
@Serendipity426 Thank you for reporting this issue and we apologize for the delay in responding to you. This issue seems to be caused by an authentication problem. Could you please try signing in again and check if the issue is resolved?

**Comment by Serendipity426** [comment]
thank you
