### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(damoa-server) is a valid function project

### ISSUE THREAD

**Issue by kangsan-rpls** [microsoft/azure-tools-for-java#7873]
IntelliJ build version: 2022.3.3 RC IU-223.8836.35
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(damoa-server) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.int

**Comment by Flanker32** [comment]
@kangsan-rpls Thank you for reporting this issue and we apologize for the delay in getting back to you. We have resolved this issue in the latest release. Could you please update to the latest toolkit v3.81.0 and confirm if the issue is fixed?
