### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Error creating Spring Boot run configuration for minfin.gov.ao.ms_servico_portal_denucia.MsServicoPortalDenuciaApplication

### ISSUE THREAD

**Issue by AugustoNapoleao1996** [microsoft/azure-tools-for-java#7882]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.80.2-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1921x1033,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Error creating Spring Boot run configuration for minfin.gov.ao.ms_servico_portal_denucia.MsServicoPortalDenuciaApplication
   java.lang.RuntimeException: Cannot invoke (class=BeforeRunTaskAdder, method=runConfigurationAdded, topic=RunManager)
	Caused by: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
		at com.microsoft.azure.toolkit.intellij.connector.dotazure.ResourceManager.reload(ResourceManager.java:61)
		at com.microsoft.azure.toolkit.intellij.connector.dotazure.ResourceManager.<init>(ResourceManager.java:52)
		at com.microsoft.azure.toolkit.intellij.connector.dotazure.Profile.<init>(Profile.java:69)
		at com.microsoft.azure.toolkit.intellij.connector.dotazure.Az

**Comment by Flanker32** [comment]
@AugustoNapoleao1996 Thank you for reporting this issue and we are sorry for the trouble. We are working on fixing this issue as soon as possible. We will keep you updated on the progress of this issue here.

**Comment by wangmingliang-ms** [comment]
Duplicate of #7898
