### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Operator called default onErrorDropped

### ISSUE THREAD

**Issue by headinthebox** [microsoft/azure-tools-for-java#7898]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1600x900,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$1@4855423f,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Operator called default onErrorDropped
   com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy to Azure Web App(automind-vm) with resource creation or updating
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.appservice.task.DeployWebAppTask.doExecute(DeployWebAppTask.java:91)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.deployArtifactsToWebApp(AzureWebAppMvpModel.java:215)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:98)
	at com.micros

**Comment by Flanker32** [comment]
@headinthebox Thanks for your report and sorry for the trouble. We are looking into it and trying to fix it as quickly as we can. We will update you on the progress here.
