### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-231002153512)

### ISSUE THREAD

**Issue by SoLongAndThanksForAllTheFish** [microsoft/azure-tools-for-java#7903]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2699x1232,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$1@7d8ffd6,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-231002153512)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:576)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:286)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.getResourceGroup(AbstractAzResource.java:309)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.exists(AbstractAzResource.java:10

**Comment by Flanker32** [comment]
@SoLongAndThanksForAllTheFish Thanks for your report and sorry for the trouble. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
