### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by TiagoGuerra001** [microsoft/azure-tools-for-java#7905]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.WebAppCreationDialog.createUIComponents(WebAppCreationDialog.java:69)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.WebAppCreationDialog.$$$setupUI$$$(WebAppCreationDialog.java)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.WebAppCreationDialog.<init>(WebAppCreationDialog.java:35)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.slimui.WebAppComboBox.createResource(WebAppComboBox.java:45)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox$AzureComboBoxEditor.la

**Comment by Flanker32** [comment]
@TiagoGuerra001 Thanks for your report and sorry for the trouble. To create a web app with azure toolkit, please sign in with your account first, you may sign in by `Tools -> Azure -> Azure Sign In`
