### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped java.lang.InterruptedException

### ISSUE THREAD

**Issue by jordyvega03** [microsoft/azure-tools-for-java#7907]
IntelliJ build version: 2023.1.1 IU-231.8770.65
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.81.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@1c19d7f0,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=java.lang.InterruptedException
	at <REDACTED: user-file-path>(Native Method)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:258)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:157)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:93)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
```

**Comment by Flanker32** [comment]
@JordyV3 Thanks for your report and sorry for the trouble, we will fix this issue in our next release, will update here once we get any updates.
