### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@5b57775b when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@4f9927e9

### ISSUE THREAD

**Issue by prshnt** [microsoft/azure-tools-for-java#7920]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1380x875,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@5b57775b when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@4f9927e9
<REDACTED: Generic Secret>
at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)

**Comment by Flanker32** [comment]
@prshnt Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
