### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Operator called default onErrorDropped

### ISSUE THREAD

**Issue by tamasazure** [microsoft/azure-tools-for-java#7921]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@692b400,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Operator called default onErrorDropped
  java.lang.InterruptedException
at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:258)
at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:157)
at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.executeSteps(FunctionRunState.java:93)
at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
```

**Comment by Flanker32** [comment]
@tamasazure Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?

**Comment by wangmingliang-ms** [comment]
Duplicate of #7907

**Comment by tamasazure** [comment]
Hi,

I cannot exactly recall when this is happened - but as far as I remember this exception was thrown when I stopped the azure function running in the Intellij.

**Comment by Flanker32** [comment]
> I cannot exactly recall when this is happened - but as far as I remember this ex

Got it, thanks for your message. It seems that toolkit did not handle the interrupted exception well, we will fix this issue in the next release, will update here once we get any updates.

**Comment by wangmingliang-ms** [comment]
Duplicate of #7898
