### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Unhandled exception in [CoroutineName(com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener), StandaloneCoroutine{Cancelling}@2f50345a, Dispatchers.Default]

### ISSUE THREAD

**Issue by The-Funk** [microsoft/azure-tools-for-java#7937]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.81.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1032,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Unhandled exception in [CoroutineName(com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener), StandaloneCoroutine{Cancelling}@2f50345a, Dispatchers.Default]
   java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.toolkit.lib.common.action.AzureActionManager$Holder
	at com.microsoft.azure.toolkit.lib.common.action.AzureActionManager.getInstance(AzureActionManager.java:40)
	at com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener.tryOpenAI(CognitiveServicesStartupListener.java:51)
	at com.microsoft.azure.toolkit.intellij.cognitiveservices.CognitiveServicesStartupListener

**Comment by Flanker32** [comment]
@The-Funk Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
