### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@4f79d0e1 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@76c7cfdc

### ISSUE THREAD

**Issue by jarbitman** [microsoft/azure-tools-for-java#7938]
IntelliJ build version: 2023.2.3 IU-232.10072.27
OS: Linux
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.81.1-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1048,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@4f79d0e1 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@76c7cfdc
  java.util.ConcurrentModificationException
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.list(AbstractAzResourceModule.java:146)
at com.microsoft.azure.toolkit.lib.common.model.AbstractAzService.list(AbstractAzService.java:50)
at com.microsoft.azure.toolki

**Comment by Flanker32** [comment]
@jarbitman Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
