### ISSUE TITLE
Travis IntegrationTest fail

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/azure-tools-for-java#799]
```

[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Content-Length: 123
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Content-Type: application/json; charset=utf-8
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Date: Tue, 18 Jul 2017 04:30:04 GMT
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Expires: -1
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Pragma: no-cache
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Server: Microsoft-HTTPAPI/2.0
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Strict-Transport-Security: max-age=31536000; includeSubDomains
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - Vary: Accept-Encoding
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - x-content-type-options: nosniff
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - x-ms-correlation-request-id: 76517e07-06b6-438b-8db2-111472990688
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - x-ms-ratelimit-remaining-subscription-writes: 1190
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - x-ms-request-id: 8562ea84-8b4d-402c-81ba-b30b31030c36
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - x-ms-routing-request-id: WESTUS:20170718T043005Z:76517e07-06b6-438b-8db2-111472990688
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - x-rp-server-mvid: 591bd6c7-22e4-4539-8fd3-9f5a21a5e75f
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - 123-byte body:
{"primaryKey":"LHH7JxG6mCunDAjlNKDFFlv8sCGpp7Raw7NGLmfztVI=","secondaryKey":"QoYVHaaf5m5upT6+3p/Cx1spx6T0cBo36RYfXUb9u3Q="}
[main] INFO com.microsoft.azure.management.redis.Redis listKeys - <-- END HTTP
[main] INFO org.eclipse.jetty.server.NetworkTrafficServerConnector - Stopped NetworkTrafficServerConnector@64b31700{HTTP/1.1}{0.0.0.0:3221}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@13c612bd{/,null,UNAVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@36dce7ed{/__admin,null,UNAVAILABLE}
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-200,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-207,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-208,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-209,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-210,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-211,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-212,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-213,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-214-selector-ServerConnectorManager@7612bfa5/1,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-219,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp948960194{STOPPING,8<=8<=10,i=10,q=7} Couldn't stop Thread[qtp948960194-220,5,main]
Tests run: 13, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 64.252 sec <<< FAILURE!
testRedisCacheCreatePremWithExistedResGrp(com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheCreateIntegrationTest)  Time elapsed: 30.337 sec  <<< ERROR!
java.lang.Exception: Cannot create workMock instance
	at com.microsoft.tooling.IntegrationTestBase.setUpStep(IntegrationTestBase.java:114)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheCreateIntegrationTest.setUp(RedisCacheCreateIntegrationTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:72)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:202)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:144)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:118)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testRedisCacheCreatePremWithExistedResGrp(com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheCreateIntegrationTest)  Time elapsed: 30.373 sec  <<< ERROR!
org.apache.http.conn.HttpHostConnectException: Connect to localhost:3221 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:311)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAssertOkAndReturnBody(HttpAdminClient.java:261)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.resetAll(HttpAdminClient.java:144)
	at com.github.tomakehurst.wiremock.client.WireMock.resetMappings(WireMock.java:210)
	at com.microsoft.tooling.IntegrationTestBase.resetTest(IntegrationTestBase.java:159)
	at com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheCreateIntegrationTest.tearDown(RedisCacheCreateIntegrationTest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.MethodRoadie.runAfters(MethodRoadie.java:150)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:102)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:72)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:202)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:144)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:118)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 51 more

Running com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisExplorerPresenterTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.614 sec
Running com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheIntegrationTest
[main] INFO org.eclipse.jetty.util.log - Logging initialized @70753ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.13.v20150730
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@f9cd1e6{/__admin,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@65da1cbe{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.NetworkTrafficServerConnector - Started NetworkTrafficServerConnector@8e3449e{HTTP/1.1}{0.0.0.0:3047}
[main] INFO org.eclipse.jetty.server.Server - Started @71171ms
[qtp184253187-226] INFO /__admin - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.AdminRequestHandler. Normalized mapped under returned 'null'
[main] INFO com.microsoft.azure.management.redis.Redis list - --> GET http://localhost:3047/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Cache/Redis/?api-version=2016-04-01
[main] INFO com.microsoft.azure.management.redis.Redis list - Accept-Encoding: gzip
[main] INFO com.microsoft.azure.management.redis.Redis list - accept-language: en-US
[main] INFO com.microsoft.azure.management.redis.Redis list - Authorization: Bearer https:/asdd.com
[main] INFO com.microsoft.azure.management.redis.Redis list - Connection: Keep-Alive
[main] INFO com.microsoft.azure.management.redis.Redis list - Content-Type: application/json; charset=utf-8
[main] INFO com.microsoft.azure.management.redis.Redis list - Host: localhost:3047
[main] INFO com.microsoft.azure.management.redis.Redis list - User-Agent: Azure-SDK-For-Java/1.1.2 OS:Linux/4.11.6-041106-generic MacAddressHash:3cc60bfbc03e6b96eefc7338d40e8b2798bd748113d88d4692dd6136ebb14e7a (RedisManagementClient, 2016-04-01)
[main] INFO com.microsoft.azure.management.redis.Redis list - x-ms-client-request-id: 2711b6fc-4dbe-4f7e-917a-e70cbd0710c0
[qtp184253187-228] INFO / - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
[main] INFO com.microsoft.azure.management.redis.Redis list - <-- 200 OK http://localhost:3047/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Cache/Redis/?api-version=2016-04-01 (73 ms, unknown-length body)
[main] INFO com.microsoft.azure.management.redis.Redis list - Content-Encoding: gzip
[main] INFO com.microsoft.azure.management.redis.Redis list - Server: Jetty(9.2.13.v20150730)
[main] INFO com.microsoft.azure.management.redis.Redis list - Transfer-Encoding: chunked
[main] INFO com.microsoft.azure.management.redis.Redis list - Vary: Accept-Encoding, User-Agent
[main] INFO com.microsoft.azure.management.redis.Redis list - 280-byte body:
{"value":[{"id":"/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Cache/Redis/cache1","location":"West US","name":"cache1","type":"Microsoft.Cache/Redis","tags":{},"properties":{"provisioningState":"Creating","redisVersion":"3.2","sku":{"name":"Standard","family":"C","capacity":6},"enableNonSslPort":true,"redisConfiguration":{},"hostName":"cache1.redis.cache.windows.net","port":6379,"sslPort":6380}}]}
[main] INFO com.microsoft.azure.management.redis.Redis list - <-- END HTTP
[main] INFO com.microsoft.azure.management.redis.Redis delete - --> DELETE http://localhost:3047/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Cache/Redis/cache1?api-version=2016-04-01
[main] INFO com.microsoft.azure.management.redis.Redis delete - Accept-Encoding: gzip
[main] INFO com.microsoft.azure.management.redis.Redis delete - accept-language: en-US
[main] INFO com.microsoft.azure.management.redis.Redis delete - Authorization: Bearer https:/asdd.com
[main] INFO com.microsoft.azure.management.redis.Redis delete - Connection: Keep-Alive
[main] INFO com.microsoft.azure.management.redis.Redis delete - Content-Length: 0
[main] INFO com.microsoft.azure.management.redis.Redis delete - Content-Type: application/json; charset=utf-8
[main] INFO com.microsoft.azure.management.redis.Redis delete - Host: localhost:3047
[main] INFO com.microsoft.azure.management.redis.Redis delete - User-Agent: Azure-SDK-For-Java/1.1.2 OS:Linux/4.11.6-041106-generic MacAddressHash:3cc60bfbc03e6b96eefc7338d40e8b2798bd748113d88d4692dd6136ebb14e7a (RedisManagementClient, 2016-04-01)
[main] INFO com.microsoft.azure.management.redis.Redis delete - x-ms-client-request-id: ef8c7f97-95db-4f0b-b19b-8e766ae45335
[main] INFO com.microsoft.azure.management.redis.Redis delete - 0-byte body:

[main] INFO com.microsoft.azure.management.redis.Redis delete - --> END DELETE
[main] INFO com.microsoft.azure.management.redis.Redis delete - <-- 200 OK http://localhost:3047/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Cache/Redis/cache1?api-version=2016-04-01 (19 ms, 0-byte body)
[main] INFO com.microsoft.azure.management.redis.Redis delete - Cache-Control: no-cache
[main] INFO com.microsoft.azure.management.redis.Redis delete - Content-Length: 0
[main] INFO com.microsoft.azure.management.redis.Redis delete - Date: Wed, 25 Jan 2017 00:10:42 GMT
[main] INFO com.microsoft.azure.management.redis.Redis delete - Expires: -1
[main] INFO com.microsoft.azure.management.redis.Redis delete - Pragma: no-cache
[main] INFO com.microsoft.azure.management.redis.Redis delete - Retry-After: 0
[main] INFO com.microsoft.azure.management.redis.Redis delete - Server: Microsoft-HTTPAPI/2.0
[main] INFO com.microsoft.azure.management.redis.Redis delete - strict-transport-security: max-age=31536000; includeSubDomains
[main] INFO com.microsoft.azure.management.redis.Redis delete - x-ms-correlation-request-id: 61d60737-6ba4-43a2-b592-bbb876a7da60
[main] INFO com.microsoft.azure.management.redis.Redis delete - x-ms-ratelimit-remaining-subscription-writes: 1179
[main] INFO com.microsoft.azure.management.redis.Redis delete - x-ms-request-id: 26ee43f3-e218-4e35-b8eb-386cf61e046b
[main] INFO com.microsoft.azure.management.redis.Redis delete - x-ms-routing-request-id: WESTUS2:20170125T001042Z:61d60737-6ba4-43a2-b592-bbb876a7da60
[main] INFO com.microsoft.azure.management.redis.Redis delete - x-rp-server-mvid: c749ebcf-3f61-4aaf-abc8-ae593af00ef8
[main] INFO com.microsoft.azure.management.redis.Redis delete - <-- END HTTP
[main] INFO org.eclipse.jetty.server.NetworkTrafficServerConnector - Stopped NetworkTrafficServerConnector@8e3449e{HTTP/1.1}{0.0.0.0:3047}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@65da1cbe{/,null,UNAVAILABLE}
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@f9cd1e6{/__admin,null,UNAVAILABLE}
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp184253187{STOPPING,8<=8<=10,i=3,q=4} Couldn't stop Thread[qtp184253187-222,5,main]
[main] WARN org.eclipse.jetty.util.thread.QueuedThreadPool - qtp184253187{STOPPING,8<=8<=10,i=0,q=4} Couldn't stop Thread[qtp184253187-223,5,]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.141 sec
Running com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisPropertyViewPresenterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.677 sec

Results :

Tests in error: 
  testRedisCacheCreatePremWithExistedResGrp(com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheCreateIntegrationTest): Cannot create workMock instance
  testRedisCacheCreatePremWithExistedResGrp(com.microsoft.tooling.msservices.serviceexplorer.azure.rediscache.RedisCacheCreateIntegrationTest): Connect to localhost:3221 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)

Tests run: 26, Failures: 0, Errors: 2, Skipped: 0

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project azure-explorer-common: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/Microsoft/azure-tools-for-java/Utils/azure-explorer-common/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :azure-explorer-common


The command "./BuildDevint -q" exited with 1.

Done. Your build exited with 1.
```

**Comment by Eskibear** [comment]
dup with #791
