### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception MsalInteractionRequiredException: AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed.

### ISSUE THREAD

**Issue by AdaoBartolomeuAB** [microsoft/azure-tools-for-java#7990]
IntelliJ build version: 2021.3 IU-213.5744.223
OS: Windows 11
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.81.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1718x1391,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:39)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:161)
	at com.microsoft.aad.msal4j.T

**Comment by Flanker32** [comment]
@AdaoBartolomeuAB Thank you for reporting this issue and we apologize for the delay in responding to you. This issue seems to be caused by an authentication problem. Could you please try signing in again and check if the issue is resolved?
