### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy to Azure Web App(rest-mockserver) with resource creation or updating

### ISSUE THREAD

**Issue by krachunov** [microsoft/azure-tools-for-java#7991]
IntelliJ build version: 2021.3 IC-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.81.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy to Azure Web App(rest-mockserver) with resource creation or updating
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.appservice.task.DeployWebAppTask.doExecute(DeployWebAppTask.java:91)
	at com.microsoft.azuretools.core.mvp.model.webapp.AzureWebAppMvpModel.deployArtifactsToWebApp(AzureWebAppMvpModel.java:215)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:98)
	at com.micr

**Comment by Flanker32** [comment]
@krachunov Thank you for reporting this issue and we are sorry for the trouble. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
