### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Failed to save icon to cache (path=expui/run/debug_stroke.svg, precomputedCacheKey=0)

### ISSUE THREAD

**Issue by FK-Christian** [microsoft/azure-tools-for-java#7993]
IntelliJ build version: 2023.2.4 IU-232.10203.10
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1494x886,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
  org.jetbrains.sqlite.SqliteException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed) (sql=insert or replace into image (key1, key2, kind, theme, w, h, data) values(?, ?, ?, ?, ?, ?, ?) )
at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewAction.lambda$doShow$2(WhatsNewAction.java:84)
at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:119)
at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$execute$0(AzureTaskManager.java:270)
at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:85)
at com.microsoft.azure.toolkit.lib.common.task.

**Comment by Flanker32** [comment]
@FK-Christian Thank you for reporting this issue and we are sorry for the trouble and late response. We are working on fixing this issue as soon as possible. We will keep you updated on the progress of this issue here.

**Comment by wangmingliang-ms** [comment]
Duplicate of #7898
