### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception [Correlation ID: ebd903ba-bcfa-411f-ad72-90dd5181abe6] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed. com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server

### ISSUE THREAD

**Issue by Jasmita2410** [microsoft/azure-tools-for-java#7995]
IntelliJ build version: 2022.2.2 IE-222.4345.35
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.4.1
Plugin version: 3.75.0-2022.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1344x840,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=[Correlation ID: ebd903ba-bcfa-411f-ad72-90dd5181abe6] Execution of class com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier failed., throwable=com.microsoft.aad.msal4j.MsalClientException: No Authorization code was returned from the server
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResultFromHttpListener(AcquireTokenByInteractiveFlowSupplier.java:148)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.getAuthorizationResult(AcquireTokenByInteractiveFlowSupplier.java:64)
	at com.microsoft.aad.msal4j.AcquireTokenByInteractiveFlowSupplier.execute(AcquireTokenByInteractiveFlowSupplier.java:37)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com

**Comment by Flanker32** [comment]
@Jasmita2410 Thank you for reporting this issue and we apologize for the delay in responding to you. This issue seems to be caused by an authentication problem. Could you please try signing in again and check if the issue is resolved?
