### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by krachunov** [microsoft/azure-tools-for-java#7996]
IntelliJ build version: 2021.3 IC-213.5744.223
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.81.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.util.ConcurrentModificationException
	at <REDACTED: user-file-path>$Itr.checkForComodification(ArrayList.java:1043)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.action.DeployWebAppAction.lambda$runConfiguration$3(DeployWebAppAction.java:76)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:119)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$execute$0(AzureTaskManager.java:270)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:85)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$execute$1(AzureTaskManager.java:267)
```

**Comment by Flanker32** [comment]
@krachunov Thank you for reporting this issue and we are sorry for the trouble. We are working on fix of this issue. We will keep you updated on the progress of this issue here.
