### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot read field "preferred" because "this.xTotal" is null

### ISSUE THREAD

**Issue by medbelmahi** [microsoft/azure-tools-for-java#7999]
IntelliJ build version: 2023.2.4 IU-232.10203.10
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1680x1050,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot read field "preferred" because "this.xTotal" is null
	at <REDACTED: user-file-path>(BoxLayout.java:294)
	at com.microsoft.azure.toolkit.intellij.common.action.WhatsNewAction.lambda$doShow$2(WhatsNewAction.java:84)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:119)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$execute$0(AzureTaskManager.java:270)
	at com.microsoft.azure.toolkit.lib.common.operation.OperationThreadContext.run(OperationThreadContext.java:85)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.lambda$execute$1(AzureTaskManager.java:267)
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager.doRunAndWait(IntellijAzureTaskManager.java:52)
	at

**Comment by Flanker32** [comment]
@medbelmahi Thank you for reporting this issue and we are sorry for the trouble. We are working on fixing this issue as soon as possible. We will keep you updated on the progress of this issue here.

**Comment by postalservice14** [comment]
Is there a workaround in the meantime?
