### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load App Service plan (sp-app-webtabaca-231113183950)

### ISSUE THREAD

**Issue by orafamoura** [microsoft/azure-tools-for-java#8003]
IntelliJ build version: 2023.2.3 IC-232.10072.27
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load App Service plan (sp-app-webtabaca-231113183950)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:576)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:286)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.getOrDraft(AbstractAzResourceModule.java:345)
	at com.microsoft.azure.toolkit.lib.appservice.config.AppServicePlanConfig.toResource(AppServicePlanConfig.java:61)
	at com.micr

**Comment by Flanker32** [comment]
@orafamoura Thank you for reporting this issue and we are sorry for the inconvenience and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
