### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@54dfedda when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@18d1e55c

### ISSUE THREAD

**Issue by OmerBilgin-TomTom** [microsoft/azure-tools-for-java#8009]
IntelliJ build version: 2023.2.4 IU-232.10203.10
OS: Linux
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1848x1053,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@54dfedda when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@18d1e55c
<REDACTED: Generic Secret>
at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)

**Comment by Flanker32** [comment]
@OmerBilgin-TomTom Thank you for reporting this issue and we are sorry for the trouble. We are working on the fix of this issue. We will keep you updated on the progress of this issue here.

**Comment by wangmingliang-ms** [comment]
Duplicate of #9450
