### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed. AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access.

### ISSUE THREAD

**Issue by Jakub-Zak** [microsoft/azure-tools-for-java#8042]
IntelliJ build version: 2021.3.1 IU-213.6461.79
OS: Windows 10
JDK: JetBrains s.r.o. 11.0.13
Plugin version: 3.81.1-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1040,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:39)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:161)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:40)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquire

**Comment by Flanker32** [comment]
@Jakub-Zak Thanks for your report and sorry for the trouble, this seems to be an authentication issue, could you please try re-signing in and see whether it helps?
