### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception at Workspace Model event handling java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.openapi.progress.CeProcessCanceledException) should never be logged. Instead, these should have been rethrown if caught.

### ISSUE THREAD

**Issue by bumahkib7** [microsoft/azure-tools-for-java#8052]
IntelliJ build version: 2023.3 IU-233.11799.241
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1728x1080,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Exception at Workspace Model event handling, throwable=java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.openapi.progress.CeProcessCanceledException) should never be logged. Instead, these should have been rethrown if caught.
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:513)
	at com.microsoft.azure.toolkit.intellij.facet.AzureFacet.addTo(AzureFacet.java:47)
	at com.microsoft.azure.toolkit.intellij.facet.AddFacetStartupActivity.lambda$addFacetWhenNecessary$0(AddFacetStartupActivity.java:57)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTask.lambda$new$0(AzureTask.java:119)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.

**Comment by Flanker32** [comment]
@bumahkib7 Thank you for reporting this issue and we are sorry for the trouble. We are working on fixing this issue. We will keep you updated on the progress of this issue here.
