### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions' com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(code) is a valid function project

### ISSUE THREAD

**Issue by rmjjesus** [microsoft/azure-tools-for-java#8053]
IntelliJ build version: 2023.1 IC-231.8109.175
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.77.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1537x817,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=DeployFunctionAppAction#update@MainMenu(preload-bgt) (com.microsoft.azure.toolkit.intellij.legacy.function.action.DeployFunctionAppAction), actionId=Actions.DeployFunction, text='Deploy to Azure Functions', throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: check if project(code) is a valid function project
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:94)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
	at com.microsoft.azure.toolkit.intellij.legacy.funct

**Comment by Flanker32** [comment]
@rmjjesus Thanks a lot for your report, this issue should be resolved in our latest release. Could you please upgrade to the latest toolkit and try again? Please feel free to re-open this issue once the problem still bother you.
