### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception execute Azure Cli command 'az account get-access-token' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by martinstuga** [microsoft/azure-tools-for-java#8054]
IntelliJ build version: 2023.3 IU-233.11799.241
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1440x875,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$setTransparentTitleBar$customBorder$1@31286e4a,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>

**Comment by Flanker32** [comment]
@martinstuga Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
