### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by mzubair157** [microsoft/azure-tools-for-java#8057]
IntelliJ build version: 2023.2.2 IU-232.9921.47
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.8
Plugin version: 3.83.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1710x993,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$1@4034798f,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  Scheduler worker in group main failed with an uncaught exception
  java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or <REDACTED: user-file-path> limits reached
at com.microsoft.azure.toolkit.lib.common.utils.TailingDebouncer.debounce(TailingDebouncer.java:28)
at com.microsoft.azure.toolkit.lib.common.utils.TailingDebouncer.debounce(TailingDebouncer.java:41)
at com.microsoft.azure.toolkit.ide.common.component.Node.refreshChildrenLater(Node.java:303)
at com.microsoft.azure.toolkit.ide.appservice.appsettings.AppSettingsNode.onEvent(AppSettingsNode.java:47)
at com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener.onEvent(AzureEventBus.java:79)
```

**Comment by Flanker32** [comment]
@mzubair157 Thank you for reporting this issue and we are sorry for the inconvenience and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?

**Comment by wangmingliang-ms** [comment]
Duplicate of #7898
