### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.AssertionError: File text mismatch: tree.length=105; psi.length=106; this=SHELL_SCRIPT; vp=Single root injected file 'Dockerfile' 

### ISSUE THREAD

**Issue by aevers1967** [microsoft/azure-tools-for-java#8088]
IntelliJ build version: 2023.3.2 IU-233.13135.103
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,3360x1784,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.AssertionError: File text mismatch: tree.length=105; psi.length=106; this=SHELL_SCRIPT; vp=Single root injected file 'Dockerfile' 
	at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:312)
	at com.microsoft.azure.toolkit.intellij.containerregistry.runner.DockerRunLineMarkerProvider.isFromCommand(DockerRunLineMarkerProvider.java:48)
	at com.microsoft.azure.toolkit.intellij.containerregistry.runner.DockerRunLineMarkerProvider.getLineMarkerInfo(DockerRunLineMarkerProvider.java:44)
```

**Comment by Flanker32** [comment]
@aevers1967 Thank you for reporting this issue and we are sorry for the inconvenience and late response. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
