### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Fapro** [microsoft/azure-tools-for-java#8089]
IntelliJ build version: 2023.3.2 IC-233.13135.103
OS: Linux
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.reflect.InvocationTargetException
	at <REDACTED: user-file-path>(Native Method)
	at com.microsoft.azure.hdinsight.spark.console.RunSparkConsoleActionDelegate.actionPerformed(RunSparkConsoleActionDelegate.kt:57)
Caused by: com.intellij.execution.ExecutionException: The library org.apache.spark:spark-core is not in project dependencies.
	at com.microsoft.azure.hdinsight.spark.console.RunSparkScalaLocalConsoleAction.onActionPerformed(RunSparkScalaLocalConsoleAction.kt:78)
	at com.microsoft.azure.toolkit.intellij.common.action.AzureAnAction.actionPerformed(AzureAnAction.java:64)
```

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8001
