### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)

### ISSUE THREAD

**Issue by Guido-Pierri** [microsoft/azure-tools-for-java#8100]
IntelliJ build version: 2023.3.2 IU-233.13135.103
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1458x1415,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.RuntimeException: Cannot invoke (class=, method=processTerminated, topic=configuration executed)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler$1.processWillTerminate(RunProcessHandler.java:88)
	at com.microsoft.azure.toolkit.intellij.common.RunProcessHandler.notifyProcessTerminated(RunProcessHandler.java:41)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.onFail(AzureRunProfileState.java:109)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$2(AzureRunProfileState.java:70)
Caused by: com.intellij.openap

**Comment by Flanker32** [comment]
@Guido-Pierri Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
