### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@4ec1971d when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@2a3d0c36 com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: execute Azure Cli command 'az account get-access-token --resource https://management.core.windows.net/  -t c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75 --output json' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by tirsogarcia** [microsoft/azure-tools-for-java#8101]
IntelliJ build version: 2023.3.1 IU-233.11799.300
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.83.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1382x875,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccount

**Comment by Flanker32** [comment]
@tirsogarcia Thank you for reporting this issue and we apologize for the delay in responding to you. This issue seems to be caused by an authentication problem. Could you please try signing in again and check if the issue is resolved?

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
