### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240116154308)

### ISSUE THREAD

**Issue by JoolyPrabhat** [microsoft/azure-tools-for-java#8107]
IntelliJ build version: 2023.2.5 IC-232.10227.8
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1281x673,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240116154308)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:575)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:287)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.getResourceGroup(AbstractAzResource.java:310)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.exists(AbstractAzResource.java:101)
	at com.mi

**Comment by Flanker32** [comment]
@JoolyPrabhat Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9674
