### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy Function app to Azure

### ISSUE THREAD

**Issue by hirenvaghela01** [microsoft/azure-tools-for-java#8108]
IntelliJ build version: 2023.3.1 IC-233.11799.300
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1393,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy Function app to Azure
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.java:102)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.java:45)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
Caused by: reactor.core.Exceptions$ReactiveException: java.lang.Interru

**Comment by Flanker32** [comment]
@hirenvaghela01 Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
