### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: SpringBootApplicationConfigurationType-PortfolioApplication_ factoryName_ Spring Boot.xml java.lang.RuntimeException: Cannot invoke (class=BeforeRunTaskAdder, method=runConfigurationAdded, topic=RunManager)

### ISSUE THREAD

**Issue by ColJops** [microsoft/azure-tools-for-java#8113]
IntelliJ build version: 2023.3.2 IU-233.13135.103
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1392,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: SpringBootApplicationConfigurationType-PortfolioApplication_ factoryName_ Spring Boot.xml, throwable=java.lang.RuntimeException: Cannot invoke (class=BeforeRunTaskAdder, method=runConfigurationAdded, topic=RunManager)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	Caused by: java.nio.file.NoSuchFileException: <REDACTED: user-file-path> <REDACTED: user-file-path>
		at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.getDefaultProfileName(AzureModule.java:185)
		at com.microsoft.azure.toolkit.intellij.connector.dota

**Comment by Flanker32** [comment]
@ColJops Thank you for reporting this issue and we are sorry for the inconvenience. To help us troubleshoot this issue, could you please provide some more details, such as the steps that you followed to encounter this issue?
