### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception unexpected failure in initializing client. java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. More info: https://aka.ms/cosmosdb-tsg-service-unavailable-java

### ISSUE THREAD

**Issue by imejiamgm** [microsoft/azure-tools-for-java#8119]
IntelliJ build version: 2023.3.2 IC-233.13135.103
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x943,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.azure.cosmos.implementation.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:546)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.getCosmosClient(SqlCosmosDBAccount.java:101)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.updateAdditionalProperties(SqlCosmosDBAccount.java:80)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.updateAdditionalProperties(SqlCosmosDBAccount.java:25)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.onRemoteUpdated(AbstractAzResource.java:166)
	at com.microsoft.azure.toolkit.lib.common.cache.Cache1.lambda$update$4(Cache1.java:103)
	at com.microsoft.azure.toolkit.lib.common.tas

**Comment by Flanker32** [comment]
@imejiamgm Thank you for reporting this issue and we apologize for the inconvenience. This issue seems to be caused by an authentication problem. Could you please try signing in again and check if the issue is resolved?

**Comment by imejiamgm** [comment]
it is working now
