### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException

### ISSUE THREAD

**Issue by JetACode** [microsoft/azure-tools-for-java#8126]
IntelliJ build version: 2023.3.2 IC-233.13135.103
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,958x606,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=reactor.core.Exceptions$ErrorCallbackNotImplemented: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
Caused by: com.microsoft.azure.toolkit.lib.common.exception.AzureToolkitRuntimeException
	at com.microsoft.azure.toolkit.lib.common.utils.StreamingLogSupport.lambda$streamingLogs$0(StreamingLogSupport.java:58)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https:/<REDACTED: user-file-path>?follow=true&tailLines=300&tenantId=91283b1b-1c44-4b4e-ac88-9fce9d7c6b11&tailLines=300&limitBytes=1048576&sinceSeconds=300&follow=true
	at com.microsoft.azure.toolkit.lib.common.utils.StreamingLogSupport.lambda$streamingLogs$0(StreamingLogSupport.java:48)
```

**Comment by Flanker32** [comment]
@JetACode Thanks a lot for your report and sorry for the trouble. Could you please help share the steps to reproduce this issue? Besides, could you please try sign out and re-sign in to see whether it could helps?
