### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent: execute Azure Cli command 'az account get-access-token --output json' failed due to error: Process exited with an error: 1

### ISSUE THREAD

**Issue by prshnt** [microsoft/azure-tools-for-java#8127]
IntelliJ build version: 2023.3.3 IU-233.14015.106
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.84.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1377x875,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccountM

**Comment by Flanker32** [comment]
@prshnt Thank you for reporting this issue and we apologize for the trouble. Please track the issue in https://github.com/microsoft/azure-tools-for-java/issues/8101. It would be very helpful if you could share some additional details to assist us in resolving this issue.

**Comment by Flanker32** [comment]
Duplicate of #8101
