### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "javax.swing.JRootPane.getClientProperty(Object)" because "rootpane" is null

### ISSUE THREAD

**Issue by ldmajewski** [microsoft/azure-tools-for-java#8159]
IntelliJ build version: 2023.2 IC-232.8660.185
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.85.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "javax.swing.JRootPane.getClientProperty(Object)" because "rootpane" is null
	at <REDACTED: user-file-path>(CPlatformWindow.java:487)
	at com.microsoft.azure.toolkit.intellij.connector.ConnectorDialog.onResourceOrConsumerTypeChanged(ConnectorDialog.java:138)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:191)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.lambda$setValue$2(AzureComboBox.java:153)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setValue(AzureComboBox.java:142)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.setValue(AzureComboBox.java:138)
	at com.microsoft.azure.toolkit.intellij.common.AzureComboBox.refreshValue(AzureComboBox.java:189

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7859
