### ISSUE TITLE
[IntelliJ] There is an error after Installing plugin and restarting IDEA

### ISSUE THREAD

**Issue by bsaby** [Microsoft/azure-tools-for-java#816]
**Repro steps:**
Clean install plugin and restart IntelliJ
OR
Update plugin without Sign-in and restart IntelliJ

Repro both Global and Azure China.
**Error Log:**
null
java.lang.NullPointerException
	at com.microsoft.azuretools.core.mvp.model.AzureMvpModel.getSelectedSubscriptions(AzureMvpModel.java:57)
	at com.microsoft.intellij.AzureActionsComponent$1.run(AzureActionsComponent.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adashen** [comment]
should already be fixed. please verify

**Comment by bsaby** [comment]
Test passed.
BUild: Daily95
