### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    Operator called default onErrorDropped

### ISSUE THREAD

**Issue by yatendrakumawat** [microsoft/azure-tools-for-java#8160]
IntelliJ build version: 2023.2.4 IC-232.10203.10
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.8.1
Plugin version: 3.85.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1366x720,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   Operator called default onErrorDropped
   com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy to Azure Web App(SANGRAH-UAT) with resource creation or updating
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.appservice.task.DeployWebAppTask.doExecute(DeployWebAppTask.java:100)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.deployArtifactsToWebApp(WebAppRunState.java:143)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:94)
	at com.microsoft.azure.tool

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/7898
