### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed    SparkJobDebugAction#update@GoToAction (com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction), actionId=SparkJobDebug, text='SparkJobDebug'

### ISSUE THREAD

**Issue by tlangs** [microsoft/azure-tools-for-java#8220]
IntelliJ build version: 2023.2.5 IU-232.10227.8
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.85.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1440,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=   SparkJobDebugAction#update@GoToAction (com.microsoft.azure.hdinsight.spark.run.action.SparkJobDebugAction), actionId=SparkJobDebug, text='SparkJobDebug'
   java.lang.RuntimeException: java.io.IOException: Record[36088472] is deleted
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findJavaMainClass(SparkContextUtils.kt:94)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:83)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.azure.hdinsight.spark.run.action.SparkRunConfigurationAction.update(SparkRunConfigurationAction.kt

**Comment by wangmingliang-ms** [comment]
Duplicate of #7898
