### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy artifact to web app (LibraryApp07)

### ISSUE THREAD

**Issue by weizhenC** [microsoft/azure-tools-for-java#8234]
IntelliJ build version: 2023.1.4 IU-231.9225.16
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 3.82.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x832,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@51c21be1,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy artifact to web app (LibraryApp07)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:99)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:58)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
Caused by: reactor.core.Exceptions$Reactive

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8096
