### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240312231640)

### ISSUE THREAD

**Issue by dayothompson** [microsoft/azure-tools-for-java#8242]
IntelliJ build version: 2023.1 IU-231.8109.175
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 3.82.0-2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1512x945,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240312231640)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:576)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:286)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.getResourceGroup(AbstractAzResource.java:309)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.exists(AbstractAzResource.java:100)
	at com.microsof

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9674
