### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception unexpected failure in initializing client. java.lang.RuntimeException: Client initialization failed. Check if the endpoint is reachable and if your auth token is valid. More info: https://aka.ms/cosmosdb-tsg-service-unavailable-java

### ISSUE THREAD

**Issue by noorsyyed** [microsoft/azure-tools-for-java#8291]
IntelliJ build version: 2023.3.6 IC-233.15026.9
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.86.1-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2760x1477,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.azure.cosmos.implementation.RxDocumentClientImpl.initializeGatewayConfigurationReader(RxDocumentClientImpl.java:546)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.getCosmosClient(SqlCosmosDBAccount.java:101)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.updateAdditionalProperties(SqlCosmosDBAccount.java:80)
	at com.microsoft.azure.toolkit.lib.cosmos.sql.SqlCosmosDBAccount.updateAdditionalProperties(SqlCosmosDBAccount.java:25)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.onRemoteUpdated(AbstractAzResource.java:166)
	at com.microsoft.azure.toolkit.lib.common.cache.Cache1.lambda$update$4(Cache1.java:103)
	at com.microsoft.azure.toolkit.lib.common.task.Azu

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8383
