### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped java.lang.InterruptedException

### ISSUE THREAD

**Issue by cursorocity** [microsoft/azure-tools-for-java#8326]
IntelliJ build version: 2023.3.5 IU-233.14808.21
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.87.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x1000,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=java.lang.InterruptedException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:565)
	at com.microsoft.azure.toolkit.ide.guidance.task.BaseDeployTask.execute(BaseDeployTask.java:65)
	at com.microsoft.azure.toolkit.ide.guidance.Step.executeTask(Step.java:118)
```

**Comment by wangmingliang-ms** [comment]
Duplicate of #9448
