### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception *** exception class was changed or removed   ExecutorRegistryImpl$RunCurrentFileExecutorAction#update@popup (com.intellij.execution.ExecutorRegistryImpl$RunCurrentFileExecutorAction), text='Run'

### ISSUE THREAD

**Issue by VoKhoiNhon** [microsoft/azure-tools-for-java#8365]
IntelliJ build version: 2023.2.5 IU-232.10227.8
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 3.82.0-2023.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=*** exception class was changed or removed, throwable=  ExecutorRegistryImpl$RunCurrentFileExecutorAction#update@popup (com.intellij.execution.ExecutorRegistryImpl$RunCurrentFileExecutorAction), text='Run'
  java.nio.file.NoSuchFileException: <REDACTED: user-file-path>
at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.getDefaultProfileName(AzureModule.java:185)
at com.microsoft.azure.toolkit.intellij.connector.dotazure.AzureModule.getDefaultProfile(AzureModule.java:133)
at com.microsoft.azure.toolkit.intellij.connector.dotazure.DotEnvBeforeRunTaskProvider$LoadDotEnvBeforeRunTask.<init>(DotEnvBeforeRunTaskProvider.java:129)
at com.microsoft.azure.toolkit.intellij.connector.dotazure.DotEnvBeforeRunTaskProvider.createTask(DotEnvBeforeRunTa

**Comment by wangmingliang-ms** [comment]
Duplicate of #7898
