### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@53bcce38 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@10fd3920 com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: execute Azure Cli command 'az account get-access-token --resource https://management.core.windows.net/  -t 27776982-d882-41b2-95ac-322f28d5a2ce --output json' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by opwvhk** [microsoft/azure-tools-for-java#8368]
IntelliJ build version: 2023.3.6 IU-233.15026.9
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.87.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2500x1415,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccount

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
