### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy Function app to Azure

### ISSUE THREAD

**Issue by werter2** [microsoft/azure-tools-for-java#8371]
IntelliJ build version: 2021.3.3 IU-213.7172.25
OS: Windows 11
JDK: JetBrains s.r.o. 11.0.14.1
Plugin version: 3.83.0-2021.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1921x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy Function app to Azure
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.java:102)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.deploy.FunctionDeploymentState.executeSteps(FunctionDeploymentState.java:45)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
Caused by: reactor.core.Exceptions$ReactiveException: java.lang.Interr

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8108
