### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@16be3e38 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@4b4a7ff2 com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: execute Azure Cli command 'az account get-access-token --resource https://management.core.windows.net/  -t 19da1f3c-d958-44ea-850d-195c1502525c --output json' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by joao-felipe-santoro** [microsoft/azure-tools-for-java#8376]
IntelliJ build version: 2024.1 IU-241.14494.240
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.87.0-2024.1
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,0,0,1020x650,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$setTransparentTitleBar$customBorder$1@a7bbd59,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
<REDACTED: Generic Secret>

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
