### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception ToolWindowHeader$2#children@ToolwindowTitle (com.intellij.toolWindow.ToolWindowHeader$2) java.lang.IllegalStateException: Write actions are prohibited

### ISSUE THREAD

**Issue by Sideghost** [microsoft/azure-tools-for-java#8379]
IntelliJ build version: 2024.1 IU-241.14494.240
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.87.0-2024.1
Additional Info: None
Parent component: 
```
javax.swing.JRootPane[,8,0,1059x642,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=ToolWindowHeader$2#children@ToolwindowTitle (com.intellij.toolWindow.ToolWindowHeader$2), throwable=java.lang.IllegalStateException: Write actions are prohibited
	at com.intellij.openapi.application.impl.RwLockHolder.throwCannotWriteException(RwLockHolder.kt:691)
	at com.microsoft.azure.hdinsight.projects.MavenProjectGenerator.importMavenProject(MavenProjectGenerator.java:221)
	at com.microsoft.azure.hdinsight.projects.MavenProjectGenerator.generate(MavenProjectGenerator.java:58)
	at com.microsoft.azure.hdinsight.projects.HDInsightModuleBuilder.moduleCreated(HDInsightModuleBuilder.java:131)
```

**Comment by xiaopong** [comment]
Any update on this? I'm having the same issue, and it's been very frequent today: it has happened 6 times already. Thnx
