### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception SparkJobRunAction#update@ProjectViewPopup (com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction), actionId=SparkJobRun, text='SparkJobRun' java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by mayarapreta** [microsoft/azure-tools-for-java#8399]
IntelliJ build version: 2022.3.1 IC-223.8214.52
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x863,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=SparkJobRunAction#update@ProjectViewPopup (com.microsoft.azure.hdinsight.spark.run.action.SparkJobRunAction), actionId=SparkJobRun, text='SparkJobRun', throwable=java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.findMainMethod(SparkContextUtils.kt:89)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkMainClassWithElement(SparkContextUtils.kt:82)
	at com.microsoft.azure.hdinsight.spark.run.SparkContextUtilsKt.getSparkConfigurationContext(SparkContextUtils.kt:70)
	at com.microsoft.az

**Comment by wangmingliang-ms** [comment]
Duplicate of #7438
