### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Scheduler worker in group main failed with an uncaught exception com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by Le-Bao-Dang** [microsoft/azure-tools-for-java#8456]
IntelliJ build version: 2022.3.2 IU-223.8617.56
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 3.77.0-2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1537x863,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Scheduler worker in group main failed with an uncaught exception, throwable=com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:47)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:257)
	at com.microsoft.azure.toolkit.lib.springcloud.AzureSpringCloud.clusters(AzureSpringCloud.java:28)
	at com.microsoft.azure.toolkit.intellij.springcloud.deplolyment.SpringCloudDeploymentConfigurationState.getDeploymentFromConfig(SpringCloudDeploymentConfigurationState

**Comment by wangmingliang-ms** [comment]
Duplicate of #9483
