### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception Operator called default onErrorDropped com.intellij.openapi.progress.ProcessCanceledException: java.lang.InterruptedException

### ISSUE THREAD

**Issue by affom1** [microsoft/azure-tools-for-java#8468]
IntelliJ build version: 2023.3.5 IU-233.14808.21
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.89.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,6,6,1537x913,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.intellij.openapi.progress.ProcessCanceledException: java.lang.InterruptedException
	at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:98)
	at com.microsoft.azure.toolkit.intellij.common.task.IntellijAzureTaskManager.doRunAndWait(IntellijAzureTaskManager.java:52)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.execute(AzureTaskManager.java:286)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.runAndWait(AzureTaskManager.java:189)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskManager.runAndWait(AzureTaskManager.java:165)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.validateAppSettings(FunctionRunState.java:380)
	at com.microsoft.azure.toolkit.intellij.legacy.function.runner.localrun.FunctionRunState.prepareSt

**Comment by wangmingliang-ms** [comment]
Duplicate of #9448
