### ISSUE TITLE
[IntelliJ] Uncaught Exception  java.lang.Throwable: com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder <clinit> requests com.microsoft.azure.toolkit.lib.common.messager.IAzureMessager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.

### ISSUE THREAD

**Issue by akram02** [microsoft/azure-tools-for-java#8473]
IntelliJ build version: 2024.2 EAP IU-242.19890.14
OS: Linux
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.90.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1400x1000,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.BorderUIResource@32133ada,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder <clinit> requests com.microsoft.azure.toolkit.lib.common.messager.IAzureMessager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.microsoft.azure.toolkit.intellij.common.messager.IntellijAzureMessager$Provider.getMessager(IntellijAzureMessager.java:172)
	at com.microsoft.azure.toolkit.lib.common.messager.AzureMessager$Holder.loadMessager(AzureMessager.java:30)
	at com.microsoft.azure.toolkit.lib.common.messager.Azur

**Comment by hamdrew** [comment]
Looks like a lot of people are reporting this issue, and this is the first instance with a maintainer assigned. Consider pinning it in your Issues section for visibility

**Comment by davidkarlsen** [comment]
will it be fixed or is the intelliJ plugin dead?

**Comment by wangmingliang-ms** [comment]
@davidkarlsen  will be fixed soon

**Comment by wangmingliang-ms** [comment]
fix released, please upgrade to the latest version, v3.92.0 or its BETA version.

**Comment by wangmingliang-ms** [comment]
this issue has been fixed since v3.92.0, please upgrade to that or newer version.
