### ISSUE TITLE
[IntelliJ] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240813142713)

### ISSUE THREAD

**Issue by Klaillton** [microsoft/azure-tools-for-java#8732]
IntelliJ build version: 2024.2 IU-242.20224.300
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.91.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,1536x816,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: load Resource group (rg-getting-started-service-240813142713)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.loadResourceFromAzure(AbstractAzResourceModule.java:574)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.get(AbstractAzResourceModule.java:286)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.getResourceGroup(AbstractAzResource.java:320)
	at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResource.exists(AbstractAzResource.java:111)
	at com.microsoft.azure.toolkit.int

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8731
