### ISSUE TITLE
Create VM flow - Use existing IP address which is already in use gives error which user can't understand easily.

### ISSUE THREAD

**Issue by anudeepsharma** [microsoft/azure-tools-for-java#91]
We are showing the error message this when expanded in case an IP Address already in used is used to create a new VM. This message is hard to understand for users. We should simplify the error message.

Without show advanced info message just shows (Message from Azure: P configuration /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/networkInterfaces/nicans3df9626)

Advance show info shows.

com.microsoft.azure.CloudException: IP configuration /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/networkInterfaces/nicans3df96268d11/ipConfigurations/primary is referencing public IP address /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/publicIPAddresses/pip90955a88 that is already allocated to resource /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/networkInterfaces/nicanse8d37483e41.: IP configuration /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/networkInterfaces/nicans3df96268d11/ipConfigurations/primary is referencing public IP address /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/publicIPAddresses/pip90955a88 that is already allocated to resource /subscriptions/9657ab5d-4a4a-4fd2-ae7a-4cd9fbd030ef/resourceGroups/ans/providers/Microsoft.Network/networkInterfaces/nicanse8d37483e41.
	at com.microsoft.azure.AzureClient.createExceptionFromResponse(AzureClient.java:585)
	at com.microsoft.azure.AzureClient.access$000(AzureClient.java:33)
	at com.microsoft.azure.AzureClient$1.call(AzureClient.java:132)
	at com.microsoft.azure.AzureClient$1.call(AzureClient.java:129)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:221)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martinsawicki** [comment]
error message: "This public IP address is already in use. Try creating a VM with another one".

BUT, we should also filter out the PIPs that are already taken within this subscription --- see PIP.ipConfiguration()

**Comment by selvasingh** [comment]
Provide a better error message

**Comment by andxu** [comment]
The public IP part has been redesigned:
![image](https://user-images.githubusercontent.com/17075863/144176541-92281c09-27cc-4174-8866-c99d07c84cde.png)
![image](https://user-images.githubusercontent.com/17075863/144176555-9976a110-b428-4d06-877e-adfa2d42fc82.png)
