### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.getPath()" because the return value of "com.intellij.openapi.vfs.VirtualFile.getParent()" is null

### ISSUE THREAD

**Issue by konstantinosraptis91** [microsoft/azure-tools-for-java#9431]
IntelliJ build version: 2023.3.7 IU-233.15325.26
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.10
Plugin version: 3.89.0-2023.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1280x1415,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarServiceImpl$setTransparentTitleBar$customBorder$1@24d68bc5,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.getPath()" because the return value of "com.intellij.openapi.vfs.VirtualFile.getParent()" is null
	at com.microsoft.azure.toolkit.intellij.container.model.DockerImage.<init>(DockerImage.java:57)
	at com.microsoft.azure.toolkit.intellij.containerregistry.runner.ContainerRegistryDockerfileActionsProvider.getActions(ContainerRegistryDockerfileActionsProvider.java:17)
	at com.microsoft.azure.toolkit.intellij.containerregistry.runner.DockerRunLineMarkerProvider.lambda$getDockerfileActions$2(DockerRunLineMarkerProvider.java:105)
	at com.microsoft.azure.toolkit.intellij.containerregistry.runner.DockerRunLineMarkerPr

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9472
