### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@28f27d3 when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@56bc36e7 com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: execute Azure Cli command 'az account get-access-token --resource https://management.core.windows.net/  -t 43ad29e3-421c-4156-8ec0-e65e6a654f1b --output json' failed due to error: Process exited with an error: 1 (Exit value: 1).

### ISSUE THREAD

**Issue by bcesur** [microsoft/azure-tools-for-java#9450]
IntelliJ build version: 2024.2.1 IU-242.21829.142
OS: Mac OS X
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1415,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliAccount$AzureCliTokenCredential.lambda$null$3(AzureCliAccount.java:113)
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
		at com.microsoft.

**Comment by wangmingliang-ms** [comment]
Duplicate of #11058
