### ISSUE TITLE
[IntelliJ] Uncaught Exception  com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.

### ISSUE THREAD

**Issue by otaku0304** [microsoft/azure-tools-for-java#9483]
IntelliJ build version: 2024.2.3 IC-242.23339.11
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.4
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1366x720,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.auth.AzureToolkitAuthenticationException: you are not signed-in.
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.lambda$account$0(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.lib.auth.AzureAccount.account(AzureAccount.java:59)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.ui.WebAppDeployConfigurationPanel.lambda$setValue$20(WebAppDeployConfigurationPanel.java:310)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.ui.WebAppDeployConfigurationPanel.setValue(WebAppDeployConfigurationPanel.java:309)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.ui.WebAppDeployConfigurationPanel.resetFromConfig(WebAppDeployConfigurationPanel.java:167)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.ui.WebAppDeployConfigurationPanel.resetFromConfig(WebAppDeployConfigurat
```[tasklist]
```

1. The above exception occurs when I try to log in using OAuth 2.0, where the browser opens two separate login pages, leading to a duplicated login process. However, it works fine when using Azure CLI.

2. In IntelliJ, every action is being executed twice when using the Azure Toolkit. When attempting to log in through OAuth 2.0, the browser opens two separate login pages, leading to a duplicated login process.
 
3. In addition to the duplicated actions in IntelliJ when using the Azure Toolkit, after submitting an error report, it redirects me to the browser and opens the issue ticket submission page twice. This results in two identical issue tickets being created.

**Comment by otaku0304** [comment]
In IntelliJ, every action is being executed twice when using the Azure Toolkit. When attempting to log in through OAuth 2.0, the browser opens two separate login pages, leading to a duplicated login process.

**Comment by otaku0304** [comment]
any update ??
