### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@411feadf when dispatching event: com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$SimpleEvent@3fac8a1e com.azure.identity.AuthenticationRequiredException: Interactive authentication is needed to acquire token. Call Authenticate to initiate the device code authentication.

### ISSUE THREAD

**Issue by jlopezcgl** [microsoft/azure-tools-for-java#9484]
IntelliJ build version: 2024.2.3 IU-242.23339.11
OS: Mac OS X
JDK: JetBrains s.r.o. 21.0.4
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2560x1335,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccountModule.lambda$loadResourcePagesFromAzure$0(CognitiveAccountModule.java:56)
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccountModule.loadResourcePagesFromAzure(CognitiveAccountModule.java:56)
		at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.getResourcesFromAzure(AbstractAzResourceModule.java:186)
		at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.re

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
