### ISSUE TITLE
[IntelliJ] Uncaught Exception  com.microsoft.azure.toolkit.lib.common.operation.OperationException: click node (AbstractAzResource(name=newgrc, resourceGroupName=appsvc_linux_centralus, status=Deploying))

### ISSUE THREAD

**Issue by jesustorresns** [microsoft/azure-tools-for-java#9501]
IntelliJ build version: 2024.2.3 IU-242.23339.11
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.4
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,2560x1392,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: click node (AbstractAzResource(name=newgrc, resourceGroupName=appsvc_linux_centralus, status=Deploying))
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.intellij.common.component.TreeUtils$3.clickNode(TreeUtils.java:164)
	at com.microsoft.azure.toolkit.intellij.common.component.TreeUtils$3.mouseClicked(TreeUtils.java:132)
Caused by: com.intellij.openapi.progress.CeProcessCanceledException: kotlinx.coroutines.JobCancellationException: BlockingCoroutine was cancelled; job=Blo

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9519
