### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@4d1c5113 when dispatching event: com

### ISSUE THREAD

**Issue by mackermann-ercot** [microsoft/azure-tools-for-java#9502]
IntelliJ build version: 2024.2.3 IU-242.23339.11
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.4
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliAccount$AzureCliTokenCredential.lambda$null$3(AzureCliAccount.java:113)
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
		at com.micro

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
