### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@219e8678 when dispatching event: com

### ISSUE THREAD

**Issue by rodrigomantoani** [microsoft/azure-tools-for-java#9541]
IntelliJ build version: 2024.2.1 IU-242.21829.142
OS: Mac OS X
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1708x1415,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliAccount$AzureCliTokenCredential.lambda$null$3(AzureCliAccount.java:113)
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
		at com.microsoft

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
