### ISSUE TITLE
[IntelliJ] Uncaught Exception Operator called default onErrorDropped com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy artifact to web app (retailers-service-dev)

### ISSUE THREAD

**Issue by otaku0304** [microsoft/azure-tools-for-java#9542]
IntelliJ build version: 2024.2.3 IC-242.23339.11
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.4
Plugin version: 3.92.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1366x720,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=Operator called default onErrorDropped, throwable=com.microsoft.azure.toolkit.lib.common.operation.OperationException: deploy artifact to web app (retailers-service-dev)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:93)
	at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:43)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:119)
	at com.microsoft.azure.toolkit.intellij.legacy.webapp.runner.webappconfig.WebAppRunState.executeSteps(WebAppRunState.java:71)
	at com.microsoft.azure.toolkit.intellij.legacy.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:68)
Caused by: reactor.core.Exceptions$ReactiveException

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/8096
