### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@16da54c2 when dispatching event: com

### ISSUE THREAD

**Issue by estaphorsius** [microsoft/azure-tools-for-java#9582]
IntelliJ build version: 2024.2.4 IU-242.23726.103
OS: Windows 10
JDK: JetBrains s.r.o. 21.0.4
Plugin version: 3.93.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,2560x1448,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliAccount$AzureCliTokenCredential.lambda$null$3(AzureCliAccount.java:113)
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccountModule.lambda$loadResourcePagesFromAzure$0(

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
