### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@39d61b43 when dispatching event: com

### ISSUE THREAD

**Issue by mackermann-ercot** [microsoft/azure-tools-for-java#9584]
IntelliJ build version: 2024.2.2 IU-242.22855.74
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.93.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1600x852,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
	at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliAccount$AzureCliTokenCredential.lambda$null$3(AzureCliAccount.java:113)
		at com.microsoft.azure.toolkit.lib.auth.cli.AzureCliUtils.executeAzureCli(AzureCliUtils.java:84)
		at com.micros

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
