### ISSUE TITLE
[IntelliJ] Uncaught Exception Exception thrown by subscriber method onEvent(com.microsoft.azure.toolkit.lib.common.event.AzureEvent) on subscriber com.microsoft.azure.toolkit.lib.common.event.AzureEventBus$EventListener@780ce476 when dispatching event: com

### ISSUE THREAD

**Issue by PunitaGosar-QHR** [microsoft/azure-tools-for-java#9598]
IntelliJ build version: 2024.2 IU-242.20224.300
OS: Windows 11
JDK: JetBrains s.r.o. 21.0.3
Plugin version: 3.93.0-2024.2
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,8,1920x1032,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
<REDACTED: Generic Secret>
<REDACTED: Generic Secret>
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccountModule.lambda$loadResourcePagesFromAzure$0(CognitiveAccountModule.java:56)
		at com.microsoft.azure.toolkit.lib.cognitiveservices.CognitiveAccountModule.loadResourcePagesFromAzure(CognitiveAccountModule.java:56)
		at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule.getResourcesFromAzure(AbstractAzResourceModule.java:186)
		at com.microsoft.azure.toolkit.lib.common.model.AbstractAzResourceModule

**Comment by yuyully** [comment]
Duplicate of https://github.com/microsoft/azure-tools-for-java/issues/9450
