### ISSUE TITLE
[IntelliJ] The OK button doesn't work in advance configuration dialog

### ISSUE THREAD

**Issue by ruoxinCheng** [Microsoft/azure-tools-for-java#996]
java.lang.NullPointerException
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigDialog.onOk(SparkSubmissionAdvancedConfigDialog.java:456)
	at com.microsoft.azure.hdinsight.spark.ui.SparkSubmissionAdvancedConfigDialog.lambda$new$6(SparkSubmissionAdvancedConfigDialog.java:110)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

**Comment by ruoxinCheng** [comment]
Yes, verified it.
